### ISSUE TITLE
typescript: Box generics

### ISSUE THREAD

**Issue by atanasster** [system-ui/theme-ui#1013]
Hi, `<Box />` has the `as` property making it possible to impersonate any tag, however some props will not work with typescript. example with colSpan:

```
  <Box
    as="th"
    //@ts-ignore 
    colSpan={3} //colSpan is not recognized as a property
>
```

I would suggest to make `<Box />` accept generics element type, something like:

```
  <Box<HTMLTableHeaderCellElement>
    as="th"
    colSpan={3}
>
```

**Comment by hasparus** [comment]
This has a trade-off. Polymorphic components are really bad for TS compilation times, and can lead to compiler crash.

We've had a pretty lengthy discussion about it issues for _@theme-ui/mdx_ and _@theme-ui/components` TypeScript conversion.

Here's a good blogpost on the topic: https://blog.andrewbran.ch/polymorphic-react-components/

One can notice `Field` types are implemented "properly" and it behaves well... until it doesn't.
This, I think, needs a lot more tests.

TypeScript supports JSX pragmas, so I believe a _preferred scenario_ for TS users would be to use

```tsx
<th
  colSpan="3"
  sx={myStyles}
/>
```

**Comment by hasparus** [comment]
If you'de like to help improve `as` prop story in Theme UI, I believe any contribution would be welcome :)

PS `component-controls` is pretty cool :D

**Comment by atanasster** [comment]
Thanks a lot for the explanation, I will close this. 

Thanks, I would love to contribute, but not sure where to start
