### ISSUE TITLE
preset option for gatsby-plugin-theme-ui does not work

### ISSUE THREAD

**Issue by blake-mealey** [system-ui/theme-ui#1016]
Using the `preset` option (either an installed package like `@theme-ui/preset-base` or an explicit theme object) does not work.

I tried the following configs (with the `@theme-ui/preset-base` npm package installed):

```js
// gatsby-config.js

module.exports = {
  plugins: [
    {
      resolve: `gatsby-plugin-theme-ui`,
      options: {
        prismPreset: 'night-owl',
        preset: '@theme-ui/preset-base',
      },
    },
  ],
};
```

```js
// gatsby-config.js

const theme = require('@theme-ui/preset-base');

module.exports = {
  plugins: [
    {
      resolve: `gatsby-plugin-theme-ui`,
      options: {
        prismPreset: 'night-owl',
        preset: theme,
      },
    },
  ],
};
```

But neither have worked. However, I was successful by using the shadowing method:

```js
// src/gatsby-plugin-theme-ui/index.js
import theme from '@theme-ui/preset-base';

export default theme;
```

**To Reproduce**
1. Create a new gatsby project
2. Use the `gatsby-plugin-theme-ui` plugin with one of the above configs

**Expected behavior**
The theme specified in preset is used

**Screenshots**
This is what I get relying on the preset option
![image](https://user-images.githubusercontent.com/2432634/85187254-8157bb80-b25b-11ea-9d25-b65771ebeb9a.png)

This is what I get when I use theme shadowing
![image](https://user-images.githubusercontent.com/2432634/85187320-fe833080-b25b-11ea-9d49-9f81baa2dcfe.png)

**Additional info**
I can use the shadowing technique as a workaround, but I'd rather use the `preset` option since it makes extending the default theme a bit simpler (I don't have to destructure every object to extend it properly) - or at least, that's my understanding from the docs.

Thanks in advance for the help! :)

**Comment by jxnblk** [comment]
Thanks for reporting this. Can you list the version of Theme UI packages that you're using? Currently this behavior is only in the `0.4` prerelease

**Comment by blake-mealey** [comment]
Ahh, that explains it then. I'm on the following versions:

```json
{
  "@theme-ui/presets": "^0.3.0",
  "@theme-ui/prism": "^0.3.0",
  "gatsby-plugin-theme-ui": "^0.3.0",
  "theme-ui": "^0.3.1"
}
```

It seems like the docs should only show full release APIs, or indicate where it is documenting a prerelease to reduce confusion.

So if I wanted to use this now, would I just need to update gatsby-plugin-theme-ui to the 0.4 prerelease?

**Comment by jxnblk** [comment]
Sorry for the current mismatch between versions and docs, ideally things would be published once they land, but for this particular feature, yes, you would need to install the `0.4` version

**Comment by blake-mealey** [comment]
Thanks for the clarification.
