### ISSUE TITLE
Browser refresh always loads colormode from localStorage

### ISSUE THREAD

**Issue by zwergius** [system-ui/theme-ui#1023]
**Describe the bug**
I'm using the Gatsby plugin and I'm setting the colormode dynamically.

I have a useEffect that sets the colormode initially, or at least it should be, problem is it's somehow not picking it up it always picks what was in localStorage.

https://codesandbox.io/s/theme-ui-color-mode-demo-qulol?file=/src/index.js

Click Toggle Dark and see localStorage sets to dark.

Refresh the browser 

The useEffect I believe should set to 

**To Reproduce**
1. Click Toggle Dark and see localStorage sets to dark.
2. Refresh the codesandbox browser 
3. Observe that colorMode is still dark

**Expected behavior**
The useEffect in the index file of the sandbox should set the colorMode to light

**Comment by lachlanjc** [comment]
Looks like you’ve got a mistake in your sandbox—the dependency on your `useEffect` should be `colorMode`, not `setColorMode`. Closing as a discussion. Thanks!
