### ISSUE TITLE
Text isn't using default variant without passing a variant prop.

### ISSUE THREAD

**Issue by pkrawc** [system-ui/theme-ui#1024]
## Description
According to the docs the `<Text/>` component should use the `text.default` variant automatically, when implemented with `next` it does not inherit the default value.

## Screens
![Screen Shot 2020-06-22 at 4 42 28 PM](https://user-images.githubusercontent.com/7158581/85338155-5eb9e280-b4a7-11ea-9854-1fe04e4129a7.png)
**In the bottom section, the card on the left is explicitly declaring `variant: default` and the card next to it isn't. Both are using the `<Text/>` component from theme-ui**

**Comment by pkrawc** [comment]
It's because the update to the Text component hasn't landed in a stable release yet.

The docs probably shouldn't dictate something that isn't in the master branch.

**Comment by cameronwlewis** [comment]
Just discovered this as well. Glad I found this issue, since I've been fruitlessly trying to solve this over the last hour. Thanks for posting @pkrawc . Guess I'll resort to putting in `text.default` variant manually for now.

**Comment by pkrawc** [comment]
@cameronwlewis and whomever else finds this until close. You can solve the issue by upgrading your package to `theme-ui@next`

**Comment by dandenney** [comment]
@pkrawc Thank you so much for the @next tip!

**Comment by lachlanjc** [comment]
@hasparus I’m cool to close since this is [merged](https://github.com/system-ui/theme-ui/pull/870) & on a published release
