### ISSUE TITLE
Any plans for table component ? 

### ISSUE THREAD

**Issue by ngprnk** [system-ui/theme-ui#1028]
**Describe the solution you'd like**
Responsive table component

**Comment by atanasster** [comment]
I am using [react-table](https://github.com/tannerlinsley/react-table). It can be fully styled. For me, its the variant prop and all styling is in the `theme-ui` theme. Lmk if you need some examples.

**Comment by thetimmyc** [comment]
@atanasster would love to see examples of how you apply the styling via the `theme-ui` theme!

**Comment by atanasster** [comment]
@thetimmyc 

I am styling it as the styles.table/xxx variants in the theme.

Here are some links, lmk if you need additional info

**live demos**: https://component-controls.com/api/components-table--overview

You can install the whole `@component-controls/components` lib, and get a few more theme-ui components, or here are the source code pieces you can extract.

**Table**: https://github.com/ccontrols/component-controls/blob/master/ui/components/src/Table/Table.tsx
**Theming**: https://github.com/ccontrols/component-controls/blob/31b0b023ef3d9df1747b8295ef241cafb94e0f7e/ui/components/src/ThemeContext/theme.ts#L258

**Comment by thetimmyc** [comment]
This is great, @atanasster! Thank you!

**Comment by atanasster** [comment]
Thanks, hope it can work for you.

I was thinking to add theme-ui responsive support at some point but haven't finalized an API and would appreciate some feedback

For columns:
- add a prop to make a columns visible/hidden at specific theme-ui media breakpoints: 
`visible: [false, false, true],`
- make width also an array of widths based on the media breakpoints
`width: [100, 200, 250],`

Anything else comes to mind?

**Comment by lachlanjc** [comment]
@atanasster Update on this?

**Comment by atanasster** [comment]
@lachlanjc - haven't done it yet. Not sure where would be the better place to work on a theme-ui table - in the theme-ui repo and have it as a standard theme-ui component or keep it in my repo. wdyt?

**Comment by lachlanjc** [comment]
@atanasster I think it depends on what the component does—if it’s pretty similar to existing Theme UI components in that it’s just providing basic HTML with fairly vanilla CSS presets, go for adding it here. If it has real functionality beyond basic styling, probably a better fit for external library we link to

**Comment by hasparus** [comment]
Don't you guys think that a table is a bit too big to keep it here?
I mean, of course you can just style HTML `<table />`, but `react-table` and alternatives are __huge__ libraries.

Neither Chakra nor Braid have a Table component. The API surface of a serious table component is a significant, and Theme UI is a styling library.

I'd vote to mark it as out of scope.

**Comment by atanasster** [comment]
Sounds good, lets close
