### ISSUE TITLE
sourcemaps for styles

### ISSUE THREAD

**Issue by amcc** [system-ui/theme-ui#1029]
Finding styles, variants, sx props in a browser inspector is very hard right now. I see emotion has support for sourcemaps, can this be implemented in theme-ui for Gatsby?

**Comment by lachlanjc** [comment]
Emotion Babel plugin will help this! https://emotion.sh/docs/babel

Still needs a bridge into the `sx`/theme variants/other places styling is used through Theme UI.

Related: #1234

**Comment by lachlanjc** [comment]
We'd welcome a PR for this, but we're not planning to implement this feature ourselves, so closing this issue for now. Thank you!
