### ISSUE TITLE
Implement Theme UI to Bootstrap utility class transformer

### ISSUE THREAD

**Issue by johno** [system-ui/theme-ui#103]
Since Bootstrap [uses utility classes](https://getbootstrap.com/docs/4.3/utilities/borders/) we can build a transformer to generate static CSS from a Theme UI config.

**Comment by holloway** [comment]
@johno on the [static css](https://theme-ui.com/static-css/) page it says Bootstrap is still TODO.

If I wanted to add support for this, where should I start? What code should I base this on?

**Comment by jxnblk** [comment]
There are currently two packages that do something similar: [`@theme-ui/tachyons`](https://github.com/system-ui/theme-ui/tree/master/packages/tachyons) and [`@theme-ui/tailwind`](https://github.com/system-ui/theme-ui/tree/master/packages/tailwind)

**Comment by lachlanjc** [comment]
We’d still love for this to happen, but due to the lack of activity we’re closing for now.
