### ISSUE TITLE
Variant responsive values not working alongside other responsive values

### ISSUE THREAD

**Issue by julianbenegas** [system-ui/theme-ui#1030]
**Describe the bug**
You have a component with the `variant` property inside `sx`. This `variant` holds a responsive value, say `fontSize: ["12px", "16px"]`. If you then put another responsive value to the `sx`, then the variant's responsive value won't work.

**To Reproduce**
1. Go to [this sandbox](https://codesandbox.io/s/nameless-sun-hspem-hspem?file=/src/App.js)
2. Resize the window
3. See that the text doesn't change size

**Expected behaviour**
The text should change it's fontSize

**Additional context**
It happens when using variant variant inside `sx`. If variant is used as a prop, it works as expected.

**Comment by jxnblk** [comment]
Thanks! This looks like an odd bug... possibly related to #720 and #832
