### ISSUE TITLE
Add `highlight` to `@types/theme-ui` in `colors` property

### ISSUE THREAD

**Issue by deadcoder0904** [system-ui/theme-ui#1050]
**Is your feature request related to a problem? Please describe.**
Can't get autocomplete on `highlight` property inside `colors` in `theme.ts`

**Describe the solution you'd like**
`highlight` is missing from the [`@types/theme-ui` package](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/theme-ui/index.d.ts#L43-L76).

Don't know how the contributions work on `DefinitelyTyped` but as per the docs `highlight` property is missing in the types. I love the autocompletes guiding me in VSCode.

Also, love `theme-ui`'s thoughtfulness into making all these properties. I don't even have to think which color to add, it's as simple as `primary` or `highlight` or `muted` so thanks to whoever made it :)

**Comment by jxnblk** [comment]
Theme UI is currently being rewritten in TypeScript, see #668 -- the latest is published with the `theme-ui@next` tag, if you want to help test it out

**Comment by deadcoder0904** [comment]
Cool, I'll be testing it as I am using it with Next.js. Should I create new issues related to TypeScript or just comment it at #668?

**Comment by hasparus** [comment]
Hey @deadcoder0904, I've sent https://github.com/DefinitelyTyped/DefinitelyTyped/pull/45967 and https://github.com/system-ui/theme-ui/pull/1058. Would you like to take a look at them?

**Comment by deadcoder0904** [comment]
LGTM 👍
