### ISSUE TITLE
Options aren't visible on Deep mode

### ISSUE THREAD

**Issue by deadcoder0904** [system-ui/theme-ui#1066]
**Describe the bug**
Can't see options on Deep mode

**To Reproduce**
1. Select 'Deep Mode'
2. Go to https://theme-ui.com/customize
3. Click on `heading`'s `select`
4. Unable to read the options

**Expected behavior**
Options should be visible/readable

**Screenshots**
<img width="1437" alt="custom-theme" src="https://user-images.githubusercontent.com/16436270/87511290-b1478280-c692-11ea-9d36-84390d93498f.png">

**Additional context**
It also doesn't work on `Dark` mode

**Comment by deadcoder0904** [comment]
Weird this still doesn't work for me. Is the website live yet?

**Comment by lachlanjc** [comment]
The package has to be published & then the website needs to be using the new version for it to go live, I think 👍
