### ISSUE TITLE
No types included in packages

### ISSUE THREAD

**Issue by ezhikov** [system-ui/theme-ui#1067]
**Describe the bug**
Documentation states:
> Theme UI is written in TypeScript.
>
>While most APIs in Theme UI should just work in TypeScript, there are a few advanced use cases which will differ slightly. This guide is intended to cover those use cases.

But with partial (e.g. `@theme-ui/core`) installation there is no types included in package and no types present as `@types/theme-ui__core` package:

```
TS7016: Could not find a declaration file for module '@theme-ui/core'. '/home/kir/work/mos-cat/libs/ds/node_modules/@theme-ui/core/dist/index.js' implicitly has an 'any' type.
  Try `npm install @types/theme-ui__core` if it exists or add a new declaration (.d.ts) file containing `declare module '@theme-ui/core';`
```

```
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@types%2ftheme-ui__core - Not found
```

**To Reproduce**
Try to use only `@theme-ui/core` and `@theme-ui/css` packages in TypeScript

**Expected behavior**
It works with TypeScript out of the box.

**Comment by deadcoder0904** [comment]
I think it's still being rewritten in Typescript. See https://github.com/system-ui/theme-ui/issues/668 although some of the unchecked packages are converted too which you already mentioned.

Weird, it should work. I'll give this a shot too.

**Comment by deadcoder0904** [comment]
You gotta install `@theme-ui/core@next` & `@theme-ui/css@next` to make it work. The next version has Typescript support.

**Comment by hasparus** [comment]
@jxnblk Documentation from the future is published :c Should I PR to revert the commit that added TypeScript chapter to the docs, or will you redeploy older version?

**Comment by jxnblk** [comment]
@hasparus Sorry, I accidentally, "un-reverted" the docs trying something out. I think a more accurate version should be published now

**Comment by lachlanjc** [comment]
I think we can close this? There are a bunch of other issues/PRs for the TypeScript conversion, sounds like the docs have been fixed appropriately.
