### ISSUE TITLE
Colors referencing other colors?

### ISSUE THREAD

**Issue by thetimmyc** [system-ui/theme-ui#1069]
**Is your feature request related to a problem? Please describe.**
I'd like colors in the colors object to be able to access other colors in that same object. The reason is, there are some elements that should remain static regardless of mode (e.g., a particular button's text should always be "white" not my mode-dependent "background" color).  I believe the cleanest way to do that is to set static colors, then let my color mode colors reference those static colors.

**Describe the solution you'd like**
This is the implementation I'm imagining:
```
colors: {
    /* Static colors */
    light: '#FFFFFF',
    light2: '#E9EBEF',
    light3: '#DFE2E7',
    dark: '#000000',
    dark2: '#434651',
    dark3: '#434651',
    error: '#F05F5F',
    error1: '#F99E9E',
    accent: '#EC2360',
    accent1: '#D61E55',
    accent2: '#C5154A',
    accentNeg1: '#CA1D51',
    /* Mode colors */
    foreground: 'dark',
    foreground2: 'dark2',
    foreground3: 'dark3',
    background: 'light',
    background2: 'light2',
    background3: 'light3 ',
    modes: {
      dark: {
        foreground: 'light',
        foreground2: 'light2',
        foreground3: 'light3',
        background: 'dark',
        background2: 'dark2',
        background3: 'dark3',
      },
    },
  },
```

**Describe alternatives you've considered**
I believe for now, I'll need to hard-code these colors multiple times (e.g., once for "white" and once for "background").

If there is a way to do this now, I would love to hear about it! If not, I think this would be a very useful feature.

**Comment by readeral** [comment]
This may not meet your needs, but here's how I consume my own colours in the colour object: by defining the base colours outside of my object to be exported, spreading that base colours object inside (so all colours are appended) but then also because it's explicitly defined, I can then reference those object values:

`const baseColors = {
  background: '#ffffff',
  accent: '#76777c',
  primary: '#0094c8',
  muted: '#76777c',
  text: '#323232'
};
  
  export default {
    ...baseColors,
    // This is a workaround for consuming our own defined values
    active: baseColors.accent
  };

  `

**Comment by readeral** [comment]
The way you'd have to do it:

```
const baseColors = {
colors: {
    /* Static colors */
    light: '#FFFFFF',
    light2: '#E9EBEF',
    light3: '#DFE2E7',
    dark: '#000000',
    dark2: '#434651',
    dark3: '#434651',
    error: '#F05F5F',
    error1: '#F99E9E',
    accent: '#EC2360',
    accent1: '#D61E55',
    accent2: '#C5154A',
    accentNeg1: '#CA1D51'
};

export default {
  ...baseColors,
  foreground: 'dark',
    foreground2: 'dark2',
    foreground3: 'dark3',
    background: 'light',
    background2: 'light2',
    background3: 'light3 ',
    modes: {
      dark: {
        foreground: 'light',
        foreground2: 'light2',
        foreground3: 'light3',
        background: 'dark',
        background2: 'dark2',
        background3: 'dark3',
      },
    }
}
```

**Comment by thetimmyc** [comment]
Hey @readeral, that's a good idea. I think this will work for my use case!
