### ISSUE TITLE
sx prop weirdness, styles occasionally being overridden until chunk is loaded in Next.js

### ISSUE THREAD

**Issue by ConnorTCM** [system-ui/theme-ui#1070]
**Describe the bug**
When utilising the `sx` prop in a Next.js project, occasionally the styles that are defined inside the object appear to be overridden by the styles defined in the component (in this case, the styles are defined inside a variant, but have tested overriding default styles defined as `defaultProps` and the same behaviour applies). Strangely, sometimes hovering over a Next.js `Link` (which will by default load in pre-load in JS chunks from the linked page) appears to fix things.

**To Reproduce**
1. Apply an `sx` override to a component.
2. Hard refresh until styles are overriden.
3. Hover over a link until Next.js loads in some JS chunks which then appears to fix the issue (making the `sx` styles override the components styles).

**Expected behavior**
The `sx` prop styles to always override those defined in the component, whether or not they are defined as part of a variant or not.

In the example below, the `padding-top` and `padding-bottom` on the button should be `10px`, not `16px` which is the default.

**Screenshots**
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/19690264/87808841-5492c600-c852-11ea-8f25-ef08c11c5f32.gif)

**Comment by xxillya** [comment]
Hello! I am having the same issue. Have you figured out how to solve it?

**Comment by lachlanjc** [comment]
Interesting! I have not encountered this issue personally—could you provide a repo reproducing it?

**Comment by lachlanjc** [comment]
Closing as stale, but please re-open if you encounter this again!
