### ISSUE TITLE
Specifying a CSS selector 

### ISSUE THREAD

**Issue by ChefYeum** [system-ui/theme-ui#1074]
Is there a way to specify a CSS selector (e.g. `:link` or `:visited`). If not, is this of your interest as a user?

Currently, I am using the following in my global css:
```css
:link {
  color: white;
}
```
I would like this to be part of the theme-ui config instead.

**Comment by lachlanjc** [comment]
Yep! @alex83130’s answer is exactly it. You can use that syntax in your theme file for `styles.a`, on individual instances, or if you want it separately in the global scope, like this: https://theme-ui.com/guides/global-styles

**Comment by hasparus** [comment]
@lachlanjc do you think this is something that's not described enough in the docs?

I'm not sure if the docs are welcoming to a reader who is not familiar with Emotion / styled-components.
