### ISSUE TITLE
transitions token support

### ISSUE THREAD

**Issue by pacxiu** [system-ui/theme-ui#1079]
Hey,

do you have in plans to support `transitions` tokens such as other base one?

For now if I've some repeating transition eg. `0.3s ease-in-out` and want to use that outside of theme file in `sx` prop I've to add it as string rather than `transition: 'standard'` token one. Are there maybe some ways to overcome this that I might have missed?

**Comment by lachlanjc** [comment]
We can close now that it’s merged @hasparus!
