### ISSUE TITLE
Improve Components DisplayNames properties

### ISSUE THREAD

**Issue by pacxiu** [system-ui/theme-ui#1080]
**Is your feature request related to a problem? Please describe.**
Hi there,

sometimes I find it extremely difficult to properly debug base components in `React Dev Tools` due to lack of `Display Name` (I think this is it?). For smaller layouts it will not be an issue, however sometimes we can construct more complex ones using only components from theme-ui. Debugging those can be a little bit of pain as some sample React's component tree can look like:

![image](https://user-images.githubusercontent.com/19193499/88154114-a054bf00-cc06-11ea-8e47-cac0f4cc6452.png)

**Describe the solution you'd like**
A little bit cleaner react's component tree to debug.

**Comment by dburles** [comment]
Related https://github.com/system-ui/theme-ui/pull/817
