### ISSUE TITLE
layout component takes class from page - only on build

### ISSUE THREAD

**Issue by amcc** [system-ui/theme-ui#1083]
I am wrapping the page element in gatsby-browser.js with my layout component in order to do some transitions, have a constant header etc. I'm doing it like this:
```
import CustomLayout from "./src/gatsby/browser/wrapPageElement"
export const wrapPageElement = CustomLayout
```
then on wrapPageElement I'm doing this:
```
import React from "react"
import Layout from "./../../components/layout"
const CustomLayout = ({ element, props }, pluginOptions) => {
  return (
    <Layout {...props}>{element}</Layout>
  )
}

export default CustomLayout
```
I don't know if this is relevant - I've done something similar before and it works fine on another site also with theme-ui. The bug is below

**Describe the bug**
Only on build, not in develop, I'm seeing the div for the layout component take on a class from within one of its children. So for instance the class on the <div> for layout will  be this: class="css-e6vost"

A completely unrelated component, within the children of my layout component will have exactly the same class as above. This will then apply its styles to the layout. I've added a screenshot of the HTML inspector showing the class names - you can see the class above on multiple divs. The layout.js itself has no styles on its root component. I've tried changing it to being wrapped in a fragment, or <div> either way it gets a class applied. This class changes depending on what page I'm on - the layout somehow inheriting it from something within its children. The layout.js file looks like this:
```
/** @jsx jsx */
import React from "react" // eslint-disable-line no-unused-vars
import { jsx, Container } from "theme-ui"
import Transition from "./navigation/Transition"
import Header from "./navigation/Header"
import Footer from "./navigation/Footer"
const Layout = (props) => {
  return (
    <>
      <Header />
      <Transition {...props}>
        <main>
          <Container p={[3, 4]}>{props.children}</Container>
        </main>
      </Transition>
      {props.location?.pathname !== "/" && <Footer />}
    </>
  )
}

export default Layout

```

Could this be a consequence of how I'm wrapping layout.js with gatsby-browser.js or is there something else going on here.

<img width="513" alt="Screenshot 2020-07-23 at 18 37 08" src="https://user-images.githubusercontent.com/115295/88319900-b6e93c00-cd14-11ea-882a-067f187aa304.png">

**Comment by lachlanjc** [comment]
Hey! I’m having trouble understanding the issue here. So Emotion is generating the same class name for two components that should have different styles?

**Comment by lachlanjc** [comment]
I’m going to close this as an inactive discussion for now but please comment if you’re still seeing an issue!
