### ISSUE TITLE
Support enctype on <Box> and/or formenctype on <Button>

### ISSUE THREAD

**Issue by aaronadamsCA** [system-ui/theme-ui#1086]
```jsx
<Box as="form" method="post" action={action} enctype="multipart/form-data">
  <Button type="submit" formenctype="multipart/form-data">Submit</Button>
</Box>
```

Theme UI eats `enctype` and `formenctype`. They're common enough `<form>` attributes, since one or the other is required for forms that upload files. I can't actually find the whitelist of props (upstream?) so I'm just sticking a bare `<form>` in there now, but I do think `enctype` is worth supporting out of the box, since it's how the docs show a form implementation.

Thanks! Love the project. 👍

**Comment by jxnblk** [comment]
Haven't used this myself, but for JSX, would `encType` and `formEncType` not work? (https://reactjs.org/docs/dom-elements.html)

**Comment by aaronadamsCA** [comment]
As soon as I read that I facepalmed. I've checked and you're right, `encType` and `formEncType` work fine on Theme UI components.

Worse, my code ended up using `<form encType="multipart/form-data">` anyway - so I'm not sure what I was doing, exactly.

Thank you! Hopefully this helps someone via search. Case matters!
