### ISSUE TITLE
(docs) Add section for Theme UI component kits / themes

### ISSUE THREAD

**Issue by cobraz** [system-ui/theme-ui#1087]
Thank you for Theme UI! ❤️

**Describe the solution you'd like**
We could grow the community by adding a section for related projects, such as component kits and themes based on Theme UI to the documentation.

**Additional context**
I believe it could grow the community when users like @atanasster and myself can share other works that extend Theme UI. Some pros I see are users can see examples of Theme UI usage in other work, they can find edge-cases that never will make it into Theme UI packages and it could motivate more people to contribute.

Examples:
- https://github.com/system-ui/theme-ui/discussions/1015

I can submit a pull request if this idea is considered good. I don't know if there should be some requirements, categorization of projects – or if this should just be a discussion topic?

**Comment by jxnblk** [comment]
This would be a great addition to the docs! I think starting simple with a list of links in markdown and adding it to the navigation in the docs site would be fine to PR

**Comment by cobraz** [comment]
Hello @jxnblk. Just pushed a pull request (#1103). Was this what you thought?

Maybe we should describe the different projects? I don't know if you'd like more? I'm not sure of other projects that could be added. Hopefully, there are others that want to add their projects if we accept #1103.

**Comment by atanasster** [comment]
Hi, thanks very much for the work. Related to this effort of consolidating `theme-ui` community components, in addition to the links on the theme-ui docs site, I made a site with `theme-ui` and `component-controls` documentation pages. Live site:  https://theme-ui-design-system.netlify.app , repo: https://github.com/atanasster/theme-ui-design-system .

@cobraz I would like to help integrate your library as well and hopefully we can keep maintaining it and have a single reference for searching and playing with `theme-ui` components. To get started, here is the tutorial I was writing for integrating external libraries into component-controls: https://component-controls.com/tutorial/getting-started/external-libraries .
