### ISSUE TITLE
Styles should only be applied within the ThemeProvider

### ISSUE THREAD

**Issue by reichert621** [system-ui/theme-ui#1096]
**Describe the bug**
If I set a background of white in my theme, the background gets applied to the whole page. I only want this to apply to elements within my `ThemeProvider`

**To Reproduce**
1. Place `ThemeProvider` around a lower level component
2. Note that background and other styles apply to components outside of the `ThemeProvider`

**Expected behavior**
Styles should only be applied to components within the `ThemeProvider`

Or, there would be any easy way to override this behavior :)

**Comment by hasparus** [comment]
Setting `useBodyStyles` to `false` should help.

https://theme-ui.com/theming/#body-styles

> ## [Configuration Flags](https://theme-ui.com/theming/#configuration-flags)
>
> The theme object can also include configuration options for Theme UI. The following keys can be used to enable and disable certain features.
>
> Flag                       | Default     | Description                                                                                                 
> -------------------------- | ----------- | ------------------------------------------------------------------------------------------------------------
> `useBodyStyles`            | `true`      | Adds styles defined in `theme.styles.root` to the `<body>` element along with `color` and `background-color`

**Comment by reichert621** [comment]
Ahh didn't catch that in the docs, thank you so much!
