### ISSUE TITLE
Webpack 5: Should not import the named export 'version'

### ISSUE THREAD

**Issue by romanlv** [system-ui/theme-ui#1097]
**Describe the bug**

https://webpack.js.org/migrate/5/#cleanup-the-code

> Using named exports from JSON modules: this is not supported by the new specification and you will get a warning. Instead of import { version } from './package.json' use import package from './package.json'; const { version } = package;

**To Reproduce**

Try to use `webpack@^5.0.0-beta.22` and `theme-ui@0.3.1` 

getting 

```
WARNING in ./node_modules/@theme-ui/core/dist/index.esm.js 37:23-30
Should not import the named export 'version' (imported as 'version') from default-exporting module (only default export is available soon)
 @ ./node_modules/theme-ui/dist/index.esm.js 1:0-37 2:0-65 2:0-65 2:0-65 2:0-65 2:0-65 59:9-12

```

in nextjs (with webpack5 enabled) it won't even compile...

**Comment by testacode** [comment]
Hi having the same issue here with "webpack": "^5.4.0". I'm trying to get the name of a package.
![image](https://user-images.githubusercontent.com/1852080/98738042-e1bfd480-2385-11eb-94eb-38caac422d86.png)

This is my code below.
![image](https://user-images.githubusercontent.com/1852080/98738081-f00df080-2385-11eb-8fe5-4d780a9dbabf.png)
