### ISSUE TITLE
Theme UI Documentation Search

### ISSUE THREAD

**Issue by ahmadatallah** [system-ui/theme-ui#1099]
**Is your feature request related to a problem? Please describe.**
I use theme-ui on daily basis on personal and work projects. The documentation is quite large and I just want to remember something that I used before so I navigate the whole docs to get it. 

Adding search in docs page will make it easy to remember things fast instead of navigating the documentation. 

**Describe the solution you'd like**
I don't have specific solution, may be any search engine like algolia!

**Comment by lachlanjc** [comment]
We’ve got #1037 as well :+1:
