### ISSUE TITLE
The css prop doesn’t pick up space values for gap, gridGap, gridColumnGap, gridRowGap

### ISSUE THREAD

**Issue by marekzelinka** [system-ui/theme-ui#110]
my `theme.js` file: 
```
export default {
  space: {
    '1': '0.25rem',
    '2': '0.5rem',
  }
}
```

my `Header.js` file:
```
<div
  css={{
    display: 'grid',
    gridGap: 2, // returns 2px, instead of 0.5rem
    p: 2, // works as intended, return 0.5rem
  }}
></div>
```

As you can see none of the grid gap properties pick up the correct value.
Is this a bug, or is my configuration wrong? Thanks!

**Comment by jxnblk** [comment]
I don’t think it currently supports those properties but we’d accept a PR in the styled-system repo

**Comment by marekzelinka** [comment]
https://github.com/styled-system/styled-system/pull/574
