### ISSUE TITLE
Heading component doesnt get theme styles

### ISSUE THREAD

**Issue by FutureKode** [system-ui/theme-ui#1131]
**Describe the bug**
Heading component doesn't get theme styles from styles: { h2: {} } for example.

**Additional context**
NextJS app with typescript. Something to do with as="" prop?

**Comment by jonashaefele** [comment]
I think you might be running into the same issue I described in #1130 

That seems to be a general issue with theme-ui in Next.js. As far as I could find, it might be a Next.js issue. In both TS and JSX. But they closed the issue there... Still trying to get to the bottom of it. More details in #1130

To verify if you're having the same issue, can you check if heading styles are missing
- only in MDX pages, with `# Headings`
- or also when you `import { Styled } from 'theme-ui'` and then render `<Styled.h1>Some Heading</Styled.h1>`

**Comment by FutureKode** [comment]
@jonashaefele Hey man,

wow ok <Styled.h2> works for me. I totally missed that in the docs. I was trying to use <Heading as="h2"> in a non MDX page.

Hope your issue gets resolved.
