### ISSUE TITLE
Webkit vendor prefixes produce Typescript errors

### ISSUE THREAD

**Issue by kevinwcyu** [system-ui/theme-ui#1145]
**Describe the bug**
Using `WebkitBoxOrient` and `WebkitLineClamp` properties in the `sx` prop produces Typescript errors.

**To Reproduce**
1. Go to 'https://codesandbox.io/s/repro-theme-ui-webkit-properties-3crbb?file=/src/App.tsx
2. See error errors produced in the `sx` prop of the `Box` component in lines 8–11.

```
(property) WebkitBoxOrient: string
Type 'string' is not assignable to type 'ThemeUIStyleObject'.ts(2322)
```

```
(property) WebkitLineClamp?: number | ThemeUICSSProperties | CSSPseudoSelectorProps | CSSSelectorObject | VariantProperty | ... 9 more ... | undefined
...
Type 'number' is not assignable to type 'ThemeUIStyleObject'.ts(2322)
```

**Expected behavior**
The Webkit vendor prefixes should not produce Typescript errors. See this comment for reference https://github.com/system-ui/theme-ui/issues/234#issuecomment-515692442.

**Additional context**
The line clamping still works as expected, it's only the Typescript error that is not expected. See the output of the provided codesandbox. Removing the `WebkitBoxOrient` and `WebkitLineClamp` gets rid of the Typescript errors.

The provided codesandbox uses `0.4.0-rc.1` of `theme-ui` but it is also present in `0.3.1`.

**Comment by hasparus** [comment]
Hey @kevinwcyu! Thanks for the issue.
We've fixed it in `@next 0.4.0-rc.5` version. 

![image](https://user-images.githubusercontent.com/15332326/92334615-0a7ad380-f090-11ea-86ba-df7752b14d37.png)
![image](https://user-images.githubusercontent.com/15332326/92334639-326a3700-f090-11ea-9f87-b8fe52686c66.png)

**Comment by kevinwcyu** [comment]
Hi @hasparus, thanks! Just tried it out and it works.

**Comment by hasparus** [comment]
Glad to hear that!
