### ISSUE TITLE
Looking for additional preset themes

### ISSUE THREAD

**Issue by jxnblk** [system-ui/theme-ui#115]
Theme UI includes a `@theme-ui/presets` package, which is intended to serve as a base for creating custom themes on top of. It'd be great to have more presets added to the package. Presets can be as minimal as a basic color palette and typographic styles, or include MDX element styles, syntax highlighting, or any other useful design tokens.

If you'd like to contribute a new preset, but aren't sure how to get started, feel free to leave a comment here, and we'll try to help you out

**Comment by lemes** [comment]
@jxnblk do you think it would make sense to have a Material Design preset?

**Comment by jxnblk** [comment]
@lemes yes, that would be great!

**Comment by yurm04** [comment]
@jxnblk 👋 I added https://github.com/system-ui/theme-ui/pull/567 as a basic preset loosely based on the Polaris design system.  It's pretty simple right now so let me know if there's any interest in building out its typography or anything else.

**Comment by TomFreudenberg** [comment]
Hi, hopefully I may post this question here.

We are preparing a new app with gatsby and are not sure to choose the right design fundament. Before looking on theme-ui we intend to go for material-ui.

We like the idea of theme-ui but as far as I get it right - if we would also like to use (something like) the material-ui components - there had to be a materialize theme and components library based on theme-ui. Currently existing themes and components for theme-ui are too primitive. Is this a correct assessment?

Another approach is discussed on that issue https://github.com/system-ui/theme-ui/issues/819 - is this a right one?

Thanks for your feedback
Tom

**Comment by jxnblk** [comment]
@TomFreudenberg could you please open a new issue since your question is off topic for this issue?

**Comment by beerose** [comment]
I recently did _sketchy_ Theme UI preset: https://www.npmjs.com/package/theme-ui-sketchy-preset.

Would you be interested in a PR that adds it to  the `@theme-ui/presets`?

**Comment by jxnblk** [comment]
@beerose I *love* this preset! It's so good! We're certainly open for a PR; whether you want to link out to your own repo from the docs or add it to this one, I'll leave that up to you (i.e. it's totally fine if you want to keep this on your own GitHub or domain)

**Comment by lachlanjc** [comment]
We’d still love for contributions of additional preset themes, but due to the lack of activity on these we’re closing for now.
