### ISSUE TITLE
Prism not working on deployment

### ISSUE THREAD

**Issue by drjosephliu** [system-ui/theme-ui#1158]
**Describe the bug**
Prism works on development, but not on deployment with netlify.

**To Reproduce**
1. Shadowed `src/gatsby-plugin-theme-ui/components.ts`:

```
import Prism from '@theme-ui/prism'
const components = {
  pre: props => props.children,
  code: Prism,
}
export default components
```

Also defined the style in `src/gatsby-plugin-theme-ui/index.ts`:
```
import nightOwl from '@theme-ui/prism/presets/night-owl.json';

export default {
    pre: {
      ...nightOwl,
      fontFamily: `"Operator Mono", monospace`,
      fontSize: '0.9rem',
      tabSize: 4,
      hyphens: `none`,
      overflow: `auto`,
      borderRadius: 6,
      p: 3,
      my: 4
    },
}
```

2. Works on localhost:8000, but not deployment. To be clear, the font family does change, but not the background colour.

**Screenshots**
Screenshot below shows what I mean. Font family is correct, but background colour hasn't changed:
<img width="820" alt="Screenshot 2020-08-28 at 7 12 24 AM" src="https://user-images.githubusercontent.com/22230085/91554811-6b086300-e962-11ea-92d0-230f5d45f2bc.png">

**Comment by hasparus** [comment]
@drjosephliu could you attach your lockfile here?

**Comment by drjosephliu** [comment]
https://github.com/drjosephliu/drjosephliu.com/blob/a1a9836ce92683f3d71eb05119ef2e5ce0219fe5/yarn.lock#L1-L16757

**Comment by drjosephliu** [comment]
@mrmartineau So i deleted yarn.lock and node_modules and reinstalled the dependencies again. However, deployment via netlify returned a build failure:

```
7:41:23 AM: failed Building production JavaScript and CSS bundles - 5.488s
7:41:23 AM: error Generating JavaScript bundles failed
7:41:23 AM: [BABEL] /opt/build/repo/.cache/polyfill-entry.js: Cannot read property 'chrome' of undefined (While processing: "/opt/build/repo/node_modules/@babel/preset-env/lib/index.js")
7:41:23 AM: error Generating JavaScript bundles failed
7:41:23 AM: [BABEL] /opt/build/repo/.cache/production-app.js: Cannot read property 'chrome' of undefined (While processing: "/opt/build/repo/node_modules/@babel/preset-env/lib/index.js")
7:41:23 AM: not finished Generating image thumbnails - 13.375s
7:41:23 AM: (sharp:1475): GLib-CRITICAL **: 11:41:23.192: g_hash_table_lookup: assertion 'hash_table != NULL' failed
7:41:23 AM: ​
7:41:23 AM: ┌─────────────────────────────┐
7:41:23 AM: │   "build.command" failed    │
7:41:23 AM: └─────────────────────────────┘
7:41:23 AM: ​
7:41:23 AM:   Error message
7:41:23 AM:   Command failed with exit code 1: gatsby build
7:41:23 AM: ​
7:41:23 AM:   Error location
7:41:23 AM:   In Build command from Netlify app:
7:41:23 AM:   gatsby build
7:41:23 AM: ​
7:41:23 AM:   Resolved config
7:41:23 AM:   build:
7:41:23 AM:     command: gatsby build
7:41:23 AM:     commandOrigin: ui
7:41:23 AM:     publish: /opt/build/repo/public
```

**Comment by drjosephliu** [comment]
Ok I finally got it working and prism is working as normal. Here's what I did:

- yarn add @emotion/core@^10.0.0

And fixed unmet/incorrect peer dependencies:
- yarn add @babel/core@^7.11.5
- yarn add typescript@^4.0.2
