### ISSUE TITLE
Proposal: helper function for theme-aware utilities

### ISSUE THREAD

**Issue by lambertbrady** [system-ui/theme-ui#1166]
### Is your feature request related to a problem? Please describe.
Often times I want to use utilities from external libraries within the `sx` prop, and map their arguments to theme-aware values.

For example, I am using the `between()` mixin from [polished.js](https://polished.js.org/docs/#between) for responsive spacing and typography. Ideally, I would map the function's arguments (`fromSize`, `toSize`, `minScreen`, `maxScreen`) to properties defined in my theme.

### Describe the solution you'd like
I would like a theme-ui helper function that wraps any utility to provide theme context. Note that this is already implemented in the [@theme-ui/color](https://github.com/system-ui/theme-ui/blob/master/packages/color/src/index.ts) package. The function I am proposing would generalize this approach, making it easier for users to extract their own utilities for use in theme-ui without resorting to a package.

Consider `between()` from polished.js. The solution I have in mind would create a `wrapUtility()` helper function (_better name suggestions welcome!_) and look something like this:

**Using the helper function:**
```
// src/utils/theme-aware.js
import { wrapUtility } from 'theme-ui'
import * as Polished from 'polished'

export const between = wrapUtility(
   Polished.between,
   ['space', 'space', 'sizes', 'sizes']
)
```

**Using the utility with the `sx` prop:**
```
import { between } from '../utils/theme-aware'
```
```
sx = {{ m: between(4, 8, 'sm', 'lg') }}

// Equivalent to:
// theme => between(theme.space[4], theme.space[8], theme.sizes.sm, theme.sizes.lg)
```

In addition to mapping each argument of a utility to a [theme scale](https://theme-ui.com/theme-spec#theme-scales), the `wrapUtility()` helper function could provide two extra features:
1. Support optional argument defaults defined using key-value pairs of the form `{themeScale: defaultVal}`, where `defaultVal` will override the initial defaults of the utility function when defined, e.g.
    ```
    wrapUtility(
       between,
       [{space: 2}, { space: 12 }, { sizes: theme => theme.breakpoints.sm }, 'sizes']
    )
    ```
    Note how `defaultVal` can be a functional value accepting the `theme` object as an argument, which enables defaults to have a different theme scale than the one specified by `themeScale`.

    Using with the `sx` prop:
    ```
    sx = {{ m: between() }}
    // Equivalent to:
    // (since polished.js sets default `maxScreen` to '1200px')
    // theme => between(theme.space[2], theme.space[12], theme.sizes.sm, '1200px')

    sx = {{ m: between(4, 8, 'md', 'lg' }}
    // Equivalent to:
    // theme => between(theme.space[4], theme.space[8], theme.sizes.md, theme.sizes.lg)
    ```
2. Support an optional callback function, to be applied to each argument passed into the utility after the argument's theme value has been retrieved (I've found need for this in situations where a utility function requires arguments converted to a particular css unit), e.g.
    ```
    import { between, rem } from 'polished'
    
    wrapUtility(
       between,
       ['space', 'space', {sizes: 'sm'}, {sizes: 'lg'}],
       rem
    )
    ```
    Using with the `sx` prop:
    ```
    sx = {{ m: between('1em', '20px') }}
    // Equivalent to:
    // theme => between(rem('1em'), rem('20px'), rem(theme.sizes.sm), rem(theme.sizes.lg))
    ```

**In Summary:**

**_Name:_** `wrapUtility()`

**_Arguments:_**
1. **Utility Function** (`fn`: _required_)
    The utility function to be wrapped and provided with theme context.

2. **Theme Mapping** (`themeMap`: _required_)
    Values describing the theme context corresponding to each argument of `fn`, including the desired theme scale (`themeScale`) to be used and an optional _theme-aware_ default theme value (`defaultVal`). This mapping can be provided as a string, an object literal, or an array wherein each array element is either a string, an object literal, or `undefined`.
    
   -  _String_: The simplest mapping is a string corresponding to a `themeScale`, which will be used as the mapping for each argument of `fn`. The `defaultVal` will be set to `undefined`.

    - _Object_: Similarly, if an object literal is provided it will be used as the mapping for every argument of `fn`. However, this technique allows a default value to be defined as well: `{themeScale: defaultVal}`. If `defaultVal` is a function, it will be executed with the `theme` object passed as its only argument.

    - _Array[String || Object || undefined]_: An array of string and/or objects can also be provided, where each such element behaves corresponding to the descriptions above. A value of `undefined` may also be used within the array, with the exception of the first (0th) element. Any `undefined` elements will be replaced by the most recent value in the array that is not `undefined`. Likewise, if the length of a given array is less than `fn.length`, the last element provided that is not `undefined` will be used as the mapping for all subsequent, unspecified elements. If the length of the passed array is greater than `fn.length`, the extra arguments will be ignored.

    Examples:
    ```
    // Suppose `fn.length === 4`: then the following values for `themeMap` are equivalent
    'space'
    {space: undefined}
    ['space']
    [{space: undefined}]
    ['space', {space: undefined}, undefined]
    ['space', 'space', 'space', 'space']
    [{space: undefined}, {space: undefined}, {space: undefined}, {space: undefined}]
    ['space', undefined, undefined, undefined, 'sizes', 'breakpoints']

    // Note: falsy values not equal to undefined will be used as `defaultVal`
    // the following values for `themeMap` are NOT equivalent
    {space: undefined}
    {space: null}
    {space: 0}

    // The most robust mapping will be an array such that `themeMap.length === fn.length`
    // wherein each element of `themeMap` is an object literal with a single key-value pair
    // corresponding to `{themeScale: defaultVal}`
    [{space: '4px'}, {space: 12}, {sizes: 'sm'}, {sizes: theme => theme.breakpoints.desktop}]
    ```

3. **Callback Function** (`callback`: _optional_)
    A function to execute on each argument passed into `fn`, _after_ the argument's theme value has been retrieved. It accepts four arguments:

    1. **Current Theme Value** (`themeVal`: _required_)
        The current theme value retrieved based on the corresponding `themeMap` entry.

    2. **Theme** (`theme`: _optional_)
        The `theme` object.

    3. **Utility Function Argument Index** (`fnArgIndex`: _optional_)
        The index of the current argument of `fn` being processed.

    4. **Utility Function Argument Array** (`fnArgs`: _optional_)
        The array of original, unprocessed arguments passed into `fn`.

_**Return Value:**_
    A function that accepts theme-aware arguments corresponding to `themeMap`, to be used in the execution of `fn`.

### Describe alternatives you've considered
There are three alternatives I have considered:

1. Currently, a user can utilize [functional values](https://theme-ui.com/sx-prop#functional-values) within the `sx` prop to provide theme values to any utility function. Once again using `between()` as an example, that might look something like this:

    ```
    import { between } from 'polished'
    ```
    ```
    sx = {{ m: theme =>
       between(
          4,
          theme.space[12],
          theme.breakpoints.mobile,
          theme.breakpoints.desktop
       )
    }}
    ```
    This works well and should be the preferred method for utilities that are used only a few times throughout a code base. However, for utilities used frequently, this technique quickly becomes cumbersome and difficult to maintain.

    This is especially true in situations where default theme values are desired. For example, the last two arguments in the code above could reasonably be set as defaults for `minScreen` and `maxScreen`, making it unnecessary to write them out every time. Additionally, if those defaults need to be changed in the future (e.g., maybe a user decides to change `theme.breakpoints.desktop` to `theme.sizes.lg`), it would be ideal to update them in a single place rather than manually replacing every function argument in the code. These solutions are not possible with functional values alone.
2. For any set of utilities, one could create a package similar to @theme-ui/colors, but this seems impractical.
3. A user could manually wrap their desired utilities using the same approach used in @theme-ui/colors. However, this would require users to understand and apply theme-ui's low-level [`get`](https://theme-ui.com/api#get) method, which is defined in the docs as "an existential getter function used internally." This wording seems to support the idea of providing a more abstract function for users to take advantage of.

### Additional context
I have implemented this idea in JavaScript (it will need to be converted to TypeScript) and created a usage example - please take a look [on codesandbox](https://codesandbox.io/s/zealous-darkness-ccuny?file=/src/utils/wrap-utility.js).

**Comment by atanasster** [comment]
@lambertbrady - thats a lot of information :) You have an excellent grasp on the subject but it might be a bit hard to understand for a newcomer. And typescript for it would be really hard.

On the other hand, have you considered a simpler solution where you just wrap the style function call, so you will not call it multiple times and get messy:

```
import * as P from "polished";

export const between = (fromSize, toSize, minScreen, maxScreen) => (t) => P.between(
  t.sizes[fromSize],
  t.sizes[toSize],
  minScreen || t.breakpoints.start,
  maxScreen || t.breakpoints.end
);
```

and usage is still exactly the same
```
<Demo
  sx={{ bg: "teal.4", pl: between(...sizeRange, ...screenRange) }}
/>
```

**Comment by atanasster** [comment]
@hasparus this can be closed for now - I think  we have a solution and its a bit old
