### ISSUE TITLE
The 'sx' prop break Theme UI Components

### ISSUE THREAD

**Issue by fcisio** [system-ui/theme-ui#1195]
**Describe the bug**
Using the `sx` prop on a button, for example, will remove all the default styling.
> Using single props like `variant=`, `bg=`, ... does not break the styling

**To Reproduce**
1. Upgrade to version 0.3.1
2. Make sure you are using the `jsx` pragma
3. import { Button } from 'theme-ui'
4. Render two buttons. One with `mx="4"` and the second with `sx={{ mx: 4 }}`
5. You should see that the one with the `sx` prop is broken

**Expected behavior**
The Theme UI component should maintain it's default styling while using the `sx` prop on it.

**Screenshots**
![Shot_0 10](https://user-images.githubusercontent.com/46095852/94210675-6bcae100-fe9d-11ea-864b-c78b1ed3c317.jpg)

**Additional context**
Bug appeared on **version 0.3.1**

> I am fairly new to Theme UI, this might also be the desired effect. Any information about this would be greatly appreciated.

**Comment by hasparus** [comment]
Hey @fcisio, I can see you closed the issue. Was there another reason for the bug, or does it still happen for you?

**Comment by fcisio** [comment]
Hey @hasparus ,
I believe my issue was related to an upgrade to some other library.

Solved that and everything seems to be working properly now!

**Comment by hasparus** [comment]
> I believe my issue was related to an upgrade to some other library.

Was it _@emotion/core_ or one of the MDX libraries?
