### ISSUE TITLE
Heading component does not render font-size and color

### ISSUE THREAD

**Issue by corbpaul** [system-ui/theme-ui#1198]
**Describe the bug**
Following the instructions on https://theme-ui.com/components/heading and https://theme-ui.com/theming#styles adding `<Heading as="h1">Heading</Heading>` does not render the correct font size or color.

**To Reproduce**
1. `import { Heading } from 'theme-ui'`
2. add 
```
styles: {
    h1: {
      fontSize: 32,
      fontFamily: 'heading',
      fontWeight: 'heading',
      color: 'primary',
      mt: 4,
      mb: 2,
    },
  }
```

**Expected behavior**
h1 to be rendered with font size and primary color

**Additional context**
Running via Storybook with theme provider

**Comment by SaberOuarezzamen** [comment]
Hi @corbpaul !
Which `ThemeProvider` are you using ?
I think you should use the `ThemeProvider` from `theme-ui`, as mentioned on the docs [Getting-started](https://theme-ui.com/getting-started)
```
// basic usage
import React from 'react'
import { ThemeProvider } from 'theme-ui'
import theme from './theme'
export default props => (
  <ThemeProvider theme={theme}>{props.children}</ThemeProvider>
)
```

**Comment by fcisio** [comment]
I think you are mixing up two different things (Styled and Variants).

You can either do:
```jsx
<Styled.h1>Heading</Styled.h1>
```

Or use variants:
```jsx
<Heading as="h1" variant="text.title">Heading</Heading>
```

> The `as` prop is only changing the output tag of the component -> `<h1></h1>`. It is the variant that is adding the styles

In the theme you can set the variant like so:

```jsx
text: {
    title: {
        fontSize: [1, 2, 3],
        fontWeight: "heading",
    },
    ...
}

```
