### ISSUE TITLE
Website flashes with light theme for a second even when dark theme is selected

### ISSUE THREAD

**Issue by deadcoder0904** [system-ui/theme-ui#120]
# Reproduction

Select any theme other than light which is default on [Theme UI](https://theme-ui.com)

Then try refreshing the page. It will flash the light theme which is the default for a second & then quickly changes to the theme selected.

I think it's a bug. Wait until local storage (which is async I think) returns value.

**Comment by jxnblk** [comment]
This is a limitation with how storing the values in localStorage (which happens client-side) and building static HTML at build time work. The side uses the [Gatsby Plugin](https://theme-ui.com/color-modes#gatsby-plugin) to attempt to minimize the flash of styles, but it would be nice to have a better solution. If you're noticing it on the live theme-ui.com, it'd be helpful to know what browser you're using for debugging

**Comment by deadcoder0904** [comment]
Firefox Quantum latest v67.0.4 (64-bit). Sucks tho.

**Comment by MarkosKon** [comment]
I notice the flash in theme-ui.com but for every other component other than body. I'm using Chrome 75.0.3770.100.

This is to be expected though, if I understand the code correctly:
- [theme-ui/src/color-modes.js](https://github.com/system-ui/theme-ui/blob/master/packages/theme-ui/src/color-modes.js#L51-#L61)
- [gatsby-theme-ui/src/provider.js](https://github.com/system-ui/theme-ui/blob/master/packages/gatsby-theme-ui/src/provider.js)
- [gatsby-theme-ui/gatsby-ssr.js](https://github.com/system-ui/theme-ui/blob/master/packages/gatsby-theme-ui/gatsby-ssr.js)

**Comment by jxnblk** [comment]
@markoskon thanks! And yes, currently, the flash prevention code only handles body text and background colors

**Comment by MarkosKon** [comment]
By the way, as a workaround you can use CSS variables. I [created an example](https://github.com/MarkosKon/theme-ui-flash-workaround).

Points of interest:
- [gatsby-ssr.js](https://github.com/MarkosKon/theme-ui-flash-workaround/blob/master/gatsby-ssr.js#L8-L10)
- [colors](https://github.com/MarkosKon/theme-ui-flash-workaround/blob/master/src/theme/colors.js)
- [global styles](https://github.com/MarkosKon/theme-ui-flash-workaround/blob/master/src/rootElement.jsx#L33-L48)

Does it make sense to alter the theme-ui code to generate the CSS variables automatically from the theme object?

**Comment by jxnblk** [comment]
I started an implementation that would work similarly, but also note that custom properties aren’t supported in IE 11 – ideally all colors could handled but this started with only text and background colors to flesh out the basic implementation

**Comment by jxnblk** [comment]
Since Theme UI uses CSS custom properties now, this is less of an issue, so closing this issue out

**Comment by deadcoder0904** [comment]
@jxnblk now it's great. 1 gotcha tho - the theme name is inconsistent now for a second when u refresh after selecting different them than light.
