### ISSUE TITLE
Gatsby reports invalid hook call with useThemeUI (React 17)

### ISSUE THREAD

**Issue by quinnturner** [system-ui/theme-ui#1201]
**Describe the bug**
While using React `17`, Gatsby `2.24.66`, theme-ui `0.3.1`, I get the following error on a `gatsby build`:

```
failed Building static HTML for pages - 1.301s

 ERROR #95313 

Building static HTML failed for path "/offline-plugin-app-shell-fallback/"

See our docs page for more info on this error: https://gatsby.dev/debug-html


  38 |   theme: null
  39 | });
> 40 | var useThemeUI = function () { return React.useContext(Context); };
     |                                            ^
  41 | var canUseSymbol = typeof Symbol === 'function' && Symbol.for;
  42 | var REACT_ELEMENT = canUseSymbol ? Symbol.for('react.element') : 0xeac7;
  43 | var FORWARD_REF = canUseSymbol ? Symbol.for('react.forward_ref') : 0xeac7;


  WebpackError: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
```

That error code is the following:

>Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons: 1. You might have mismatching versions of React and the renderer (such as React DOM) 2. You might be breaking the Rules of Hooks 3. You might have more than one copy of React in the same app See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.

I believe I am using the classic runtime for Gatbsy + React 17, here is my `.babelrc`:

```jsonc
{
  "presets": ["babel-preset-gatsby"],
  "plugins": [
    [
      "@babel/plugin-transform-react-jsx",
      {
        // TODO: This is to handle theme-ui pragma issues: https://github.com/system-ui/theme-ui/issues/1160
        "throwIfNamespace": true, // defaults to true
        "runtime": "classic", // defaults to classic
        "importSource": "react" // defaults to react
      }
    ]
  ]
}
```

**Comment by hasparus** [comment]
I'd guess you have multiple versions of React or a React renderer in the same app.
Theme UI depends on 16 with a peerDependency, but somebody else can install it.
Using 17 (a major in semver) causes two versions of React to be installed.

Could you send your yarn.lock here so we can look which library installed the culprit?
You could also try Yarn `"resolutions"` as a workaround to force everyone in your node_modules to use React 17.

**Comment by lachlanjc** [comment]
Closing as a discussion since it’s been 2+ months, but please follow up if you’re still having issues with the most recent releases!
