### ISSUE TITLE
Image broken on Avatar and Image docs page

### ISSUE THREAD

**Issue by googol88** [system-ui/theme-ui#1222]
**Broken Avatar Images**
The examples in the docs for the Image and Avatar component contain images that are broken. It appears that the images are from [contrast.now.sh](https://contrast.now.sh/fff/000?text=UI&size=96&fontSize=1.5&baseline=1) but Vercel gives a 404 error and says that the deployment was disabled.

**To Reproduce**
Go to [https://theme-ui.com/components/image](https://theme-ui.com/components/image) or [https://theme-ui.com/components/avatar](https://theme-ui.com/components/avatar)

**On Image Docs**
<img width="806" alt="image_docs" src="https://user-images.githubusercontent.com/57511576/97024766-2c87c280-1525-11eb-9822-2642fd69b377.png">

**On Avatar Docs**
<img width="806" alt="avatar_docs" src="https://user-images.githubusercontent.com/57511576/97024794-33aed080-1525-11eb-9bfe-ee82a29ff648.png">

[contrast.now.sh](https://github.com/jxnblk/contrast-swatch) is also used in [other files](https://github.com/system-ui/theme-ui/search?q=contrast.now.sh) across the theme-ui repo.
So it seems that someone should notify the owner, @/jxnblk, of contrast.now.sh to resolve this, or include the image as a file in the static folder.

**Comment by atanasster** [comment]
Do you have a good source of images - or select one from a library and I can submit a PR. 
For example if you go
 https://theme-ui-design-system.netlify.app/docs/components-theme-ui-avatar--overview and in the Controls section click on randomize - those are face images from AWS using fakerjs.

**Comment by googol88** [comment]
Hmm... this unfortunately doesn't appear to solve the problem, since the images are still broken on the docs :( Any reason why?

Also, should we use the [theme-ui logo](https://raw.githubusercontent.com/system-ui/theme-ui/master/packages/docs/static/logo.png) instead? If someone could guide me through a PR for this (not sure if this is weird to ask), I'd greatly appreciate it.

**Comment by atanasster** [comment]
@googol88 - I believe its not deployed yet. 

I think you are right that #1233 is using the gatsby logo, and it should probably use the theme-ui logo. Thanks a lot for the link - I created #1235.

I have temporarily published the site if you can please confirm
image: https://theme-ui-draft.netlify.app/components/image
avatar: https://theme-ui-draft.netlify.app/components/avatar

**Comment by hasparus** [comment]
Yup, we should have closed the issue.

@jxnblk I've cherry-picked a fix for this to `previous`. Could you set up docs to be deployed from that branch?
