### ISSUE TITLE
⛱ Release v0.4.0

### ISSUE THREAD

**Issue by hasparus** [system-ui/theme-ui#1239]
This is an umbrella issue for bugfixes, problems and tasks regarding next Theme UI releases.

I updated the [changelog](https://github.com/system-ui/theme-ui/blob/master/CHANGELOG.md) to include current additions to both [`previous`](https://github.com/system-ui/theme-ui/blob/master/CHANGELOG.md#v032-unreleased) and [`master` (incomplete)](
https://github.com/system-ui/theme-ui/blob/master/CHANGELOG.md#v040-unreleased) branches.

Following list is obviously work in progress and a subject to change. Please feel free to discuss it and share your ideas in this issue. 

### v0.3.2 (released)

- [x] Publish `@theme-ui` @0.3.2-alpha.10
  - `gatsby-theme-ui-blog` failed with 403
- [x] Test 0.3.2-alpha manually @hasparus 
- [x] Make sure CHANGELOG.md is updated
- [x] Publish v0.3.2 from `previous` branch with bugfixes and minor improvements 
- [x] Get all NPM permissions
- [x] Deploy updated docs from `previous` branch (This is not super urgent, there are mostly fixes to the docs there, no new content per se)

### v0.4.0

- [x] Write a changelog
- [x] Publish 0.4.0-rc.7 with newest changes
- [ ] Get permissions to deploy the docs? or deploy to another domain.
- [ ] Deploy the docs
- [ ] Give more people GitHub and NPM permissions.
- [x] Release final prerelease to test in our apps (0.4.0-rc.13)
- [x] Close "Convert to TypeScript" issue https://github.com/system-ui/theme-ui/issues/668

### v0.5.0
- [x] Add support for automatic JSX runtime https://github.com/system-ui/theme-ui/pull/1237
- [ ] Set up docs to deploy from `master` branch on git tag (i.e. on NPM release)

### Later

- [ ] Type check property values against theme scales #832 #1090
- [ ] Set up longer CI tests — run tests in a few bigger open source respositories which use Theme UI. We have a huge API surface, and I'm worried our unit tests don't cover it fully. This would also be a nice check for unexpected breaking changes.  
- [ ] Solve React context discrepancy bugs
- [ ] Migrate to Preconstruct and Changesets
- [ ] Make continous canary releases in GitHub Actions
- [ ] Continously deploy "next version" docs to another URL in GitHub Actions 

cc @lachlanjc @atanasster @joe-bell @dcastil @nandorojo

**Comment by atanasster** [comment]
Great plan, whats the status of typescript converting the components package ?

**Comment by hasparus** [comment]
> Great plan, whats the status of typescript converting the components package ?

Not urgent? I don't expect myself working on it a lot, though if somebody needs a review or a pair programming session, I'd be happy to help.

**Comment by atanasster** [comment]
For me it was/is the biggest hurdle to learning theme-ui - the current syntax was very hard to read for me. 

Whats the 0.4 timeLine, if there are still a few weeks i can take on this.

**Comment by hasparus** [comment]
> For me it was/is the biggest hurdle to learning theme-ui - the current syntax was very hard to read for me.

What do you mean by "syntax" here? The `sx` prop and pragmas?

**Comment by atanasster** [comment]
I meant the source code of the components to learn from where starting to use the library. Usually i look at the source to learn how to create my own components and in the case if theme-ui the js code for the components is not intuitive for me.

**Comment by hasparus** [comment]
> Usually i look at the source to learn how to create my own components and in the case if theme-ui the js code for the components is not intuitive for me.

I'd get rid of styled-system dependency and rewrite to use Theme UI public API (sx prop).

**Comment by atanasster** [comment]
Yes agreed

**Comment by hasparus** [comment]
I release 0.3.2 and 0.4.0-rc.7 yesterday. 0.3.2 should be stable, 0.4.0-rc.7 contains minor breaking changes in types (useColorMode), but required updates shouldn't take longer than a minute.

<details>
<summary>
Excerpt from changelog
</summary>


## v0.4.0-rc.7 2020-11-08

### `@theme-ui/core`

- Make ThemeProvider `theme` prop required

### `@theme-ui/editor`

- Removes overriding property on editor combobox #687

### `@theme-ui/preset-sketchy`

- Add `@theme-ui/preset-sketchy`

### `@theme-ui/prism`

- Add support for highlighting lines #895

### `@theme-ui/sidenav`

- `@theme-ui/sidenav`: move React to peerDependencies #978

### `@theme-ui/style-guide`

- Pass `size` prop to ColorRow component #941

### `@theme-ui/color-modes`

- Accept SetStateAction and generic parameter #1174

### docs

- Fix broken base-preset link on `theming` page

## v0.3.2 2020-11-08

- Fix peer dependencies. Issue #725, PR #836

### `@theme-ui/css`

- Add theme colors support to columnRuleColor and caretColor #1085
- Support scrollPadding variations in sx props. Issue #1214

### `@theme-ui/core`

- Support Webpack 5. (Uses default export from package.json instead of named export) #1141

### `@theme-ui/components`

- Add `primary` as default variant for `Badge` component #1109
- Add `primary` as default variant for `Alert` component #1102
- Add `theme.text.default` variant for `Text` component #870

### docs

- Fix example logo on Avatar & Image component docs #1233
- Fix theme editor output in docs #1182



</details>

**Comment by dcastil** [comment]
@hasparus What do you think about moving #1237 to a `v0.5` release? `v0.4` is in RC stage, so no new big features are expect and we could speed up the release by postponing this a little.

**Comment by sneridagh** [comment]
Emotion 11 is out! Is it possible to have it integrted soon?

**Comment by dcastil** [comment]
@sneridagh Emotion 11 is part of the v1 roadmap, you can read more about it here https://github.com/system-ui/theme-ui/issues/832

**Comment by sneridagh** [comment]
@dcastil ok, thanks! Seems a long list to reach there! Just wondering, how much are the expectations for it to happen?

**Comment by hasparus** [comment]
> @hasparus What do you think about moving #1237 to a v0.5 release? v0.4 is in RC stage, so no new big features are expected and we could speed up the release by postponing this a little.

Makes sense.

**Comment by jordie23** [comment]
Anything stopping 0.4 now? Had a look at the commit logs, looks like you guys have done a huge amount of work recently that's really encouraging to see! Thanks for all the work you guys do, just want to say it's appreciated a lot. :D

**Comment by hasparus** [comment]
@jordie23, You can use the last 0.4.0-rc version and treat it as stable. It won't get any breaking changes, maybe some important bugfixes.

> - [ ] Get permissions to deploy the docs? or deploy to another domain.
> - [ ] Deploy the docs
> - [ ] Give more people GitHub and NPM permissions. 

We're not publishing it to NPM, because we can't deploy the docs to the main docs domain, nor change the fact that we link to it on repository page. Organizational problems are slower to solve than software problems.

**Comment by jordie23** [comment]
@hasparus I understand now. Thanks for the info!
