### ISSUE TITLE
Incorrect return type?

### ISSUE THREAD

**Issue by deckchairlabs** [system-ui/theme-ui#1251]
Shouldn't this be returning a `ThemeUICSSObject`? Passing the resulting theme derived function to the `sx` prop results in Typescript error as it expects `ThemeUICSSObject | ThemeDerivedStyles`

https://github.com/system-ui/theme-ui/blob/f45a5a8fe59f2df4538fbe38438ba6da59467e99/packages/css/src/index.ts#L274-L276

**Comment by hasparus** [comment]
I’m not sure, but I don’t think so. `css` accepts ThemeUICSSObject as an argument. The value passed to sx prop is being passed to css function.

I mean, this function should be probably called `sx`. We go one level of abstraction down with it.

We could pass the result of css(styles) to Emotion’s css prop.

**Comment by deckchairlabs** [comment]
@hasparus right, because the theme-ui `css, get` functions are the main magic for ***themifying*** the CSS object correct?

**Comment by hasparus** [comment]
`get` is just `"lodash/get"` for taking values on paths which may not exist, but you're right about `css` it transforms an object with design tokens from your theme to an object accepted by Emotion (camelcase css, no special values)

![image](https://user-images.githubusercontent.com/15332326/98953346-dcd16100-24fc-11eb-8ab5-df95fbd69152.png)
(taken from [tests](https://github.com/system-ui/theme-ui/blob/f45a5a8fe59f2df4538fbe38438ba6da59467e99/packages/css/test/index.ts))

`css` is probably the most important function in the whole repo.
