### ISSUE TITLE
Hidden props for button doesn't hide button

### ISSUE THREAD

**Issue by cktang88** [system-ui/theme-ui#1254]
**Describe the bug**
I tried applying
`<Button hidden={true}>hello</Button>`
but the button is still visible.

**To Reproduce**
See above.

**Expected behavior**
I'd expect the button to be hidden with that attribute.

**Screenshots**
N/A

**Additional context**
Using v0.3.1

There was a previous indication this was a bug here: https://github.com/system-ui/theme-ui/discussions/1253#discussioncomment-126903

**Comment by lachlanjc** [comment]
Do we document somewhere that `hidden` is an available prop? I’ve never heard of it/seen it in the code.

**Comment by atanasster** [comment]
@lachlanjc , `hidden` is an html attribute that is applicable to all tags, its not a theme-ui thing

https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/hidden

**Comment by lachlanjc** [comment]
We can close this @hasparus!
