### ISSUE TITLE
theme ui returns empty object when using sx

### ISSUE THREAD

**Issue by dailin4** [system-ui/theme-ui#1257]
**Describe the bug**
I am trying to us sx prop in my react js file but I am not getting the expected result.
so in my nav.js I have:

```js
import { jsx } from 'theme-ui';
import React from "react";

const skipNavStyles = {
  border: 0,
  clip: `react(0 0 0 0)`,
  height: `1px`,
  width: `1px`,
  margin: `-1px`,
  padding: 0,
  overflow: `hidden`,
  position: `absolute`,
}

const SkipNavLink = (props) => (
  <a {...props} sx={{ ...skipNavStyles }} href="#skip-nav" data-skip-link="true">
    {props.children}
  </a>
)

export default SkipNavLink

```
but end result is like this in the browser inspect:

```html
<a sx="[object Object]" href="#skip-nav" data-skip-link="true">Skip to content</a>
```

**Comment by deckchairlabs** [comment]
You need to specify the jsx pragma at the top of your file.

https://theme-ui.com/sx-prop

**Comment by hasparus** [comment]
`Box` and other components from from `@theme-ui/components` can accept `sx` prop without the pragma, but to use it on a instrinsic element, you need the pragma to make `jsx` function work.

**Comment by lachlanjc** [comment]
What @hasparus said! I’m cool to close this
