### ISSUE TITLE
Implement Theme UI to CSS variables utility transformer

### ISSUE THREAD

**Issue by alex-page** [system-ui/theme-ui#128]
Given a theme-ui object, create usable css variables for ingestion in a front end framework.

**Comment by jxnblk** [comment]
Hey @alex-page! Have you started any work on this? If not, I might pick this up soon

**Comment by alex-page** [comment]
@jxnblk yes let me share my progress. Just been having a hectic few weeks.

**Comment by alex-page** [comment]
Here is a gist with what I was working on. I have some questions around if this package should be creating units for things like `px` and `rem` or if that should be provided in the theme object.

https://gist.github.com/alex-page/fc52e2aea996782e2ef56981e721be1f#file-themeui-css-variables-js

**Comment by alex-page** [comment]
I opened a pull request with a few things to discuss 👍

**Comment by alex-page** [comment]
This is done 🚀
