### ISSUE TITLE
re-renders are triggered even if the style props aren't changed

### ISSUE THREAD

**Issue by alexanderchan** [system-ui/theme-ui#1300]
**Describe the bug**
When `sx` remains constant, the component re-renders on both 0.3.x and 0.4.x-rcs

**To Reproduce**

1. Go to https://91hn6.csb.app/ or [code](https://codesandbox.io/s/frosty-dream-91hn6?file=/src/App.tsx) 

2. In react-dev-tools enable highlights when a component re-renders
3. type in the first input box (emotion `jsx`), see that only the input triggers the highlights
4. type in the second input box (theme-ui `jsx`) see that the input triggers highlights even if the sx prop is hoisted out and is a constant object

**Expected behavior**
Ideally, if the value that is passed in to `sx` doesn't change, then emotion could also use their caching to not re-render.  

**Screenshots**

![Screen Recording 2020-11-25 at 10 58 42 AM](https://user-images.githubusercontent.com/1864372/100265309-501b9f80-2f0d-11eb-8902-64209f283241.gif)

**Additional context**
We probably need to dig into how emotion is able to return the same component if the style stays the same.

**Comment by alexanderchan** [comment]
ahh closing, looks like this is an emotion 11 feature and moving to 0.5.0 alpha fixes it.

**Comment by hasparus** [comment]
Inline `sx` props would still break `memo` / `PureComponent`, right?

@atanasster That's probably something a Babel macro/plugin could do.

**Comment by alexanderchan** [comment]
@hasparus I put together a small babel plugin that might help with it https://github.com/skyverge/kodiak-ui/tree/master/packages/babel-plugin and was just testing it out.  It's actually pretty tiny and should be easy to port here if we think it can help.

**Comment by alexanderchan** [comment]
it looks like even `Box` is rendering fine with inline styles so I'm actually not sure the plugin is needed, although emotion is auto-hoisting in their [plugin code](https://github.com/emotion-js/emotion/blob/1ee34005a5e02c9041b36f73395700f1965388eb/packages/babel-plugin/src/core-macro.js#L31) so 🤷 : 

https://umvvb.csb.app/

![Screen Recording 2020-11-25 at 10 58 42 AM](https://user-images.githubusercontent.com/1864372/100271097-261aab00-2f16-11eb-9fa7-71bfc035298f.gif)

**Comment by alexanderchan** [comment]
thinking about this more, it might be that they have the `css()` wrapper function that gets hoisted probably so that the generation of the results of `css` is only done once.

**Comment by atanasster** [comment]
@alexanderchan - I am a bit behind - do you think we need to incorporate the hoisting in the plugin?

**Comment by alexanderchan** [comment]
@atanasster it looks like theme-ui `0.5.0-alpha` with emotion 11 doesn't have the re-render issue so we can probably go without the plugin for now. I'll keep you posted if I find other cases of re-rendering due to object styles.
