### ISSUE TITLE
bugs from development docs

### ISSUE THREAD

**Issue by hasparus** [system-ui/theme-ui#1319]
1. It seems that something (#1273?) broke how variants compose with mdx styles, what's visible in docs home page.
2. Did `@theme-ui/prism` stop working or did we break something in the docs?

**Comment by lachlanjc** [comment]
for context:

![image](https://user-images.githubusercontent.com/5074763/100681682-45fd0500-3342-11eb-9aa4-eaedaf590dd4.jpeg)

![image](https://user-images.githubusercontent.com/5074763/100681692-4b5a4f80-3342-11eb-8709-db2c89721258.jpeg)

**Comment by atanasster** [comment]
I'll take a look tonight, seems something is off

**Comment by atanasster** [comment]
@hasparus - was there something else besides the Prism code highlighting?

**Comment by hasparus** [comment]
There are link buttons on home page.
![image](https://user-images.githubusercontent.com/15332326/100725016-ce6fba00-33c3-11eb-8c28-28459b4b261f.png)
![image](https://user-images.githubusercontent.com/15332326/100725065-db8ca900-33c3-11eb-9402-76636b0e65b1.png)

I fiddled with it for a while, but this is quite tricky. The color from variant should override color from anchor styles.

**Comment by atanasster** [comment]
Thanks @hasparus - the order for variant sx props is now preserved, and the issue seems fixed

**Comment by atanasster** [comment]
#1326 and #1320 should close this issue

**Comment by lachlanjc** [comment]
Down to 75 issues!! Hurray!
