### ISSUE TITLE
Optional CSS custom properties support for color modes

### ISSUE THREAD

**Issue by jxnblk** [system-ui/theme-ui#134]
Currently the color mode flash prevention only handles foreground and background colors for the `<body>` element, which means that colors used in other elements will still flash on page load. The styles generated by the [`ColorMode` component](https://github.com/system-ui/theme-ui/blob/master/packages/theme-ui/src/color-modes.js#L51-L72) could optionally include all values as CSS custom properties, and the `ThemeProvider` component could map the values used in context to their relevant custom properties instead of raw color values.

This should be an opt-in feature since custom properties are not supported in IE 11.

**Comment by souporserious** [comment]
I messed around with this a couple of weeks ago [here](https://codesandbox.io/s/cocky-bartik-044p7zw0zl). Landed on adding an `includeCSSVariables` prop to `ThemeProvider` that created the CSS properties through Emotion's `Global` component so it should be SSR friendly.

If you think that's similar to what you're thinking I'd be happy to start a PR and discuss things further :)

**Comment by jxnblk** [comment]
@souporserious Awesome! This isn't too far off from what I was thinking. The current `ColorMode` component also uses `Global` (it'd be great if global CSS could generally be avoided though). With theme-ui and color modes, I think it'd make sense for each mode's custom properties were on something like a `.theme-ui-color-<MODE>` selector so that the render-blocking script used on page load would only need to apply a single classname to the `<body>` element

If you're down to start a PR, that'd be great!
