### ISSUE TITLE
adding flags to theme Object not working properly while running gatsby-plugin-theme-ui

### ISSUE THREAD

**Issue by fyrepenguin** [system-ui/theme-ui#1369]
I want to make my site amp-friendly but gatsby-plugin-theme-ui is inserting script 
`<script>(function() { try {
  var mode = localStorage.getItem('theme-ui-color-mode');
  if (!mode) return
  document.body.classList.add('theme-ui-' + mode);
} catch (e) {} })();</script>`

I used all the available flags to make it disappear from final build but none of them worked.

commenting out 
`
export const onRenderBody = ({ setPreBodyComponents }) => {
  setPreBodyComponents([jsx(InitializeColorMode, { key: 'theme-ui-no-flash' })])
}
`
in gatsby-ssr.js is solving my issue temporarily.

**Comment by atanasster** [comment]
Thanks for the report, it's a valid request and we created a PR.
