### ISSUE TITLE
csstype version mismatch

### ISSUE THREAD

**Issue by hasparus** [system-ui/theme-ui#1371]
When installed in user TypeScript project, the return of `css` may be incompatible with `CSSObject` type exported from Emotion due to version mismatch on `csstype`.

---

- `@types/react@16` depends on `csstype@2`
- `theme-ui/css` and `@emotion/serialize` depend on `csstype@3`
- `@types/react@17` depends on `csstype@3`, but dependency update is not a full fix, because many packages still depend on old `@types/react`.

---

We need to stop defining CSSObject ourselves, and reexport the one from Emotion. I did it already on `inject-exact-theme`, but I doubt we'll merge it before 0.6 stable release.

---

**Attachments**

```
Type 'import("/home/hasparus/workspace/homepage/node_modules/@theme-ui/css/dist/types").CSSObject' is not assignable to type 'import("/home/hasparus/workspace/homepage/node_modules/@emotion/serialize/types/index").CSSObject'.
  Types of property 'overflowX' are incompatible.
    Type '"clip" | "-moz-initial" | "inherit" | "initial" | "revert" | "unset" | "hidden" | "auto" | "scroll" | "visible" | "-moz-hidden-unscrollable" | undefined' is not assignable to type '"-moz-initial" | "inherit" | "initial" | "revert" | "unset" | "hidden" | "auto" | "scroll" | "visible" | ("-moz-initial" | "inherit" | "initial" | "revert" | "unset" | "hidden" | "auto" | "scroll" | "visible" | undefined)[] | OverflowX[] | undefined'.
      Type '"clip"' is not assignable to type '"-moz-initial" | "inherit" | "initial" | "revert" | "unset" | "hidden" | "auto" | "scroll" | "visible" | ("-moz-initial" | "inherit" | "initial" | "revert" | "unset" | "hidden" | "auto" | "scroll" | "visible" | undefined)[] | OverflowX[] | undefined'.ts(2322)
```

![image](https://user-images.githubusercontent.com/15332326/102330912-6e177580-3f8a-11eb-8b6f-5730b875693b.png)

**Comment by lachlanjc** [comment]
@hasparus Is this solved by the Emotion change or updates in the last year?

**Comment by hasparus** [comment]
I'm not sure. Do we still define `CSSObject`?

**Comment by lachlanjc** [comment]
Looks like you removed it, if I’m understanding correctly? https://github.com/system-ui/theme-ui/commit/c29011ec877fdaa3498bfbc09534fcf3d449853e

**Comment by hasparus** [comment]
> Looks like you removed it, if I’m understanding correctly?

Brilliant. And of course I forgot to close the issue right after. Thanks.
