### ISSUE TITLE
system color mode

### ISSUE THREAD

**Issue by hasparus** [system-ui/theme-ui#1372]
**Is your feature request related to a problem? Please describe.**

1. I visit a website styled with Theme UI which has `useColorModeMediaQuery` set to true during the evening, and I see dark mode.
2. When I visit it again in the morning next day, there's still dark mode.
3. If I clear my local storage, the website will use light mode.
4. When I visit it later at night, it's still going to be in light mode. 
5. Pretty inconvenient, right?

**Describe the solution you'd like**

1. As a user, I'd like Theme UI to respect my color scheme preference until I change the color mode.
2. As a user, I'd like to be able to go back to this state, effectively chosing "System" color mode.

**Additional context**

At this moment when no color mode value is set in local storage and `useColorSchemeMediaQuery` is set to true, `@theme-ui/color-modes` sets current preference to local storage.

This is a mutation on read, which makes the little functional programmer inside me cry.
I'd like to get rid of this, and instead if there is no color mode set, use system's color scheme.

```tsx
// initialize state
  React.useEffect(() => {
    const stored = theme.useLocalStorage !== false && storage.get()
    document.body.classList.remove('theme-ui-' + stored)
    if (!stored && theme.useColorSchemeMediaQuery) {
      const query = getMediaQuery()
      setMode(query)
      return
    }
    if (!stored || stored === mode) return
    setMode(stored)
  }, [])

  React.useEffect(() => {
    if (!mode || theme.useLocalStorage === false) return
    storage.set(mode)
  }, [mode])
```

**Comment by lachlanjc** [comment]
We already have PR #981 :)

Personally I don't think we should directly change the behavior of `useColorSchemeMediaQuery` to implement this, but should of this behavior & the current one separately: https://github.com/system-ui/theme-ui/pull/981#issuecomment-744634202
