### ISSUE TITLE
[gatsby-theme-ui] required theme location breaks if module resolvers include `/src`

### ISSUE THREAD

**Issue by erikdstock** [system-ui/theme-ui#138]
The problem, in brief: If you are using `src` as a relative module lookup directory, the location of the theme file shadows the actual gatsby-theme-ui module because they have the same name. Could we set the path to the theme file in the plugin options?

```js
// gatsby-node.js

exports.onCreateWebpackConfig = ({ actions }) => {
  actions.setWebpackConfig({
    resolve: {
      modules: [path.resolve(__dirname, "src"), "node_modules"],
    },
  })
}
```
```js
// src/gatsby-theme-ui/index.js
import baseTheme from 'gatsby-theme-ui'  /* Uh oh */

export default {
  ... baseTheme.
  colors: { ...
}

```

**Comment by jxnblk** [comment]
Personally I'd advise against setting a `resolve.modules` field like this – I think this will cause issues generally with the way that Gatsby shadowing is intended to work. What are you trying to import in your example?

**Comment by erikdstock** [comment]
I hear where you are coming from for sure, but this is an architecture choice that some teams have made. It's not exactly pressing for me but an ability to configure the theme path seems like a fair longer-term way to address it. Either way, no big deal.

**Comment by jxnblk** [comment]
I'm not sure there's anything we can address WRT how Gatsby shadowing works from this repo, so closing this out for now. If you're unable to use shadowing with your current setup, you can use the `ThemeProvider` directly instead of the Gatsby plugin
