### ISSUE TITLE
Module not found: Can't resolve 'theme-ui/jsx-dev-runtime' while using the /** @jsxImportSource theme-ui */

### ISSUE THREAD

**Issue by thiniulian** [system-ui/theme-ui#1419]
**Describe the bug**
Replacing the /** @jsx jsx */ with /** @jsxImportSource theme-ui */ results in an error while building.
`Module not found: Can't resolve 'theme-ui/jsx-dev-runtime' in...`

**To Reproduce**

1. Replace /** @jsx jsx */ with /** @jsxImportSource theme-ui */
2. Start building
4. See error `Module not found: Can't resolve 'theme-ui/jsx-dev-runtime' in...`

**Expected behavior**
I would expect everything should work like before.

**Additional context**

I have next.js project where I use theme-ui with the @jsx pragma. I want to update the react version to 17.0.1 and I faced the issue of the automatic runtime. After updating theme-ui to v0.3.5 and searching through the documentation I found that I should use the  /** @jsxImportSource theme-ui */ instead, but replacing the old pragma with this gives me the mentioned error.

**Comment by hasparus** [comment]
Update to `0.6.0-alpha.4`. `0.3.5` doesn't support automatic runtime.
0.6 should be quite stable, but we need to work more on the docs, especially the parts regarding automatic/classic runtime and Babel configuration.

However, new JSX runtime is _opt-in_. You can still use `@jsx` pragma with React 17.
https://reactjs.org/blog/2020/10/20/react-v17.html#new-jsx-transform
> The classic JSX transform will keep working, and there are no plans to stop supporting it.

**Comment by thiniulian** [comment]
Thanks for the fast response! I'll keep using the jsx pragma. Looking forward for the release.

**Comment by flo-sch** [comment]
v0.6.0 is available, this might be closed perhaps?

**Comment by hasparus** [comment]
Yup. Thanks @flo-sch!
