### ISSUE TITLE
Duplicate package @emotion/is-prop-valid through styled-system dependency

### ISSUE THREAD

**Issue by okonet** [system-ui/theme-ui#1420]
**Describe the bug**

When using `DuplicatePackageCheckerPlugin` with the latest version `0.6.0-alpha.4` and `"@emotion/react": "^11.1.4"` and `"@emotion/styled": "^11.0.0"` I'm seeing:

```
warn  - @emotion/is-prop-valid
  Multiple versions of @emotion/is-prop-valid found:
    0.8.8 ./~/@emotion/is-prop-valid
    1.0.0 ./~/@emotion/styled/~/@emotion/is-prop-valid
```

**To Reproduce**

Add https://github.com/darrenscerri/duplicate-package-checker-webpack-plugin to the project using Theme UI and try building.

**Expected behavior**

No duplicated packages should be added to the bundle.

**Additional context**

```
➜ npx npm-why @emotion/is-prop-valid

  Who required @emotion/is-prop-valid:

  monolisa-website > theme-ui > @theme-ui/components > @styled-system/should-forward-prop > @emotion/is-prop-valid@0.8.8
```

so it looks like it's coming from styled-system which is a dependency of Theme UI and probably needs to be updated there.

**Comment by hasparus** [comment]
Thanks for the issue @okonet!
We're planning to drop `@styled-system/should-forward-prop` dependency pretty soon. I'm glad there's yet another reason to do this :D
