### ISSUE TITLE
Styles root, body vs. html

### ISSUE THREAD

**Issue by fcisio** [system-ui/theme-ui#1434]
**Is your feature request related to a problem? Please describe.**
Theme UI root element is `body` which, for most use cases works fine.
There are although some times when you really need to apply styles to to `html` tag.

One of these uses cases is when dealing with `rem` units (which are relative the root `html`). So `rem` units currently do not work with Theme UI.

It would be nice to have a way to target the `html` tag somehow.

**Describe the solution you'd like**
Creating a version of `<Global />` with Theme UI capabilities could be useful.

I'll be working on something like that on one of my projects. We could potentially package it for the library.

I was thinking of a component inside the provider with an instance of Emotion `<Global />` onto which we could inject a part of the Theme Context.

**Additional context**
I'd love to know what you guys think about something like this and if you've experienced similar issues.

**Comment by fcisio** [comment]
Here's my working "hack":

```jsx
import React from 'react'
import { css, useThemeUI } from 'theme-ui'
import { pickBy, omitBy, isObject } from 'lodash'
import { Global } from '@emotion/core'

const ThemeGlobalRoot = ({ key = '_root' }) => {
  const theme = useThemeUI(null).theme.styles[key]
  const _ = (func) => func(theme, isObject)

  return <Global styles={css({ html: _(omitBy), ..._(pickBy) })} />
}

export default ThemeGlobalRoot
```

Theme:

```js
styles: {
  _root: {
    // HTML scope
  },
  root: {
    // default scope
  },
}
```

```jsx
<ThemeProvider theme={theme}>
  <ThemeGlobalRoot />
  {children}
</ThemeProvider>
```

**Comment by atanasster** [comment]
@fcisio i havent encountered such issue, but it seems legit.

for the implementation, have you thought about making it a theme prop - similar to useCustomProps, this way it will all work automatically without the need for another ThemeGlobal?

**Comment by fcisio** [comment]
I think it would be the best solution yes!
I'm looking into a PR, but I'm not familiar with the codebase yet. Could take a while.

I did find a comment from @hasparus dating from a year ago:
`packages/theme-ui/src/index.ts`:

```ts
// TODO: work this into root provider/global styles?
export const BaseStyles = (props: Record<string, unknown>) =>
  jsx('div', {
    ...props,
    sx: {
      fontFamily: 'body',
      lineHeight: 'body',
      fontWeight: 'body',
      variant: 'styles',
    },
  })
```

**Comment by atanasster** [comment]
@fcisio i think you can start here https://github.com/system-ui/theme-ui/blob/90b7c10b2c2533c0126c9e12787997c67778eb39/packages/color-modes/src/custom-properties.ts#L72

You will also need to update the theme typescript types and add some tests.

i will be happy to help out on your PR, i should be back home by Monday.

not sure what @hasparus had in mind with the comments?

**Comment by hasparus** [comment]
Jackson wrote that comment in https://github.com/system-ui/theme-ui/commit/6958fe067d1eb32043959f3a10c561d0b52eb0d1#diff-af7e7c411a6e309962e5827ba35871f56b28123b89869a977ac883a3c7c3d021R22 or even earlier :P

I think we can safely remove it and add a nice jsdoc for BaseStyles instead.

> for the implementation, have you thought about making it a theme prop - similar to useCustomProps, this way it will all work automatically without the need for another ThemeGlobal?

Not a strong opinion here, but I think I'd prefer exporting a new component over adding new config option. **programmable** > **configurable**. A thin wrapper around Emotion's Global sounds good, and it came up in a bunch of issues already.

@fcsio [`BodyStyles`](https://github.com/system-ui/theme-ui/blob/c7081e5178369874a05c1a48e57c409aacaf0bf6/packages/theme-provider/src/index.ts#L13-L13) may be more useful than `BaseStyles` here.

**Comment by hasparus** [comment]
Can we close this? @fcisio
