### ISSUE TITLE
Add Emotion CacheProvider to our top level context provider

### ISSUE THREAD

**Issue by hasparus** [system-ui/theme-ui#1436]
### What's wrong?

All Emotion components which are not under a CacheProvider, create a new CacheProvider, what results in duplicate styles during SSR.

- https://github.com/emotion-js/emotion/issues/1061
- https://github.com/emotion-js/emotion/issues/1061#issuecomment-549562840
- https://github.com/emotion-js/emotion/issues/1061#issuecomment-646168118

[A repro CodeSandbox I and @lachlanjc made while investigating this.](https://codesandbox.io/s/theme-ui-next-ssr-number-of-emotion-style-tags-8kqsp?file=/pages/index.js)

### What needs to be done?

1. We need to wrap React tree in a CacheProvider imported from `@emotion/core` in a top level ThemeProvider.
2. Add a test to make sure no duplicate style tags are emitted

### Tips

- The code that needs to be changed is located in `packages/core/src/index.ts`.
- You can use [cache-provider branch as a starting point](https://github.com/system-ui/theme-ui/compare/cache-provider?expand=1). I already added an if statement testing if the context provider is on top-level.
- [This code sandbox](https://codesandbox.io/s/theme-ui-next-ssr-number-of-emotion-style-tags-8kqsp?file=/pages/index.js) can be helpful to understand the problem and write a test.
- You build the package in question with `yarn workspace @theme-ui/core prepare` and test it with `yarn test core`.

---

cc @lachlanjc (This could be a nice PR to make as _good first issue_ for new contributors, as it's a perf improvement, and not very urgent — we had this problem at least since Emotion 10, maybe even earlier)

**Comment by Zolwiastyl** [comment]
Hi, I've started working on this bad boy!

**Comment by hasparus** [comment]
After thorough testing I don't think this is worth changing on our side as it significantly complicates SSR setup, thus breaking every SSRed app that previously worked out of the box.

https://github.com/system-ui/theme-ui/pull/1717#issuecomment-832647180
