### ISSUE TITLE
Add compatibility with React Fast Refresh

### ISSUE THREAD

**Issue by fcisio** [system-ui/theme-ui#1440]
**Is your feature request related to a problem? Please describe.**

`react-refresh` is the successor for `react-hot-loader`

While using Fast Refresh on a project, changes in the theme don't trigger HMR. Which make sense, since it's supposed to preserve the context and states.

**Describe the solution you'd like**
It would be nice to find a way, to have HMR work on theme changes, while using this feature. Not sure how we could go around this.

**Describe alternatives you've considered**
We could mention, the compatibility issue in the docs.
Gatsby now has a `FAST_REFRESH` flag, which makes it easy to break theme HMR.

**Additional context**
You can test this out on [a repro I did for another issue.](https://github.com/fcisio/repro-theme-ui-broken-keys)
1. Simply set the Fast Refresh flag to true

```js
// gatsby-config.js

flags: {
  FAST_REFRESH: true,
},
```

**Comment by fcisio** [comment]
I realized that I've been getting this error with HMR all along.
And using fast refresh just skip full reload altogether.

Is it an issue on my end or Theme UI is simply not working with HMR at all so far?

![ScreenShot 2021-02-15 at 3 33 20 PM](https://user-images.githubusercontent.com/46095852/107990910-7ea49600-6fa3-11eb-961d-dada2e880dad.png)

**Comment by hasparus** [comment]
That theme/index.js is just a big JavaScript object with a bunch of colors and styles inside, right? How does that conflict with Fast Refresh?

**Comment by fcisio** [comment]
Essentially, without Fast Refresh, changes trigger full reload (logs above).
But when using Fast Refresh, changes to the theme don't trigger anything at all. No full reload nor HMR.

The same thing happens when the theme lives in `gatsby-plugin-theme-ui`.

**Comment by pieh** [comment]
Hi, just wanted to mention that this issue is most likely fully `gatsby` issue. I'm using reproduction you provided (thank you @fcisio!) to come up with proper fix for it there (work in progress PR https://github.com/gatsbyjs/gatsby/pull/29752)

**Comment by fcisio** [comment]
Hey @pieh great to hear! I'll be following your PR.
Thanks

**Comment by fcisio** [comment]
Hey, @pieh I believe your Gatsby PR has been merged on v3, that's awesome!
Any chance you could help us with this issue? I think some logic from that PR could be useful here.

Thanks.
