### ISSUE TITLE
Setting up preset using `gatsby-config` doesn't work in v0.3.5

### ISSUE THREAD

**Issue by amilosmanli** [system-ui/theme-ui#1443]
**Describe the bug**
Trying to setup preset in `gatsby-config` for `gatsby-plugin-theme-ui` doesn't work. Followed [this](https://www.gatsbyjs.com/docs/how-to/styling/theme-ui/#gatsby-plugin-theme-ui-configuration) and the [README](https://github.com/system-ui/theme-ui/tree/develop/packages/gatsby-plugin-theme-ui) of the plugin itself, but still no luck.

I want to change preset dynamically from API during the build.

**To Reproduce**

https://codesandbox.io/s/purple-river-z8tbg?file=/gatsby-config.js

**Comment by xaviemirmon** [comment]
Hey @cyberlake,

I ran into the same issue and spent quite a few hours debugging.  After a bunch of playing, I think I might have a solution.  The latest stable version is quite behind (0.3.5) if you upgrade to the alphas it should start to work.  If you run one of the following commands it should fix the issue:

`npm i theme-ui@^0.5.0-alpha.6 gatsby-plugin-theme-ui@0.6.0-alpha.6`
or
`npm i theme-ui@next gatsby-plugin-theme-ui@next`

I hope that helps!

**Comment by amilosmanli** [comment]
Hey @xaviemirmon,

Thanks for the workaround. Seems that this is working. Although, don't know how much we can trust alpha version. Since your comment, there's another version released.

**Comment by hasparus** [comment]
Hey @cyberlake, it should be quite stable, but we want to squash a few bugs and work on some internals/ops stuff before a stable release.

If you find any problems with the alpha, feel free to ping me on our [Discord](https://discord.gg/stp6BY7MXA).
I'd advise to lock the version without caret `^` in your package.json to ensure more stability.

**Comment by xaviemirmon** [comment]
Hey @hasparus and @cyberlake FWIW I haven't noticed any problems when I tried it out on my site.  (It's just in development though)

**Comment by hasparus** [comment]
I'll close this. Theme UI 0.6 was published as stable version. If somebody really needs to backport preset in gatsby-config to 0.3.5, we'll accept a PR.
