### ISSUE TITLE
sx prop does not correctly apply theme in nested ThemeProviders with ColorMode

### ISSUE THREAD

**Issue by rezavation** [system-ui/theme-ui#1456]
**Describe the bug**

When having an application that has a nested ThemeProviders with the same theme and color modes but different values, toggling the colorMode changes the colorMode and theme in both the top level and nested theme provider, but when utilizing that theme in the nested component with the sx prop, the wrong colour gets applied.

**To Reproduce**
Here is a simple codesandbox that reproduces the issue. https://codesandbox.io/s/exciting-banzai-hrjom?file=/src/index.js
**Expected behavior**

In the example provided, I would expect the inner components background value for light mode to be "darkcyan", and it is if you print out the theme object. But when its applied to the div using `sx={{ bg: "background" }}` it applies "red".

<img width="492" alt="Screenshot 2021-01-21 at 11 48 01" src="https://user-images.githubusercontent.com/8388676/105347253-8f4d3080-5bde-11eb-8486-4a1f2eceac4f.png">

![Kapture 2021-01-21 at 11 54 02](https://user-images.githubusercontent.com/8388676/105347954-86a92a00-5bdf-11eb-862e-406dcf6a33c4.gif)

**Comment by hasparus** [comment]
Hi rezaabedian 👋
Thanks for the issue!

**Comment by hasparus** [comment]
Okay, currently only ColorModeProvider updates its inner emotion context with updated theme, and nested theme providers don't render ColorModeProvider.

![image](https://user-images.githubusercontent.com/15332326/105415956-c0a71a00-5c39-11eb-8113-4d9c9ce623ae.png)

We should split _providing_ and _consuming_, and start respecting the color mode in `@theme-ui/theme-provider`.

**Comment by rezavation** [comment]
Any ideas how we can fix it?

**Comment by atanasster** [comment]
Short of rewriting `ColorModeProvider` I dont see how to fix it. Hope I am missing something as it looks like a significant work, including avoid cross require and keep backward compatibility (to have one ColorModeProvider that can be *inside* or *outside* of (multiple) ThemeProvider).

@hasparus ?

**Comment by hasparus** [comment]
> @hasparus ?

We could split CollorModeProvider into actual React context provider and consumer?
Provide color mode in top level ThemeProvider (from theme-provider package, not core), consume in all ThemeProviders.

**Comment by hasparus** [comment]
@atanasster @rezaabedian does one of you guys want to work on this?

**Comment by rezavation** [comment]
Happy to try to help, but will probably need some assistance. @hasparus

**Comment by hasparus** [comment]
@rezaabedian Sweet! Thanks! Of course, I'm here to help.

Here's ColorModeProvider: https://github.com/system-ui/theme-ui/blob/develop/packages/color-modes/src/index.tsx#L126-L153
And here's the ThemeProvider: https://github.com/system-ui/theme-ui/blob/develop/packages/theme-provider/src/index.ts#L44-L75

- ColorModeProvider now both _keeps the state_ and _uses it to affect EmotionContext_. I think these are two different responsibilities.
- We'd like nested ThemeProviders respect color mode and affect EmotionContext, but we don't want them to have their own color modes (by default, as nested toggles wouldn't be comfortable).

_contributing tips:_

As the full repo build takes a while (I'm working on it, but not so trivial) you build only the packages you're changing with 

```
yarn workspace @theme-ui/css prepare
```

There's just one Jest project in the entire repo, and you run a subset of tests like this:

```
yarn test css
```

**Comment by rezavation** [comment]
Hi @hasparus , I didn't get an opportunity to look at this yet. Is there any chance one of the existing maintainers of theme-ui will be able to tackle it?
