### ISSUE TITLE
(theme-ui): Add support for sx prop to BaseStyles component

### ISSUE THREAD

**Issue by lachlanjc** [system-ui/theme-ui#1470]
**Is your feature request related to a problem? Please describe.**
It's frustrating to have any DOM nodes that don't allow styling, especially when they're provided by Theme UI.

**Describe the solution you'd like**
To be consistent with #1350, let's support `sx` on the `BaseStyles` component.

**Additional context**
https://github.com/system-ui/theme-ui/blob/develop/packages/theme-ui/src/index.ts#L27

**Comment by hasparus** [comment]
:rocket: Issue was released in [`v0.14.0`](https://github.com/system-ui/theme-ui/releases/tag/v0.14.0) :rocket:
