### ISSUE TITLE
properties leaking through

### ISSUE THREAD

**Issue by atanasster** [system-ui/theme-ui#1471]
**Describe the bug**
Object properties are leaking from the pagination component 

**To Reproduce**
1. go to a page with pagination : https://theme-ui.com/getting-started
2. Observe the pagination component:

![sidebar-props](https://user-images.githubusercontent.com/6075606/105801800-f0bb2980-5f67-11eb-976b-0eab45a78bad.png)

**Comment by hasparus** [comment]
:rocket: Issue was released in [`v0.14.0-develop.2`](https://github.com/system-ui/theme-ui/releases/tag/v0.14.0-develop.2) :rocket:

**Comment by hasparus** [comment]
:rocket: Issue was released in [`v0.14.0`](https://github.com/system-ui/theme-ui/releases/tag/v0.14.0) :rocket:
