### ISSUE TITLE
alpha docs sidebar scrollbar doesn't take it's full height

### ISSUE THREAD

**Issue by hasparus** [system-ui/theme-ui#1512]
![image](https://user-images.githubusercontent.com/15332326/108112033-d6bbc500-7095-11eb-9989-e30ce151bb5b.png)

**Comment by evanfrawley** [comment]
Cause: once stickied, the max-height is still at `calc(100vh - 64px)` when it should go to `100vh`

Probably need to use an intersection observer + some JS to fix this. Found [this article](https://davidwalsh.name/detect-sticky) that might be useful
