### ISSUE TITLE
Consider adding non-markdown elements to `Styled`

### ISSUE THREAD

**Issue by jxnblk** [system-ui/theme-ui#152]
Some HTML elements might be expected to exist in the `Styled` components, e.g. `Styled.button`, but don't currently. It's probably not harmful to add a few more common elements to the mix.

**Comment by connorholyday** [comment]
This idea makes sense to me as I'm using theme-ui for both HTML (landing page) and markdown (blog). Adding all of my base elements to the theme config keeps things nice and tidy without having to look-up which elements markdown doesn't support -  or double checking my variants for those extra elements. Then markdown can pick up all of the `Styled` components it needs and I have one section for all of my base elements.

Is it as simple as updating the `tags` array [here](https://github.com/system-ui/theme-ui/blob/master/packages/theme-ui/src/components.js)?

**Comment by jxnblk** [comment]
Yes, but we'll want to still limit *which* tags we add here since they'll increase the overall bundle size and cannot be tree-shaken

**Comment by connorholyday** [comment]
I see! Forgive me if this is a silly question, but could these extra non-markdown elements be generated by mapping over the `theme.styles` keys? Thinking along the lines of letting people define what they need up-front via the theme config

**Comment by jxnblk** [comment]
I guess they *could* be created based on `theme.styles`, but that would probably require creating components during render, which is generally not good for performance

**Comment by connorholyday** [comment]
Oh okay that's interesting, in that case is using variants different from creating components during render? (have you got any links where I can read more about this?)

As for element suggestions, how about the base form elements: `form`, `label`, and `input`

**Comment by jxnblk** [comment]
There are some docs here, but they certainly could use some work: https://theme-ui.com/guides/variants

Variants use the theming context available in the `sx` prop to add the styles, so it's a bit different from creating a React component. As far as *which* elements, you could start a PR for discussion, if you're interested in taking a stab at it
