### ISSUE TITLE
Improve Spinner performance

### ISSUE THREAD

**Issue by lbebber** [system-ui/theme-ui#1547]
**Is your feature request related to a problem? Please describe.**
Right now, due to how the [Spinner component is implemented](https://github.com/system-ui/theme-ui/blob/develop/packages/components/src/Spinner.js#L29-L63), it increases the CPU usage, due to causing re-layouts on the page

(notice the layouts/sec and style recalc/sec measurements at the bottom, along with CPU usage at the top)
<img width="222" alt="Screen Shot 2021-03-04 at 22 53 14" src="https://user-images.githubusercontent.com/5691711/110060405-a0906d80-7d44-11eb-9b7a-77f5bf15dca4.png">

This is because [animating an element of an SVG](https://github.com/system-ui/theme-ui/blob/develop/packages/components/src/Spinner.js#L47-L61) triggers this event (at least on Chrome 88 on desktop) and is not (fully?) GPU accelerated.

**Describe the solution you'd like**
Spinning a DOM element--for example, an entire SVG element, instead of just a part of it--fixes this issue.
<img width="224" alt="Screen Shot 2021-03-04 at 22 51 41" src="https://user-images.githubusercontent.com/5691711/110060637-f9600600-7d44-11eb-92e9-e95f8a5e08a2.png">

This could be done without making any changes to the visuals of the spinner element as it is.

**Describe alternatives you've considered**

**Additional context**

**Comment by hasparus** [comment]
Thanks for the issue @lbebber! Great catch!

**Comment by hasparus** [comment]
:rocket: Issue was released in [`v0.15.5-develop.2`](https://github.com/system-ui/theme-ui/releases/tag/v0.15.5-develop.2) :rocket:

**Comment by hasparus** [comment]
:rocket: Issue was released in [`v0.15.5`](https://github.com/system-ui/theme-ui/releases/tag/v0.15.5) :rocket:
