### ISSUE TITLE
Support for Gatsby v3

### ISSUE THREAD

**Issue by laurieontech** [system-ui/theme-ui#1563]
Currently the peer deps cause issues. Should upgrade that and publish a new alpha.

**Comment by hasparus** [comment]
Closed by 55dab22f6c17286dbbfd806ba281f4d310da4548 and released with `0.6.0-alpha.8`.

**Comment by fcisio** [comment]
@hasparus 🙌

**Comment by t2ca** [comment]
~~Im still getting the warning, I believe i updated everything to the latest version.~~
My mistake
