### ISSUE TITLE
Possible to use styled syntax from '@emotion/styled' with theme-ui?

### ISSUE THREAD

**Issue by ehowey** [system-ui/theme-ui#158]
Hello,

I wrote some Gatsby themes using Styled Components and their baked in ThemeProvider API to create something similar, but less robust, than theme-ui.  Now that themes have officially been released it seems that the "way-to-go" is using the Theme-UI framework and accompanying set of tools.  I originally chose Styled Components because I liked the ability to write 'normal' CSS using the `const Header = styled.header` syntax.  Coming from more of a CSS/HTML background this made sense to me and let me continue using semi-colons which I was used to while allowing me to also use design tokens which I could pass down to child themes and starter sites using component shadowing.

I am planning to migrate the work I have done to the Theme-UI and Emotion styling systems and was wondering if there was any way to do this while keep the syntax and format I am familiar with, e.g. styled.div or styled.(Img)?  And if I do this can I still refer back to the theme-ui theme like I have been doing with the ThemeProvider from styled components?  Or is it really best to transition to the `{sx}` pragma you talk about in the docs?  My strong preference is to write old-school normal CSS but with the power of CSS-in-JS. 

You can see a bit of what I am trying to do in this repository: 

https://github.com/ehowey/gatsby-theme-catalyst-core

It is on NPM but the package on there is a bit out of date as I have been working on it locally in a Yarn workspace.

**Comment by jxnblk** [comment]
If you've already started a library of components with `styled-components`, generally you should be able to swap the import to `import styled from '@emotion/styled'` and they should still work (even with embedded string/template literal syntax). There are a few minor differences, e.g. Emotions doesn't have the `.attr()` API, but I'd recommend avoiding most of the one-off APIs like that. Whether or not you use the `sx` prop is up to you, but if you're using `styled` components, you can optionally use https://styled-system.com, which follows the same theme-spec/naming convention and should work well with the core parts of the theme-ui library.

All that said, theme-ui is completely optional for Gatsby themes, but the more themes that use it, the more things will "just work", and theme authors will be able to take advantage of some of the other things we're planning to work on

**Comment by ehowey** [comment]
Thanks Jackson. Amazing work on this by the way!

I think I am gonna just do some refactoring to try and use the sx pragma. I am more of a hobbyist dev with a wordpress background, a lot of this is brand new for me. I really appreciate all the emphasis on good docs for both Gatsby and theme-ui.

**Comment by jxnblk** [comment]
Yeah, of course!

FWIW, we don't have any docs specifically around this, but if you go the route of using `sx` (or `css`) prop, you can always create custom styled-components-like components by wrapping a single element and handling the props like you would in any React component:

```jsx
const Box = ({ width, ...props }) =>
  <div
    {...props}
    sx={{
      width,
    }}
  />
```

**Comment by kutyel** [comment]
I have visual componentes declared with `@emotion/styled` and they are not able to fetch the **theme colors** from the `ThemeProvider`, should they be prefixed with a special symbol ($, @) or something? Calling them as "strings" does not work 😕

**Comment by arnaudjnn** [comment]
I get the following error when using theme-ui with emotion.

```
const SomeText = styled.div`
  color: ${props => props.theme.colors.primary};
`
```
```
Property 'colors' does not exist on type 'object'
```

**Comment by chaddjohnson** [comment]
> I get the following error when using theme-ui with emotion.
> 
> ```
> const SomeText = styled.div`
>   color: ${props => props.theme.colors.primary};
> `
> ```
> 
> ```
> Property 'colors' does not exist on type 'object'
> ```

Old thread, but for completeness, using the `css` helper [like so](https://github.com/system-ui/theme-ui/issues/841#issuecomment-613672399) should let you reference the theme.
