### ISSUE TITLE
Attempted import error: 'Switch' is not exported from 'theme-ui'.

### ISSUE THREAD

**Issue by dukedhx** [system-ui/theme-ui#1583]
**Describe the bug**
Attempted import error: 'Switch' is not exported from 'theme-ui'. (Other imports are working properly)

**To Reproduce**

1. Start a Next.js project
2. import `Switch` into your component
3. Run the app and the said error occurs

**Expected behavior**
The `Switch` component should be imported from `theme-ui`

**Additional context**
```
\\ myComponent.tsx
import {Flex,Box,Link,Button,Label,Spinner,Switch} from 'theme-ui'
```

```
\\package.json
  "dependencies": {
    "@now/node": "^1.8.5",
    "@theme-ui/presets": "^0.3.5",
    "basic-auth": "^2.0.1",
    "next": "^9.3.1",
    "node-fetch": "^2.6.0",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-viewer": "^3.2.2",
    "sass": "^1.32.8",
    "theme-ui": "^0.3.5"
  },
```

**Comment by lachlanjc** [comment]
Hey! Switch isn't available in that version—it's from quite awhile ago. Try upgrading to the new 0.6.0! :)

**Comment by dukedhx** [comment]
@lachlanjc thanks so much for the swift response! All sorted!
