### ISSUE TITLE
'px' values don't seem to work for breakpoints

### ISSUE THREAD

**Issue by erikdstock** [system-ui/theme-ui#159]
See example [here](https://codesandbox.io/s/theme-ui-color-mode-demo-jgmvu) with the note in the theme file:

with default `em` units (sorry for beachball, hot summer is not kind to my old mac):
![2019-07-04 12 42 15](https://user-images.githubusercontent.com/9088720/60680450-60833400-9e59-11e9-9454-444ed81254a4.gif)

with `px` units
![2019-07-04 12 42 46](https://user-images.githubusercontent.com/9088720/60680452-62e58e00-9e59-11e9-839d-d1ba9d95ab0b.gif)

**Comment by jxnblk** [comment]
The example you linked to *seems* to work (https://ipv4m.codesandbox.io/), but I did notice that the way you've used the `Layout` component (which includes `display: flex`) is keeping the page at a min-width which might be causing issues with Code Sandbox's preview

**Comment by erikdstock** [comment]
Hmmm, not sure I follow but happy to close if you don't think it is an issue...

On second look it appears that the browser preview in codesandbox doesn't respond correctly to px values, but when i click the open in new window button it works as expected.
