### ISSUE TITLE
Error: importSource cannot be set when runtime is classic.

### ISSUE THREAD

**Issue by corbpaul** [system-ui/theme-ui#1596]
**Describe the bug**
When using `theme-ui@0.6.0` and `gatsby@3.1.1` I get the error message `importSource cannot be set when runtime is classic.` 

**To Reproduce**
* add `/** @jsxImportSource theme-ui */` to the top of the file
* I have a `.babelrc` that sets runtime to automatic via `@babel/plugin-transform-react-jsx` and `@babel/preset-react`
* if I set the runtime via a comment at the top of the file I get the error `pragma and pragmaFrag cannot be set when runtime is automatic.`

Use branch https://github.com/corbpaul/gatsby-content-demo/tree/logo-icon-component and run `yarn storybook` to replicate

**Expected behavior**
HTML element should render with the correct value

**Screenshots**

**Additional context**

**Comment by jinhyuk** [comment]
As you know, Gatsby uses [babel-preset-gatsby](https://github.com/gatsbyjs/gatsby/tree/master/packages/babel-preset-gatsby) as the default preset. so You can solve the problem when you set reactRuntime to `automatic` in babel-preset-gatsby using .babelrc.

```json
{
  "plugins": [["@babel/plugin-proposal-decorators", { "legacy": true }]],
  "presets": [
    [
      "babel-preset-gatsby",
      {
        "reactRuntime": "automatic",
        "targets": {
          "browsers": [">0.25%", "not dead"]
        }
      }
    ]
  ]
}
```

**Comment by nrakochy** [comment]
I ran into this as well in a context outside of `gatsby`. A potential fix for future travelers  

```js
      {
                test: /\.(js|jsx|ts|tsx)$/,
                exclude: /node_modules/,
                loader: "babel-loader",
                options: {
                    presets: [
                        ["@babel/preset-env"],
                        "@babel/preset-typescript",
                        [
                            "@babel/preset-react",
                            {
                                runtime: "automatic",
                                importSource: "react"
                            }
                        ]
                    ],
                    plugins: ["@babel/proposal-class-properties", "@babel/proposal-object-rest-spread"]
                }
            },
```

**Comment by hasparus** [comment]
As a note, you can also configure this within TypeScript config with

```
"jsx": "react-jsx",
"jsxImportSource": "theme-ui" 
```

https://www.typescriptlang.org/tsconfig#jsxImportSource

---

@nrakochy Just FYI, If you change `importSource` in your preset-react config from "react" to "theme-ui" you won't use the pragma comment to configure Theme UI JSX pragma per file. This has some small performance impact, so I wouldn't do this if I didn't use  `sx` a lot.

---

@lachlanjc don't close this issue yet. Let's improve the docs on using Theme UI within and outside of Gatsby, and keep this open for "future travelers' until we do.

**Comment by nrakochy** [comment]
> As a note, you can also configure this within TypeScript config with
> 
> ```
> "jsx": "react-jsx",
> "jsxImportSource": "theme-ui" 
> ```
> 
> https://www.typescriptlang.org/tsconfig#jsxImportSource
> 
> @nrakochy Just FYI, If you change `importSource` in your preset-react config from "react" to "theme-ui" you won't use the pragma comment to configure Theme UI JSX pragma per file. This has some small performance impact, so I wouldn't do this if I didn't use `sx` a lot.

Ah yes thanks 👍 . I will check it out

**Comment by fwextensions** [comment]
FWIW, after creating a new site with Gatsby v4 and trying to style the `Link` component from there, I created a `.babelrc` file with @jinhyuk's code.  But I had to remove the `plugins: ...` line, because none of the babel plugins had been installed.  After that, I could style the link with `sx` while retaining its prefix paths behavior.
