### ISSUE TITLE
Opt into Babel transpilation in gatsby-plugin-theme-ui (?)

### ISSUE THREAD

**Issue by aaronadamsCA** [system-ui/theme-ui#1598]
I'm getting an IE 11 error on my Gatsby production site, despite using its standard Babel config that should support IE 11.

This line is responsible:

https://github.com/system-ui/theme-ui/blob/4b34c2c8ca1d553806b07d30009d1aa49bad767e/packages/color-modes/src/index.tsx#L62

Unfortunately IE 11 doesn't implement `NodeList.forEach`.

~~It should be possible for a module to opt into Gatsby's Babel transpilation by adjusting its Webpack configuration in `gatsby-node.js`. I think that would be a good feature to add to gatsby-plugin-theme-ui, to opt in `theme-ui` and `@theme-ui/*`, so that the theme is always transpiled by Babel to be compatible with the set of browsers defined in the site's Babel configuration.~~

As far as I can tell, since Gatsby v3 includes core-js v3, and core-js v3 includes a polyfill for `NodeList.forEach`, this should be working out of the box. 🤷‍♂️

**Comment by hasparus** [comment]
Thanks for the issue, @aaronadamsCA!

**Comment by aaronadamsCA** [comment]
No problem @hasparus, after further investigation I got the feeling it was upstream:

https://github.com/gatsbyjs/gatsby/issues/30473

Looks like it'll be fixed in the next Gatsby point release. 👍

**Comment by aaronadamsCA** [comment]
Gatsby has fixed the upstream problem, and Theme UI no longer supports IE 11 anyway, so I'm closing this. Thanks!
