### ISSUE TITLE
Document the Highlight Color Variable

### ISSUE THREAD

**Issue by jayliu50** [system-ui/theme-ui#1600]
**Is your feature request related to a problem? Please describe.**
I spent many hours trying to override what I later found out was the `highlight` color variable, used in a number of Components in the code. I had no idea that this variable existed. :(

**Describe the solution you'd like**
Maybe just include the `highlight` default value in the base theme, so that developers building on that would know that it exists (i.e., that the code will USE it), so that they can more readily override it.

**Describe alternatives you've considered**
Also, please update the docs that the `highlight` variable is used in all the relevant example `theme` json objects, such as in https://theme-ui.com/components/forms  and https://theme-ui.com/color-modes. 

**Additional context**
It took me so many hours to figure out how to override this `:focus` style, because I didn't know about `highlight`. Had it been called out, I would have know about it and overridden it to my needs. Without knowing, I was stuck with this:
![image](https://user-images.githubusercontent.com/673862/112404845-81538300-8ce7-11eb-9948-50fadd0a6cbd.png)

**Comment by hasparus** [comment]
:rocket: Issue was released in [`v0.12.0`](https://github.com/system-ui/theme-ui/releases/tag/v0.12.0) :rocket:
