### ISSUE TITLE
Consider allowing freeform scales for shadows

### ISSUE THREAD

**Issue by chrisdhanaraj** [system-ui/theme-ui#161]
Hello!

Not entirely sure if this is where to put this, but just wanted to open up an issue around freeform scales on shadows. Generally, my shadow usage corresponds to an elevation level, so in my head, I'd prefer to be able to do something like 

```
{
	boxShadow: 'standard.3'
}
```

versus explicitly naming each shadow.

Thanks!

**Comment by chrisdhanaraj** [comment]
Ah I think I just had typo'd somewhere! It seems to be working fine to pass an array in, sorry!

**Comment by jxnblk** [comment]
No worries! Any of the theme scales *should* support objects, arrays, or any combination of nested objects (there is a bug with `theme.breakpoints` currently), and theme values can be used with dot syntax like you have above
