### ISSUE TITLE
Idea - responsive toTheme with @theme-ui/typography

### ISSUE THREAD

**Issue by rjgux** [system-ui/theme-ui#162]
Using `toTheme` from `@theme-ui/typography` works really nicely to create our theme object for Theme UI, but it doesn't create any responsive styles.

The way I'm getting around this is to override individual elements within `styles`, like so -

```
const typography = toTheme({
  baseFontSize: "20px",
  baseLineHeight: 1.5,
  scaleRatio: 3,
  headerFontFamily: [
    "Avenir Next",
    "Helvetica Neue",
    "Segoe UI",
    "Helvetica",
    "Arial",
    "sans-serif",
  ],
  bodyFontFamily: ["Georgia", "serif"],
})

export default merge(typography, {
  // optional style overrides go here
  styles: {
    h1: {
      fontSize: [3, 4, 5],
    },
  },
})
```

The problem is I would need to create a lot of overrides to handle every element responsively. I wonder whether it would be possible to have a `responsive: bool` option with `toTheme` that generates an array/scale within `styles` based on the default breakpoints? 

Being able to do something like this might be even better -

```
const typography = toTheme({
  baseFontSize: ["14px", "20px"]
})
```

There may be a better way of doing this, thinking out loud!

**Comment by jxnblk** [comment]
Thanks! This is an interesting idea – something I've thought a little bit about, but don't have a solid direction for yet. Currently, there is a bug where responsive styles in the `theme` can cause issues when overriding responsive values, see #43 – I think changing how the core merges the `theme.styles` object might help resolve this issue, and I'm planning on looking into that soon

Generally, though, I would like to have a better API for handling default responsive styles like this

**Comment by jxnblk** [comment]
Closing this out since there hasn't been much traction on this, but feel free to open a PR if anyone wants to look into this
