### ISSUE TITLE
Typings do not allow numbers for borderTopWidth in @theme-ui/css

### ISSUE THREAD

**Issue by skrivanos** [system-ui/theme-ui#1621]
**Describe the bug**
It seems like borderTopWidth is included in OverwriteCSSProperties for seemingly no reason (no other border width properties are included here) and thus does not allow numbers.

**Comment by hasparus** [comment]
Good catch! Thanks for the issue @skrivanos!

**Comment by hasparus** [comment]
Bugfix released with 0.6.2.
