### ISSUE TITLE
'system' export from styled-system

### ISSUE THREAD

**Issue by Bram-Zijp** [system-ui/theme-ui#1638]
**Is your feature request related to a problem? Please describe.**
I really dig the power the following import gives: `import { system, ResponsiveValue } from "styled-system";`
This allows one to make any prop respsonive. One of my use-cases is an AspectRatio component. I pass it an aspect ratio and it can change based on a passed `ResponsiveValue`

**Describe the solution you'd like**
Exporting the system util in theme-ui or something similar.

**Describe alternatives you've considered**
Import `system` from `styled-system` and use it next to `theme-ui`

**Additional context**
It could be that there are better practices. Perhaps it's an idea to document these if they do not already exist.
There is also the possibility to make something similar yourself, I just really liked the introduction to the sort of API in `styled-system`.

**Example**
```
export const ratioSystem = system({
  ratio: {
    property: "paddingBottom",
    scale: "space", // I think this is only here as I had to define something
    transform: (value) => {
      return value ? `${100 / value}%` : false;
    },
  },
});
```

**Comment by lachlanjc** [comment]
Is there any reason for Theme UI to export it instead of just accessing it directly from styled-system? What's the advantage of it being bundled?

**Comment by fcisio** [comment]
I remember using a lot of custom `system` in Styled System.
When I switched to Theme UI, I was able to get the same results using only variants.

It alleviated a lot of complexity from the codebase, and in the end, I realized I didn't need this level of responsiveness from props.

To me, this feature is not inlined with Theme UI. I recommend you try to use variants instead and import `system` from `styled-system` when truly needed.

---

> Here's a refactoring example to illustrate my point, try combining variants with CSS Custom Properties.

```js
// '--aspect-ratio': ['1/1', '16/9', '2/3'],
'::after': {
  content: '""',
  pb: 'calc(100% / (var(--aspect-ratio)))'
}

```

And implemented with a custom prop
```js
const Component = ({ ratio, sx, ...props }) => (
  <Box sx={{ '--aspect-ratio': ratio, ...sx }} {...props} />
)

<Component ratio={['1/1', '16/9', '2/3']} />
```

PS: I've been 👀   at the [aspect-ratio](https://caniuse.com/mdn-css_properties_aspect-ratio) CSS property for a while now. When it gets enough support, we could simply create an aspect-ratio scale, which would allow using predefined ratios in responsive arrays. EX: `{ aspectRatio: ['video', 'portrait', 'landscape', 'square'] }`

**Comment by Bram-Zijp** [comment]
> Is there any reason for Theme UI to export it instead of just accessing it directly from styled-system? What's the advantage of it being bundled?

Not really, perhaps under the hood of theme-ui, a similar or more simple function is available for export. I wanted to put it open for debate and see what other peoples thoughts on this are.


@fcisio That is a nice way to solve it too. Considering support for IE11 is dropped in most of my projects, this should be a neat solution for my use cases.

Another possibility would be to create a tiny converter helper function. This would probably tackle most my use cases and have support for IE11. e.g.

```
const responsiveValue = (value, converter) => {
  const convertValue = (value) =>
    value || value === 0 ? converter(value) : value;

  if (Array.isArray(value)) {
    return value.map(convertValue);
  } else if (typeof value === "number" || typeof value === "string") {
    return convertValue(value);
  }
  return value;
};


const Component = ({ ratio, sx, ...props }) => (
  <Box sx={{ pb: responsiveValue(ratio, (value) => `${100 / value}%`), ...sx }} {...props} />
)
```
