### ISSUE TITLE
v 0.6.2 warning installing

### ISSUE THREAD

**Issue by estaub** [system-ui/theme-ui#1655]
**Describe the bug**

theme-provider/package.json calls for css 0.6.0, but css 0.6.2 is what's included in 0.6.2.
I'd guess that the css dependency just needs to be updated, but you know better.

**To Reproduce**

npm i theme-ui 

**Screenshots**

```
C:\Users\estau\git\try-vite>npm i theme-ui
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: @theme-ui/css@0.6.2
npm WARN node_modules/@theme-ui/css
npm WARN   @theme-ui/css@"^0.6.2" from theme-ui@0.6.2
npm WARN   node_modules/theme-ui
npm WARN     theme-ui@"*" from the root project
npm WARN   4 more (@theme-ui/color-modes, @theme-ui/components, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer @theme-ui/css@"0.6.0" from @theme-ui/theme-provider@0.6.2
npm WARN node_modules/@theme-ui/theme-provider
npm WARN   @theme-ui/theme-provider@"^0.6.2" from theme-ui@0.6.2
npm WARN   node_modules/theme-ui

```

**Comment by lachlanjc** [comment]
Hmm, thanks for reporting! I'm not sure exactly where this issue lays at a cursory glance, but I suspect it's something tiny. @hasparus?

**Comment by hasparus** [comment]
Yeah, a peer dependency wasn't updated on deploy. Sorry for this! It's 100% safe to disregard.

**Comment by hasparus** [comment]
This should be already fixed in the newest version. Please reopen if you still see the warning after updating to 0.7.
