### ISSUE TITLE
Make `textDecorationColor` use Variable Colours

### ISSUE THREAD

**Issue by sampoder** [system-ui/theme-ui#1666]
**Is your feature request related to a problem? Please describe.**

Kind of, bit of a pain in dev.

**Describe the solution you'd like**

For the same thing to happen for `color` and `textDecorationColor`
<img width="262" alt="Screenshot 2021-04-24 at 7 06 58 PM" src="https://user-images.githubusercontent.com/39828164/115956620-69625f80-a530-11eb-9044-8dc708adaf57.png">
<img width="374" alt="Screenshot 2021-04-24 at 7 06 45 PM" src="https://user-images.githubusercontent.com/39828164/115956623-6a938c80-a530-11eb-80df-04acb12c0d81.png">

Thanks for reading my request!

**Comment by fcisio** [comment]
Hey, in addition to the PR, I would recommend the use of the `currentColor` CSS property.

It works like this:

```js
color: 'elevated',
textDecorationColor: 'currentColor'
```

This property allows affecting the value of the `color` property to any other property.
It's a bit more efficient way to handle that kind of use case. This way you can define the color only once.

So if you have to change the color at any point you can change it in a single place.
Hope this helps 👋

**Comment by lachlanjc** [comment]
That's a great tip! I use it all the time. I wonder if there's any spot in the docs it'd be good to just mention that CSS technique @fcisio?

**Comment by fcisio** [comment]
@lachlanjc Yeah good idea!
Perhaps a note right under the first paragraph of this section [Theme-Aware Properties](https://dev.theme-ui.com/sx-prop#theme-aware-properties)

Something like:

> GOTCHA 💡: Before using "Theme-Aware Properties", see if the [currentColor](https://css-tricks.com/currentcolor/) CSS Property is a good fit for your use case.

**Comment by sampoder** [comment]
oh that's great, thank you for the tip @fcisio !

**Comment by hasparus** [comment]
:rocket: Issue was released in [`v0.7.4-develop.2`](https://github.com/system-ui/theme-ui/releases/tag/v0.7.4-develop.2) :rocket:

**Comment by hasparus** [comment]
:rocket: Issue was released in [`v0.7.4`](https://github.com/system-ui/theme-ui/releases/tag/v0.7.4) :rocket:
