### ISSUE TITLE
Can I use it in React Native?

### ISSUE THREAD

**Issue by nicolazj** [system-ui/theme-ui#170]
After some hacks,( getting rid of `document` ),  I managed to get theme-ui work in React Native. 
But just wondering is it a good idea to use theme-ui in React Native? 
Did I miss anything? 
I haven't tested the responsive part.

**Comment by jxnblk** [comment]
"Responsive" won't work with RN since Android and iOS don't use media queries. There is a related RN issue in the [Styled System](https://github.com/styled-system/styled-system/issues/302) library (which is pure js with no frameworks or css-in-js libraries), and you should be able to leverage the [Styled System CSS](https://styled-system.com/css/) package directly in RN if you want a similar API

**Comment by flybayer** [comment]
Fyi, here's how I'm getting the `sx` experience in react-native & react-native-web

<img width="767" alt="Screen Shot 2019-10-31 at 20 53 27" src="https://user-images.githubusercontent.com/8813276/68001347-f15bf780-fc20-11e9-9978-2d1f74db2182.png">

**Comment by nandorojo** [comment]
@flybayer Any shot you could elaborate a little bit on this? Do you just set the theme ui provided, make those components, and that’s it?

**Comment by nandorojo** [comment]
> "Responsive" won't work with RN since Android and iOS don't use media queries. 

Expo now polyfills the match media api: https://github.com/expo/match-media/blob/master/README.md

Could that add responsive features?

**Comment by nandorojo** [comment]
Sorry to keep harping on this, but @flybayer would you happen to have example code of your implementation? If not, just let me know. I tried to use your suggestion but get many TS errors.

**Comment by flybayer** [comment]
@nandorojo my last comment has all the code (sorry it's an image instead of text). TS types were working fine then. Maybe something has changed that needs updated? I've moved on from that project, so can't provide anything else unfortunately.

**Comment by hasparus** [comment]
Hey @nandorojo 👋 Paste me your TS errors, I'll try to help.

We should probably keep this out of Theme UI issues, however, since it's `styled-components/native` and `styled-system`.

**Comment by nandorojo** [comment]
Sounds good, where should I put the issue?

I made a repo that seems to have gotten this to work. I can drop a link to the repo or just paste the code. In order to implement responsive behavior, I’m using React Native `Dimensions` and conditionally-rendering styles based on that.

**Comment by hasparus** [comment]
We can talk in your repo, if you drop me a link here or move to Twitter or Discord.

**Comment by cmaycumber** [comment]
@nandorojo Were you able to get media queries working with expo/theme-ui? This would be really sweet for rnw.

**Comment by nandorojo** [comment]
@cmaycumber Yes, I ended up moving it to another repo called dripsy. `yarn add dripsy`

**Comment by rafaelrinaldi** [comment]
So it seems like the current state for interop between React and React Native with Theme UI is still not quite possible out of the box, correct?

Given the suggestions on this post, seems like the way to go would be to both isolate all the primitives in some sort of adapter and then perhaps use @nandorojo's solution for responsiveness on the React Native side?

Anyone else willing to shed some light on this?

**Comment by nandorojo** [comment]
@rafaelrinaldi Yup. `dripsy` is still actively getting worked on. It will have the same / very similar primitives as Theme UI, and basically the same API for styling. You're welcome to try it out now, I'll be adding full docs soon, with the help of @cmaycumber

**Comment by rafaelrinaldi** [comment]
My good friend @estevaolucas just shared this library with me: [`theme-ui-native`](https://github.com/samjbmason/theme-ui-native). Seems to be a really good alternative to solve this specific use case. Has anyone ever used it?

**Comment by nandorojo** [comment]
@rafaelrinaldi that looks really cool. Unfortunately it doesn't have responsive styles. But I could definitely see how I could integrate a lot of the ideas there into `dripsy`. A goal I have is to support Expo/Vanilla RN + RN Web + Server Side Rendering (Next.js).

**Comment by cmaycumber** [comment]
@rafaelrinaldi I've used it in the past just to experiment with it. I liked how it had jsx pragma and basically the same API as theme-ui. The main reason I started to help @nandorojo with dripsy was the responsiveness that allows for building web apps with react native as well as mobile apps.

**Comment by rafaelrinaldi** [comment]
Thanks for the input @nandorojo @cmaycumber. Do you guys plan on making the theme specification compliant to Theme UI's standard?

**Comment by nandorojo** [comment]
I'm currently using the `ThemeProvider` from `theme-ui`, as well as the same `css` function, with some additions for React Native-combatible responsive styles. So once we make the primitives, theming should basically be the same as `theme-ui`. 

I can't confirm that every detail will always be identical, since it's tailored to React Native/React Native Web, which may have some of its own quirks down the road. But I love the theming in `theme-ui`, and I made `dripsy` to be able to use the same theming in my native apps.

**Comment by rafaelrinaldi** [comment]
@nandorojo Have you thought about using something like [`react-primitives`](https://github.com/lelandrichardson/react-primitives) for dripsy? In theory it would allow you to isolate the runtime for both the browser and native environments.

**Comment by nandorojo** [comment]
@rafaelrinaldi that's interesting. I haven't. React Native Web seems like the most practical application at the moment, so for now I'm sticking to targeting the platforms that are well-supported by React Native.

**Comment by rafaelrinaldi** [comment]
@nandorojo Do you guys plan on supporting `sx` anytime soon? This seems to me the only big piece missing.
