### ISSUE TITLE
Universal `margin: 0;` has precedence over `marginLeft`

### ISSUE THREAD

**Issue by deltaepsilon** [system-ui/theme-ui#1701]
**Describe the bug**
Universally applied `margin` has precedence over more specific margins.

**To Reproduce**

1. Add `marginLeft` to `<Flex />` tag.

**Expected behavior**

You should get the `marginLeft` that you asked for.

**Screenshots**

The `margin: 0;` on the `<Flex />` tag beats my `marginLeft`.

![image](https://user-images.githubusercontent.com/878947/116707940-721dc000-a98c-11eb-9e73-72f858d77da8.png)

**Comment by lachlanjc** [comment]
Sorry about that! Want to look through #1622?

**Comment by deltaepsilon** [comment]
That's 100% the same issue. I searched for it, but didn't find it.
