### ISSUE TITLE
Watch bundle size on CI

### ISSUE THREAD

**Issue by hasparus** [system-ui/theme-ui#1722]
**Is your feature request related to a problem? Please describe.**

I'd like to know if a PR increased or decreased bundle size, and I'm too lazy to check this manually every time. 
Continous Integration is the right place for this.

**Describe the solution you'd like**

I like CodeChecks (https://github.com/codechecks/build-size-watcher), but there are tons of solutions for this.

![image](https://user-images.githubusercontent.com/15332326/117370023-0d032680-aec6-11eb-8968-4e9e66474413.png)

---

Connected issues: https://github.com/system-ui/theme-ui/issues/1720

**Comment by flo-sch** [comment]
Great addition!
How does it work for such services with theme-UI, do we use personal accounts?

**Comment by hasparus** [comment]
Sorry @flo-sch, I was a bit too optimistic here. Solving this requires access to repository settings. However, I'd really appreciate your code review in #1740.

**Comment by hasparus** [comment]
:rocket: Issue was released in [`v0.9.0-develop.0`](https://github.com/system-ui/theme-ui/releases/tag/v0.9.0-develop.0) :rocket:
