### ISSUE TITLE
Is there a way to access component props in Theme-UI?

### ISSUE THREAD

**Issue by ehowey** [system-ui/theme-ui#173]
Hi Again,

Another question, I apologize if this is really simple.  Based on whether the mobile menu is open or closed I want to conditionally change the background color of the header component. I have this working in my own component but was hoping to use the core theme-ui layout header component if I could.

Basically I would like to do something like this inside of the theme spec:
`styles: {
    Header: {
              backgroundColor: props.open ? "header.backgroundOpen" : "header.background,
    }
}`

Is this possible? Is there a way to get at this prop from the Header component included with theme-ui?

**Comment by jxnblk** [comment]
In JSX, the `props` object should be in scope inside the *component*. The `theme` is meant to be a mostly JSON-serializable object, that is provided to the entire application. So, I think what you're describing can be achieved in a component. The side navigation on the docs site uses an `open` state as an example. Hope that makes sense

**Comment by ehowey** [comment]
Thanks - that is what I figured but just wanted to ask. I have it working in a component was curious if I could extend that to theme-ui or not.
