### ISSUE TITLE
`gatsby-theme-code-recipes` can be removed

### ISSUE THREAD

**Issue by hasparus** [system-ui/theme-ui#1750]
I'm not sure if anybody noticed, but _Recipes_ section in the docs is broken.

We're using `gatsby-theme-code-recipes` for it, and the package is... _effectively internal_? as it doesn't have any documentation and it seems to be used only by our docs.

[![image](https://user-images.githubusercontent.com/15332326/118445746-1f176d00-b6ef-11eb-9f0a-b9f1b9baa72a.png)](https://www.npmjs.com/package/gatsby-theme-code-recipes)

I tried to fix it for a while, but Gatsby plugins tend to behave in a _CSS-style fail silently manner_ instead of a _fail-fast with fatal error_, so I'm not sure when it went wrong (dependabot update perhaps?) and it seems we can safely remove it instead.

After moving all MDX from _/recipes_ to _pages/recipes_ it Just Works™.

---

In general, I'd like to make the API surface of Theme UI packages family smaller, as we currently have unmaintained and unused "dead sectors".

**Comment by lachlanjc** [comment]
Oof, thanks for pointing this out! Considering I wasn't aware of that package I'm not sure how my face is on the npm page. 👀
