### ISSUE TITLE
RFC: Can `@theme-ui/editor` be deprecated?

### ISSUE THREAD

**Issue by hasparus** [system-ui/theme-ui#1751]
`@theme-ui/editor` has about 1000 weekly downloads, and a few nicer alternatives mentioned in our Resources section.

I want to motion to deprecate `@theme-ui/editor` and in its place recommend alternatives and document how to build something like it.

Notable alternatives:

- @gillkyle's Theme UI Gallery: https://theme-ui-gallery.netlify.app/
- components.ai Theme Builder: https://components.ai/theme (cc @johno — I need to ask here, as it doesn't seem to be written anywhere: Is the your builder compliant with Theme UI by design or by accident?)
- @PaulieScanlon Skin UI: https://www.skin-ui.com/

As I mentioned in https://github.com/system-ui/theme-ui/issues/1750, I'd like to make Theme UI packages family smaller and more polished, minimize its API surface, clearly communicate what's public API and what's not, and remove unmaintained/unused code. 

If there is a better editor, we could focus our efforts on it, help out its maintainers, and set up Theme UI CI to check if our changes don't break it.

cc @lachlanjc

**Comment by johno** [comment]
The Components AI theme builder is compliant with Theme UI by design. One of our goals with our tooling is to be able to "speak" different frameworks and libraries (including Theme UI).

**Comment by flo-sch** [comment]
I have personally never used the editor itself, so might be biased by 👍 here, but I am in favor of minimizing the maintenance surface, especially before a stable v1.0 is released.
(Even though Theme Specifications arguably do not change too often, Editor feels like a nice-to-have feature that is not "core" to Theme UI, and maintenance could be separated)

**Comment by lachlanjc** [comment]
I vote we’re good to deprecate/make internal to docs! It’s been 6 months here without any pushback.

**Comment by hasparus** [comment]
:rocket: Issue was released in [`v0.15.0-develop.17`](https://github.com/system-ui/theme-ui/releases/tag/v0.15.0-develop.17) :rocket:
