### ISSUE TITLE
Transform theme-ui colors outside of sx prop

### ISSUE THREAD

**Issue by sonapraneeth-a** [system-ui/theme-ui#177]
Currently , it looks like we do not support the below use case. In the below use case, I'm trying to use primary color defined in theme as a string as we do in sx prop. But the color does not transform to required string when rendering.

It would be better if theme-ui can transform primary to actual color when used outside sx/css prop.

**Use case:**

```
<Helmet
 meta={[
          {name: "theme-color", content: "primary"}, // Here primary should transform to the actual color as defined in theme-ui
        ]}
/>
```

**Comment by jxnblk** [comment]
Hi, have you tried using the `useThemeUI` hook for this? I haven't done this exactly, but you should be able to pull the colors object like so:

```js
import { useThemeUI } from 'theme-ui'

export default props => {
  const context = useThemeUI()
  const { colors } = context.theme
}
```

**Comment by sonapraneeth-a** [comment]
Yes I have tried something like this

```
const context = useThemeUI();
const {theme, colorMode} = context;
let primary = "";
if (colorMode === "light") {
  primary = theme.colors.primary;
} else if (colorMode === "dark") {
  primary = theme.colors.modes.dark.primary;
}
```

This works. But my intention is to have code as described in the issue. Currently, I need to use if else condition to check the color mode and retrieve the primary value, whereas it would be better if we can simply use "primary" as we use in ```sx``` prop.

What do you think @jxnblk ?

**Comment by jxnblk** [comment]
The `theme.colors.value` in context should change depending on the current color mode. You shouldn't need to check for the value. If that's not working then that's a bug

**Comment by sonapraneeth-a** [comment]
Hi @jxnblk ,

Are you expecting it to be something like

```
const {theme} = useThemeUI();
<Helmet
 meta={[
          {name: "theme-color", content: "theme.colors.primary"}, // Here primary should transform to the actual color as defined in theme-ui
        ]}
/>
```

and it should be working?

or something like 

```
<Helmet
 meta={[
          {name: "theme-color", content: "primary"}, // Here primary should transform to the actual color as defined in theme-ui
        ]}
/>
```

**Comment by jxnblk** [comment]
You should be able to do this, but I'm not sure how clients would handle dynamically changing values in the meta tags like this. Often the static meta tags are the only ones that are picked up for stuff like this, but I haven't tested it

```jsx
import React from 'react'
import { useThemeUI } from 'theme-ui'
import { Helmet } from 'react-helmet'

export default props => {
  const context = useThemeUI()
  const { colors } = context.theme

  return (
   <Helmet 
      meta={[
        { name: 'theme-color', content: colors.primary },
      ]}
    />
  )
}
```

**Comment by sonapraneeth-a** [comment]
Hi @jxnblk ,

The above suggestion is not working. With the above suggestion if the initial color mode is light, that value is assigned to meta ```theme_color``` but when we change the ```colorMode```, the value does not change

**Comment by jxnblk** [comment]
It looks like this might've been a bug, related: #226

**Comment by johno** [comment]
Going to close this since it should be fixed. Please feel free to reopen if it isn't fixed with the latest release @sonapraneeth-a!
