### ISSUE TITLE
Paragraph margin can't be overridden by theme

### ISSUE THREAD

**Issue by bernharduw** [system-ui/theme-ui#1774]
**Describe the bug**
Paragraph margins can't be changed via theming because the `m={0}` value is always added after applying the theme. This was first fixed in #1476, but reintroduced by #1560.

**To Reproduce**
I created a sandbox in https://codesandbox.io/s/aged-silence-42b7m
See the output - all 4 paragraphs should have margins applied.

**Expected behavior**
Margins should be set to 0 by default. But no matter what method of styling you prefer, they should always be overrideable. 

**Screenshots**
![image](https://user-images.githubusercontent.com/740978/119557838-fd7a4d80-bda0-11eb-8cb2-9585a9705cda.png)

**Additional context**
It seems that margin:0 is set twice. Maybe it helps to remove the `m={0}` completely because it's set anyway.
![image](https://user-images.githubusercontent.com/740978/119558338-91e4b000-bda1-11eb-94f2-5ff57120aa13.png)

**Comment by hasparus** [comment]
:rocket: Issue was released in [`v0.9.1-develop.0`](https://github.com/system-ui/theme-ui/releases/tag/v0.9.1-develop.0) :rocket:

**Comment by hasparus** [comment]
:rocket: Issue was released in [`v0.9.1`](https://github.com/system-ui/theme-ui/releases/tag/v0.9.1) :rocket:

**Comment by hasparus** [comment]
:rocket: Issue was released in [`v0.9.2-develop.0`](https://github.com/system-ui/theme-ui/releases/tag/v0.9.2-develop.0) :rocket:
