### ISSUE TITLE
Exporting types correctly?

### ISSUE THREAD

**Issue by jeffscottward** [system-ui/theme-ui#1778]
**Describe the bug**
<img width="576" alt="Screen Shot 2021-05-26 at 11 54 29 AM" src="https://user-images.githubusercontent.com/1263486/119692169-30602800-be19-11eb-964d-9e99784b72da.png">
<img width="597" alt="Screen Shot 2021-05-26 at 11 54 36 AM" src="https://user-images.githubusercontent.com/1263486/119692170-30602800-be19-11eb-92aa-d352561d04d1.png">

When trying to deploy my next.js project to vercel - I get type errors above.
When running locally, it builds fine.
Unsure why this is. I even overode the build command to insure yarn installs everything first for sure.
Here's the repo. 
https://github.com/Web3-API/web3hub

**Comment by hasparus** [comment]
Theme UI 0.3.1, the version you are using, is written in JavaScript. You can grab its types from DefinitelyTyped by _@types/theme-ui_.

Later versions of Theme UI, including current 0.9.1, are written in TypeScript, and ship their own types.

**Comment by jeffscottward** [comment]
Yup working nicely (mostly - filed one small bug) since, thanks!
