### ISSUE TITLE
Using the sx prop in MDX

### ISSUE THREAD

**Issue by MarkosKon** [system-ui/theme-ui#178]
If you want to use the `sx` prop to style a component inside an MDX file you can create a wrapper component and use that instead:

```jsx
/** @jsx jsx */
import { jsx, Box as BaseBox, Flex as BaseFlex } from "theme-ui";

const Box = props => <BaseBox {...props} />;
const Flex = props => <BaseFlex {...props} />;

export { Box, Flex };
```

Is there a better way?

**Comment by jxnblk** [comment]
Hi! We've been thinking about this a little, and *would* like to add better support for using the `sx` prop within an MDX file. For the time-being, the approach you have above is probably the most explicit way to do it, but if you have any thoughts or suggestions, we'd love to hear them!
