### ISSUE TITLE
Type Error: Label element is expected to be a string?

### ISSUE THREAD

**Issue by jeffscottward** [system-ui/theme-ui#1782]
**Describe the bug**
<img width="519" alt="Screen Shot 2021-05-27 at 4 08 54 PM" src="https://user-images.githubusercontent.com/1263486/119890585-06386400-bf06-11eb-8df9-d930f6892f7e.png">
<img width="448" alt="Screen Shot 2021-05-27 at 4 09 12 PM" src="https://user-images.githubusercontent.com/1263486/119890587-06d0fa80-bf06-11eb-9895-5778df1f2569.png">

**To Reproduce**
Write some basic code with some styles a Field element like so
<img width="274" alt="Screen Shot 2021-05-27 at 4 11 13 PM" src="https://user-images.githubusercontent.com/1263486/119890778-3da71080-bf06-11eb-9731-1bd1c0978a41.png">

**Comment by hasparus** [comment]
Yes, the `label` is a corner case. It's the string appearing in devtools. You can style nested label elements with `& label` selector.  https://emotion.sh/docs/labels
