### ISSUE TITLE
Why is it `theme.space` instead of `theme.spaces`?

### ISSUE THREAD

**Issue by KyleAMathews** [system-ui/theme-ui#179]
Just wondering since other properties are plural.

**Comment by jxnblk** [comment]
It came from space as in *negative space*, *outer space*, *white space*, etc. still plural just the uncountable version of the word *space* – I went with this word early on, but I've also seen *spacing*, *spacings*, and *spaces*

**Comment by KyleAMathews** [comment]
Cool 👍 makes sense! Just was curious.
