### ISSUE TITLE
Responsive borders?

### ISSUE THREAD

**Issue by KyleAMathews** [system-ui/theme-ui#180]
I was trying to figure out how to only show a top border on mobile and all four borders on larger screens and couldn't figure this out. Is there a theme-uish way to do this?

https://github.com/KyleAMathews/gatsby-theme-cooper-hewitt/blob/b2707e09f5b88f5150b9397855a73edb1329ca81/gatsby-theme-cooper-hewitt/src/gatsby-theme-blog/components/layout.js#L10-L16

**Comment by jxnblk** [comment]
I think you might've uncovered an unintentional gap in the API.

```js
// ideally this API should work
// but I think this can be considered a bug
// since I don't think it works currently
borderWidth: t => [
  `${t.space[2]}px`,
  0,
],

// this should also work based on the current implementation
borderWidth: [
  t => `${t.space[2]}px`,
  0
]
```

It's also worth noting that there is an optional `theme.borderWidths` scale that can be used specifically for borders, but it doesn't default to `theme.space`

**Comment by KyleAMathews** [comment]
The second one worked! I'll roll with that for now. Thanks!

**Comment by jxnblk** [comment]
Closing in favor of #229
