### ISSUE TITLE
Errors caused by custom pragma comment

### ISSUE THREAD

**Issue by t2ca** [system-ui/theme-ui#181]
When adding the custom pragma code

`/** @jsx jsx */`

Im getting this error in my console during development.

`It looks like you're using the css prop on Global, did you mean to use the styles prop instead?`

However this is my code

```
        <Global
          styles={{
            "*": {
              boxSizing: "border-box",
            },
            body: {
              margin: 0,
            },
          }}
        />
```

When I remove the custom pragma code, the error goes away.

Also using the pragma code gives my a linter error. 'React' is defined but never used.

Just wondering how to fix this, thanks!

**Comment by jxnblk** [comment]
The first one is only a warning, and you should be able to safely ignore it for now. See #182

**Comment by t2ca** [comment]
Thank you.
