### ISSUE TITLE
Proper typescript support

### ISSUE THREAD

**Issue by sashalavron** [system-ui/theme-ui#1834]
**Is your feature request related to a problem? Please describe.**
Hi. I am frustrated with lack of proper typescript support. Official docs recommends to use `get` function to access theme properties. It seems very unsafe, because `get` method basically disables the whole typescript support - it allows me to access to non-existing value and doesn't provide the explicit return type. Also, the `Theme` type seems not very useful - it does not represent the exact theme, and all of the properties are optional. I even cant add my own color, because of type incompatibility (see the screenshot). Could you please recommend me something in this situation?

**Describe the solution you'd like**
Allow user to extend / specify properly the exact Theme type. `get` function just workarounds the whole types and can cause a lot of bugs.

**Additional context**
Cant extend the theme-ui with my own colors:
![image](https://user-images.githubusercontent.com/25880234/122397448-a91e5400-cf81-11eb-87a3-406619c1ed3b.png)
![image](https://user-images.githubusercontent.com/25880234/122397475-ade30800-cf81-11eb-8db6-c6a1e7d744cb.png)

Cant specify my own theme type:
![image](https://user-images.githubusercontent.com/25880234/122397837-ff8b9280-cf81-11eb-9d99-762c372d7a8e.png)
![image](https://user-images.githubusercontent.com/25880234/122397985-1fbb5180-cf82-11eb-8ccd-d88221aadd04.png)

**Comment by MuhammadJamaluddin** [comment]
https://theme-ui.com/guides/typescript/#typescript

Probably we can close this?Cc: @hasparus
