### ISSUE TITLE
When using __css vs sx

### ISSUE THREAD

**Issue by sergeylukin** [system-ui/theme-ui#1844]
Hi,

May I ask why did you use __css prop instead of sx here:
https://github.com/system-ui/theme-ui/blob/9343cf8358459486a49d83e66843c09d0bcfbd87/packages/components/src/Select.js#L31

Thanks :)

**Comment by lachlanjc** [comment]
That's only for internal usage, so the styles get overwritten by sx. Just use sx in your Theme UI projects!
