### ISSUE TITLE
Grid gap property not reading theme space values

### ISSUE THREAD

**Issue by sergeylukin** [system-ui/theme-ui#1857]
**Describe the bug**

Hi, `<Grid />` `gap` property doesn't respect spaces from connected theme while `sx` does.
 
**To Reproduce**

1. Setup basic example with theme:

```
const theme = {
    space: [0, 2, 4, 8, 12, 16, 20, 24, 32, 64, 128, 256, 512],
   ...
}
```

**Expected behavior**

`<Grid gap={2} />` resulting in grid with gap of 4px

**Comment by hasparus** [comment]
Hey @sergeylukin, do you maybe have a reproduction repo or CodeSandbox? It seems to work in the docs.

![image](https://user-images.githubusercontent.com/15332326/124487976-9b553500-ddaf-11eb-8250-c152bfd813bf.png)

What versions of Theme UI and Emotion do you have? Are you maybe using Theme UI inside of Storybook?

**Comment by lachlanjc** [comment]
Fwiw, this works fine for me! So more likely a setup issue.

**Comment by hasparus** [comment]
The problem might be caused by context version mismatch (and serve as another reason for us to move Emotion to peerDeps), so I'd look for the cause in _package.json_.

**Comment by sergeylukin** [comment]
Will export my setup to codesandox during today-tomorrow and provide a proof or will prove myself wrong, thank you @lachlanjc @hasparus !

**Comment by sergeylukin** [comment]
@hasparus you're right, I found 2 versions of `@emotion/react` in my `yarn.lock` (I'm using `11.4.0` while theme-ui is using `11.1.1`):

<img width="1121" alt="Screen Shot 2021-07-06 at 19 43 18" src="https://user-images.githubusercontent.com/720339/124637496-7be30880-de92-11eb-84e7-f06cbb369270.png">


...because I've used @emotion/react internals in my project. What's the solution as long as I do want to use @emotion/react in my project? Is it just aligning the version of `@emotion/react` to the one used by current theme-ui?

**Comment by lachlanjc** [comment]
Check this out! https://github.com/system-ui/theme-ui/issues/1531#issuecomment-787517891 There's some other issues with that label with more conversations as well.

**Comment by hasparus** [comment]
@sergeylukin, you can either use yarn resolutions to enforce the new Emotion version on Theme UI or downgrade yours (does 11.4 have anything new you're using)?

We're definitely moving Emotion to peerDeps in next bigger release, @lachlanjc :/

**Comment by sergeylukin** [comment]
@hasparus makes sense, thank you! 🙏
