### ISSUE TITLE
404 status on "How custom pragma works" link

### ISSUE THREAD

**Issue by freshtonic** [system-ui/theme-ui#187]
This link doesn't work: https://github.com/system-ui/theme-ui/blob/master/how-it-works/#jsx-pragma

**Comment by jxnblk** [comment]
Thanks! Where did you get the link?

**Comment by samburgers** [comment]
Stumbled across this too. Found an example in the main Readme with the text "how the custom pragma works"

**Comment by jxnblk** [comment]
Should be fixed now

**Comment by freshtonic** [comment]
Thanks @jxnblk 👍
