### ISSUE TITLE
`@theme-ui/color-modes` framework-agnostic API

### ISSUE THREAD

**Issue by cudr** [system-ui/theme-ui#1875]
**Is your feature request related to a problem? Please describe.**
We don't have API to use color modes without React.

Would be great if we will have public API to use theme with color modes.

**Describe the solution you'd like**
Extract and export [core logic](https://github.com/system-ui/theme-ui/blob/5a378bd6a478949778095cdf3e29b8d9293f2076/packages/color-modes/src/index.tsx#L187)

**Additional context**
Partially related to #1865

**Comment by lachlanjc** [comment]
Interesting. What inputs/outputs would you expect from this API?

**Comment by lachlanjc** [comment]
Closing this as we're not planning to build this feature, but anyone is welcome to extract this functionality & we can link to it in the docs. If you're using Next.js, I've had great success with <https://github.com/pacocoursey/next-themes>!
