### ISSUE TITLE
Docs don't tell you to use ThemeProvider early enough.

### ISSUE THREAD

**Issue by 0-Captain** [system-ui/theme-ui#1876]
**Describe the bug**
the color value can't be converted to real color
code:
![image](https://user-images.githubusercontent.com/36297071/127734859-784131f1-23b6-469e-8045-bbc813854734.png)
product:
![image](https://user-images.githubusercontent.com/36297071/127734709-5f922ac2-a9fb-4cc3-94fa-8aee3f31f661.png)

**To Reproduce**

1. yarn create next-app --ts
2. yarn add theme-ui
3. edit tsconfig.json, add this line
`"jsxImportSource": "theme-ui",`
4. create babel.config.js
```
module.exports = {
  presets: [
    [
      "next/babel",
      {
        "preset-react": {
          importSource: "theme-ui", // or '@theme-ui/core'
          runtime: "automatic",
          throwIfNamespace: false,
        },
      },
    ],
  ],
};
```

**demo**:
https://codesandbox.io/s/reverent-wright-q1u54?file=/src/pages/index.tsx:81-88

**Comment by hasparus** [comment]
Hey @0-Captain, Theme UI doesn't know about your theme yet. You need to pass your theme object to `ThemeProvider` so the JSX pragma can pick `primary` from React context.

Take a look at the third paragraph in _Getting Started_.

https://theme-ui.com/getting-started#getting-started

I made the required change in your CodeSandbox, here it is:

https://codesandbox.io/s/theme-ui-repro-you-gotta-use-provider-bro-hebjd?file=/src/pages/_app.tsx

I'll try to improve the docs so it's more evident.

**Comment by hasparus** [comment]
Hey @0-Captain, I made a small change to the index page and _Getting Started_ section in the docs. (#1877)

Here's the preview of new index page: https://theme-ui-iuu8kzl45-systemui.vercel.app/#create-your-theme
And the same thing in _Getting Started_: https://theme-ui-iuu8kzl45-systemui.vercel.app/getting-started

Do you think this would be more welcoming to new Theme UI users?

**Comment by 0-Captain** [comment]
Great, I think it would be better to take the CodeSandbox as an example in the docs
