### ISSUE TITLE
Paragraph styles not applied through variant: "styles"

### ISSUE THREAD

**Issue by rjgux** [system-ui/theme-ui#188]
I'm having an issue where styles aren't being applied to paragraph tags that are children of a component that uses `sx={{ variant: "styles" }}`.

```
const Copy = props => (
  <div
    {...props}
    sx={{
      variant: "styles",
    }}
  >
    {props.children}
  </div>
)

<Styled.p>I am a styled paragraph</Styled.p>
<Copy>
  <p>I am a styled paragraph</p>
</Copy>
```

In my code above, `<Styled.p>` is working as expected and picks up from `theme.styles.p`, but the `<p>` tag within `<Copy>` has no styling attached to it. This only seems to be an issue for paragraphs, all other tags seem to work (`ul, h1, h2` etc).

**Comment by jxnblk** [comment]
Do you have the pragma comment in the file with the `sx` prop? Also if you can link to a reproduction that would be helpful

**Comment by rjgux** [comment]
@jxnblk Yep, using the JSX pragma comment. Here's a sandbox where I've reproduced it - https://codesandbox.io/s/gatsby-starter-default-votxl?fontsize=14

**Comment by jxnblk** [comment]
This was possibly related to https://github.com/styled-system/styled-system/pull/610 – can you check to see if the issue persists with the updated `@styled-system/css` dependency?

**Comment by rjgux** [comment]
@jxnblk Yep, that's fixed it. Thanks!
