### ISSUE TITLE
Fallbacks

### ISSUE THREAD

**Issue by andrewfairlie** [system-ui/theme-ui#189]
Is it possible to define fallbacks using Theme-UI SX?

For instance, with Emotion you can do

```
display: ['block','flex','grid']
```

Which renders as 

```
display: block;
display: flex;
display: grid;
```

However where Theme UI uses arrays for breakpoints it doesn't seem to be possible.

Any help would be much appreciated.

**Comment by jxnblk** [comment]
With the `sx` prop that's not possible, due to the responsive array styles, but you *can* use the `css` prop for the example you have:

```jsx
<div
  css={{
    display: [ 'block', 'flex' ],
  }}
/>
```

If you need access to the `theme` object, then you can pass a function in:

```jsx
css={theme => {
  // couldn't think of an example that really makes sense here...
  color: [ theme.colors.blue, theme.colors.red ]
}}
```
