### ISSUE TITLE
Type error: Property or signature expected.  ` ... 157 more ...`

### ISSUE THREAD

**Issue by watsuyo** [system-ui/theme-ui#1920]
**Describe the bug**
When deploying a Next.js project to vercel, I get the error shown in the screenshot below.

The error location is . /node_modules/@theme-ui/preset-sketchy/dist/declarations/src/index.d.ts.
For some reason, the ` ... 157 more ...` is omitted.

<details>
<summary>package.js</summary>

```json
"dependencies": {
    "@emotion/styled": "^11.3.0",
    "@theme-ui/presets": "^0.11.1",
    "front-matter": "^4.0.2",
    "gray-matter": "^4.0.3",
    "next": "11.1.2",
    "next-mdx-enhanced": "^5.0.0",
    "next-mdx-remote": "^3.0.4",
    "react": "17.0.2",
    "react-device-detect": "^1.17.0",
    "react-dom": "17.0.2",
    "react-icons": "^4.2.0",
    "theme-ui": "^0.11.1"
  },
  "devDependencies": {
    "@types/react": "17.0.19",
    "@typescript-eslint/eslint-plugin": "^4.30.0",
    "@typescript-eslint/parser": "^4.30.0",
    "babel-plugin-emotion": "^11.0.0",
    "eslint": "^7.32.0",
    "eslint-config-next": "11.1.2",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-react": "^7.25.1",
    "eslint-plugin-react-hooks": "^4.2.0",
    "prettier": "2.3.2",
    "typescript": "4.4.2"
  }
```

</details>

**Screenshots**
![image](https://user-images.githubusercontent.com/13050604/132129520-eabf8717-a05f-471a-b8bf-7c6b793ba574.png)

**Comment by watsuyo** [comment]
Is there any way to solve this problem?

**Comment by hasparus** [comment]
Hey @watsuyo, I'll try to solve or at least research this today. For now, you can disable typechecking in Next.js builds.

Did this error occur in TypeScript 4.3?

**Comment by watsuyo** [comment]
Thank you for reply.
I tried TypeScript 4.3 and got the same resul.

I tried ignoreBuildErrors and build passed.

**Comment by hasparus** [comment]
Thanks for this issue @watsuyo! It's pretty hilarious actually — we managed to break the build system.

![image](https://user-images.githubusercontent.com/15332326/132465191-0e916cf4-b335-4f10-8726-4d0638842f87.png)

This "157 more" was emitted to our typings in the build.

I'm publishing a new version with a fix, and adding a test to ensure it doesn't happen again.

---

On a side note, I'm sorry for advising you to ignore build errors. Turning `skipLibCheck: true` in _tsconfig.json_ would be enough — you don't have to ignore your build errors, only the ones from us 😓
