### ISSUE TITLE
ThemeProvider can be accidentally imported from Emotion. Consider renaming to ThemeUIProvider?

### ISSUE THREAD

**Issue by timfee** [system-ui/theme-ui#1921]
**To Reproduce**
See: https://codesandbox.io/s/silent-surf-4omzj
Using the latest version of everything on Next.js

**Expected behavior**
Based on [the documentation](https://theme-ui.com/guides/global-styles):
> By default, the `ThemeProvider` component will apply styles in `theme.styles.root` to the `<html>` element.

This isn't happening in my instance. While I don't mind manually adding stuff, I wanted to make sure I wasn't doing anything awry :)

**Comment by hasparus** [comment]
Hey @timfee 👋 Thanks for the issue!

You imported `ThemeProvider` from `@emotion/react`, not from `theme-ui`.

It's kind of our fault — in the world with auto-imports we should have used a unique name.

**Comment by timfee** [comment]
Ah man, tricky :)

I also wonder if having more context in documentation could help. For instance, the only real place with all of the boilerplate code is in Getting Started, and it’s tough to find theme provider details and examples elsewhere on the site. 

Thank you for the help!!

**Comment by hasparus** [comment]
:rocket: Issue was released in [`v0.16.0-develop.0`](https://github.com/system-ui/theme-ui/releases/tag/v0.16.0-develop.0) :rocket:

**Comment by hasparus** [comment]
:rocket: Issue was released in [`v0.16.0`](https://github.com/system-ui/theme-ui/releases/tag/v0.16.0) :rocket:
