### ISSUE TITLE
Shorthand for padding collides with nested styling for paragraphs

### ISSUE THREAD

**Issue by jlengstorf** [system-ui/theme-ui#194]
When styling nested tags, the `p` tag collides with the `padding` shorthand (also `p`) and results in a confusing failure to apply styles.

I put together a small reproduction here: https://glitch.com/~theme-ui-p-collision

## Proposed fix 1 — maybe too magic

Unless there's something I'm unaware of in Theme UI, an object is not a valid value to pass to `padding`. If that's the case, it might work to just check the value's type and make a decision there.

Pseudo-code:
```js
if (typeof p !== 'number' || typeof p !== 'string' || !Array.isArray(p)) {
  // these are paragraph styles or an invalid value
  return p;
}

// this is padding shorthand; do padding handling stuff
```

This should be a non-breaking change, but it might be a little magical to have `p` mean different things based on its value.

## Proposed fix 2 — less magic

This would be a breaking change, but maybe the more obvious way to solve this is to change the shorthand to not collide with valid nested selector syntax.

For example, it could change to `pa` (for "padding all") and this problem would go away entirely.

```jsx
<div
  sx={{
    pa: 4,
    p: {
      color: 'tomato',
    }
  }}
>
  <p>This will pick up styles!</p>
</div>
```

**Comment by jxnblk** [comment]
Good catch! I'll add some tests, but I think moving this line to after the value type check would probably fix this https://github.com/styled-system/styled-system/blob/master/packages/css/src/index.js#L159
