### ISSUE TITLE
color-modes: printColorModeName option not working properly

### ISSUE THREAD

**Issue by xiaoxinghu** [system-ui/theme-ui#1964]
**Describe the bug**
`printColorModeName` doesn't seem to work, at least with nextjs.

**To Reproduce**
I have created an [example repo](https://github.com/xiaoxinghu/next-with-print-issue), which is a simple copy of the `next` project in the examples folder. I did the following extra to make it work:
- install `typescript` and `@types/react` as it's complained after `yarn`
- add `printColorModeName: 'light'` to the `theme.ts` file.
- toggle to dark mode, then cmd + p to print the page, you get the dark them in preview.

**Expected behavior**
the print should use light theme

**Screenshots**
![CleanShot 2021-10-03 at 14 17 57@2x](https://user-images.githubusercontent.com/1196745/135736141-913ad044-1008-43d7-8d5d-4d119570894e.png)
I have checked the source, it seems the current theme is applied in` @media print`.
![CleanShot 2021-10-03 at 14 18 38@2x](https://user-images.githubusercontent.com/1196745/135736161-0af9864b-1d9c-4625-af27-251d12031192.png)

**Comment by lachlanjc** [comment]
Thank you for the repo + details!

**Comment by lachlanjc** [comment]
Updated the repro to the latest Theme UI & dependencies, issue is unresolved. https://codesandbox.io/s/broken-tree-pm9nh?file=/src/theme.ts / https://pm9nh.sse.codesandbox.io/
