### ISSUE TITLE
Migrate from Yarn v1

### ISSUE THREAD

**Issue by hasparus** [system-ui/theme-ui#1971]
Yarn 1 seems to be... _less maintained_ than it used to be and bugs start to cause problems in Theme UI maintenance.

See [Yarn's bug report template](https://raw.githubusercontent.com/yarnpkg/yarn/master/.github/ISSUE_TEMPLATE/bug_report.md) and https://github.com/yarnpkg/yarn/issues/7734#issuecomment-819110350.

I'm not a huge fan of `npm@7`, though I'm not very opinionated here. I'd give `pnpm` a shot.

**Comment by lachlanjc** [comment]
Yeah, I'm not sure what the best practice is these days. Yarn v2 seems like it was never embraced, but I use npm 7 at work & it's not great either. I hear good things about https://turborepo.com/ but haven't seen it being used in open source projects yet.

**Comment by fcisio** [comment]
I'm having the same dilemma on my stack. Going away from Yarn would also mean dropping yarn workspaces.
I kinda feel like Yarn v2 could be great, I heard good things. But I have not yet actually used it with anything.

**Comment by hasparus** [comment]
@fcisio https://pnpm.io/workspaces :D

**Comment by lachlanjc** [comment]
We just switched to pnpm + Turborepo at work, now that Turbo is open source this seems to be the direction folks are heading in.

**Comment by lachlanjc** [comment]
BOOM you did it @hasparus
