### ISSUE TITLE
v0.11.x renders div for ThemeProvider instead of nothing and breaks some designs

### ISSUE THREAD

**Issue by webcore-it** [system-ui/theme-ui#1976]
**Describe the bug**
Updating from 0.10.0 to 0.11.x did break some of our grid designs when a ThemeProvider is used as first child of the Grid component.

**To Reproduce**

1. Go to https://codesandbox.io/s/themeui-themeprovider-issue-xp7qq?file=/src/App.js
2. Check the rendered page. You see a Grid with a the column template of `'1fr 1fr 1fr'`.
3. Check the code. The first 2 Box components are wrapped inside a `ThemeProvider`, the 3rd is a direct child of the Grid.
4. Change the theme-ui version to 0.11.x (The issue starts with 0.11.0)
5. Now the ThemeProvider renders a `div` (for the NestedColorModeProvider) and the design breaks, since the 1st 2 Boxes are not the direct children of the Grid anymore.

**Expected behavior**
ThemeProvider does not render a div.

**Screenshots**
Theme UI 0.10.0
![image](https://user-images.githubusercontent.com/900799/137089016-80d54936-bec9-4b24-be80-4c062b6dcf48.png)

Theme UI 0.11.0
![image](https://user-images.githubusercontent.com/900799/137088658-d38d94bc-9e93-4ba6-a762-9ddccc443202.png)

**Comment by hasparus** [comment]
> ThemeProvider does not render a div.

Well, this is why v0.11 was a breaking change. This `div` is needed in nested theme providers to change values of custom CSS properties.

The ThemeProvider in your example has the following CSS class.

```css
.css-1as3bl3-NestedColorModeProvider {
    --theme-ui-colors-primary: red;
    --theme-ui-colors-text: darkred;
}
```

Unfortunately, this is needed for SSR, and people mostly expect SSR to work out of the box without color flashes.

If you're interested in overriding context without automatically merging color modes, you can `import { ThemeProvider } from '@theme-ui/core'`. The value you pass to this provider will be deeply merged with the theme you already have in context so you need to keep it in sync with color modes, if you want them to affect it.

[**Take a look at this CodeSandbox I prepared for you.**](https://codesandbox.io/s/themeui-themeprovider-issue-solution-rft6z?file=/src/App.js)

If you want to know more about the change and the issue it solved, you can take a look at https://github.com/system-ui/theme-ui/pull/1838 and https://github.com/system-ui/theme-ui/issues/1456.

**Comment by webcore-it** [comment]
Thanks for the info and the suggestion to import the ThemeProvider from core. Currently we do not use color modes and can probably go with this approach.
