### ISSUE TITLE
[@theme-ui/prism] Unable to add syntax highlighting for unsupported languages.

### ISSUE THREAD

**Issue by 5parkp1ug** [system-ui/theme-ui#1979]
As per the docs, in order to enable the syntax-highlighting for the unsupported languages one must import the language and pass a custom Prism instance to the Theme UI component:

```
// src/gatsby-plugin-theme-ui/components.js
import ThemeUIPrism from '@theme-ui/prism'
import PrismCore from 'prismjs/components/prism-core'
import 'prismjs/components/prism-r'

export default {
  pre: (props) => props.children,
  code: (props) => <ThemeUIPrism {...props} Prism={PrismCore} />,
}
```

However, while doing so, I am getting the following error - 
```
./src/gatsby-plugin-theme-ui/components.js
Module not found: Can't resolve 'prismjs/components/prism-core' in '<CLIPPED>/src/gatsby-plugin-theme-ui'
```

What am i doing wrong here? I believe I shouldn't install `prismjs` manually as it could interfere with the underlying installation of `@theme-ui`.

**Comment by lachlanjc** [comment]
@5parkp1ug Hi! If you're still running into this issue, could you link code to reproduce this? I just this week updated the docs on Prism, not sure if that helps at all.

**Comment by lachlanjc** [comment]
Closing unless there's more confirmation here, please feel free to comment!
