### ISSUE TITLE
How to use variants with Box, Flex, etc.?

### ISSUE THREAD

**Issue by TranquilMarmot** [system-ui/theme-ui#2010]
Looking at the docs here: https://theme-ui.com/components/variants

It says:

> The following components support the variant prop, but do not include default variant keys.
>    - `Box`
>    - `Flex`
>    - etc.

But it does not specify how to use `variant` with those components. I see with other components, there is a specific "Variant group" in the table (i.e. `Grid` goes with `grids`, `Button` goes with `buttons`) but there's no variant group for `Box` or `Flex`.

Using the `Theme` type to specify a theme in TypeScript, there is no way to add a `boxes` variant group. The `Box` component seems to be [looking at a `variants` key](https://github.com/system-ui/theme-ui/blob/8d80c4ea7139173872993faf096f322bd822742f/packages/components/src/Box.js#L19-L20) but you also cannot add that in TypeScript.

How do you define variants for `Box` and all of the other components that don't have their own variant group?

**Comment by lachlanjc** [comment]
Ah, we should totally make this clearer! If there's no theme key, that means you can use any variant from anywhere in the theme, but it needs a category prefix. E.g. you can write `<Grid variant="cards.sunken"` to make a Grid look like a Card, or `variant="layout.container"` to add Container's styling. (See the former [in use here](https://sourcegraph.com/github.com/hackclub/theme/-/blob/docs/pages/index.js?L166:10).)
