### ISSUE TITLE
Bug with customize menu option on theme-ui.com

### ISSUE THREAD

**Issue by acao** [system-ui/theme-ui#2015]
**Describe the bug**
The customize menu option (and only this option) on the docs site for whatever reason causes fatal exceptions that crash the entire application :/

**To Reproduce**

1. Go to https://theme-ui.com
2. Expand the menu
3. Choose "Customize"

**Expected behavior**
Excited to find out!

**Screenshots**
<img width="854" alt="Screenshot 2021-11-21 at 00 18 48" src="https://user-images.githubusercontent.com/1368727/142743649-7bc386e6-2398-408d-95fd-3a485a700e65.png">

**Comment by hasparus** [comment]
It seems our customize page didn't survive update to Gatsby 4 and other dependency version bumps.

As a workaround: You can visit it if you open [https://theme-ui.com/customize/](https://theme-ui.com/customize/) in new window.

**Comment by hasparus** [comment]
Hey @acao, it should be fixed now. (cc @lachlanjc I downgraded `stringify-object` — one of transitive dependencies was supposedly not exporting `.default`, might be bcs v4 is now publishing ESM code.)

**Comment by acao** [comment]
@hasparus ah, that keeps happening to me as well! thanks! this is awesome!
