### ISSUE TITLE
prism: Cannot read properties of undefined (reading 'replace')

### ISSUE THREAD

**Issue by hasparus** [system-ui/theme-ui#2016]
**Discussed in https://github.com/system-ui/theme-ui/discussions/2014**

_@theme-ui/prism_ crashes when `className` prop is not passed. It's a bit counterintuitive, so let's handle it.

See the sandbox and comment out both `className` and `sx`.
https://codesandbox.io/s/theme-ui-prism-crash-oqz29?file=/src/App.js

**Comment by drydenwilliams** [comment]
Thanks for creating this @hasparus! I'll give it another try with the classname

**Comment by hasparus** [comment]
:rocket: Issue was released in [`v0.15.0-develop.27`](https://github.com/system-ui/theme-ui/releases/tag/v0.15.0-develop.27) :rocket:

**Comment by hasparus** [comment]
:rocket: Issue was released in [`v0.15.0-develop.27`](https://github.com/system-ui/theme-ui/releases/tag/v0.15.0-develop.27) :rocket:
