### ISSUE TITLE
Use Theme UI Presets in Material UI library

### ISSUE THREAD

**Issue by facinick** [system-ui/theme-ui#2025]
**Is your feature request related to a problem? Please describe:**
I use material UI heavily just like a lot of other devs, it's accessible, comprehensive, beautiful and all that. However the themes in theme UI are just great, I want to be able to pass down theme UI theme presets to material UI with 0 configuration.

**(output of solution should be similar to this)**
import theme from theme UI like
`import { funk } from '@theme-ui/presets'`
pass it to material UI theme provider
```
import { ThemeProvider } from '@mui/material/styles';
<ThemeProvider theme={ funk }> </ThemeProvider>
```

**Additional context**
https://github.com/system-ui/theme-ui/discussions/819
https://github.com/system-ui/theme-ui/issues/164
https://github.com/TheFirstMe/theme-ui/blob/package-material-ui/packages/material-ui/src/to-mui.js

**Comment by lachlanjc** [comment]
Hey, thanks for the issue! While we’d accept a PR for an interoperability package, we have no plans as maintainers to build this. It’d also be a perhaps better fit for an external package we link to from docs. We’d encourage MUI to follow the [System UI Theme Spec](https://system-ui.com/theme/) that Theme UI also follows, but it’s not the concern of the Theme UI library itself to handle that sort of interop.
