### ISSUE TITLE
TypeScript inline definitions

### ISSUE THREAD

**Issue by vorillaz** [system-ui/theme-ui#2039]
**Describe the bug**
Hi there, thanks a ton for the amazing library, it is a breeze using it.
I have a question regarding TypeScript inline definitions using the `as` prop:
Is there any way to use `theme-ui` along with TypeScript without redeclaring and exporting the component?

A solution as following would be amazing:
```tsx
<Box<AmazingLinkProps> as="a" href="/buzz"></Box>
```

**Screenshots**
![Screenshot 2021-12-11 at 11 51 31 PM](https://user-images.githubusercontent.com/1022166/145692756-414912a2-5d49-4349-b580-b3bd94f074b0.png)

**Comment by hasparus** [comment]
Hey @vorillaz 👋 Thanks for the issue!

This is a footgun and won't be supported. Typed `as` prop is the easiest way to make your TypeScript compilation slow. You can use `sx` prop and JSX pragma instead.

```tsx
/** @jsxImportSource theme-ui */

<a sx={{ color: "primary" }} />

```
