### ISSUE TITLE
`theme-ui` along with `next.js` color mode is rendered incorrectly

### ISSUE THREAD

**Issue by vorillaz** [system-ui/theme-ui#2042]
**Describe the bug**
Hi there, once again thanks a lot of the great library, I am facing some issues with the `useColorMode` hook as it seems that it get's messed up with the hydration mode of `next.js`. As I am switching through the color modes upon refreshing the rendered results is pretty weird.

**To Reproduce**

1. Go to https://stackblitz.com/edit/nextjs-7whv5w?file=components/color-switcher.js
2. Click on `Toggle Mode icon`
3. Refresh the "inner window of the editor"
4. See the weird state of the icon.

**Expected behavior**
The rendered icon should reflect the color mode state.

**Screenshots**

https://user-images.githubusercontent.com/1022166/145886214-f2dffad1-c566-4c42-8eef-774cbbe68294.mov

**Comment by hasparus** [comment]
Hey @vorillaz, I can't reproduce this and to be fair, I'm not quite sure how Theme UI would affect the rendering of that icon.

**Comment by vorillaz** [comment]
@hasparus Closing this one, it appears that it is an issue with SSR from Next.js.
Thanks for the help.
