### ISSUE TITLE
Cursor image doesn't work

### ISSUE THREAD

**Issue by chefnubi** [system-ui/theme-ui#2063]
If you add   cursor: 'url("https://s3-us-west-2.amazonaws.com/s.cdpn.io/9632/happy.png")' to, for example, root, it ignores the image and doesn't show anything.

Any fixes?

**Comment by lachlanjc** [comment]
Thanks for the report! Could you provide a link to a CodeSandbox/etc for reproducing?

**Comment by chefnubi** [comment]
this is how it should work https://codepen.io/geoffgraham/pen/qZjwGe
put the cursor into any of theme ui elements and it won't change

**Comment by lachlanjc** [comment]
Oh yeah, I’m aware of the CSS property—was looking for a reproduction of it not working with Theme UI. We can try to reproduce it ourselves, but it’ll likely take longer for the issue to get addressed than if we can immediately jump into debugging it.

**Comment by hasparus** [comment]
Hey @chefnubi, thanks for the issue.
I'm sorry, but it works. Here's a CodeSandbox for you: https://codesandbox.io/s/laughing-goldberg-8sjps?file=/src/App.js

**Comment by chefnubi** [comment]
great, thanks, the docs are totally silent on cursor url and also that you need to add an auto tag, without which it doesn't work. maybe worth mentioning somewhere in case someone else is looking for this

**Comment by lachlanjc** [comment]
Since Theme UI doesn't change anything about the cursor property, it & other modified properties are purposefully not mentioned in the docs.
