### ISSUE TITLE
docs(color-modes): Add examples of array or object color scales

### ISSUE THREAD

**Issue by PeterlitsZo** [system-ui/theme-ui#2123]
After read source code. We find that it sounds like that color can be plain object or array and so on. But we do not find it in https://theme-ui.com/color-modes.

Does it need update? If it need, I can help you with PR.

**Comment by lachlanjc** [comment]
Good call! Yes, would love a PR.

**Comment by PeterlitsZo** [comment]
OK, I will try. Wait for soon.

**Comment by PeterlitsZo** [comment]
Done, I am going to close this.
