### ISSUE TITLE
Does not work in the Storybook using Vite builder

### ISSUE THREAD

**Issue by RoyalHunt** [system-ui/theme-ui#2131]
**Describe the bug**
Building Storybook using Vite as a builder (https://github.com/eirslett/storybook-builder-vite) display HTML elements without style. 
<img width="900" alt="Screenshot 2022-02-11 at 17 52 05" src="https://user-images.githubusercontent.com/22590130/153623896-c8121339-febe-45d9-9767-723f81b57526.png">

My storybook config file:
```javascript

const path = require('path');

module.exports = {
  core: {
    builder: 'storybook-builder-vite',
  },
  framework: '@storybook/react',
  features: {
    storyStoreV7: true,
    /*unlock theming for emotion11-based libraries */
    emotionAlias: false,
    /*Storybook no longer provides its own default configuration and is primarily configured via babelrc file, with small, incremental updates from Storybook addons. */
    babelModeV7: true,
  },
  staticDirs: [],
  stories: ['../packages/**/*.stories.@(ts|tsx|mdx)'],
  addons: [
    {
      name: '@storybook/addon-docs',
      options: { transcludeMarkdown: true },
    },
    '@storybook/addon-actions',
    '@storybook/addon-a11y',
    '@storybook/addon-viewport',
    '@storybook/addon-controls',
    '@storybook/addon-links',
    '@storybook/addon-toolbars',
  ],
  typescript: {
    reactDocgen: false,
  },
  async viteFinal(config) {
    config.esbuild = {
      jsxFactory: 'jsx',
      jsxInject: `import { jsx } from 'theme-ui'`,
    };
 
    config.resolve.alias = {
      ...config.resolve.alias,
      '@emotion/react': path.resolve(path.join(__dirname, '../node_modules/@emotion/react')),
      '@emotion/styled': path.resolve(path.join(__dirname, '../node_modules/@emotion/styled')),
      '@emotion/core': path.resolve(path.join(__dirname, '../node_modules/@emotion/react')),
      'emotion-theming': path.resolve(path.join(__dirname, '../node_modules/@emotion/react')),
    };

    return config;
  },
};

```

**Expected behaviour**
Wait successfully attached styles.

**Comment by PeterlitsZo** [comment]
Hello, would you please give me the link about a runable project?

It looks like that it do not use `jsx` from `theme-ui`, so we cannot parse the sx prop.

**Comment by RoyalHunt** [comment]
> Hello, would you please give me the link about a runable project?
> 
> It looks like that it do not use `jsx` from `theme-ui`, so we cannot parse the sx prop.

Yes. This is the reason. But what could be the solution?

Link to the repo: https://github.com/RoyalHunt/themeUI-storybook

Thank you.

Steps:
1. yarn
2. yarn storybook

I've tried to add babel importSource in several places, but no luck. 
Thank you.

**Comment by PeterlitsZo** [comment]
Hello. I am sorry that I cannot fix it. I try to replace the JSX:
``` diff

 const Button: React.FC<ButtonProps> = ({ children, ...rest }) => (
-  <button sx={{ bg: 'red', padding: '20px 40px', }} {...rest}>
-    {children}
-  </button>
+  jsx("button", {
+      children,
+      sx:{ backgroundColor: 'red', padding: '20px 40px' },
+      ...rest
+    },
+  )
 );
```

It works well. It looks that the `jsxFactory` and `jsxInject` not work at all. I think because that storybook do not read `vite.config.ts` and `viteconfig.base.ts` at all. Because I add a statement in those files:
``` tsx
throw new Error('FUCK');
```

But nothing happen. Would you please try to ask storybook that how to add config for vite?

**Comment by RoyalHunt** [comment]
OK. Thank you for your support

**Comment by PeterlitsZo** [comment]
Open discussion in `storybook`: https://github.com/storybookjs/storybook/discussions/17500.

Or it is a better idea to use other build tool (for example, webpack) because it may have more document than vite.
