### ISSUE TITLE
Using colors in nested color objects

### ISSUE THREAD

**Issue by SpadarShut** [system-ui/theme-ui#219]
I want to be able to reference colors in nested objects like this:
```
{
	colors: {
		primary: 'hotpink',
		dialog: {
			header: 'primary'
		}
	}
}
```

But this gives `primary` as the output in CSS. Is it not supported or am I doing something wrong?

**Comment by jxnblk** [comment]
You can use dot notation to reference nested values, e.g. `color: 'dialog.header'`, but `primary` isn't a valid CSS color, and it doesn't self-reference like this in the object. You can define the `primary` value first, then use it in multiple places within the color object, if that's what you're aiming for

**Comment by SpadarShut** [comment]
Thanks for clarifying. Looks like I just needed to use `variant` and write my styles outside of `colors` object.
