### ISSUE TITLE
`useBreakpointIndex` and `useResponsiveValue` don't handle full `@media` queries in `theme.breakpoints`

### ISSUE THREAD

**Issue by hasparus** [system-ui/theme-ui#2197]
`useBreakpointIndex` and `useResponsiveValue` don't handle full `@media` queries in `theme.breakpoints`.

Thanks for finding this @danimadmolil 🙏.

### Discussed in https://github.com/system-ui/theme-ui/discussions/2195

<div type='discussions-op-text'>

<sup>Originally posted by **danimadmolil** April  7, 2022</sup>
Hellow, i'm new to theme-ui. my project is simple react-app.on index.js i create a theme and use it with ThemeProvider like this:
### index.js
```
const theme = {
 breakpoints: [
    "@media screen and (min-width:300px) and (max-width:499px)",
    "@media screen and (min-width: 500px) and (max-width:899px)",
    "@media screen and (min-width: 900px)",
  ],
} 
<ThemeProvider theme={theme}>
   <App/>
</ThemeProvider>

```
### App.js
```
import { useResponsiveValue, useBreakpointIndex } from "@theme-ui/match-media";
function App(){
  const color = useResponsiveValue((theme) => ["red", "blue", "orange"]);
  return <div className="app" style={{backgroundColor:color}}></div>
} 
```

the result color is always red. i'm not whay it's like that. can any one help me please?
**note**:if i use breakpoint:['40em','50em','60em'] it work fine but i like to use media queries with condition like (min-width) and (max-width).</div>

**Comment by hasparus** [comment]
:rocket: Issue was released in [`v0.14.3`](https://github.com/system-ui/theme-ui/releases/tag/v0.14.3) :rocket:

**Comment by manwaring** [comment]
Not sure if a regression or I'm just misconfiguring but the same issue originally reported is happening for me in v0.16.1

**Comment by sbeben** [comment]
none of the versions works for me

**Comment by hasparus** [comment]
@sbeben what's your setup? Framework, package manager version?
