### ISSUE TITLE
Consider applying body color in Gatsby plugin without color modes

### ISSUE THREAD

**Issue by jxnblk** [system-ui/theme-ui#223]
Currently, when using the Gatsby plugin with themes that have color modes enabled, the `text` and `background` colors are applied to the `<body>`. This functionality could be enabled for themes that do not have color modes as well

**Comment by crhayes** [comment]
I think I just wrestled with an issue related to this for the last little while.

I have been building a Gatsby project from the `hello-world` starter, and essentially replicating the setup that exists in the theme-ui blog starters.

When following the directions regarding theme ui presets, the theme body text color and background color were not being applied:

```js
import { swiss as theme } from "@theme-ui/presets"

export default {
  ...theme,
  styles: {
    ...theme.styles,
  },
}
```

After changing the code to the following, it worked:

```js
import { swiss as theme } from "@theme-ui/presets"

export default {
  initialColorModeName: "default",
  ...theme,
  colors: {
    ...theme.colors,
    modes: {},
  },
  styles: {
    ...theme.styles,
  }
}
```

IMO this is not very intuitive. It would be nice if the background color and text color were applied even when working with only one default color mode.
