### ISSUE TITLE
It's not obvious that `@theme-ui/core` doesn't apply `styles.root`.

### ISSUE THREAD

**Issue by CamilleHbp** [system-ui/theme-ui#2235]
**Describe the bug**
The default 8px margin that Chrome puts on the <body> element is present, even when styling `root` to have margin and padding set to 0.

**To Reproduce**

Have `"@theme-ui/core": "^0.14.5"` (not using the complete theme-ui package since the mdx package causes problems with Vite build).
Inspect body and find a `margin: 8px` applied by default to the <body> element

**Expected behavior**
Expected the <body> to have `margin: 0` on the body.

**Screenshots**
<img width="761" alt="image" src="https://user-images.githubusercontent.com/11173924/169222389-8484fb2a-4ac3-4766-a4af-7f29689999f5.png">

**Additional context**
I'm using React v18 and Vite as a builder. I saw [this issue](https://github.com/system-ui/theme-ui/issues/1719), but it's marked as resolved. Has there been a regression?

**Comment by hasparus** [comment]
> Have "@theme-ui/core": "^0.14.5" (not using the complete theme-ui package since the mdx package causes problems with Vite build).

`@theme-ui/core` doesn't add any styles to the root. This is implemented "later" in `theme-ui` (actually `@theme-ui/theme-provider`). I'm not sure if this is explained in the docs TBH.

Take a look at [RootStyles](https://github.com/system-ui/theme-ui/blob/2bf16859ee3001c1a0666535b6a3e2a0ccbe55e2/packages/theme-provider/src/index.tsx#L18)

**Comment by hasparus** [comment]
:rocket: Issue was released in [`v0.15.2`](https://github.com/system-ui/theme-ui/releases/tag/v0.15.2) :rocket:

**Comment by CamilleHbp** [comment]
Thanks for the follow-up and the change to the documentation ! 🙏
