### ISSUE TITLE
Radio forces iframe to scroll in a wrong way

### ISSUE THREAD

**Issue by AlexisLeite** [system-ui/theme-ui#2236]
As the title says, the radio button in a particular situation, forces the browser to scroll in a bad manner.

**To Reproduce**

- Please, visit: https://codesandbox.io/s/clever-tamas-2wszu6?file=/src/App.js:37-43
- Focus the input at the beginnig of the document.
- Press tab until the scroll gets broken

**Comment by lachlanjc** [comment]
Hey! I'm trying this out but I don't see any scrolling that's broken—I wouldn't recommend scrollable fixed-position elements in general, but pressing tab through the focusable elements, the frame scrolls just fine for me. Can you be more specific about the behavior you're expecting vs seeing here?

**Comment by AlexisLeite** [comment]
I dont know why it didn't fail to you, we tried it with my mates and it failed to us all. Here you have an attached video to see what happens to me

https://vimeo.com/712960511

**Comment by hasparus** [comment]
Can you remove `overflow: hidden` from the top level box? It solves the problem. 

https://codesandbox.io/s/sad-lichterman-cenwbv?file=/src/App.js

If you have bandwith, we'd love a deeper insight into why does this fail in your use case. Is the visually hidden input the culprit? Can this behaviour be observed with other styled radio inputs?

**Comment by AlexisLeite** [comment]
Hi, sorry for the delay.

I've solved the problem with this css code:

`input[type="radio"], input[type="checkbox"] {
  position: relative !important;
  float: right;
}`

Greetings
