### ISSUE TITLE
Enabling "useCustomProperties" breaks dot selector for colors

### ISSUE THREAD

**Issue by KyleAMathews** [system-ui/theme-ui#224]
Can be replicated in https://github.com/KyleAMathews/gatsby-theme-hyde

If you install and run and navigate to http://localhost:8000/hello-world which has some code blocks — all the prism color tokens aren't getting replaced by their actual values but are left as strings e.g. `background-color: prism.background;`

**Comment by johnletey** [comment]
@KyleAMathews I was trying to reproduce this,

But for some reason, after executing the following commands:

- `git clone KyleAMathews/gatsby-theme-hyde` (I use [hub](https://github.com/github/hub))
- `cd gatsby-theme-hyde`
- `yarn`
- `yarn workspace starter develop` (I have created a PR to fix this command in your README ... https://github.com/KyleAMathews/gatsby-theme-hyde/pull/1)

I get an error:

![Shot 2019-07-26 at 10 27 03](https://user-images.githubusercontent.com/30328854/61941823-2278bc00-af90-11e9-86a7-45f3421b1c65.jpg)

@jxnblk Any thoughts? 💭

**Comment by jxnblk** [comment]
@johnletey that error can occur if there are mismatched versions of Emotion or Theme UI, and it can't find the same React context, but I'm not entirely sure why that would happen in this case

**Comment by loganpowell** [comment]
I am also experiencing this (using `useCustomProperties: true`

**Comment by loganpowell** [comment]
my package.json:
```js
"dependencies": {
    "@emotion/core": "^10.0.14",
    "@emotion/styled": "^10.0.14",
    "@mdx-js/loader": "^1.0.19",
    "@next/mdx": "^8.1.0",
    "color": "^3.1.2",
    "lodash.mapkeys": "^4.6.0",
    "next": "^9.0.2",
    "next-mdx-enhanced": "^2.0.0",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-flip-toolkit": "^6.6.9",
    "remark-autolink-headings": "^5.2.1",
    "remark-emoji": "^2.0.2",
    "remark-slug": "^5.1.2",
    "remark-toc": "^6.0.0",
    "remark-unwrap-images": "^1.0.0",
    "theme-ui": "^0.2.23"
  },
  "author": "Logan Powell",
  "license": "MIT",
  "devDependencies": {
    "@babel/core": "^7.0.0",
    "cross-env": "^5.2.0",
    "lodash.camelcase": "^4.3.0"
  }
```

**Comment by loganpowell** [comment]
I can also confirm that removing the `useCustomProperties` from my theme.js enables me to use the dot accessor

**Comment by loganpowell** [comment]
but also causes the F.O.U.C.
