### ISSUE TITLE
peer dependency issue for @theme-ui/prism@0.14.5

### ISSUE THREAD

**Issue by julianste** [system-ui/theme-ui#2251]
**Describe the bug**
 Output of `npm info @theme-ui/prism@0.14.5 peerDependencies` is

```
{ 'theme-ui': '^0.11' }
```
so it is not compatible to theme-ui 0.14.5, but probably should be?

**Expected behavior**
I'm no javascript expert but shouldn't @theme-ui/prism@0.14.5 be compatible to theme-ui 0.14.5? So output is something like
```
{ 'theme-ui': '^0.14' }
```

**Screenshots**
on npm install
<img width="644" alt="Screenshot 2022-06-15 at 11 22 58" src="https://user-images.githubusercontent.com/8767660/173793323-82b36951-ab9c-4132-ab41-95de8dde9a3a.png">

**Comment by hasparus** [comment]
Good catch @julianste! Thanks for the issue.

**Comment by hasparus** [comment]
Released in [v0.14.6](https://github.com/system-ui/theme-ui/releases/tag/v0.14.6)
