### ISSUE TITLE
I wish to change the color of checkbox after checked.

### ISSUE THREAD

**Issue by charleshoong97** [system-ui/theme-ui#2253]
I do not found any documentation stated how to change the color of checkbox once checked.

Please provide the description to achieve this.

**Comment by lachlanjc** [comment]
The Checkbox component will use your theme's `primary` color when checked: https://github.com/system-ui/theme-ui/blob/develop/packages/components/src/Checkbox.tsx#L92

Here's our docs on adding colors to your theme: https://theme-ui.com/theming#colors

Happy to help with any specific issues you're running into with your theme!
