### ISSUE TITLE
Change the placeholder for Input type = Date

### ISSUE THREAD

**Issue by charleshoong97** [system-ui/theme-ui#2267]
How can I change the placeholder from mm/dd/yyyy to '-Select-'?

![image](https://user-images.githubusercontent.com/45910910/177905090-39c81711-7f23-4801-b3da-4edbbe593061.png)

**Comment by lachlanjc** [comment]
The placeholder attribute does not work with the input type date—this isn't Theme UI specific, just a browser behavior. You'll have to either make your own datepicker, layer inputs on top of one another, hack a text layer on top of the unfilled input using CSS, or settle for the browser behavior. Sorry it's not more satisfying :(
