### ISSUE TITLE
Using babel plugin instead of pragma

### ISSUE THREAD

**Issue by adamsoffer** [system-ui/theme-ui#227]
The documentation states:
"To change the underlying create element function, you can either add an option to the Babel plugin or you can set a pragma comment at the beginning of a module."

Is that referring to @styled-system/babel-plugin?

**Comment by jxnblk** [comment]
No, this is referring to how JSX works generally with [@babel/plugin-transform-react-jsx](https://babeljs.io/docs/en/babel-plugin-transform-react-jsx) – the recommended way to use Theme UI is with the pragma comment `/** @jsx jsx */`

**Comment by adamsoffer** [comment]
Thanks. I know it's not as performant but is it still possible to use a babel plugin instead of the pragma?

**Comment by jxnblk** [comment]
Yes, it's still possible, the pragma comment and Babel plugin option both replace `React.createElement` with the custom function – one works per file and the other works globally in a project

**Comment by adamsoffer** [comment]
Sweet, thanks! Last question - what's the Babel plugin option?

**Comment by adamsoffer** [comment]
Hey - @jxnblk what's the babel plugin option to get the sx prop working? Couldn't find it in the docs.

**Comment by adamsoffer** [comment]
@jxnblk I'm using theme-ui with next. If I don't include the pragma at the beginning of the file, sx props are ignored. Any idea what to include in my `babelrc` file to get it working?

**Comment by jxnblk** [comment]
You can use the Babel plugin linked above, it includes docs for setting project-wide jsx pragma: https://babeljs.io/docs/en/babel-plugin-transform-react-jsx

**Comment by adamsoffer** [comment]
@jxnblk gotcha. So something like this?
```
{
  "presets": ["next/babel"],
  "plugins": [
    ["@babel/plugin-transform-react-jsx", {
      "pragma": "jsx"
      "pragmaFrag": "React.Fragment"
    }]
  ]
}
```

**Comment by adamsoffer** [comment]
This above doesn't seem to work :/

@jxnblk any chance you could provide an example on how to use theme-ui without using the pragma? Either in the docs or in a codesandbox?

Not a big deal, but ideally I don't have to put this at the beginning of each component file:
```
/** @jsx jsx */
import { jsx } from 'theme-ui'
```

**Comment by Grsmto** [comment]
Any reason this issue is closed? Does it mean you have a strong preference for the pragma design vs the global Babel plugin? Is that worth writting one? Would you accept it?
I'm asking this because Xstyled has made the choice and provides a Babel plugin. @adamsoffer maybe you can take a look at [their implementation](https://github.com/smooth-code/xstyled/tree/master/packages/babel-preset-emotion-css-prop), that should be fairly easy to adapt it to ThemeUI?

I built an entire website with ThemeUI and JSX pragma, it's fine this way but it happened to me a couple of times to not understand why my styles were not working and figure out I forgot the pragma. 
Also it's less intuitive for noobs ("_wtf is this comment at the top?_") and that's not something you **have** to understand to style a component.

**Comment by AndrewPrifer** [comment]
I also don't understand this preference. Why wouldn't users want to use design tokens and `sx` for all their components? If anything, I think that's the rarer case. Plus you can also do all sorts of other nice things with a babel plugin, just look at emotion.

**Comment by adamsoffer** [comment]
@AndrewPrifer there's an [open PR](https://github.com/system-ui/theme-ui/pull/479) that introduces a theme-ui babel preset. Until this gets published if you want to avoid having to add a jsx pragma to every file you can add the following to your `.babelrc`.
```
{
  "plugins": [
    [
      "@emotion/babel-plugin-jsx-pragmatic",
      {
        "module": "theme-ui",
        "import": "jsx",
        "export": "jsx"
      }
    ],
    [
      "@babel/plugin-transform-react-jsx",
      {
        "pragma": "jsx",
        "pragmaFrag": "React.Fragment"
      }
    ]
  ]
}
```

**Comment by AndrewPrifer** [comment]
@adamsoffer nice!

**Comment by Ericnr** [comment]
I get this when running the above babel plugins with CRA 4 and Craco
```
Module parse failed: Identifier 'jsx' has already been declared (18:9)
File was processed with these loaders:
 * ./node_modules/@pmmmwh/react-refresh-webpack-plugin/loader/index.js
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
| import { Input } from '../components/inputs/Input';
| import { Button } from '../components/buttons/Button';
> import { jsx } from "theme-ui";
| export const Login = () => {
|   _s();
```
has anyone gotten it to work with react 17?

**Comment by AndrewPrifer** [comment]
@Ericnr CRA4 introduces a new Babel config that allows you to stop having to `import React from 'react'` in every file. I strongly think it's in connection to that.

I have a hunch if you rename jsx in the above Babel plugins and in the import to something else, it'll work.

**Comment by hasparus** [comment]
@Ericnr we don't support the new `automatic` jsx runtime yet. @dcastil is working on it.

In the meantime, you can change `automatic` to `classic` in your babel options with `"runtime": "classic"` or a pragma comment `@jsxRuntime classic`

https://babeljs.io/docs/en/babel-plugin-transform-react-jsx#:~:text=React%20Automatic%20Runtime,to%20will%20be%20imported%20automatically.

**Comment by Ericnr** [comment]
yea I did try it with classic runtime but still get the same error. I'll wait for the fix, thx!

**Comment by hasparus** [comment]
@Ericnr, okay let me try one last thing.

Are you're using `"@emotion/babel-plugin-jsx-pragmatic"` from the post above?
If so, do you also have some lines importing { jsx } from 'theme-ui'?
Is the problem fixed if you remove those lines?

**Comment by Ericnr** [comment]
oh I had to remove `DISABLE_NEW_JSX_TRANSFORM=true` I had on cause I was trying many different things. I dont get that error anymore but now TS complains about the `sx` prop `Property 'sx' does not exist on type 'DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>'`. How can I tell TS that babel is importing theme-ui's jsx?

**Comment by AndrewPrifer** [comment]
@Ericnr I guess that's because you don't explicitly import anything from theme-ui that could extend JSX.IntrinsicElements so you have to do it manually. I'd just take a look at theme-ui's code and copy the type they're using. Should look sth like 

```ts
declare global {
  namespace JSX {
    interface IntrinsicElements {
      // ...
    }
  }
}
```

**Comment by Ericnr** [comment]
@AndrewPrifer that does it, thanks

**Comment by adamsoffer** [comment]
This actually stopped working for me. TS compains `Property 'sx' does not exist on type 'DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>'` for me as well. @Ericnr how did you end up solving this?

**Comment by hasparus** [comment]
Sorry @adamsoffer, we forgot to document this.

Here's what happened and how to solve the problem (tldr: declare module 'react' and augment Attributes instead of global.JSX): https://github.com/system-ui/theme-ui/issues/1335#issuecomment-749543430

**Comment by a-y-u-s-h** [comment]
@adamsoffer @hasparus Can you explain that a bit more. @adamsoffer 's adding something to `.babelrc` trick worked earlier for me in Javascript as well. What do I need to change to make it work again?

**Comment by hasparus** [comment]
Hey @a-y-u-s-h. Are you using _automatic_ or _classic_ JSX runtime?

We have some info on automatic runtime config in the docs https://theme-ui.com/guides/jsx-pragma#automatic-jsx-runtime

**Comment by a-y-u-s-h** [comment]
@hasparus I'm not very familiar with it. Here's what my babel entry looks like in `package.json` now after you mentioned it, I'll try out a few more things and let you know if any of it works. Let me know if anything's wrong about this, I can't figure it out. 

```json
  "babel": {
    "presets": [
      "next/babel"
    ],
    "plugins": [
      [
        "@emotion/babel-plugin-jsx-pragmatic",
        {
          "module": "theme-ui",
          "import": "jsx",
          "export": "jsx"
        }
      ],
      [
        "@babel/plugin-transform-react-jsx",
        {
          "pragma": "jsx",
          "runtime": "automatic",
          "importSource": "theme-ui",
          "pragmaFrag": "React.Fragment",
          "throwIfNamespace": false
        }
      ]
    ]
  },

```

No luck with this either - 

```json
  "babel": {
    "presets": [
      [
        "next/babel",
        {
          "preset-react": {
            "importSource": "theme-ui",
            "runtime": "automatic",
            "throwIfNamespace": false
          }
        }
      ]
    ]
  },
```

**Comment by hasparus** [comment]
Could you define what "no luck" means in this case, @a-y-u-s-h? What errors do you see?

You don’t need plugin-jsx-pragmatic if you’re already using Automatic runtime. You’ll end up with two jsx functions automatically imported for you.

Do you get errors at runtime? Or does TypeScript lack knowledge about the `sx` prop?

**Comment by a-y-u-s-h** [comment]
I'm using Javascript NextJS. No errors, just that when I use sx prop like this anywhere: 

```html
<div sx={{ variant: "something" }}>
```

I'm getting this as the rendered output `[object Object]` which I guess means it's not working: 

![screenshot_20210810_164947](https://user-images.githubusercontent.com/19586719/128858142-5bdfd1ba-a253-430b-960f-6b8edae3d026.png)

Note: I've also edited my `jsconfig.json` file and the results are same:

```json
{
  "compilerOptions": {
    "jsx": "react-jsx",
    "jsxImportSource": "theme-ui",
    "baseUrl": ".",
    "paths": {
      "@/*": ["src/*"]
    }
  }
}

```

**Comment by hasparus** [comment]
@a-y-u-s-h, this should help you: https://nextjs.org/docs/advanced-features/customizing-babel-config

I'm not sure if `"babel"` property in package.json is accepted in Next.js. I'd go with `.babelrc` like they say in the docs.

```json
  {
    "presets": [
      [
        "next/babel",
        {
          "preset-react": {
            "importSource": "theme-ui",
            "runtime": "automatic",
            "throwIfNamespace": false
          }
        }
      ]
    ]
  }
  ```
