### ISSUE TITLE
`IntrinsicSxElements` does not include `span` property

### ISSUE THREAD

**Issue by Merlin04** [system-ui/theme-ui#2291]
**Describe the bug**
The `IntrinsicSxElements` interface, defined in `@theme-ui/core/src/types.ts`, appears to be the only public-facing way to access the types of props of Theme UI's JSX intrinsic elements. It does not include a `span` property, despite including properties for seemingly every other major element type (like `div`, `h1`-`h6`, `img`, `code`, etc).

**To Reproduce**

1. Attempt to make a component that looks something like this:
```tsx
function CustomSpan(props: IntrinsicSxElements["span"] & { myProp: string }) {
    return <span sx={{ ...props }} />;
}
```
2. Observe that TypeScript gives an error on `"span"`:
   > TS2339: Property 'span' does not exist on type 'IntrinsicSxElements'.

**Expected behavior**
This interface should include a `span` property.

**Additional context**
The workaround I'm currently using is to use `JSX.IntrinsicElements["span"] & SxProp`, which is what each `IntrinsicSxElements` property eventually expands to.

I'd be happy to make a PR to fix this, just wanted to check that this wasn't intentional for some reason I didn't realize before spending time doing so.

**Comment by hasparus** [comment]
I've removed `IntrinsicSxElements` in my latest PR. You can use `React.ComponentPropsWithoutRef<'span'>` in your case. If you have `@jsxImportSource` comment or `"jsxImportSource"` configured in your TypeScript config, it should automatically add the `sx` prop to `span` props.

**Comment by Merlin04** [comment]
Oh nice, didn't realize that - thanks so much!
