### ISSUE TITLE
why not call getIndex() as initialState?

### ISSUE THREAD

**Issue by yulodl** [system-ui/theme-ui#2297]
https://github.com/system-ui/theme-ui/blob/571ba9faed73c64f06498c8467b60416cd89448f/packages/match-media/src/index.ts#L25

I wonder why not automately call getIndex() as initialState?
Only call getIndex() inside useEffect, so the hook will be compatible with SSR ? But we can distinct with window existence to make compatible with SSR.

**Comment by hasparus** [comment]
If we depend on `window` we will make it incompatible with SSR, won't we? We'd get one result on serverside render, then another one in hydration, that causes a mismatch and shows up everyone's favorite SSR error message.

Take a look at this: https://nextjs.org/docs/messages/react-hydration-error#possible-ways-to-fix-it

**Comment by yulodl** [comment]
Got it！Thanks for answering. I will close this.
