### ISSUE TITLE
Property 'to' does not exist on type 'IntrinsicAttributes & Pick<LinkProps ...

### ISSUE THREAD

**Issue by gabobaxx** [system-ui/theme-ui#2332]
**Describe the bug**
Link Component does not recognize the "to" property and typescript detect that as error but the server runs with no problem.

**Screenshots**

![complete error](https://user-images.githubusercontent.com/59029788/193142699-f676f07d-6dbb-4da6-99e7-f849607d067e.png)
![react component](https://user-images.githubusercontent.com/59029788/193142724-7e73ffa4-6650-4e07-859d-2aaa68efc8af.png)

**Additional context**
This error is more ts and eslint than anything else but i have not been able to remove it. 
Does anyone know if i have to install separate types or some other config?

**Comment by hasparus** [comment]
Hey 👋  Thanks for the issue!

`Link` doesn’t support isomorphic `as` prop in TypeScript, because it affected typechecking times severely.

Whenever you’re using `as=` in JSX, you might also need to use TypeScript type assertion (`x as NewType`).

```ts
interface MyLinkProps extends LinkProps, RLinkProps {
  as: typeof RLink // this is now required
}

const MyLink = Link as any as (props: MyLinkProps) => JSX.Element
```

**Comment by gabobaxx** [comment]
> Hey wave Thanks for the issue!
> 
> `Link` doesn’t support isomorphic `as` prop in TypeScript, because it affected typechecking times severely.
> 
> Whenever you’re using `as=` in JSX, you might also need to use TypeScript type assertion (`x as NewType`).
> 
> ```ts
> interface MyLinkProps extends LinkProps, RLinkProps {
>   as: typeof RLink // this is now required
> }
> 
> const MyLink = Link as any as (props: MyLinkProps) => JSX.Element
> ```

Thanks a lot. The problem was solved correctly!
