### ISSUE TITLE
How to apply `-webkit-font-smoothing: antialiased;` within `sx` prop

### ISSUE THREAD

**Issue by loganpowell** [system-ui/theme-ui#234]
Is it possible to use `-webkit-font-smoothing: antialiased;` inside the `sx` prop? It doesn't quite map to the camelCase situation...

**Comment by connorholyday** [comment]
I believe you use it like this `sx={{ "-webkit-font-smoothing": "antialiased" }}`

**Comment by jxnblk** [comment]
Most vendor prefixes use uppercase like this in Emotion: `WebkitFontSmoothing` – I believe that should work but haven't tried myself

**Comment by connorholyday** [comment]
I've just tried on CodeSandbox and both methods work 👍

**Comment by loganpowell** [comment]
Thank you both!
