### ISSUE TITLE
Not working with Web Component and Shadow DOM

### ISSUE THREAD

**Issue by ycgarrido** [system-ui/theme-ui#2350]
Hello, I am currently working on creating widgets. Widgets are developed with ReactJS and a bundle is compiled to include them as a Web Component. When I don't use shadowDom everything works perfect, but when I activate shadowDom the widget styles are lost.

Without Shadow DOM:
![image](https://user-images.githubusercontent.com/32363657/197794202-9af51416-5a94-40e3-982d-d789bae64765.png)

With Shadow DOM:
![image](https://user-images.githubusercontent.com/32363657/197794514-e6b506e5-9a74-4c34-bc2c-16f57d5f79ec.png)

**Comment by lachlanjc** [comment]
Hi there! Theme UI has no official support for web components, I don't know anything about the topic personally. Can you provide source code & a repro vs what the expected behavior is?
