### ISSUE TITLE
Unable to override initialColorMode from site

### ISSUE THREAD

**Issue by sonapraneeth-a** [system-ui/theme-ui#236]
I'm trying override the ```initialColorMode``` defined in theme with a different one in site. But the override in not successful. However, I'm able to override colors defined for light/dark theme.

Repo link: [Link](https://github.com/sonapraneeth-a/gatsby-theme-simple-bio/)
Overriden files: [Colors override](https://github.com/sonapraneeth-a/gatsby-theme-simple-bio/tree/master/demo/src/gatsby-theme-simple-bio/gatsby-plugin-theme-ui/colors.js) and [Default theme override](https://github.com/sonapraneeth-a/gatsby-theme-simple-bio/tree/master/demo/src/gatsby-theme-simple-bio/gatsby-plugin-theme-ui/index.js)

**Comment by johnletey** [comment]
@sonapraneeth-a Shouldn't the [Color override](https://github.com/sonapraneeth-a/gatsby-theme-simple-bio/tree/master/demo/src/gatsby-theme-simple-bio/gatsby-plugin-theme-ui/colors.js) file be more like this?

```js
export default merge({}, defaultThemeColors, {
  modes: {
    light: {
      text: "red",
    },
    dark: {
      text: "white",
    },
  },
});
```

**Comment by sonapraneeth-a** [comment]
@johnletey , From this [page](https://theme-ui.com/color-modes), there is no special key word for light theme.
- So, is ```light``` keyword necessary?
- How do I override ```initialColorMode``` in site?

**Comment by johnletey** [comment]
Yes @sonapraneeth-a ... I was looking at other Theme UI sites and they don't use the `light` keyword ... so ignore my above comment

Take a look at this gatsby-theme-documentation [file](https://github.com/johno/gatsby-theme-documentation/blob/master/examples/gatsby-starter-documentation/src/gatsby-theme-documentation/theme.js) ... it might help

**Comment by sonapraneeth-a** [comment]
@johnletey ,

I have been using [Default theme override](https://github.com/sonapraneeth-a/gatsby-theme-simple-bio/tree/master/demo/src/gatsby-theme-simple-bio/gatsby-plugin-theme-ui/index.js) to override ```initialColorMode``` defined in [Actual theme](https://github.com/sonapraneeth-a/gatsby-theme-simple-bio/tree/master/gatsby-theme-simple-bio/src/gatsby-plugin-theme-ui/index.js) which is not working (I'm expecting it to work). I'm not sure what I'm doing wrong?

**Comment by jxnblk** [comment]
This is probably an unclear part of the API and a poor choice in naming conventions. The default color mode must be defined as the root-level `theme.colors` object. The `initialColorMode` value is *only* used as a name for the root-level `theme.colors` and should not be used to set an initial color mode. 

If you want to set a dark mode as your initial color mode, you'll need to have a theme object something like the following:

```js
export default {
  initialColorMode: 'dark',
  colors: {
    text: 'white',
    background: 'black',
    modes: {
      light: {
        text: 'black',
        background: 'white',
      }
    }
  }
}
```

**Comment by sonapraneeth-a** [comment]
@jxnblk , this means ```initialColorMode``` cannot be overriden in sites where the theme is used?

**Comment by jxnblk** [comment]
@sonapraneeth-a I'm not entirely sure what you mean, but you can override anything in the object. The `initialColorMode` value is only used to give a *name* to the `theme.colors` object – it should not match one of the keys in `theme.colors.modes`

**Comment by sonapraneeth-a** [comment]
@jxnblk , Ok! I seem to understand now. ```initialColorMode``` is a name given to ```theme.colors``` object defined before ```modes```.

My question is if the theme has defined ```initialColorMode``` to be ```light``` and other color modes are ```dark1```, ```light1``` etc., is it possible to have site load with a theme other than ```light``` on its first ever load which is currently not the case? (That is, if you are loading the site for the first time, then is it possible to have site load theme other than ```light``` theme. I've tried using ```setColorMode("dark1")``` after reading ```colorMode``` from ```useColorMode()``` but that solution was not that good and had some issues.)

**Comment by jxnblk** [comment]
The default color mode is the top-level `theme.colors` object. If you want those colors to be different, then you'll need to redefine the color values. For example, if you wanted to swap the `gatsby-theme-blog` color modes around and default to the dark mode, you could do something like this:

```js
import theme from 'gatsby-theme-blog/src/gatsby-plugin-theme-ui'
import omit from 'lodash.omit'

export default {
  ...theme,
  initialColorMode: 'dark',
  colors: {
    ...theme.colors.modes.dark,
    modes: {
      light: {
        ...omit(theme.colors, ['modes']),
      }
    }
  }
}
```

**Comment by johnletey** [comment]
@jxnblk Thanks for explaining ... makes sense!

Also, congratulations on the engagement!

**Comment by sonapraneeth-a** [comment]
> The default color mode is the top-level `theme.colors` object. If you want those colors to be different, then you'll need to redefine the color values. For example, if you wanted to swap the `gatsby-theme-blog` color modes around and default to the dark mode, you could do something like this:
> 
> ```js
> import theme from 'gatsby-theme-blog/src/gatsby-plugin-theme-ui'
> import omit from 'lodash.omit'
> 
> export default {
>   ...theme,
>   initialColorMode: 'dark',
>   colors: {
>     ...theme.colors.modes.dark,
>     modes: {
>       light: {
>         ...omit(theme.colors, ['modes']),
>       }
>     }
>   }
> }
> ```

Now I clearly understand how to achieve what I want. Thanks @jxnblk . 

However, I'm unable to override [index.js](https://github.com/sonapraneeth-a/gatsby-theme-simple-bio/blob/master/demo/src/gatsby-theme-simple-bio/gatsby-plugin-theme-ui/index.js). I tested by ```console.log``` baseTheme value and I don't see it printed on browser console and hence the override is not working for me.

**Comment by jxnblk** [comment]
I haven't looked super closely at your code base, but instead of shadowing the plugin within the theme like this: `src/gatsby-theme-simple-bio/gatsby-plugin-theme-ui/index.js`, have you tried shadowing `src/gatsby-plugin-theme-ui/index.js` directly? It can be a little easier to understand with a flatter shadowing structure

**Comment by shoaibsharif** [comment]
I still have the same problem where my primary color is not overriding. if you see [this link](https://5d563ef256e7adf97c9934af--sad-cray-763e40.netlify.com/) , you will see when clicking the icon top right corner is not changing its hover color. I have solved the problem by creating a light and dark modes inside the colors.modes and that way I can only override the issue. [source code] (https://github.com/shoaibsharif/gatsbyPortfolio)

**Comment by jxnblk** [comment]
Closing this for now since the API in [v0.3](https://github.com/system-ui/theme-ui/pull/535) *should* hopefully be clearer
