### ISSUE TITLE
@theme-ui/global breaks when using with Vite.js define global config

### ISSUE THREAD

**Issue by arantespp** [system-ui/theme-ui#2393]
**Describe the bug**

When I have this configuration on `vite.config.ts` (it's a solution to use Vite.js with AWS Amplify as shown [here](https://stackoverflow.com/a/71064726/8786986)):

```js
export default defineConfig(async () => {
  return {
    define: {
      global: {},
    }
    ... // rest of config
  }
}
```
I got this error:

```sh
[vite]: Rollup failed to resolve import "@theme-ui/{}" from "/hdd1T/startup/ttoss/ttoss/node_modules/theme-ui/dist/theme-ui.esm.js".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
error during build:
```

![image](https://user-images.githubusercontent.com/16626980/219014816-ed13590a-5e26-46e5-bb75-e0e8e560cbd6.png)

It seems that whenever I use to define `global,` it replaces `export { default as Global } from '@theme-ui/global';` on `theme-ui/dist/theme-ui.esm.js.` For example, if I use `global: 'window'` on `vite.config.ts,` the error message changes to:

```
[vite]: Rollup failed to resolve import "@theme-ui/window" from
```

![image](https://user-images.githubusercontent.com/16626980/219015007-36f8d8ce-bd65-41b0-bc99-828897ed1c33.png)

**To Reproduce**

1. Clone https://github.com/ttoss/ttoss
2. Add `{ define { global: { } }` on [`vite.config.ts`](https://github.com/ttoss/ttoss/blob/main/terezinha-farm/app/vite.config.ts)
3. On the monorepo root, run `yarn` and `yarn turbo run build.`

**Expected behavior**

It shouldn't not replace the `global` from `@theme-ui/global.`

**Additional context**

If you're using `{ define { global: { } }` to use with AWS Amplify, you can remove the config and add [this script](https://github.com/aws/aws-sdk-js/issues/3673#issuecomment-1004521760).

**Comment by hasparus** [comment]
I'm sorry, but this Amplify issue, not Theme UI issue.
It seems that the [StackOverflow](https://stackoverflow.com/questions/70938763/build-problem-with-react-vitejs-and-was-amplify/71064726#71064726) post you've linked was edited to include a proper solution.

```js
optimizeDeps: {
  esbuildOptions: {
    define: {
      global: 'globalThis',
    },
  },
},
```

https://github.com/aws/aws-sdk-js/issues/3673#issuecomment-1416518328
https://github.com/vitejs/vite/issues/2878
