### ISSUE TITLE
button colors for dark mode not working theme ui

### ISSUE THREAD

**Issue by sikhaman** [system-ui/theme-ui#2407]
**Describe the bug**
If I specify button colors for dark mode they don't apply when dark mode is on

**To Reproduce**
to reproduce open the link with small project on [codesandbox](https://codesandbox.io/s/gallant-colden-9xpyz8?file=/src/theme.js) 

1. look at theme object it contains styles for dark modes
2. click on button to change the color mode

**Expected behavior**
I expect after a button is clicked, it's background becomes white and text black

**Actual behaviour**
Button doesn't change styles

**Additional context**
Maybe I wrongly point colors?

**Comment by hasparus** [comment]
Take a look at this sandbox: https://codesandbox.io/p/sandbox/intelligent-orla-gcijxc?file=%2Fsrc%2Fmain.tsx&selection=%5B%7B%22endColumn%22%3A1%2C%22endLineNumber%22%3A11%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A11%7D%5D

Theme UI doesn't switch _styles_ per color mode, just _colors_.

**Comment by sikhaman** [comment]
Ohhhh I see now! Thank you so much for helping. Now I guess this issue can be closed

**Comment by hasparus** [comment]
I'm glad I helped :)
