### ISSUE TITLE
Module '"theme-ui"' has no exported member 'Grid'.ts(2305)

### ISSUE THREAD

**Issue by mohammed-bahumaish** [system-ui/theme-ui#2410]
**Describe the bug**
I'm working on a project where theme-ui is being used. and the project can't build becouse of this error (Module '"theme-ui"' has no exported member 'Grid'.ts(2305))

**To Reproduce**
import { Grid, useThemeUI } from 'theme-ui'

**Expected behavior**
to work as in the documentation

**Additional context**
versions:
    "theme-ui": "^0.3.5"
    "react": "17.0.1"
    "@emotion/react": "^11.1.5"

**Comment by hasparus** [comment]
Hey @mohammed-bahumaish! Version `^0.3.5` was published 2 years ago. You can update to a new version (and get better TypeScript experience, not needing @types/theme-ui anymore.) which includes `Grid`.
