### ISSUE TITLE
Give logo image a white BG on README

### ISSUE THREAD

**Issue by ghost** [system-ui/theme-ui#2417]
**Is your feature request related to a problem? Please describe.**
On the [README.md file](https://github.com/system-ui/theme-ui/blob/cbea6302a721a06b4240850ad9df2313ff0d56d3/packages/theme-ui/README.md), the [logo](https://github.com/system-ui/theme-ui/blob/cbea6302a721a06b4240850ad9df2313ff0d56d3/packages/docs/static/logo.png) that is displayed is impossible to see on Github's Default Dark Theme. Screenshot provided in context section.

**Describe the solution you'd like**
Give the logo image a white background.

**Describe alternatives you've considered**
Just switching to light mode- but can't really do that just for one repository every time you want to look at it...

**Additional context**
![Screen Shot 2023-04-15 at 10 44 21 AM](https://user-images.githubusercontent.com/130259005/232244998-a01956ad-5409-4aa6-a403-52cee67bf626.png)

**In the screenshot it looks easier to see, however in real life on a real computer, it is hard to see the logo.**

**Comment by sammarxz** [comment]
PR: https://github.com/system-ui/theme-ui/pull/2446

**Comment by ghost** [comment]
FIxed with #2446
