### ISSUE TITLE
Unable to use sx prop on Input component

### ISSUE THREAD

**Issue by rilrom** [system-ui/theme-ui#2426]
Description

When using the Input component, sx does not apply.

This does not happen for any of the other components I've tried (e.g. Box, Label etc).

The only difference I can see between these components is that sx is being called explicitly in the Input code.

To reproduce:

1. Set up a theme provider.
2. Apply some basic styles in forms.input.
3. Attempt to override them using an sx prop.
4. Styles do not appear in the browser styles console log.

Expected behaviour

sx prop for Input works the same as other components.

**Comment by Caryyon** [comment]
@rilrom could you provide some example code, with a quick glance at the [Input component](https://github.com/system-ui/theme-ui/blob/develop/packages/components/src/Input.tsx#L44-L53) it is a simple passthrough. We need a bit more context of your specific usage.

**Comment by rilrom** [comment]
@Caryyon apologies for not setting up a reproducible example when this ticket was created.

I am unable to reproduce at this time so i'm okay with closing this ticket, thanks.
