### ISSUE TITLE
TS error: Namespace 'React.JSX' has no exported member 'ElementType'.

### ISSUE THREAD

**Issue by jlowcs** [system-ui/theme-ui#2433]
**Describe the bug**
`@theme-ui/core/dist/declarations/src/jsx-namespace.d.ts` references `JSX.ElementType`, which doesn't exist in [@types/react](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/ts5.0/index.d.ts#L3127)

**To Reproduce**
Use theme-ui with the latest `react` and `@types/react` versions. Try to compile with TS.

**Comment by jlowcs** [comment]
should it be `React.ElementType`?

**Comment by GTCarmona** [comment]
Having exactly the same issue here

**Comment by hasparus** [comment]
What's your version of `@types/react`?

Take a look at the playground here: https://www.typescriptlang.org/play?target=99#code/JYWwDg9gTgLgBAbzgKQMoA04F84DMoQhwDkUApgIYDGMxA3AFAwCeYZcA+nALwoYB0AUQA2ZEGQB2MACqsyQA

**Comment by hasparus** [comment]
I just installed fresh `@types/react`, `react` and `theme-ui` in a new repo and it works 🤔  Could you upload your package.json and lockfile?

```
  "dependencies": {
    "@types/react": "^18.2.39",
    "react": "^18.2.0",
    "theme-ui": "^0.16.1",
    "typescript": "^5.3.2"
  }
```

Feel free to reopen if you still have the problem.
