### ISSUE TITLE
Add accordion option to `@theme-ui/sidenav`

### ISSUE THREAD

**Issue by jxnblk** [system-ui/theme-ui#253]
The side nav component could accept a prop to enable accordion style interactions. This would need to be fully keyboard navigable and generally accessible

**Comment by MunifTanjim** [comment]
As `@theme-ui/sidenav` consumes an MDX file, this would need something to manipulate the mdx list (for adding buttons, accessibility stuffs etc.), right?

Something like this https://mdxjs.com/advanced/transform-content/ ?

**Comment by jxnblk** [comment]
You shouldn't need to dig into the AST at all, the React children elements could be looped over and cloned with the additional UI

**Comment by MunifTanjim** [comment]
Well, if you wanna take a look: https://github.com/MunifTanjim/gatsby-theme-dox/tree/6f46903d7a9027cac3bea289dcdb4a5ca45882f1/theme/src/components/Sidebar

It contains a subset of features extracted from the [official Gatsby.js site](https://www.gatsbyjs.org/)'s sidebar.

**Comment by kent-williams** [comment]
@jxnblk thanks so much for adding this! How hard would it be to add the option to have the sidenav items auto expand when you are on any of the pages under that section? I've been getting a lot of requests for this from my users .

**Comment by jxnblk** [comment]
@kent-williams not sure, mind opening a new issue for this feature request?

**Comment by kent-williams** [comment]
@jxnblk Will do, thanks!
