### ISSUE TITLE
CSS custom properties set color modes via a class selector

### ISSUE THREAD

**Issue by alex-page** [system-ui/theme-ui#257]
As mentioned in https://github.com/system-ui/theme-ui/pull/235#discussion_r308298513 it would be nice to have a way to set color modes via a css class.

```js
colors: {
    default: {
        text: '#000',
        background: '#fff',
        primary: '#07c',
        secondary: '#05a',
        accent: '#609',
        muted: '#f6f6f6',
    },
    dark: { ... },
    extraDark: { ... },
    pink: { ... }
},
```
```html
<body>
<body class="dark">
<body class="pink">
<body class="extra-dark">
```

**Comment by jxnblk** [comment]
It's worth noting that the core package and Gatsby plugin use a prefixed class selector during hydration, e.g. `.theme-ui-dark`

**Comment by lachlanjc** [comment]
To me, this counteracts the philosophy of React—React never reads from the DOM to change its state, you change the state on React’s end, it renders to the VDOM then the DOM is updated. While I think adding functionality to automatically use color modes like #1144 & respecting `prefers-color-scheme` in realtime totally make sense, & #979/#982 make Theme UI colors more available in vanilla CSS, I don’t think this is a feature we should support.

@hasparus

**Comment by hasparus** [comment]
Totally agreed!
