### ISSUE TITLE
Can not get ref from the <Box>

### ISSUE THREAD

**Issue by Albert-Gao** [system-ui/theme-ui#260]
don't know what I am missing, I checked the code is indeed `forwardRef`, but in this example, 3 inputs there, when typing in the inputs, except for the last one which uses raw `<input>`, the 2 `Box` from `theme-ui` does not have ref.

https://codesandbox.io/s/fervent-swanson-t8wsu

**Comment by jxnblk** [comment]
Looks like the forwarded ref wasn't being passed on to the element – fixed in #261

**Comment by Albert-Gao** [comment]
Thanks for the rapid fix!
