### ISSUE TITLE
Adding "fill" to keys?

### ISSUE THREAD

**Issue by tbrasington** [system-ui/theme-ui#275]
Hello

Is it possible to add extra css properties like "fill" so that they are recognised by the color transformation when using variants.

For example I have a token for a button

 ```
primary: {
    ...shared,
    color: "PrimaryWhite",
    bg: "PrimaryBlack.0",
    ":hover": {
      bg: "PrimaryBlack.1"
    },
    "path" : {
      fill: 'PrimaryWhite'
    }
  }
```

Which when styled with emotion

```
const Button = styled.button(
    props => css(props.theme.buttons[props.kind])
);
```

Which on the element returns the css :

```
.css-1p77o0p-Button {
    color: #fff;
    background-color: #000;
}

.css-ofzrbh-Button path {
    fill: PrimaryWhite;
}
```

I had a look https://styled-system.com/api#system but haven't had any luck using it.

Any help appreciated!

**Comment by jxnblk** [comment]
Yeah, both `fill` and `stroke` could be added here for Theme UI `sx` prop: https://github.com/styled-system/styled-system/blob/master/packages/css/src/index.js#L43-L45

In the meantime, you can either inherit with `fill: 'currentcolor'` or use functional values, e.g. `fill: t => t.colors.primary`

**Comment by tbrasington** [comment]
Thank you! currentcolor is perfect for this. Always good to learn something new!

**Comment by jxnblk** [comment]
Going to keep this open because I think support the fill property would be a good addition

**Comment by jxnblk** [comment]
The `fill` and `stroke` properties should now be supported in the latest version of `@styled-system/css`. You might need to update dependencies in your lock file to see the changes

**Comment by tbrasington** [comment]
All good! thank you very much.
