### ISSUE TITLE
Invalid hook call: maybe issue with HOC?

### ISSUE THREAD

**Issue by K-Kit** [system-ui/theme-ui#283]
Hello, I'm trying to use theme-ui along with creative Tim's material kit.
It uses a lot of HOC's which I think may be the issue... would that make sense?

I am getting the following error when I add gatsby-plugin-theme-ui or even try to wrap a themeprovider around any element.  I tried wrapping a page then to narrow it down wrapping a simple <div> and keep getting this.

Thanks in advance for any help :)

```
×
Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
```

**Comment by K-Kit** [comment]
woops reinstall node modules fixed

**Comment by gitnix** [comment]
For others ending up here.
The result of `npm ls react` was:
```
├── react@16.9.0 
└─┬ theme-ui@0.2.33
  └── react@16.9.0
```
deleting node_modules and reinstalling won't work by itself
must also resolve in `package-lock.json`
(was a new project for me so I just deleted `package-lock.json`
before npm installing again)
The result of `npm ls react` is now:
```
├── react@16.9.0 
└─┬ theme-ui@0.2.33
  └── react@16.9.0  deduped
```
where the second react is deduped, which resolves this
https://reactjs.org/warnings/invalid-hook-call-warning.html#duplicate-react

**Comment by joernroeder** [comment]
running into this right now but i dont see `theme-ui` mentioned at all.

```
├─┬ @storybook/addon-actions@5.3.12
│ ├─┬ @storybook/api@5.3.12
│ │ └── react@16.12.0  deduped
│ ├─┬ @storybook/components@5.3.12
│ │ └── react@16.12.0  deduped
│ └── react@16.12.0  deduped
├─┬ @storybook/react@5.3.12
│ └─┬ @storybook/core@5.3.12
│   └─┬ @storybook/ui@5.3.12
│     └── react@16.12.0  deduped
├─┬ gatsby@2.19.16
│ └─┬ gatsby-cli@2.8.29
│   └── react@16.12.0  deduped
└── react@16.12.0
```
could this have something to do with the peerDependency or themeui `/* jsx */` renderer?
https://github.com/system-ui/theme-ui/blob/master/packages/core/package.json#L23

**Comment by joernroeder** [comment]
seems like a glitch in the matrix. removing `node_modules` and reinstalling them fixed it together with `gatspy cleanup` 🤷‍♂️.
