### ISSUE TITLE
How to use dynamic colors?

### ISSUE THREAD

**Issue by SpadarShut** [system-ui/theme-ui#292]
In the theme I have a declaration for NavItem component
```
{
    NavItem: {
	    backgroundColor: 'primary',

		'&:hover': {
			backgroundColor: 'primary.alpha50%'
		}
    }
}
```

I need to give designers the ability to reference a color and modify it, e.g. add opacity, but not have to declare all possible variations in the theme. 
What is the proper way to handle this use case in theme-ui?

**Comment by jxnblk** [comment]
I might be misunderstanding the question, but `opacity` is its own CSS property that you can use in *addition* to color. You can also set colors with `rgba` or `hsla` values if you'd like. You can also pass functions as values in the Theme UI `sx` prop, which will let you manipulate the `theme` object in any way you'd like, including using custom utilities for color manipulation

**Comment by SpadarShut** [comment]
@jxnblk Thanks for reply, but what I need is declaring color modifications at theme level, not component level. 

Our app is white-labelable and theme needs to be modified from the UI. I want to expose the theme object via controls that allow to set colors and in certain places designers need to set derivative colors, like primary with alpha 50%.

So I want to know if there is a way to declare such colors at theme level and maybe provide custom value getters to transform colors.

**Comment by jxnblk** [comment]
Sounds like what you want is:
- https://theme-ui.com/theming#colors
- https://theme-ui.com/sx-prop#functional-values

**Comment by SpadarShut** [comment]
Looks like I was looking for something like https://github.com/emotion-js/emotion/pull/1299 .

**Comment by jxnblk** [comment]
Just a heads up the Emotion PR you linked to was in response to the work we're doing here in Theme UI. AFAICT I don't think they'll be adding that in anytime soon, but pulling colors from a global theme object is *exactly* what Theme UI does
