### ISSUE TITLE
Error when updating gatsby-plugin-theme-ui

### ISSUE THREAD

**Issue by t2ca** [system-ui/theme-ui#298]
Since updating to the latest version 0.2.33 I get the following error when running gatsby develop

Everything works after going back to version 0.2.29

```
 ERROR #98123  WEBPACK

Generating SSR bundle failed

Unexpected token (7:24)

File: ../node_modules/gatsby-plugin-theme-ui/gatsby-ssr.js:7:24
```

**Comment by jxnblk** [comment]
Thanks! I *think* I know what the culprit might be
