### ISSUE TITLE
Style MDX wrapper via theme

### ISSUE THREAD

**Issue by oliverjam** [system-ui/theme-ui#304]
Is it possible to configure styles for the MDX wrapper component via the theme? I can manually create a styled wrapper and add it via the ThemeProvider's components prop, but it would be nice to keep all the MDX styles in one place.

I guess this would require theme-ui always inserting a wrapper div around the MDX children.

My use case for this is stuff like vertical rhythm. It's easier to do `& > * + * { mt: 3 }` on the wrapper than add margin-top to every MDX element separately. I can't add this to the `root` because that's not the direct parent of the MDX elements.

**Comment by jxnblk** [comment]
We intentionally went with a separate `Styled.root` component for styling as opposed to the MDX `wrapper` (I'm forgetting exactly why we made that decision). You *can* use the `<Styled.root>` component in your own custom `wrapper` if that's something you'd like to do:

```jsx
import React from 'react'
import { Styled } from 'theme-ui'

const wrapper = props =>
  <Styled.root>
    {props.children}
  </Styled.root>

export default {
  wrapper,
}
```

Generally, I'd recommend avoiding the use of the universal selector (`> * + *`), but that's totally up to you

**Comment by oliverjam** [comment]
Fair enough, it's not too hard to pass in a custom wrapper I guess. Thanks for the answer!
