### ISSUE TITLE
Why theme change doesn't propagate to the child?

### ISSUE THREAD

**Issue by moroshko** [system-ui/theme-ui#314]
In the following example, when the theme selector changes to "product", the Button is rerendered but it still sees the "marketing" theme. What am I missing here?

[CodeSandbox](https://codesandbox.io/s/confident-wescoff-kq17m)

```js
function Button({ primary, children }) {
  return (
    <button
      sx={{
        bg: primary ? "primary" : "secondary"
      }}
    >
      {children}
    </button>
  );
}

function App() {
  const [theme, setTheme] = useState("marketing");

  return (
    <ThemeProvider theme={require(`./themes/${theme}`)}>
      <select
        value={theme}
        onChange={e => {
          setTheme(e.target.value);
        }}
      >
        <option value="marketing">Marketing</option>
        <option value="product">Product</option>
      </select>
      <Button primary>Do something</Button>
    </ThemeProvider>
  );
}


```

**Comment by jxnblk** [comment]
I believe this is due to the root-level ThemeProvider keeping theme in state. You can use a nested ThemeProvider to get around this behavior, passing the desired theme object to the inner provider, but it's not really intended to be used for this sort of thing. You could also wrap the ThemeProviders with your own component, e.g.: 

```jsx
const MyThemeProvider = ({ theme, ...props }) => {
  switch (theme) {
    case 'marketing':
      return <ThemeProvider {...props} theme={marketingTheme} />
    case 'product':
    default:
      return <ThemeProvider {...props} theme={productTheme} />
  }
}
```

**Comment by moroshko** [comment]
> but it's not really intended to be used for this sort of thing

What do you mean by that?

What's the recommended way to style nested components with theme-ui?

**Comment by jxnblk** [comment]
I mean that it’s not intended to have the theme value change dynamically the way you’ve done in your example is all. It’s something I suspect we could/should support, but will have to investigate it a little

**Comment by moroshko** [comment]
Oh, got you!
Would be good to state in the docs explicitly that the theme cannot change.

**Comment by jxnblk** [comment]
@moroshko we've updated the behavior here a little bit. If you *not* using `gatsby-plugin-theme-ui` and using the `ThemeProvider` directly for this, I think the theme should be able to update in a setup like this. Could you try with the latest version to see if this is still an issue?

**Comment by jxnblk** [comment]
Closing this because the behavior will be changing in v0.3 -- see #535
