### ISSUE TITLE
Correct way to persist theme state in Next.js?

### ISSUE THREAD

**Issue by wbunting** [system-ui/theme-ui#316]
I have a minimal repo that uses `theme-ui` with Next.js to set color modes. It uses cookies to render the correct color mode on a server side render. 

https://github.com/wbunting/theme-ui-next-example

Currently `theme-ui` produces a warning about setting the `initialColorMode` to `dark` on the server, but everything works fine. 

I believe the warning is overly aggressive for this use case, but want to make sure I'm not missing something.

**Comment by jxnblk** [comment]
We're working on making this API a little simpler, but it sounds like you might be using `initialColorMode` incorrectly. The `initialColorMode` value is only intended to be used as a key for the top-level color mode. If it's the same as a key in `theme.colors.modes`, then the warning will show. If you want to set the default color mode to dark, the values need to be in the top-level `theme.colors` and *not* in `theme.colors.modes`

**Comment by wbunting** [comment]
ah I see! that was the missing piece -- thanks
