### ISSUE TITLE
use without mdx or typography js

### ISSUE THREAD

**Issue by zebapy** [system-ui/theme-ui#317]
I love the basic set up with just the sx prop. Do the mdx packages and typography bloat this? Is there a way just to use the sx prop feature and theme? I tried installing just emotion core and theme ui but it wanted mdx react as well.

**Comment by jxnblk** [comment]
Thanks! The Typography.js integration is a separate package `@theme-ui/typography` and the MDX features are part of the core `theme.styles` API. You can use https://styled-system.com/css/ on its own if you'd like to customize what you're bundling at a more granular level

**Comment by MunifTanjim** [comment]
Is it possible to extract the core `theme.styles` API to a separate package?
If it's possible and you are open to the idea, I would love to help... @jxnblk

**Comment by zebapy** [comment]
I wanted to use styled system css prop but in Create react app, it seems I need to switch to react-app-rewired or import the styled components macro on every file to allow the css prop. So now moving to theme-ui is possible but I have no need for mdx and it seems my app fails without installing `@mds-js/react`

**Comment by jxnblk** [comment]
Yes, as stated in the [Getting Started](https://theme-ui.com/getting-started/) page, Theme UI requires both MDX and Emotion - if you want a smaller bundle, you can combine `@styled-system/css` with another CSS-in-JS solution like stated above
