### ISSUE TITLE
Color mode flashes on initial load but not on subsequent loads

### ISSUE THREAD

**Issue by brotzky** [system-ui/theme-ui#341]
When visiting a site that uses `theme-ui` and `gatsby-theme-ui-plugin` and having an OS that prefers dark mode the site flashes light mode initially and then correctly switches to dark mode. All subsequent refreshes don't have the flash of light mode and properly load dark mode. 

[Using v0.2.40](https://github.com/narative/gatsby-theme-novela/blob/%40bug/dark-mode/%40narative/gatsby-theme-novela/package.json#L54)

Example:
https://5d6f07c8eba349000a9d7e46--gatsby-theme-novela.netlify.com/

![Screen Recording 2019-09-03 at 5 48 51 PM](https://user-images.githubusercontent.com/8007686/64217730-5f7b7c80-ce73-11e9-9c05-45029ff86c4b.gif)

Reference theme file:
https://github.com/narative/gatsby-theme-novela/blob/%40bug/dark-mode/%40narative/gatsby-theme-novela/src/gatsby-plugin-theme-ui/index.ts

**Comment by jxnblk** [comment]
Since the `prefers-color-scheme` media query can only be detected on the client side, the app needs to hydrate before it picks up the media query value. Subsequent loads are using the value stored in `localStorage`. The `gatsby-plugin-theme-ui` script could also check for the `prefers-color-scheme` media query, but it's not very widely supported at the moment

**Comment by brotzky** [comment]
I was wondering about that. Is there any way to disable `prefers-color-scheme`? Seems like it's a flawed solution even though the intentions are right.

Maybe a workaround for the time-being is setting localStorage at the very start to be light before the page loads in our site.

**Comment by brotzky** [comment]
I went with setting light mode default if no mode is set:
https://5d6fe69fd76710000838e257--gatsby-theme-novela.netlify.com/

This resolves the flash of light mode content if a user prefers dark mode. It doesn't set to dark without manual user control, but it's a tradeoff we're willing to have to a cleaner experience.

**Comment by jxnblk** [comment]
> Is there any way to disable prefers-color-scheme?

I feel like this might be something we should disable by default
