### ISSUE TITLE
Typography compatibility with Material-UI and convert-css-length

### ISSUE THREAD

**Issue by revmischa** [system-ui/theme-ui#343]
Sorry I'm not really sure of what needs to happen here but there is some conflict between Material-UI/typography and @theme-ui/typography
Please see https://github.com/doczjs/docz/issues/979#issuecomment-528407926 for more info

I guess depends on https://github.com/KyleAMathews/convert-css-length/issues/4 ?

**Comment by jxnblk** [comment]
Sorry for the delay! I'm closing this out due to inactivity, and am assuming this is related to module resolutions. If there's anything that can be done from the perspective of this library, please feel free to reopen this
