### ISSUE TITLE
Styling MDX with `linear-gradient` and theme object

### ISSUE THREAD

**Issue by robphoenix** [system-ui/theme-ui#352]
How could I use a `linear-gradient` with an MDX component?

I have the following `<a>` tag that I want to use in my MDX components:

```js
const Link = props => {
  const { theme } = useThemeUI()
  return (
    <a
      sx={{
        color: 'text',
        textDecoration: 'none',
        cursor: 'pointer',
        backgroundImage: `linear-gradient(
          ${theme.colors.primary},
           ${theme.colors.primary})`,
        backgroundRepeat: 'no-repeat',
        backgroundPosition: '0 bottom',
        backgroundSize: '100% 8%',
        transition: 'all 0.2s ease-in-out',
        ':hover,:focus': {
          backgroundSize: '100% 100%',
          color: 'background',
        },
      }}
      {...props}
    />
  )
}
```

Moving this to the `styles` field of the theme object, I can't reference the theme in the `backgroundImage` field. I tried moving the `colors` object out of the theme object, so as to reference it directly, which works but of course doesn't pick up the theme changes.

Is there a way to use `backgroundImage: 'linear-gradient(primary, primary)'` with the theme object for MDX components?

**Comment by jxnblk** [comment]
You can use a function as a value with the `sx` prop: ```backgroundImage: t => `linear-gradient(${t.colors.primary}, ${t.colors.secondary})`,``` – If you'd like to add gradients to the theme object, you can use [variants](https://theme-ui.com/guides/variants/) that include functional values as well

**Comment by robphoenix** [comment]
ah-ha fantastic, that worked a charm, thankyou!
