### ISSUE TITLE
integrating theme-ui with storybook in a gatsby project

### ISSUE THREAD

**Issue by dennyabrain** [system-ui/theme-ui#354]
Hi,

I have a gatsby project where I have integrated theme-ui. Now i am trying to incorporate storybook in the project so I can develop a component library for my project.

I want my components to rely on theme-ui and the sx prop for styling but when i write stories, they render in the storybook UI without the style applied.

I am a bit lost on how to debug this.

this is what the relevant portion of my .storybook/config.js file looks like
```
import { configure, addDecorator } from '@storybook/react';
import React from 'react'
import { ThemeProvider } from 'theme-ui'
import theme from '../src/gatsby-plugin-theme-ui/index'

// automatically import all files ending in *.stories.js
const req = require.context('../stories', true, /\.stories\.js$/);
function loadStories() {
  req.keys().forEach(filename => req(filename));
}

addDecorator((story) => (
  <ThemeProvider theme={theme}>
    {story()}
  </ThemeProvider>
))

configure(loadStories, module);
```

Any help on where to start debugging this are appreciated.

**Comment by jxnblk** [comment]
Hi! Not entirely sure what's going wrong here, but be sure you have Storybook set up for use with Emotion (you'll have to consult their docs for that) - I suspect it might have something to do with how Storybook's iframes work

**Comment by dennyabrain** [comment]
Oh i see. Right! i only looked at gatsby, theme-ui and storybook documentation so far.
I will look into emotion now. thanks

**Comment by dennyabrain** [comment]
I have two observations to share

1. I dont find any documentation on setting up storybook for emotion. 
2. I am trying to test storybook and theme-ui with a dummy react component that looks like this
```

const SearchInput = (props) => {
    return(
        <div sx={{
            background: 'gray.2'
        }}>
            <h3> Search </h3>
        </div>
    )
}
```

I notice that when this renders in storybook without the style applied. but also when I inspect the component, i see its background property to be this :
`background: gray.2`

This indicates some issue with babel, doesnt it?

my webpack config for storybook looks like this
```
module.exports = ({ config }) => {
    // Transpile Gatsby module because Gatsby includes un-transpiled ES6 code.
    config.module.rules[0].exclude = [/node_modules\/(?!(gatsby)\/)/]
  
    // use installed babel-loader which is v8.0-beta (which is meant to work with @babel/core@7)
    config.module.rules[0].use[0].loader = require.resolve("babel-loader")
  
    // use @babel/preset-react for JSX and env (instead of staged presets)
    config.module.rules[0].use[0].options.presets = [
      require.resolve("@babel/preset-react"),
      require.resolve("@babel/preset-env"),
      require.resolve("@emotion/babel-preset-css-prop")
    ]
  
    config.module.rules[0].use[0].options.plugins = [
      // use @babel/plugin-proposal-class-properties for class arrow functions
      require.resolve("@babel/plugin-proposal-class-properties"),
      // use babel-plugin-remove-graphql-queries to remove static queries from components when rendering in storybook
      require.resolve("babel-plugin-remove-graphql-queries"),
    ]
  
    // Prefer Gatsby ES6 entrypoint (module) over commonjs (main) entrypoint
    config.resolve.mainFields = ["browser", "module", "main"]

    return config
  }
```

I see that there's nothing that indicates any loader/preset for theme-ui or emotion.
Emotion's documentation talks about a plugin 'babel-plugin-emotion', maybe i should add this here?

Another concern, if i am not wrong, i think emotion adds the css prop but its actually theme-ui that adds the sx prop, right? so to support that do we need some other babel plugin?

Sorry if this sounds scattered. I am new to the theme-ui, emotion, gatsby eco system and trying to piece together all moving parts to make sense of it.

**Comment by johno** [comment]
Since the css is being applied to your dummy component, it seems to indicate that theme-ui's custom pragma is working but it's missing context from Theme UI's ThemeProvider.

**Comment by dennyabrain** [comment]
i see. what could be causing that? is there any additional information i could provide to make it easier for you to assess this?

**Comment by johno** [comment]
The first think I'd try is manually wrapping your test component to see if the styles are picked up:

```js
import { ThemeProvider } from 'theme-ui'
import theme from './some/place'

const SearchInput = (props) => {
    return(
      <ThemeProvider theme={theme}>
        <div sx={{
            background: 'gray.2'
        }}>
          <h3> Search </h3>
        </div>
      </ThemeProvider>
    )
}
```

**Comment by dennyabrain** [comment]
I did. the style isn't picked up.

**Comment by johno** [comment]
To clarify, it _does_ still show `background: 'gray.2'` being applied to the div in dev tools?

**Comment by dennyabrain** [comment]
Yes. i should have been clearer. in the inspector the style is still `background: gray.2`

not sure if this is significant but its actually gray.2 and not 'gray.2'

**Comment by johno** [comment]
Hmmm, yeah it's odd. Could you provide a reproduction? Seems like provider context is being lost in Storybook but I have no idea how/why.

**Comment by dennyabrain** [comment]
I had a functioning gatsby site with theme-ui and typography.js configured. I am able to use the sx prop to set style and all the items in the theme object are available to me. 

First i tried to setup storybook in my project.
`cd <project-dir>`
`npx -p @storybook/cli sb init`

which created a .storybook directory in my gatsby project. this is the content of my .storybook/config.js file
```
import { configure, addDecorator } from '@storybook/react';
import React from 'react'
import { ThemeProvider } from 'theme-ui'
import theme from '../src/gatsby-plugin-theme-ui/index'


// automatically import all files ending in *.stories.js
const req = require.context('../stories', true, /\.stories\.js$/);
function loadStories() {
  req.keys().forEach(filename => req(filename));
}

// Gatsby's Link overrides:
// Gatsby defines a global called ___loader to prevent its method calls from creating console errors you override it here
global.___loader = {
  enqueue: () => {},
  hovering: () => {},
}
// Gatsby internal mocking to prevent unnecessary errors in storybook testing environment
global.__PATH_PREFIX__ = ""
// This is to utilized to override the window.___navigate method Gatsby defines and uses to report what path a Link would be taking us to if it wasn't inside a storybook
window.___navigate = pathname => {
  action("NavigateTo:")(pathname)
}

addDecorator((story) => (
  <ThemeProvider theme={theme}>
    {story()}
  </ThemeProvider>
))

configure(loadStories, module);
```

I think the only thing of relevance is the addDecorator function here, which i learnt is how storybook wants you to wrap your components. its also how you would implement something like redux into storybook.

this is the basic setup. i'll also post somethings i tried after this.

**Comment by dennyabrain** [comment]
here's a webpack config file i found online meant for gatsby to work with storybook. though i am not sure if its relevant. pasting here regardless

it goes in /storybook/webpack.config.js

```
module.exports = ({ config }) => {
    // Transpile Gatsby module because Gatsby includes un-transpiled ES6 code.
    config.module.rules[0].exclude = [/node_modules\/(?!(gatsby)\/)/]
  
    // use installed babel-loader which is v8.0-beta (which is meant to work with @babel/core@7)
    config.module.rules[0].use[0].loader = require.resolve("babel-loader")
  
    // use @babel/preset-react for JSX and env (instead of staged presets)
    config.module.rules[0].use[0].options.presets = [
      require.resolve("@babel/preset-react"),
      require.resolve("@babel/preset-env"),
      require.resolve("@emotion/babel-preset-css-prop")
    ]
  
    config.module.rules[0].use[0].options.plugins = [
      // use @babel/plugin-proposal-class-properties for class arrow functions
      require.resolve("@babel/plugin-proposal-class-properties"),
      // use babel-plugin-remove-graphql-queries to remove static queries from components when rendering in storybook
      require.resolve("babel-plugin-remove-graphql-queries"),
    ]
  
    // Prefer Gatsby ES6 entrypoint (module) over commonjs (main) entrypoint
    config.resolve.mainFields = ["browser", "module", "main"]

    return config
  }
```

**Comment by dennyabrain** [comment]
is that helpful?

**Comment by dennyabrain** [comment]
looks like its some kind of a known bug with no known solution so far
https://github.com/storybookjs/storybook/issues/7325

**Comment by dennyabrain** [comment]
ok this has been a weird journey :P

i just realized that the issue only happened if i set the style as 'background: gray.2'. if i set the style as backgroundColor: gray.2, it works as expected. I will paste my ./storybook/config.js here for anyone who is trying to get storybook working with theme-ui and typography.js.

closing my issue since its resolved for me i think.

```
import { configure, addDecorator, addParameters } from '@storybook/react';
import React from 'react'
import { ThemeProvider } from 'theme-ui'
import theme from '../src/gatsby-plugin-theme-ui/index'
import typography from '../src/gatsby-plugin-typography'

// automatically import all files ending in *.stories.js
const req = require.context('../stories', true, /\.stories\.js$/);
function loadStories() {
  req.keys().forEach(filename => req(filename));
}

addDecorator((story) => (
  <ThemeProvider theme={theme}>
    {story()}
  </ThemeProvider>
))

configure(loadStories, module);
typography.injectStyles()
```

**Comment by szymkab** [comment]
@johno @dennyabrain have you tried using components from `theme-ui`? The same issue occurs for me I think. 
I have the following code:

```
import { Box } from "theme-ui";

export const Foo: FC = memo(() => {
  return (
    <Box bg="primary">Box</Box>
  );
});
```

In dev tools I can inspect `background-color: primary;` as you said. The context is lost somewhere between storybook and theme-ui.

**Comment by theomjones** [comment]
Realise this is a year old now but I'm also seeing this. `sx` prop seems to work with some properties, e.g. `bg` and `backgroundColor` but not `background`. Additionally when using variants, the styles aren't applied no matter what css property was used. Very strange. I can see the css being applied e.g. `background-color: "primary"` but it doesn't get the value off the theme context, just uses the plain string "primary". 

I can't work out whether it's a pragma issue or something to do with react context getting messed up.

**Comment by hasparus** [comment]
@theomjones There are two Emotion contexts. Emotion 11 and Emotion 10. You need to either downgrade Theme UI to 0.3.5, enforce Emotion version with Yarn resolutions and webpack aliases in Storybook's config or upgrade Storybook to a version that depends on Emotion 11 if it exists (PR here: https://github.com/storybookjs/storybook/pull/13300)

**Comment by hasparus** [comment]
https://github.com/storybookjs/storybook/pull/13300

**Comment by theomjones** [comment]
@hasparus ah thanks for the quick reply! Been scratching my head for hours!

**Comment by theomjones** [comment]
I managed to fix this with the below `main.js` storybook config. As @hasparus says you can force storybook to use emotion 11. Everything seems chill from what I can see!

```js
const path = require('path')

const resolve = (p) => path.join(process.cwd(), p)

module.exports = {
    webpackFinal(config) {
        config.resolve.alias = {
            ...config.resolve.alias,
            "@emotion/core": resolve("node_modules/@emotion/react"),
            "@emotion/styled": resolve("node_modules/@emotion/styled"),
            "emotion-theming": resolve("node_modules/@emotion/react"),

        };
        return config;
    },
    // .. rest of config
};
```

Such a sneaky issue

**Comment by hasparus** [comment]
> Such a sneaky issue

Context mismatch is our most common bug... like really, this is a fundamental flaw.
I think we'll shirk responsibility and move Emotion and mdx-js/react back to peer deps in a future release — not a fix, but users will be more aware they have these React contexts.
