### ISSUE TITLE
@theme-ui/color is broken when useCustomProperties is set to true

### ISSUE THREAD

**Issue by cluk3** [system-ui/theme-ui#360]
I'm getting the error:
`Error: Couldn't parse the color string. Please provide the color as a string in hex, rgb, rgba, hsl or hsla notation`

Looks like that as the colors in the theme are in the format: `var(--theme-ui-colors-primary, #FFB013)`, this is the breaking the polished functions.
A possible solution would be to check if useCustomProperties is true and in this case extract the color with a regex.
I can come up with a PR if needed!

**Comment by jxnblk** [comment]
Thanks! Yeah this definitely won't work as-is – feel free to open a PR if you have time to look into this

**Comment by johnpolacek** [comment]
Would this work for you? No need to test for `useCustomProperties` as if the reg ex doesn’t match, nothing happens.

*packages/color/src/index.js*
~~~
const g = (t, c) => get(t, `colors.${c}`, c).replace(/var\(--(\w+)(.*?), /,'').replace(/\)/,'')
~~~

**Comment by jxnblk** [comment]
@johnpolacek Thanks! That looks like it'd work – would still wanna have a few unit tests in there to account for any edge cases that might crop up

**Comment by bitwhys** [comment]
Forgive me if there is a better channel to present this question. 

I just pulled in the package (v 0.2.40) into a gatsby project and I'm receiving the same error as the original poster. Looking into the node_modules folder I see that the accepted PR changes are not present in my version of the package. Is there a way to fix this?
