### ISSUE TITLE
Handling of ::selection

### ISSUE THREAD

**Issue by robmoggach** [system-ui/theme-ui#366]
Noticed the `::selection` pseudo selector isn't handled and in gatsby with the `localhost:8000/designsystem` route it's obviously broken on `div`.

Might I suggest something like... and handle `div`?

```jsx
const selection = {
    '::selection': {
        background: 'highlight',
        backgroundColor: 'highlight',
        textShadow: 'none',
        color: 'text',
    },
}
```

**Comment by jxnblk** [comment]
The `::selection` pseudo-element should work with the `sx` prop; are you reporting a bug? If so, could you please provide a reproduction in a code sandbox?
