### ISSUE TITLE
initialColorMode in gatsby-plugin-theme-ui not working 

### ISSUE THREAD

**Issue by juanhenriquez** [system-ui/theme-ui#367]
When using the `gatsby-plugin-theme-ui` plugin with Gatsby, it is not using the `initialColorMode` in the `/src/gatsby-plugin-theme-ui/index.js` file, and instead, it is using the `dark` mode directly.  

Take this theme as an example: 

```javascript
export default {
  initialColorMode: 'light',
  colors: {
    text: '#000',
    background: '#fff',
    primary: '#6e67ff',
    secondary: '#212121',
    modes: {
      dark: {
        text: '#fff',
        background: '#212121',
        secondary: '#fff',
      },
    },
  },
};
```

It should use the light mode as the default mode, but instead, it is using the `dark` mode with no reason.

Here is a reproduction of the issue: https://codesandbox.io/embed/gatsby-starter-default-qyqkp

**Comment by juanhenriquez** [comment]
I've been reading the source code of theme-ui and seems that it looks for the `prefers-color-scheme`  media query, and given that I'm using dark mode on my Macbook, the site is picking dark mode too ignoring the value provided in the `initialColorMode` property.

I think it would be great if you could ignore what values is `prefers-color-scheme` set to, and give us the possibility of deciding what initial color should the site use.

**Comment by iamkevinwolf** [comment]
On my end it is not working at all, I have this color configuration:

```ts
export default {
  initialColorMode: 'light',
  colors: {
    primary: '#00ccd7',
    background: '#fff',
    text: '#4f4f4f',
    accent: '#333',
    muted: '#a8a8a8',
    modes: {
      dark: {
        background: '#000',
        text: '#fff',
      },
    },
  },
}
```

And the MacOS settings defined to use Dark Mode, but still can't get it to work automatically.

**Comment by jxnblk** [comment]
@iamkevinwolf as of the latest version, if you want to initialize color mode based on the `prefers-color-scheme: dark` media query, you'll need to add the `useColorSchemeMediaQuery` option to your theme, see https://theme-ui.com/color-modes#initialize-dark-mode-with-prefers-color-scheme-dark

**Comment by mcs07** [comment]
I agree with the comment by @iamkevinwolf. My preferred behaviour would be localStorage would never be set until and unless `setColorMode` was explicitly called. And also, if `useColorSchemeMediaQuery: true` then ideally the color mode would dynamically update as the system preference changes from dark to light, without a refresh. It would also be nice to be able to reset the color mode back to 'auto' after choosing light/dark, e.g. by `setColorMode(null)` clearing the local storage.

**Comment by jxnblk** [comment]
Closing this since the behavior will be changing slightly in v0.3 -- see #535
