### ISSUE TITLE
Container is hard-coded to max-width: 1024px instead of complying with theme breakpoints

### ISSUE THREAD

**Issue by timkindberg** [system-ui/theme-ui#371]
Hello, Thank you for this amazing project!

I noticed that the `Container` layout component has it's max-width hard-coded to `1024px`. Is this intentional?

I think it could be nice if it functioned similar to tailwind's container, where the max-width was "responsive" and set to each breakpoints width, then on smaller screen sizes it takes up 100% with a fluid width.

Maybe something like this, totally threw this together:
```javascript
export const Container = props => {
  const { breakpoints } = useThemeUI()
  const smallestBreakpointActive = useMediaQuery(`(max-width: ${breakpoints[0]})`)
  return jsx(Box, {
    ...props,
    sx: {
      ...(smallestBreakpointActive ? {
        width: '100%'
      } : {
        width: breakpoints.map(bp => bp),
      })
      mx: 'auto',
      p: 4,
      variant: 'styles.Container',
    },
  })
}
```

**Comment by jxnblk** [comment]
The `Container` is meant to have a max-width, not a fixed width based on the breakpoint values. It's hard-coded rather than using a value from `theme.sizes` because some themes might not have a value defined for the container. Hope that makes sense!
