### ISSUE TITLE
Testing components in Storybook for theme-ui colorModes

### ISSUE THREAD

**Issue by sonapraneeth-a** [system-ui/theme-ui#372]
I'm trying to test my component ```Button``` in storybook for various color modes like light, dark etc.

I've added a ThemeProvider decorator from where I can add the theme. But when I try to toggle theme using ```useColorMode()```, I get the error

"[useColorMode] requires the ThemeProvider component"

Not sure what am I missing. Any help is appreciated.

I've setup the project with config as defined in gatsby docs.

**Comment by jxnblk** [comment]
Hi, do you have a reproduction available?

**Comment by sonapraneeth-a** [comment]
Repo: [https://github.com/sonapraneeth-a/issue-storybook-themeui](https://github.com/sonapraneeth-a/issue-storybook-themeui)

File: [https://github.com/sonapraneeth-a/issue-storybook-themeui/blob/master/tests/storybook/button.stories.js](https://github.com/sonapraneeth-a/issue-storybook-themeui/blob/master/tests/storybook/button.stories.js)

**Comment by jxnblk** [comment]
Thanks, I don't really remember much about storybook's custom API, but you can check to make sure the context is being passed through by using the `useThemeUI` hook

**Comment by G-Ray** [comment]
@sonapraneeth-a in your storybook config.js, just replace
```js
addDecorator((story) => (
  <ThemeProvider theme={index}>
    {story()}
  </ThemeProvider>
))
```
by :
```js
addDecorator((Story) => (
  <ThemeProvider theme={theme}>
    <ColorMode />
    <Story />
  </ThemeProvider>
))
```

**Comment by danvim** [comment]
Sorry, I just found out about this issue. I've already made mine https://github.com/system-ui/theme-ui/issues/537

**Comment by jxnblk** [comment]
Closing this for now due to inactivity, but I suspect this is an issue related to mismatched React contexts in Storybook
