### ISSUE TITLE
Issues with Next.js example

### ISSUE THREAD

**Issue by calspre** [system-ui/theme-ui#379]
Hi, I started working with Next.js and Theme UI and found two issues:

- Can we remove the code inside `getInitialProps` in `_app.js` (and perhaps `_document.js`)?
- Can we remove `<Container />` in `_app.js`?

With `getInitialProps` in `_app.js`, every page becomes server-rendered when we `next build` and we don't get automatic static optimization (see related [Next.js blog](https://nextjs.org/blog/next-9#automatic-static-optimization) and [docs](https://nextjs.org/docs#custom-app)). I looked into the pull request (#277) but not sure if this code is necessary. 

Also when I run the example, it warns `<Container />` is deprecated. 

I am pretty new to Next.js so I am not sure how those two works in the context of Theme UI. Perhaps @jordanoverbye knows? When I removed those everything seems to work as expected but maybe I am missing something.

**Comment by jordanoverbye** [comment]
Hi @calspre,

I've opened a PR to fix this
https://github.com/system-ui/theme-ui/pull/386

**Comment by calspre** [comment]
Awesome! That looks good to me. Thanks for your effort @jordanoverbye 🙂
