### ISSUE TITLE
Styles getting applied after the website has already loaded

### ISSUE THREAD

**Issue by pepibumur** [system-ui/theme-ui#387]
## Context
I've been using theme-ui in a few websites with no problems. However, when I ported my personal website from styled-system & rebass, I'm running into a weird issue that I couldn't figure out.

## What
When [the website](https://ppinera.es/) loads, there are some padding and marging styles that are applied right after the website is loaded. My guess is that the inlined styles are not loaded before the DOM elements are rendered. [This is the layout](https://github.com/pepibumur/website/blob/master/src/components/layout.js) component where the styles are defined.

Not sure if it has to do with how I configured things or it's a bug in theme-UI or Emotion. I'd appreciate if you con point me to where the issue might me coming from.

PS: Thanks for making such a great library for the community.

**Comment by jxnblk** [comment]
Not entirely sure what's happening, but I do see some invalid HTML markup – `body` should not be a child of `div` – might or might not affect how the browser is rendering things. It also might be worth seeing if disabling `gatsby-plugin-emotion` has any effect, since it does some things related to SSR

**Comment by pepibumur** [comment]
> Not entirely sure what's happening, but I do see some invalid HTML markup – body should not be a child of div

Ouch, good catch. I fixed that.

> It also might be worth seeing if disabling gatsby-plugin-emotion has any effect, since it does some things related to SSR

I fixed it but the issue keeps happening. I actually added it in case that was the reason why it didn't work. I've also tried removing the `<Global/>` component from emotion that I'm using to add global styles.

I'm a bit lost, not sure where to debug the issue.

**Comment by pepibumur** [comment]
Actually, the issue was having a `<body>` tag inside the `<body>` tag that Gatsby already created. After turning it into a `<div>` the issue went away.

Thanks for the help @jxnblk
