### ISSUE TITLE
Better media queries??

### ISSUE THREAD

**Issue by danspratling** [system-ui/theme-ui#397]
I've started using the built in tools for creating media queries in theme-ui and it's far better than writing out the old css, but i'm afraid that the code will be unclear if i leave the project for 6 months.

When i write a media query the shortest clearest way i've found is to do this

```
textAlign: ['center', , , 'left']
```
But obviously if you don't know that breakpoints are defined in an array in the theme and that we're manipulating that, then this looks really weird.

Is there a better way of doing this where i can do something like
breakpoint[0]: 'center', breakpoint[3]:'left'

I saw emotion had something like this but that was pretty verbose and required mapping the breakpoint array in every file where you wanted to do this (eww).

I'm okay with the weird array if there isn't - just curious what others have come up with.

**Comment by dburles** [comment]
You could opt instead to use an object [as in this example](https://styled-system.com/guides/array-props/#origins), however I've found skipping breakpoints to be relatively uncommon to warrant switching, but it's a personal preference.

```js
// with plain objects (not all that different)
<Box width={{ default: 1, small: 1 / 2, medium: 1 / 3, large: 1 / 4 }} />
```

**Comment by danspratling** [comment]
Yeah, after thinking about it i think that objects are even more verbose. My problem was mostly coming from the fact that i'd defined too many breakpoints, so i removed a couple (down to 5, which is still plenty). I've still got skips in like before but they occur far less which makes it easier to read the array. Think the empty spaces are something i'm just not used to, rather than something 'bad'.

Thanks for the reading. Helped me decide on the best approach.
