### ISSUE TITLE
Creating Multiple Variants

### ISSUE THREAD

**Issue by moshemo** [system-ui/theme-ui#403]
I am looking for a way to create multiple variants for buttons.  For example, let's say I want to have the following three variants:

1. Size (small, medium, large, etc). 
2. Look (primary, secondary, disabled, etc).  
3. Kind (default, outline, text, etc).

So that I could style a button like this:

```
<button
 sx={{
    size="buttons.size.large"
    kind="buttons.kind.outline"
    look="buttons.look.secondary"
 }}
/>
```

This IS possible with style system -- here is an example:

* https://mathanpec.github.io/component-library/?path=/story/button--size-variant
* https://github.com/mathanpec/component-library/blob/basic-setup/src/theme/buttonStyle.ts

But I can't figure out how to do with with Theme-UI.

Is this possible with Theme-UI?  If so, can how can I do it?

Thanks.

**Comment by timkindberg** [comment]
Seems like an array could work, where it would just `merge` the variants.

```
sx={{
  variant: [
    'buttons.size.large',
    'buttons.kind.outline',
    'buttons.look.secondary'
  ]
}}
```

**Comment by jxnblk** [comment]
Currently the `variant` property only accepts a single argument, but it's something I've considered. @timkindberg the array syntax would allow you to use different variants at different breakpoints

**Comment by moshemo** [comment]
Okay, thanks for letting me know.

**Comment by jferrettiboke** [comment]
@jxnblk Any solution to this? I have the same need. Could you consider to re-open this issue?

**Comment by jferrettiboke** [comment]
I get it working doing this. However, it would be cooler to support this internally.

```js
import { useResponsiveValue, useBreakpointIndex } from "@theme-ui/match-media";
import get from "lodash.get";
import theme from "../theme";

function variants(...variantBlocks) {
  const variants = useResponsiveValue(variantBlocks);
  let styles = {};
  variants.map(variant => {
    styles = { ...styles, ...get(theme, variant) };
  });
  return styles;
}

function Example() {
  return (
    <Button
      sx={{
        ...variants(
          ["buttons.colors.secondary", "buttons.sizes.xs"],
          ["buttons.colors.primary", "buttons.sizes.lg"]
        )
      }}
    >
      Breakpoint index: {index}
    </Button>
  );
}
```

**Comment by CanRau** [comment]
How about comma separated strings? @jxnblk 

Merry Christmas to y'all 🎅 🎉

**Comment by Pirastrino** [comment]
> Seems like an array could work, where it would just `merge` the variants.
> 
> ```
> sx={{
>   variant: [
>     'buttons.size.large',
>     'buttons.kind.outline',
>     'buttons.look.secondary'
>   ]
> }}
> ```

This approach breaks on breakpoints with e.g. `breakpoints: ['40em', '52em', '64em']`, `buttons.size.large` is applied at min 40em, `buttons.kind.outline` at min 52em etc. and only at min 64em are applied all 3 variants 😔.

**Comment by lachlanjc** [comment]
I feel like this isn't quite right, but there is the (obvious?) solution of adding a `variants` prop that accepts an array of `variant` values (strings, or I guess arrays if you want the behavior described above with breakpoints).

**Comment by CanRau** [comment]
I like the `variants` prop 👍 last array item wins I guess?

Lachlan Campbell <notifications@github.com> schrieb am Mi., 15. Jan. 2020,
17:38:

**Comment by lachlanjc** [comment]
Yeah, if they conflict, treat it like CSS declarations, the later declarations override the earlier.

**Comment by jxnblk** [comment]
We've discussed adding support for a `variants` key which would deep merge multiple variants, but haven't introduced that yet

**Comment by nandorojo** [comment]
Are there still plans to finish this PR @lachlanjc? Would be awesome. Thanks to everyone for the great work on theme ui!

**Comment by lachlanjc** [comment]
@nandorojo I’d love to, unfortunately the surrounding code has changed a bunch while there was discussion & I’ve had a new job/lot going on recently. Not sure if the specific timeline but I’d love to get back to that soon, it’s functionality I’d use every day 🙂

**Comment by thetimmyc** [comment]
I would too @lachlanjc ! :)

**Comment by mryechkin** [comment]
Hi folks. Has this been given any more consideration? It would be a great feature to have for our use case.

For example, I need to be able to specify that a button is "disabled" while also being a `secondary` variant. Is there a clean way of doing this currently?

**Comment by lachlanjc** [comment]
@mryechkin No work on this, but still very much wanted! We recently had a discussion about what the API should look like, over here: https://github.com/system-ui/theme-ui/pull/1226#issuecomment-977597495

It needs a fresh PR for implementing, contributions extremely welcome!
