### ISSUE TITLE
[Feature Request] Add auto expand option to Sidenav (AccordionNav)

### ISSUE THREAD

**Issue by kent-williams** [system-ui/theme-ui#418]
Hello,

I'd like to request the following addition of an option for auto expanding the AccordionNav wrapper of Sidenav. Currently the AccordionNav requires the user to manually expand the nav, but I've had many users, including myself, often miss content that was never discovered because it is hidden under the section. It would be great to have an auto expand option that expands the nav section if the user is currently on any of the sub-links beneath that nav section. 

Happy to explain further if needed!
-Kent

@jxnblk

**Comment by jxnblk** [comment]
Sorry for the delay! I think this was added at some point, but feel free to reopen if you have any questions

**Comment by kent-williams** [comment]
@jxnblk Would you mind describing how to enable auto expanding on click for the accordion nav please, it's not documented in the sidenav readme and isn't obvious from the code.

Thank you,
Kent
