### ISSUE TITLE
Combining presets and typography, fontSizes messed

### ISSUE THREAD

**Issue by kuworking** [system-ui/theme-ui#424]
I am combining presets and typography in gatsby with the index.js

```js
import merge from 'deepmerge'
import typography from './typography'
import colors from './colors'
import styles from './styles'
import { swiss } from '@theme-ui/presets'

export default merge.all([
  swiss,
  typography,
  {
    initialColorMode: `light`, // rename default as light
    colors,
    styles,
  },
])
```

And I get wrong responsiveness with the `<h1>` element

Before the breakpoint

![image](https://user-images.githubusercontent.com/4474004/67523908-e0a30300-f6af-11e9-9d5b-7c2eb5122944.png)

After the breakpoint

![image](https://user-images.githubusercontent.com/4474004/67523953-f9abb400-f6af-11e9-892d-15f0c04d0a37.png)

And after the breakpoint when I only use `swiss`

![image](https://user-images.githubusercontent.com/4474004/67524441-ffee6000-f6b0-11e9-9796-e3723c47ecbe.png)

The problem is that fontSizes get merged, so I can fix it like this

```js
import merge from 'deepmerge'
import typography from './typography'
import colors from './colors'
import styles from './styles'
import { swiss } from '@theme-ui/presets'

const ex = merge.all([
  swiss,
  typography,
  {
    initialColorMode: `light`, // rename default as light
    colors,
    styles,
  },
])
ex.fontSizes = swiss.fontSizes
export default ex
```

Is this what should be done? Is there any other way? Perhaps some documentation alerting about this would be good?

**Comment by jxnblk** [comment]
I'm not sure what is in your `./typography` module, but `deepmerge` will replace arrays by default IIRC – I don't see anything specifically related to `theme-ui` here, this seems to be related to working with objects generally.

**Comment by kuworking** [comment]
I think it comes to what I was expecting by reading the docs

Somehow I had the idea I could apply the typography styling through theme-ui and get the same exact results as if applying typography directly

But (this is at least what I understand, so please correct me if I'm wrong) what theme-ui does is to use typography to fill the theme object, nothing more beyond that

In other words, I'm unable to replicate the look&feel of typography by using typography through theme-ui, but this was never an intended feature (?)

**Comment by kuworking** [comment]
Didn't know about this one, I'm using `Styled.el` so far (and so good)

But my conceptual question is not about non-mdx content:

What I'm asking (out of curiosity) is whether with `theme-ui+typography` it is possible to get the same look-and-feel as you get with typography alone, in `mdx` content

My conclusions is that this is not possible (or not straightforward), but maybe it is and I'm just not getting things right (?)

**Comment by jxnblk** [comment]
Here are the docs for using Typography.js with Theme UI https://theme-ui.com/typography/

**Comment by kuworking** [comment]
Yes yes, this is what I've done and then I've seen what I've posted above in the 1st comment

Is there anything wrong I've done there?

**Comment by jxnblk** [comment]
Your code example doesn't include `@theme-ui/typography` at all so it's hard to know what you're trying to do. If you have a reproduction or example code sandbox, that might help

**Comment by kuworking** [comment]
Sorry, it is in the `typography.js` file

```js
import typography from './typography'
```

```js
// ./typography.js
import 'typeface-open-sans'
import { toTheme } from '@theme-ui/typography'
import wordpress2012 from 'typography-theme-wordpress-2012'

export default toTheme(wordpress2012)
```

I'll try to make an example code asap
