### ISSUE TITLE
flexbox and layout API in Box component by default

### ISSUE THREAD

**Issue by S1lentium** [system-ui/theme-ui#425]
Wouldn't it be better if **layout** and **flexbox** API were included in Box components by default, since these props are often used?

```js
// theme-ui/packages/components/src/Box.js

export const Box = styled('div', {
  shouldForwardProp,
})(
  {
    boxSizing: 'border-box',
    margin: 0,
    minWidth: 0,
  },
  base,
  variant,
  flexbox,
  layout,
  space,
  color,
  sx,
  props => props.css
)
```

Moreover, the current implementation of **sx** prop does not support the responsive values for width and height.

**Comment by jxnblk** [comment]
Thanks for the suggestion! The `sx` prop should be the primary way to add styles for layout and flexbox, so we're not currently planning on adding more Styled System props.

> Moreover, the current implementation of sx prop does not support the responsive values for width and height.

If you've found a bug, please open another issue with a reproduction

**Comment by S1lentium** [comment]
What is the point of adding `space` and `color` props?
