### ISSUE TITLE
Responisive shortcut values not working

### ISSUE THREAD

**Issue by S1lentium** [system-ui/theme-ui#431]
```jsx
<Box sx={{ width: [1 / 2] }}>test</Box>
```
generated css: 
```
{
  width: 0.5px
}
```

**Comment by jxnblk** [comment]
Theme UI does *not* support fractions for percentage-based widths. Did you see that somewhere in the docs? If so, that should be corrected

**Comment by S1lentium** [comment]
Thanks for the clarification, but it would be nice to have it inside sx props for compatibility with styled-system props. Perhaps this behavior is implemented inside the styled-system

**Comment by jxnblk** [comment]
We've decided not to carry that shortcut over to Theme UI, you can still use string percentage values though, e.g. `width: '50%'`

**Comment by aaronadamsCA** [comment]
Just gonna toss a +1 in here, because this was a bit confusing to me as I came from Styled System, and also because I really liked that `width: [1 / 3, 1 / 4, 1 / 6]` told me I'd get 3, 4, and 6 elements to a row. I can live without it, but I will miss it!
