### ISSUE TITLE
Color mode changes to inexplicit theme on hydration

### ISSUE THREAD

**Issue by kylemh** [system-ui/theme-ui#434]
```javascript
import { deep } from "@theme-ui/presets";

const primaryColor = "#32D8D6";

export default {
  initialColorModeName: "default",
  ...deep,
  colors: {
    // Doing modes enables global styles being applied
    modes: {
      default: {
        ...deep.colors,
        primary: primaryColor,
        background: primaryColor,
      },
      dark: {
        ...deep.colors,
        primary: primaryColor,
        background: primaryColor,
      },
    },
  };
```

I've got the following setup because I need color modes to force the body background color to instantiate as desired, but I don't quite care about providing dark/light mode in reality, so the values are identical.

My Mac uses dark mode, and the site looks as expected on first load, but post-hydration, it looks like it's not picking up any of my theme values?

I've tried:
- setting `useColorSchemeMediaQuery` to false
- not defining `initialColorModeName`,
- defining `initialColorModeName` to "light"

**Comment by jxnblk** [comment]
The top-level color object needs to have your default color mode and `initialColorModeName` cannot be the same as one of the nested `theme.colors.modes` palettes - see https://theme-ui.com/color-modes#renaming-the-default-color-mode

**Comment by kylemh** [comment]
I saw the dev warning and documentation, but I’m still confused. Do I name it something that I’m not defining?! I don’t really care about renaming it, I just turned on modes to automatically have the background of the body colored.

**Comment by jxnblk** [comment]
It sounds like what you're going after is more like this, maybe:

```js
export default {
  ...deep,
  primary: primaryColor,
  background: primaryColor,
  modes: {
    dark: {
      // you might not need this if you're not using color modes
    }   
  }
}
```

If the only reason you're doing this is to set body and background colors, though, you might consider using Emotion's `Global` component directly
