### ISSUE TITLE
Serverside rendering in NextJS example

### ISSUE THREAD

**Issue by hasparus** [system-ui/theme-ui#437]
I think it doesn't work, and considering it's a focus of Next, it probably should. Just wanted to note it here.

Solution might be somewhere in this way -- https://emotion.sh/docs/ssr.

**Comment by jxnblk** [comment]
Emotion *should* work out of the box for server side rendering. If you're encountering a specific issue with Next.js, could you please clarify what's happening

**Comment by hasparus** [comment]
I was getting a flash of unstyled content, but now I think it's not exactly emotion/core nor theme-ui problem. (A repro I wanted to post is not buggy.) I'll try to find the cause of the issue but I feel this is a moment when I say sorry for spam.

**Comment by jxnblk** [comment]
If it's related to colors flashing when rendering a page with the non-default color mode, that's a known issue. We'd like to have a Next.js plugin (similar to the Gatsby plugin) to help with this. It's not been created yet, but this PR & example was meant as a placeholder: https://github.com/system-ui/theme-ui/pull/277

**Comment by erikdstock** [comment]
artsy/fresnel may help here. It's worked for me, anyways.
