### ISSUE TITLE
pre-built UI @theme-ui/components or Rebass?

### ISSUE THREAD

**Issue by AaronBentley** [system-ui/theme-ui#442]
Hi 👋

I've just read the docs for the @theme-ui/components package, I was wondering if there's any difference or benefit from implementing @theme-ui/components instead of Rebass?

Thanks in advance,

Aaron.

**Comment by jxnblk** [comment]
The components here in Theme UI are part of a suite of packages that work together. Theme UI includes color modes, a Gatsby plugin and more to come, whereas Rebass is a smaller library of React components

**Comment by AaronBentley** [comment]
Thank you for clarifying @jxnblk.
