### ISSUE TITLE
Advice - using sx prop and importing theme into component

### ISSUE THREAD

**Issue by omonk** [system-ui/theme-ui#443]
Just wondering if there is any guidance around whether doing this is considered the wrong way, I have a feeling it is.

StyledLink can be modified with the color prop 

```javascript
import theme from '../../themes/default'

interface StyledLinkProps {
  color: 'reverse' | 'secondary' | 'muted' | 'text';
  href: string;
}

const StyledLink: React.FC<StyledLinkProps> = ({ color, href }) => (
  <Styled.a
    href={href}
    sx={{
      lineHeight: 'body',
    }}
    css={{
      background: theme.colors[color],
    }}
  />
);
```

We're using typescript so color is a union type but we now totally diverge away from the consistency of tying the theme to the sx props instead. I guess we could enforce the values to exist in the theme colors that we have in the StyledLink interface?

Are there any other suggestions for how to solve this issue? A switch case based upon the color prop could work... but seems to be a bit much in this instance.

**Comment by jxnblk** [comment]
You could probably use [functional values](https://theme-ui.com/sx-prop#functional-values) for this, using a prop as a key on `theme.color`. That said, I'd suggest not conflating `color` with `backgroundColor` as far as naming conventions go
