### ISSUE TITLE
How to change default shadow color on dark mode?

### ISSUE THREAD

**Issue by isBatak** [system-ui/theme-ui#453]
If we have:
```
...
shadows: {
  default: '0 1px 3px 0 rgba(0, 0, 0, 0.1)',
},
...
```
how to change color to white in dark mode?

**Comment by jxnblk** [comment]
You can use functional values in cases like this (see https://theme-ui.com/sx-prop#functional-values). The `theme.colors` object passed to the functional value will include the current mode's color palette

**Comment by armand1m** [comment]
how would I do this using modes?

**Comment by danhab99** [comment]
Can I get documentation for how that arrow function works? I want to do something similar but I can't find any mention of what this is.

> boxShadow: theme => `0 2px 7px ${theme.colors.shadow1}, 0 5px 13px ${theme.colors.shadow2}`,

**Comment by jxnblk** [comment]
Color modes are currently only supported via the `theme.colors` scale, see https://theme-ui.com/color-modes/
