### ISSUE TITLE
Request: Theme-able pseudo selectors

### ISSUE THREAD

**Issue by folz** [system-ui/theme-ui#454]
**Feature request:**

I would like the ability to associate pseudo-selectors with theme values. For example:

```jsx
// In:
<Box sx={{
  ':hover': {
    backgroundColor: 'blue',
  },
}} />
```

```js
// Theme:
export const theme = {
  colors: {
    blue: '#0099BA',
  },
  selectors: {
    ':hover': '&:not(:disabled):not([aria-disabled]):hover',
  },
}
```

```css
// Out:
.css-0:not(:disabled):not([aria-disabled]):hover' {
  background-color: #0099BA;
}

<div class="css-0" />
```

**Rationale:**

I'm working with reakit, which will sometimes set `aria-` attributes on components when they're in particular states. For example, `<Button disabled focusable />` will set `aria-disabled` but not `disabled`. In this case, I want our disabled styles to apply even though the `:disabled` pseudo-selector is technically not active, because the Button component will not fire event callbacks in the `disabled focusable` state. I have done so by defining a `selectors.disabled = "&:disabled, &[aria-disabled=true], &[data-disabled=true]"`, and reference `[theme.selectors.disabled]` instead of `':disabled'`.

Relatedly, I use the `data-hover/active` data attribute to artificially apply hover/active styles, which I use when cross-browser quirks do not correctly apply those styles to the real pseudo-selectors. I have a similar `selectors.hover/active` definition.

This works for my use case, but when engineers who consume my library need to write their own disabled/hover/active styles, they tend to use the literal string `':disabled'`. I can try to socialize usage of the `theme.selectors.whatever` import, but I think it would be a more sustainable solution to make selectors theme-associated to `selectors` (or similar name) in the same way that other style fields are theme-associated.

**Why theme-ui:**

I think this is appropriate for theme-ui because the relationship between selector states is also a constraint on our design system. Allowing theme creators to control this relationship at the theme level will support the same kind of DX improvements that theme-field associations do.

**Comment by jxnblk** [comment]
Thanks for the suggestion! I think since this is a *very* specific use-case, you'd be better off writing a helper function to use in your `sx` prop to achieve something like this. This also seems like something that could be hard-coded at the component level, since I'd assume this is mostly for `<button>` elements, right? I don't think that obscuring the rendered CSS in this way is something we'd really want to support at the theme level in this library

**Comment by folz** [comment]
This pattern is something I bring into anything tabbable/focusable, so I don't think it'd fit at the component level. For example, we have a `<Touchable>` component for accessible unstyled interactions, which is actually a div but sets the appropriate role/aria/onclick/etc handlers to act like a button. `theme.selectors` is also how I control focus styles when anything composing Box gets a `tabIndex={0}` set on it.

I definitely see your point about this being quite niche, so yep, I can add this as a helper to where I handle the `sx` prop. Thanks for the feedback on the idea.
