### ISSUE TITLE
post-list-a2 always gives vertical list for me with gatsby .. not sure what i am missing

### ISSUE THREAD

**Issue by mannp** [system-ui/theme-ui#456]
My first theme-ui attempt and use of gatsby, so go easy :)

Using parts of @jxnblk blog code as a template, as I find his code easier to read and it follows closely the theme-ui site examples.

I have hooked up gatsby to strapi and all is great, except using the theme-ui recipe post-list-a2 always gives me a vertical list of posts, rather than placing columns across the page.

I am using the whole recipe with just the nodes changed to strapi nodes rather than mdx

Any reason why that could be?

https://theme-ui.com/recipes/post-list-a2/

@jxnblk

**Comment by jxnblk** [comment]
If you have a reproduction to look at, that would help

**Comment by mannp** [comment]
Thanks for the time to take a look :)

The following result is from the code snippet below, while whatever i do with gridTemplateColumns, the result is always a vertical list of posts, rather than across the page.

![example](https://user-images.githubusercontent.com/4335298/68852730-66730680-06d0-11ea-808b-74966d197843.jpg)
```
import React from "react"
import { Link } from "gatsby"
import { graphql } from 'gatsby'
import Img from 'gatsby-image'
import { Styled } from 'theme-ui'
import Layout from "../components/layout"


  const BlogPage = ({ data }) => (
    <Layout>
      <Styled.h1
        sx={{
          maxWidth: 512,
          mx: 'auto',
          px: 3,
          py: 4,
          m: 0,
        }}>
        Hi people.
      </Styled.h1>
      <Styled.p
        sx={{
          m: 0,
        }}>
        Welcome to your new Gatsby site.
      </Styled.p>
      <Styled.p
        sx={{
          m: 0,
        }}>
        How to build something great
      </Styled.p>
      <ul
        sx={{
          listStyle: 'none',
          display: 'grid',
          gridGap: 3,
          gridTemplateColumns: 'repeat(auto-fit, minmax(256px, 1fr))',
          m: 0,
          px: 3,
          py: 4,
        }}>
        {data.allStrapiArticle.edges.map(document => (
          <li key={id}
          sx={{
            }}>
            <Styled.h2
              sx={{
                m: 0,
              }}>
              <Link to={`/${id}`}
                sx={{
                  color: 'inherit',
                  textDecoration: 'none',
                  ':hover,:focus': {
                    color: 'primary',
                    textDecoration: 'underline',
                  }
                }}>
                {document.node.title}
              </Link>
              </Styled.h2>
              <small sx={{ fontWeight: 'bold' }}>{title}</small>
              <Styled.p
                sx={{
                  m: 0,
                }}>
              {excerpt}
              </Styled.p>
            </li>
          ))}
        </ul>
    </Layout>
  )```

**Comment by jxnblk** [comment]
You'll need to use the pragma comment to use the `sx` prop, see https://theme-ui.com/sx-prop/

**Comment by mannp** [comment]
At first read, I don't know what that means to be honest.

I have previously added the following to the import statements; 

/** @jsx jsx */
import { jsx } from 'theme-ui'

On building it throws the warning that jsx is not being used.

Weird thing is, using the tabular footer https://theme-ui.com/recipes/footer-a4 works fine and creates the columns across the page..frustrating.

**Comment by jxnblk** [comment]
I suspect the warning you're seeing is because ESLint is not configured correctly to support jsx syntax - it should be safe to ignore that warning

**Comment by mannp** [comment]
Yes the warning doesn't appear to have any ill effects, so I did ignore.

Only reviewing your blog code did i start to understand theme-ui, so thank, but until then the permutations and combinations of libraries to use and the way different coders utilised them was overwhelming. 

if the issue is not an easy fix, I'll move on to the rest of the website that I can create :)

Thanks.
