### ISSUE TITLE
Is Theme UI compatible with Styled Components?

### ISSUE THREAD

**Issue by kiastorm** [system-ui/theme-ui#457]
I have an existing component library set up with Styled Components + Styled System. Now trying to integrate dark mode, and upon switching over from SC `<ThemeProvider />` to the Theme UI alternative, I can't seem to get it working.

Am I doing something wrong or will I need to switch all my components to use Emotion instead of SC?

**Comment by jxnblk** [comment]
Theme UI is built with Emotion, and while it generally shouldn't clash with Styled Components, the theming context in the two libraries is not shared

**Comment by kiastorm** [comment]
So in order to continue to use my components, many of which are built using Styled System's themed css function, AND integrate Theme UI - I will need to switch over to Emotion?

I'm happy to do so, I just want to be clear before investing the time into switching over.

**Comment by coreybruyere** [comment]
@kiastorm Did you end up needing to switch to emotion?

**Comment by jxnblk** [comment]
Sorry for the delayed response! Generally, I think it would make more sense to use only one CSS-in-JS library and Theme UI uses Emotion, but you *can* technically use both libraries together
