### ISSUE TITLE
Add option for applying root styles with gatsby-plugin-theme-ui

### ISSUE THREAD

**Issue by jxnblk** [system-ui/theme-ui#466]

**Comment by lachlanjc** [comment]
This might not be your style but wanted to bring it up. Thoughts on a component for use on non-Gatsby sites that wraps Emotion’s Global with these styles? I need this on every site.

**Comment by jxnblk** [comment]
FWIW, in v0.3, this is set up to work with the `ThemeProvider` component, so it's not dependent on `gatsyb-plugin-theme-ui`

**Comment by lachlanjc** [comment]
Oh gorgeous, even better!
