### ISSUE TITLE
Colors don't work in IE

### ISSUE THREAD

**Issue by prateekkathal** [system-ui/theme-ui#467]
Hey,

Due to no `var()` support for IE11, the colours don't pop up.

![Screen Shot 2019-11-19 at 1 48 33 PM](https://user-images.githubusercontent.com/7609893/69176329-8ab95380-0ad3-11ea-9b3a-b238295ceab0.png)

Can we please have something as fallback to fix this?

Thanks,

**Comment by jxnblk** [comment]
You can disable custom properties with this option: https://theme-ui.com/color-modes#turn-off-custom-properties

**Comment by prateekkathal** [comment]
@jxnblk Thanks. That does solve the issue. 

However, I am getting this warning when using Typescript:

![image](https://user-images.githubusercontent.com/7609893/69193273-602bc280-0af4-11ea-8a06-5fecfe8f7fb8.png)

Can I create a PR for this with `useCustomProperties: boolean` added right before `initialColorMode`?

![image](https://user-images.githubusercontent.com/7609893/69193353-85b8cc00-0af4-11ea-8fee-1bc6b56fb00d.png)

**Comment by jxnblk** [comment]
Looks like whoever create the type definitions you're using didn't account for that - not sure where you'd need to look to fix that, but it's not in this repo

**Comment by prateekkathal** [comment]
@jxnblk I have created a PR referencing to the current issue. Thanks for the support.
