### ISSUE TITLE
Exportable style types?

### ISSUE THREAD

**Issue by prateekkathal** [system-ui/theme-ui#471]
I am trying to extract common code between styles and move it to a base styles file

For eg: **Buttons**
![image](https://user-images.githubusercontent.com/7609893/69259330-142c5c80-0b8c-11ea-9a38-a675033c7490.png)

But it doesn't work in Typescript
![image](https://user-images.githubusercontent.com/7609893/69259369-24dcd280-0b8c-11ea-801e-6bd50dc85f62.png)

and this is the TS Error that I get: 
![image](https://user-images.githubusercontent.com/7609893/69259440-43db6480-0b8c-11ea-8459-117c9e70f628.png)

Questions:
1. What style type should I be using for my Theme? I am using `Theme from "theme-ui"`.
2. What style type should I give to my base styles so that can use all properties used by `SystemStyleObject` can be inherited inside theme?

**Comment by jxnblk** [comment]
If you're using TS, you'll want to create your own type definition for your own custom theme shape afaik

**Comment by prateekkathal** [comment]
@jxnblk I will take care of this i my downtime and add it to the current type definitions of theme-ui as a PR. 

Thanks for all the help 😄
