### ISSUE TITLE
Gatsby/theme-ui css prop issue.

### ISSUE THREAD

**Issue by pjeziorowski** [system-ui/theme-ui#472]
Hi!

I found an [issue](https://github.com/gatsbyjs/gatsby/issues/19661) with css prop and theme-ui and reported it on Gatsby github, but I was redirected here. 

Could you take a look at the issue linked above as it may be theme-ui issue?

**Comment by jxnblk** [comment]
Sorry for the delay -- it looks like the reproduction is outdated. If you have an up-to-date reproduction, please feel free to reopen this issue
