### ISSUE TITLE
Composing Variants

### ISSUE THREAD

**Issue by adamsoffer** [system-ui/theme-ui#475]
What's the recommended way to compose variants? For example, what if I want my button to use a `primary` variant but a smaller version of it?

**Comment by jxnblk** [comment]
As far as the current API goes, you can use a variant in another variant to extend it, e.g.

```js
buttons: {
  primary: {
    paddingX: 3,
    paddingY: 2,
    color: 'white',
    bg: 'blue',
  },  
  small: {
    variant: 'buttons.primary',
    paddingX: 2,
    paddingY: 1,
  },  
},
```

**Comment by adamsoffer** [comment]
ah pretty neat. Thanks @jxnblk !

**Comment by adamsoffer** [comment]
I guess the one downside is you have to create an object key for every permutation. But, good enough for now.
