### ISSUE TITLE
Refs not being passed to some Layout components

### ISSUE THREAD

**Issue by EverDawnDigital** [system-ui/theme-ui#476]
When you pass a ref to the Header layout component, it produces the following react warning in the browser console.

Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

The Box layout component does allow refs to be forwarded.

This is a simplified recreation of something I am trying to do.

`
/** @jsx jsx */
import { jsx, Header, Box } from 'theme-ui'

import { useRef } from 'react'

const RefComponent = () => {

    const headerRef = useRef()
    const boxRef = useRef()

    return (
        <div>
        <Header ref={headerRef} >Header</Header>{/* This will error */}
        <Box ref={boxRef} >Box</Box>{/* This works fine */}
        </div>
    )
}

export default RefComponent`

I have dug around the code but I cannot work out why. 

Many thanks

**Comment by jxnblk** [comment]
The `Header` component does not accept refs, you can use the `Box` component from the `@theme-ui/components` package instead, e.g. `<Box as='header' ref={ref} />`
