### ISSUE TITLE
Question: How to set MDX styles for different color modes?

### ISSUE THREAD

**Issue by dance2die** [system-ui/theme-ui#478]
Is there a way to access a current theme mode in the theme declaration (or declare different color for MDX styles)?

I am trying to change the font color within `blockquote` element in "dark" mode  
because the darkmode's text color changes all colors under top-level layout.

Refer to the example of blockquote's color (generated from MDX) changing to white below.

![demo](https://user-images.githubusercontent.com/8465237/69489373-3a305600-0e45-11ea-90ed-3ae318a0311d.gif)

Here are three failed attempts to overwrite blockquote's color in dark mode.  

```javascript
export const theme = {
  initialColorMode: "light",

  colors: {
    text: "#000",
    background: backgroundColor,
    primary: themeColor,
    gray: ["#efefef", "#ddd", "#333", "#111"],
    highlight: "#ffd",

    modes: {
      dark: {
        text: "#ffffffe0",
        background: "#282c35",
        gray: ["#101010", "#222222", "#cccccc", "#eeeeee"],
        
        // 1️⃣ first attempt
        blockquote: {
          color: "red",
        }
      },
    },
  },
   // ...
  
  styles: {
    // 2️⃣ second attempt
    modes: {
      dark: {
        blockquote: {
          color: "red",
        }
      }
    },
    root: {
      fontFamily: "body",
      lineHeight: "body",
      fontWeight: "body",
    },
    // rest redacted for brevity.
    
    blockquote: {
      padding: "16px",
      backgroundColor: "highlight",
      borderRadius: "4px",
      borderLeft: t => `8px solid ${t.colors.primary}`,

      // 3️⃣ third attempt
      modes: {
        dark: {
          color: "red",
        },
      },
    },
}
```

**Comment by dance2die** [comment]
Would it be too "hacky" to use a random `accent` value that's same in both `default/dark` modes?

![hacky workaround using accent](https://user-images.githubusercontent.com/8465237/69489603-d9a31800-0e48-11ea-9986-751bd716822c.gif)


```javascript
export const theme = {
  initialColorMode: "light",

  colors: {
    text: "#000",
    background: backgroundColor,
    primary: themeColor,
    gray: ["#efefef", "#ddd", "#333", "#111"],
    highlight: "#ffd",
    // 👇
    accent: "#000",

    modes: {
      dark: {
        text: "#ffffffe0",
        // 👇
        accent: "#000",
        background: "#282c35",
        gray: ["#101010", "#222222", "#cccccc", "#eeeeee"],
      },
    },
  },

  styles: {
    blockquote: {
      padding: "16px",
      backgroundColor: "highlight",
      borderRadius: "4px",
      borderLeft: t => `8px solid ${t.colors.primary}`,
      // 👇
      color: t => t.colors.accent,
    },
  }
}
```

**Comment by jxnblk** [comment]
If you reference a color key in `theme.styles.blockquote` it'll automatically switch based on the current color mode, which is what's happening when you reference `accent` - you can also use a string value for this, e.g. `color: 'accent'`

**Comment by dance2die** [comment]
Thank you, Brent for the explanation and the tip (string value for `'accent'`).
Now I see what had happened and what to do on theme changes :)
