### ISSUE TITLE
styling <code> in MDX when using backticks?

### ISSUE THREAD

**Issue by kuworking** [system-ui/theme-ui#489]
I'm facing the following

If in my `mdx` doc I write

```js
`eh`

<code>eh2</code>
```

and I have a styles like this

```js
    code: {
      fontFamily: 'monospace',
      backgroundColor: '#000',
    },
```

I only see the `<code>` element styled

Looking at the html, I can see that the backtick gets transformed into a

```js
<p><code>eh</code></p>
```

And if I specifically style this code, it works

```js
    p: {
      code: {
        fontFamily: 'monospace',
        backgroundColor: '#000',
      },
    },
    code: {
      fontFamily: 'monospace',
      backgroundColor: '#000',
    },
```

But, shouldn't the `code` styling apply to everything here, included the nested `code`? Maybe it's in the docs and I haven't read it? Or this shouldn't happen and it has to be something else?

**Comment by kuworking** [comment]
I also have noted that if I add a `blockquote` directly, then it gets styled, but if I add it from a component, it does not

```js
import { MyBQ } from blah

this gets styled

> test 

this does not

<MyBQ />
```

where the component is just a `export const MyBQ = () => <blockquote>hello</blockquote/>`

I find this illogical (or unexpected) in the sense that the tags are created in the `mdx` document, so they should be styled (at least that's what I was expecting)

*Only trying to understand how it works, `theme-ui` is a fabulous contribution to gatsby ecosystem :D

**Comment by jxnblk** [comment]
`theme.styles` applies to MDX components, as specified here: https://mdxjs.com/getting-started#table-of-components - I suspect you might need to use `theme.styles.inlineCode` to target the elements created with backticks.

In the case of `MyBQ`, MDX treats that as a component so its styling isn't targeted by default with Theme UI. 

Hope that makes sense

**Comment by kuworking** [comment]
Totally, thanks :)
