### ISSUE TITLE
Responsive styles used before variant in sx prop not working properly - only first value used for all breakpoints

### ISSUE THREAD

**Issue by acal11** [system-ui/theme-ui#490]
When using any responsive value in my sx prop, followed by the variant, only the first value in the responsive array is actually applied across all breakpoints.

E.g: 
` sx={{
        color: ['red', 'blue'],
        variant: 'layout.section',
      }}`

Results in `color: red` being applied regardless of breakpoint. If I reverse the order and put color after variant then it works as intended. This happens for other properties as well.

Edit: switching the order then means that responsive values in my variant don't work. Is there some incompatibility where responsiveness will only work for variant _or_ the other properties but not both?

**Comment by jxnblk** [comment]
Can you include a reproduction and the code that you have in your theme?

**Comment by VarunDevPro** [comment]
I guess the breakpoints will work only for length values like 'min-width', 'height', 'margin', 'padding', etc.,

Am I right? @jxnblk
