### ISSUE TITLE
Make @mdx-js/react optional?

### ISSUE THREAD

**Issue by brambow** [system-ui/theme-ui#494]
Would you consider making `@mdx-js/react` optional/not a peerDependency? I've been migrating to Theme UI from Rebass for a component library and some SPA's (analytics dashboards with maps and charts). I don't need the MDX functionality for these uses, so it feels wrong having to add `@mdx-js/react` to those types of projects. 

Alternatively, would you recommend sticking to Rebass for these types of applications?

**Comment by mrmartineau** [comment]
I have no need for mdx either and was also wondering the same thing. Is it actually needed when using Theme UI?

**Comment by jxnblk** [comment]
With [v0.3](https://github.com/system-ui/theme-ui/pull/535), the main package will be split into smaller packages, which will include a `@theme-ui/core` package that can be used without MDX. Closing this issue out for now
