### ISSUE TITLE
ThemeUI breaks when localStorage is not supported

### ISSUE THREAD

**Issue by clairefritz** [system-ui/theme-ui#512]
Hi!
I'm running into the following issue:
We have a native app that renders some of our web app's ThemeUI-powered pages. Those pages crash with the following error:
```
TypeError: Cannot read property 'getItem' of null
  at storage(./node_modules/theme-ui/dist/index.esm.js:422:19)
  at e(./node_modules/theme-ui/dist/index.esm.js:447:18)
```
This is the line that's causing havoc: `return window.localStorage.getItem(STORAGE_KEY) || init;`.
This is because ThemeUI tries to read the currently selected color mode from localStorage, but our native app doesn't have localStorage in the webViews.

**Expected behavior**
ThemeUI checks for localStorage support and falls back to the default color mode if it localStorage isn't supported.

**Comment by cainvommars** [comment]
@jxnblk Thanks for the fix!

**Comment by clairefritz** [comment]
@jxnblk Thanks 🙂
