### ISSUE TITLE
Flex component always overrides display prop from sx

### ISSUE THREAD

**Issue by SpadarShut** [system-ui/theme-ui#518]
**Describe the bug**
The `display` sx style is always overridden by 'display:flex' at the end.

**To Reproduce**
```<Flex sx={{display: 'none'}}>Should be hidden</Flex>```
The code above does not hide the Flex component.

**Expected behavior**
Display none should be applied

**Additional context**
Any display value gets overridden by a following `display: flex`.

**Comment by jxnblk** [comment]
You can yse the `Box` component if you need to change the `display` property
