### ISSUE TITLE
Adaptive borders to color mode change

### ISSUE THREAD

**Issue by emadabdulrahim** [system-ui/theme-ui#519]
What's the easiest way to make border colors change based on color mode?

Since this is not allowed
```js
borders: {
  base: '1px solid primary'
}
```

currently, I do the following
```js
borders: {
  base: `1px solid ${palette.primary}`
}
```

Given how I define borders now, is there an easy way to make it adapt to color mode?

**Comment by emadabdulrahim** [comment]
My solution which isn't ideal is to handle border colors separately in the single CSS using css custom props.

**Comment by jxnblk** [comment]
For shorthand properties, you can use [functional values](https://theme-ui.com/sx-prop#functional-values), or you can use the `borderColor` property

**Comment by emadabdulrahim** [comment]
@jxnblk Thanks for the speedy reply.

Functional values only work with `sx` prop though,  not when I'm defining the theme, correct?

```js
export default {
  ...theme,
  borders: {
    base: `1px solid ${palette.primary}`
  }
}
```

Is there any solution where border color is responding to the color mode?

**Comment by emadabdulrahim** [comment]
Oh, you're saying I should do this

```js
<div sx={{ border: 'base', borderColor: 'muted' }} />
```
That way I'm picking a border color from the theme colors

So the only compromise is 2 rules vs 1 rule.

**Comment by jxnblk** [comment]
You can also use [variants](https://theme-ui.com/guides/variants) with either `borderColor` or functional values
