### ISSUE TITLE
How to properly modify @theme-ui/components styles without just overriding them?

### ISSUE THREAD

**Issue by emadabdulrahim** [system-ui/theme-ui#522]
Using `gatsby-plugin-theme-ui`, how to change `@theme-ui/components` styles without just overriding the default styles they come with?

Right now I'm overriding them but I'd like my CSS output to be cleaner.

Thanks!

**Comment by emadabdulrahim** [comment]
Looking at the source code, I suspect that's not supported. But I could be wrong.

**Comment by emadabdulrahim** [comment]
The reason I'm asking this is to reduce the size of my CSS. Mainly when it comes to global styles, such as typography.

For example, if I only use one font, `font-family: system-ui` in the app, I wouldn't want any of my typography elements specifying the `font-family` rule because that would be redundant.

Is there a way to do this right using ThemeUI?

**Comment by jxnblk** [comment]
Currently, I don't think there is a way to avoid this other than *not* using particular components from the package and using custom ones instead
