### ISSUE TITLE
Custom JSX pragma does not work with `@emotion/babel-preset-css-prop`

### ISSUE THREAD

**Issue by jxnblk** [system-ui/theme-ui#53]
When defining a custom pragma with theme-ui and using the Emotion preset, the preset still applies transforms from `babel-plugin-emotion`, meaning that theme-ui's pragma no longer works.

**Comment by VinSpee** [comment]
it took this config for me:

```json
{
  "presets": […, "@emotion/babel-preset-css-prop"],
  "plugins": [
    [
      "babel-plugin-transform-react-jsx",
      {
        "pragma": "jsx"
      }
    ],
    [
      "@emotion/babel-plugin-jsx-pragmatic",
      {
        "module": "theme-ui",
        "import": "jsx",
        "export": "jsx"
      }
    ],
    [
      "@styled-system/babel-plugin",
      {
        "breakpoints":[…]
      }
    ]
  ]
}
```

this has the undesired effect of making everything else that `@styled-system/babel-plugin` does _also_ work, so if you don't want to enable props as styled-system css attributes, you're kind of SOL.

**Comment by jxnblk** [comment]
Yeah, I wouldn’t recommend using the Styled System Babel plugin with Theme UI – they sort of work at different levels. #69 should make things work like you’d expect (we just have to settle on a new prop name)

**Comment by jxnblk** [comment]
With v0.2.0, the custom pragma now uses the `sx` prop, which should work with or without the Emotion Babel plugin

**Comment by SpadarShut** [comment]
Does it mean that now it's possible to add @emotion/babel-preset-css-prop to babel and not have to add the pragma manually for every file? Doesn't seem to work for me now.

**Comment by jxnblk** [comment]
@SpadarShut if you want to use the Theme UI `jsx` function, you should use the `/** @jsx jsx */` pragma comment
