### ISSUE TITLE
useThemeUI does not contain setColorMode in Storybook config

### ISSUE THREAD

**Issue by danvim** [system-ui/theme-ui#537]
I originally posted my question here.

https://stackoverflow.com/questions/59560557/themeuis-usethemeui-does-not-contain-usecolormode

**Describe the bug**
useThemeUI does not contain setColorMode in Storybook config

**To Reproduce**

1. Create a new storybook using the "react" config.
2. Install this package: 'storybook-dark-mode/register' to get a button in storybook for switching color scheme

3.
 a.  ***Route 1***
  Try `useColorMode` in `.storybook/config.js` to integrate color theme.
  Sees error:

  > [useColorMode] requires the ThemeProvider component

 b. ***Route 2***
  Try `useThemeUI` instead.

  ```js
  const context = useThemeUI()
  const { setColorMode } = context
  //...
  ```

  Sees error:

  > useColorMode is not a function.

  `context` contains:

  ```js
  {
     components: Object { p: {…}, b: {…}, i: {…}, … }
     emotionVersion: "10.0.27"
     theme: null
  }
  ```

**Expected behavior**
According to the guide, I should be able to use `useColorMode` to initialize and setup my theme.

**Screenshots**
![image](https://user-images.githubusercontent.com/5255292/71659017-f05e5800-2d80-11ea-841c-16448fb1aa1d.png)

**Additional context**

My `.storybook/config.js`

```js
import React, { useEffect } from 'react'
import addons from '@storybook/addons';
import { addDecorator, configure } from '@storybook/react';
import { ColorMode, ThemeProvider, useThemeUI } from 'theme-ui'
import theme from '../theme'

const channel = addons.getChannel();

const ThemeWrapper = (props) => {
  const context = useThemeUI()
  const { setColorMode } = context

  console.log(context)

  const setDarkMode = isDark => setColorMode(isDark ? 'dark' : 'default')

  useEffect(() => {
    channel.on('DARK_MODE', setDarkMode);
    return () => channel.removeListener('DARK_MODE', setDarkMode);
  }, [channel, setColorMode]);

  return (
    <ThemeProvider theme={theme}>
      <ColorMode/>
      {props.children}
    </ThemeProvider>
  );
}

addDecorator(renderStory => <ThemeWrapper>{renderStory()}</ThemeWrapper>);

configure([
  require.context('../components', true, /\.stories\.(jsx?|mdx)$/),
  require.context('../stories', true, /\.stories\.(jsx?|mdx)$/)
], module);

```

**Comment by jxnblk** [comment]
If you're seeing this message:

> [useColorMode] requires the ThemeProvider component

That means either you don't have a `ThemeProvider` component wrapping the component that's calling `useColorMode` or there are multiple versions of Emotion installed, which will cause conflicts with React context.

**Comment by danvim** [comment]
@jxnblk So does that mean there is no way of setting the color mode outside of `ThemeProvider`?

**Comment by danvim** [comment]
Thanks. I modified my code to the following it the problem was solved.

```js
import React, { useEffect } from 'react'
import addons from '@storybook/addons';
import { addDecorator, configure } from '@storybook/react';
import { ColorMode, ThemeProvider, useColorMode } from 'theme-ui'
import theme from '../theme'

const channel = addons.getChannel();

const ThemeChanger = () => {
  const [colorMode, setColorMode] = useColorMode();

  const setDarkMode = isDark => setColorMode(isDark ? 'dark' : 'default')

  useEffect(() => {
    channel.on('DARK_MODE', setDarkMode);
    return () => channel.removeListener('DARK_MODE', setDarkMode);
  }, [channel, setColorMode]);

  return <div/>
}

const ThemeWrapper = ({ children }) => {
  return (
    <ThemeProvider theme={theme}>
      <ThemeChanger/>
      <ColorMode/>
      {children}
    </ThemeProvider>
  );
}

addDecorator(renderStory => <ThemeWrapper>{renderStory()}</ThemeWrapper>);

configure([
  require.context('../components', true, /\.stories\.(jsx?|mdx)$/),
  require.context('../stories', true, /\.stories\.(jsx?|mdx)$/)
], module);

```

**Comment by mrmartineau** [comment]
@danvim how do you actually change the theme in Storybook? Is it based on the user's `prefers-color-scheme` value? or is it something else?
