### ISSUE TITLE
Background/text theme color not applying?

### ISSUE THREAD

**Issue by maxkrieger** [system-ui/theme-ui#544]
**Describe the bug**
Setting the `background`/ key for `colors` in the theme doesn't apply to the body. But it's [documented](https://theme-ui.com/theming) that this is the expected behavior.

**To Reproduce**
See `theme.js` here https://codesandbox.io/s/pensive-hypatia-4imxn?fontsize=14&hidenavigation=1&theme=dark

**Comment by jxnblk** [comment]
In the current version, the body colors are *only* applied if you have color modes enabled. This behavior will change in the next version

**Comment by maxkrieger** [comment]
I see. This behavior is undocumented otherwise? Glad to see it's being changed.

**Comment by jxnblk** [comment]
The color mode behavior is documented here, but might not be super clear: https://theme-ui.com/color-modes#applying-colors

**Comment by maxkrieger** [comment]
Gotcha, my confusion was that on the Theming page it treats color modes as
a subheading of colors. No problem!
