### ISSUE TITLE
Difference between BaseStyles and Styled.root components

### ISSUE THREAD

**Issue by Grsmto** [system-ui/theme-ui#552]
Hi!

**Describe the bug**
There seems to be 2 ways of doing the same thing using `BaseStyles` and `Styled.root` components to style components outside of MDX.

Is there any difference between these two?

It's confusing on which component should be used in that case since the doc is basically describing the same behaviour for both.
There should be only one component to do top-level styling.

**Comment by jxnblk** [comment]
The `BaseStyles` component includes child selectors, which you really shouldn't use unless you have non-MDX markdown content. The `Styled.root` element only adds base typographic styles. The API will be changing slightly in the next version to hopefully make this a little easier to work with
