### ISSUE TITLE
Support for upcoming Emotion 11

### ISSUE THREAD

**Issue by jonavila** [system-ui/theme-ui#560]
Hi @jxnblk. I'm looking at using Theme-UI in a project where I'll need some of the improvements being done to emotion in v11. In the version of emotion, @emotion/core has been renamed to @emotion/react.

Any thoughts on how theme-ui will support this? Not sure that I cant v11 with theme-ui at the moment due to these changes.

**Comment by jxnblk** [comment]
When the stable Emotion 11.0.0 is released, we'll likely bump a major beta (e.g. v0.4) version for Theme UI. I don't imagine much will change with the API in this library when that happens

**Comment by jonavila** [comment]
Thanks for the quick response. Looking forward to trying it out when the new version is released.
