### ISSUE TITLE
Breakpoints in em set to 16px

### ISSUE THREAD

**Issue by 7-Chord** [system-ui/theme-ui#566]
Given the following breakpoints: 
breakpoints:['40em', '52em', '64em', '80em'],

my media queries kick in at 640px, 832px, 1,024px and 1,280px.  

I've set my app body to 10px, so I would expect the queries to kick in at 400px, 520px, 640px and 800px.  Is there a key in the theme that I need to set in order to set my base font size?

Thanks

**Comment by lachlanjc** [comment]
Theme UI doesn’t automatically set your body font size, so unless you do that manually with Emotion Global, styled-jsx, etc, your fontSizes will have no effect on your breakpoints.

**Comment by 7-Chord** [comment]
Sounds good.  Thanks.

**Comment by KD33** [comment]
Can someone give an example?  I'm having the same problem and @lachlanjc suggestion didn't work using Emotion Global

**Comment by lachlanjc** [comment]
Sure! https://github.com/lachlanjc/gunfunded/blob/glitch/pages/_app.js#L20
