### ISSUE TITLE
Order of generated media queries is wrong

### ISSUE THREAD

**Issue by 454de6e** [system-ui/theme-ui#577]
**Describe the bug**
I came across a case when the order of media queries generated by Theme UI is wrong and incorrect styles are applied. The root cause of the bug might be in `styled-system`, not `theme-ui`.

**To Reproduce**
1. Clone https://github.com/UNDataForum/gatsby-themes and switch to branch `theme-ui-issue`
1. Run `yarn` and `yarn start`.
1. Make sure your viewport width in Chrome or Firefox is more than 960px (60em.)
1. Load http://localhost:8000/ and inspect the page with DevTools.
1. Choose the parent element of the "United Nations" text in the hero image. See this comment for a screenshot that shows the element you need to choose https://github.com/UNDataForum/gatsby-themes/issues/291#issuecomment-573878753
1. Look at the CSS rules that are applied to the chosen element (see second screenshot in issue comment from previous step).
1. You should see that the `min-width` media queries have the wrong order and the `min-width: 30em` rule overrides the `min-width: 60em` rule leading to the wrong left and right padding being applied.

**Expected behavior**
The `min-width: 60em` media query should be at the top and override the `min-width: 30em` query.

**Additional context**
The CSS is generated from the `sx` prop here: https://github.com/UNDataForum/gatsby-themes/blob/theme-ui-issue/site/src/components/hero.js#L50-L64:

```
sx={{
  flexDirection: 'column',
  justifyContent: ['flex-start', null, 'flex-end'],
  color: 'background',
  backgroundImage: [
    theme =>
     `linear-gradient(to bottom, ${theme.colors.primary}, transparent 75%  )`,
    null,
    theme =>
      `linear-gradient(to top, ${theme.colors.text}, transparent 75%)`,
    ],
  height: '100%',
  px: [2, 3, 4],
  py: 4,
}}
```
Note the 3 CSS pros that define responsive behavior with an array. 2 of them skip one breakpoint with a `null` value as described in the [styled-system docs](https://styled-system.com/guides/array-props/#origins).

I noticed that if I replace **all** `null` values in the responsive arrays with preceding array value (creating more verbose CSS) like this

```
sx={{
  flexDirection: 'column',
  justifyContent: ['flex-start', 'flex-start', 'flex-end'],
  color: 'background',
  backgroundImage: [
    theme =>
     `linear-gradient(to bottom, ${theme.colors.primary}, transparent 75%  )`,
    theme =>
     `linear-gradient(to bottom, ${theme.colors.primary}, transparent 75%  )`,
    theme =>
      `linear-gradient(to top, ${theme.colors.text}, transparent 75%)`,
    ],
  height: '100%',
  px: [2, 3, 4],
  py: 4,
}}
```
the bug goes away and the order of the generated CSS rules is as expected.

**Comment by jxnblk** [comment]
Thanks for reporting this! I know this was an issue with styled-system core, but I bet this isn't accounted for in the `css` package. I can add a failing test and should have a fix soon if it's as simple as I think it is

**Comment by 454de6e** [comment]
I updated `theme-ui` deps to v0.3.0 in this branch (https://github.com/UNDataForum/gatsby-themes/tree/theme-ui-issue) to test but I still see the issue. The `30em` rule still overrides the `60em` rule (see screenshot).

<img width="1429" alt="Screen Shot 2020-01-22 at 15 03 51" src="https://user-images.githubusercontent.com/1482402/72929976-e4830780-3d28-11ea-96a8-9fe216db5109.png">

Deployment: https://gatsby-themes-elnco96sa.now.sh/

**Comment by 454de6e** [comment]
v0.3.1 fixed it.
