### ISSUE TITLE
Extending a variant does not override its styles

### ISSUE THREAD

**Issue by joernroeder** [system-ui/theme-ui#580]
**Describe the bug**
I would not only extend a variant but also alter some of its defined styles. In my case I'm defining some heading style and would like to extend those by overriding color.

**To Reproduce**
define the following in your config:

```js
colors: {
    text: '#000',
    primary: '#f00',
},
text: {
    heading: {
      fontFamily: 'heading',
      fontWeight: 'heading',
      lineHeight: 'heading',
      color: 'text'
    },
    headingLight: {
      variant: 'text.heading',
      color: 'primary'
    }
  }
```

and use `<Heading variant='headingLight'>Testing</Heading>` somewhere. 

**Expected behavior**
Headline should be red, but it is using the text color.

**Additional context**
It works if you remove `color: 'text'` from the `headling` variant.

**Comment by lachlanjc** [comment]
I’d absolutely love this. For example, I have a set of container styles, & they’re mostly the same, but I want to change the `maxWidth` on each one. Some basic composition/overrides like this would shorten my theme enormously.

**Comment by jxnblk** [comment]
This sounds like a bug -- I'll try to add a failing test in a PR

**Comment by jxnblk** [comment]
Sorry, but I'm unable to reproduce this. Could you add a Code Sandbox link with a reproduction of the bug?

**Comment by lachlanjc** [comment]
I also can't reproduce this, using Next.js. I tried with Buttons & they work as expected. I didn't know about this composition feature before though, so useful anyway!

- Code: https://glitch.com/edit/#!/theme-ui-580
- App: https://theme-ui-580.glitch.me

Feel free to remix that & see if you can get the bug to happen.

**Comment by joernroeder** [comment]
@jxnblk @lachlanjc are you both using version `^0.3.0-alpha.4`? 
I'm on `^0.2.52` and will give the latest alpha a try when I am back.

**Comment by lachlanjc** [comment]
The demo was on v2 but I just upgraded it to the latest alpha & everything is continuing to work as expected.

**Comment by joernroeder** [comment]
I revisited the components recently and now its working as expected. Not sure if it was related but having to pass down `className` all the time wasnt clear to me before reading through https://github.com/system-ui/theme-ui/issues/396 
Maybe a high level explanation in the docs@Guides/HowToBuildYourOwnComponent so people can start with an example from there.
Thanks for all the work btw, its amazing to work with!
