### ISSUE TITLE
VScode syntax highlighting and auto complete for sx prop

### ISSUE THREAD

**Issue by NatPagles** [system-ui/theme-ui#582]
Been using styled-components but was having a couple of performance issues but there was great support for syntax highlighting and auto completion for css inside template literals. 

Decided to switch and try out theme-ui with jsx css object literals instead but couldnt find any proper plugins that work with jsx css.

Found [this emotion issue](https://github.com/emotion-js/emotion/issues/447) but none of those plugins will work with jsx css.

Has anyone gotten syntax highlighting to work? or is there different way to handle this?

**Comment by jxnblk** [comment]
Since it's object literal syntax, your default JavaScript syntax highlighting *should* work

**Comment by NatPagles** [comment]
Unfortunately its not working for me. My file extension is .js and using [Babel Javascript by Michael](https://marketplace.visualstudio.com/items?itemName=mgmcdermott.vscode-language-babel)

![Screen Shot 2020-01-16 at 11 37 40 AM](https://user-images.githubusercontent.com/9328287/72557054-cfa00300-3854-11ea-9b16-b7c69975ef18.png)

**Comment by jxnblk** [comment]
Closing this since it's a text editor issue and not specific to this library. If you're still running into issues, I'd recommend asking someone who uses the same text editor
