### ISSUE TITLE
[@theme-ui/components] Add variants for Spinner component 

### ISSUE THREAD

**Issue by alexpermiakov** [system-ui/theme-ui#583]
**Is your feature request related to a problem? Please describe.**
For now, theme-ui Spinner component is quite hardcoded - keyframe animation is baked into it.

Some years ago I created [Styled HTML5 Progress element demo](https://codepen.io/alexdevp/pen/JXRWrJ)

**Describe the solution you'd like**
It would be great to pass keyframe animation into the theme. For example:

```
const theme = {
  buttons: {
    primary: {
      color: 'background',
      bg: 'primary',
    },
    secondary: {
      color: 'background',
      bg: 'secondary',
    },
  },
  spinners: {
    primary: {
      title = 'Loading...',
      color: 'secondary',
      animation: {
        name: spin.toString(),
        timingFunction: 'linear',
        duration: 500,
        iterationCount: 'infinite',
      },
    },
  },
}
```

While it's fine for the spinners above, it's not enough for others: for example, [these nice ones](https://loading.io/css/) have a different number of animated items. One solution might be to pass an argument - the number of animated items (usually it's between 1-12).

**Describe alternatives you've considered**
Create named Spinners, something like HeartSpinner.

**Comment by jxnblk** [comment]
Haven't looked at the related code very closely yet, but think it totally makes sense to support Spinner variants in ways that it might not already handle -- IIRC you should be able to target the inner `<circle>` element from a variant, but YMMV

**Comment by lachlanjc** [comment]
Hey! I think themes are already diverse enough in their scope & functionality (writing CSS & theme-based CSS in variants/components, styling document content in `styles`, the scales, plus Theme UI configuration options), I think it’d make it pretty confusing to also define component props inside the theme. I think these spinners would be a great fit either for the Recipes on the docs site or as an external package linked to on our Resources page (#1275).

@hasparus I’m cool to close
