### ISSUE TITLE
On the possibility of a Css reset component for consistent style across browsers 

### ISSUE THREAD

**Issue by peter-75** [system-ui/theme-ui#584]
**Problem of style consistency across browser**

On various projects, I often fall into problems of consistency in css due to different user agent styles applied depending on the browser used. Fixing the theme to be independent on the browser used is  something that you consider in your roadmap ?  

**Solution**

A possible solution would be as the Material ui library does is using a [CssBaseline](https://material-ui.com/components/css-baseline) component (either based on css reset or normalise css) 

**Alternative solution**

An alternative solution would be to provide documentation about this problem and the way to solve it maybe by enforcing some css reset in theme.styles.root, for the theme presets for example and/or giving some guidelines. 

I am very curious to have your thoughts on this.

**Comment by jxnblk** [comment]
Generally you shouldn't need a large CSS reset these days. The next version of theme-ui will include a body margin reset and `box-sizing: border-box`, both of which can be optionally disabled. If you need anything more than that, I'd recommend using Normalize CSS

**Comment by peter-75** [comment]
Thank you for your answer. Indeed I think it's mostly because I was targeting some old browser version, I faced more frequently this issue.

**Comment by lachlanjc** [comment]
You could also publish your own package with a component wrapping your reset, like [this](https://github.com/merelinguist/styled-preflight) 👍
