### ISSUE TITLE
Support for margins and paddings in theme.style definitions

### ISSUE THREAD

**Issue by jarimustonen** [system-ui/theme-ui#585]
Typically I like to have default margins/paddings in some elements such as header (h1, h2, etc.). The theme.style definitions seems to be a good place for them so that following would work.

```
const theme = {
  ...
  styles: {
    h1: {
      my: 3,
      ...
    },
    ...
};
```

**Comment by jxnblk** [comment]
This *should* work. If you've found a bug, please provide a reproduction of the issue

**Comment by lachlanjc** [comment]
FWIW, I do this on all my sites & it works as expected.

**Comment by jarimustonen** [comment]
Thank you for you quick response. I have created a simple project that demonstrated the problem (see attached files).

Page definition:
```
const App = () => (
  <ThemeProvider theme={theme}>
    <Styled.root>
      <Header
        sx={{
          display: "block"
        }}
      >
        <Heading as="h1">Heading defined without sx</Heading>
        <Heading
          as="h1"
          sx={{
            py: 3,
            my: 3
          }}
        >
          Heading defined with sx
        </Heading>
        <div>Text</div>
      </Header>
      <Main></Main>
    </Styled.root>
  </ThemeProvider>
);
```

Where the `theme` contains the following:
```
  styles: {
    h1: {
      color: "text",
      fontFamily: "heading",
      lineHeight: "heading",
      fontWeight: "heading",
      py: 3,
      my: 3,
      fontSize: 5
    }
  }
```

[theme_ui_issue_585_demo.zip](https://github.com/system-ui/theme-ui/files/4075327/theme_ui_issue_585_demo.zip)

**Comment by jxnblk** [comment]
Based on the code example above, the `Heading` component will *not* pick up values from `theme.styles.h1` -- that's reserved for markdown content and `Styled.h1`. To add default variants for the `Heading` component, you'll need to add `theme.text.heading` styles

**Comment by jarimustonen** [comment]
Ok, thank you. Do I understand correctly that `Heading` component does not support different heading levels? (In a sense that you can define different behaviour in `theme` object.) If you would like to use multiple levels of headings, you should use `Styled.h1`, `Styled.h2`, etc. Correct?

**Comment by jxnblk** [comment]
You can specify styles and HTML semantics separately with the Heading component: e.g. `<Heading as='h3' variant='title' />`
