### ISSUE TITLE
v0.3 Odd behaviour with flexDirection and responsive array

### ISSUE THREAD

**Issue by ehowey** [system-ui/theme-ui#601]
**Describe the bug**
This seems to be limited to `flexDirection` at least this is the only spot I have encountered it. It seems like when flexDirection goes "buggy" it causes all of the other responsive queries, just in that element, to stop working and default to their first value.

Prior to v0.3 the following code worked fine:

```js
<div
      sx={{
        display: "flex",
        flexDirection: ["column", null, "row", null, null],
        width: ["100vw", "auto", null, null, null],
        position: ["relative", "static", null, null, null],
        left: ["calc(-50vw + 50%)", "auto", null, null, null],
        backgroundColor: "accent",
        p: 3,
        mb: 4,
        borderRadius: 3,
      }}
      key={title}
    >
```

Now the code has to be written like this:

```js
<div
      sx={{
        display: "flex",
        width: ["100vw", "auto", null, null, null],
        position: ["relative", "static", null, null, null],
        left: ["calc(-50vw + 50%)", "auto", null, null, null],
        backgroundColor: "accent",
        p: 3,
        mb: 4,
        borderRadius: 3,
        flexDirection: ["column", "column", "row", null, null],
      }}
      key={title}
    >
```

The flexDirection value _also_ needs to be at the bottom of the sx prop...otherwise more odd behaviour ensues.

As far as I can tell all of my other responsive queries are working fine.  It is also working fine in another flexDirection query.

**To Reproduce**
https://github.com/ehowey/gatsby-theme-catalyst/blob/master/themes/gatsby-theme-catalyst-writer/src/components/work-card.js

**Expected behavior**
You can see the expected behaviour of the card component here: https://gatsby-starter-catalyst-writer.netlify.com/

**Screenshots**
Here is a screen shot of what those components look like with the odd behaviour, you can see it going wide across the screen when it should actually be contained.

![Screen Shot 2020-01-22 at 21 16 32](https://user-images.githubusercontent.com/204841/72956325-8a9c3500-3d5c-11ea-92fd-7aaacc08f6ca.png)

**Comment by jxnblk** [comment]
Possibly related to #600

**Comment by ehowey** [comment]
Yep - fixed! Awesome, thank-you!
