### ISSUE TITLE
Does jest-emotion work with theme-ui?

### ISSUE THREAD

**Issue by callumacrae** [system-ui/theme-ui#606]
I don't know if this is a bug report or a feature request because I don't know if it's supposed to work already!

I'm using storyshots to power snapshot tests of components themed using theme-ui, and storyshots is powered by jest snapshot testing. I'm trying to add jest-emotion so that I can see CSS in my snapshots: https://github.com/emotion-js/emotion/tree/master/packages/jest-emotion

It isn't doing anything. There are no errors and it isn't changing the output.

Do you know if it is supposed to work with theme-ui?

**Comment by jxnblk** [comment]
It *should* work -- `jest-emotion` is used to test the library itself. You might want to check and ensure that only one version of Emotion is installed; sometimes that can cause issues

**Comment by callumacrae** [comment]
According to `npm ls`, there's only one version of `@emotion/core`. I'll try to get a minimal repro up next week :)

**Comment by jxnblk** [comment]
Going to close this for now, but if you're still having issues, feel free to reopen with a repro

**Comment by callumacrae** [comment]
Sorry, forgot about this!

We managed to get it working in the end - I'm not sure what the issue was, but this works: https://github.com/uswitch/trustyle/blob/b41d14611f68fa3e91e037fc2f2694a48b407f97/test/Storyshots.test.js
