### ISSUE TITLE
@theme-ui/editor doesn't use @theme-ui/components

### ISSUE THREAD

**Issue by jordanoverbye** [system-ui/theme-ui#608]
**Is your feature request related to a problem? Please describe.**
Currently `@theme-ui/editor` doesn't use `@theme-ui/components`. This means that the styles defined in your theme won't get applied to editor components.

**Describe the solution you'd like**
Replace custom components from `@theme-ui/editor` with ` @theme-ui/components`

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by jordanoverbye** [comment]
Oops, I think I am wrong. It does - was on old version 😓

**Comment by jxnblk** [comment]
Yeah, I think because `@theme-ui/editor` predated `@theme-ui/components`, it wasn't originally built with the components, but tried to update the package a little with v0.3 -- could still use some work though, I'm sure :)
