### ISSUE TITLE
non-pixel units (not mentioned in docs)

### ISSUE THREAD

**Issue by yairEO** [system-ui/theme-ui#609]
Hi, good job with this, been using for almost a year.

No where in the docs units are mentions, and all examples uses "pixels" and the user reading is expecting to figure it out without explanation.

I want to define `spaces`, `fontSizes` and pretty much anything in other units. sometimes `em`, sometimes `em`, sometimes `%`..  it would be incredibly helpful to show it in the example pages, [this](https://system-ui.com/theme/) & [this](https://theme-ui.com/theming/)

I have **no idea** why there are two pages explaining the same thing.. it's confusing which is better.

---

Also i'm reporting a dead link in the README:

![image](https://user-images.githubusercontent.com/845031/73139935-f8f23780-407b-11ea-87f2-a13c1bbd6a14.png)

**Comment by jxnblk** [comment]
Thanks! That's a good point, and we should definitely mention that more explicitly in the docs

**Comment by flo-sch** [comment]
I think we might be able to close this?

On theme-ui.com, the [Theme Specifications](https://theme-ui.com/theme-spec#font-sizes-typographic-scale) and [Theming](https://theme-ui.com/theming#typography) pages mention both:

> Values defined as numbers are converted to pixel units where appropriate. For other units, use string values, e.g. '1em'.

And system-ui.com is potentially out of scope for this issue tracker...?

**Comment by lachlanjc** [comment]
Yep, agreed on all counts. @hasparus Can you close?
