### ISSUE TITLE
Improve Demo page

### ISSUE THREAD

**Issue by alexpermyakov** [system-ui/theme-ui#617]
**Is your feature request related to a problem? Please describe.**
For now, [theme-ui.com/demo](https://theme-ui.com/demo) is very simple and gives quite a blurry view of what the selected theme looks like.

**Describe the solution you'd like**
We can add more components (buttons, forms) on this page, like [here](https://bootswatch.com/default/). I think it can really improve the perception of the themes.

**Describe alternatives you've considered**
Material-ui has [themes & templates](https://themes.material-ui.com/), but it looks like products to buy, rather than a theme&components demo. 

**Additional context**

**Comment by CanRau** [comment]
Agree also
<img width="873" alt="Bildschirmfoto 2020-01-27 um 15 03 53" src="https://user-images.githubusercontent.com/5196971/73209694-cc3f2e00-4116-11ea-9c69-ee94654b3936.png">
is a little bit confusing^^
