### ISSUE TITLE
Checkbox and Radio components should support CSS :checked selector

### ISSUE THREAD

**Issue by isBatak** [system-ui/theme-ui#619]
Users should be able to style a checkbox label based on CSS `:checked` state. 

CheckboxIcon element should go first, then input and after that `{children}`.
Then the user could do something like this:
```
<Checkbox css={{ '&:checked + label': { fontWeight: 'bold' } }}>
  <Label>I Am Checked</Label>
<Checkbox>
```
An alternative could be to remove the wrapping Box and use Fragment instead.
```
<Checkbox css={{ '&:checked + label': { fontWeight: 'bold' } }} />
<Label>I Am Checked</Label>
```
`css` prop is used because currently `sx` is passed to SVG element and not to INPUT element.
Here is the example of what I'm trying to achieve https://codepen.io/isBatak/pen/OJPGzBb

**Comment by atanasster** [comment]
@isBatak - I dont think you can have the label inside the checkbox, actually theme-ui expects the label to be the parent of the checkbox, so your css selector wouldnt work anyway.

On the other hand, you can easily create a component to work as you desire - here is a codesandbox: https://codesandbox.io/s/headless-cdn-922n9 

@hasparus  - can we close this, its a bit old too :)
