### ISSUE TITLE
❓ Question about 0.2 -> 0.3 migration: emotion and mdx dependencies

### ISSUE THREAD

**Issue by kuworking** [system-ui/theme-ui#621]
From the docs

```
@emotion/core and @mdx-js/react are now dependencies of theme-ui and should not be installed separately. 
```

Does this mean that I should remove the packages from my `package.json` __even though__ I am using emotion and mdx independently of theme-ui?

*likely obvious, but I don't know 🤷‍♂️

These are my current dependencies, before upgrading

```
    "@emotion/core": "^10.0.21",
    "@emotion/styled": "^10.0.17",
    "@mdx-js/mdx": "^1.3.1",
    "@mdx-js/react": "^1.5.1",
    "gatsby-plugin-emotion": "^4.1.12",
    "gatsby-plugin-mdx": "^1.0.24",
    "theme-ui": "^0.2.44"
```

**Comment by jxnblk** [comment]
If you are importing and using those libraries in addition to using `theme-ui`, you can keep them in your dependencies, but if not, they can be removed. Note that Yarn often does not handle this correctly and you might need to add a `resolutions` field to your `package.json`

**Comment by kuworking** [comment]
Thanks, I thought it was common to use syled-components through emotion in addition to theme-ui, but I'm start thinking that this is not the case

For others, this link helps in understanding yarn resolutions

https://mnaks.me/yarn-resolutions/

And in my case I've just added to package.json

```
  "resolutions": {
    "**/core": "10.0.21",
    "**/react": "1.5.1"
  },
```
