### ISSUE TITLE
Can not import component from theme-ui

### ISSUE THREAD

**Issue by aditya-lw** [system-ui/theme-ui#622]
**Describe the bug**
I am trying to build gatsby-theme using `gatsby-plugin-theme-ui` which comes with `theme-ui`. And when I try to import components from `theme-ui` it gives me the following error: 

> warn "export 'Header' was not found in 'theme-ui'

**Steps to reproduce**
[clone this repo](https://gitlab.com/aditya48/gatsby-theme-example)
install modules
run command: `yarn workspace site gatsby develop` in the root directory

**Expected behavior**
It should load the component with appropriate styles as shown in this [video](https://egghead.io/lessons/gatsby-use-and-override-a-theme-in-gatsby-with-component-shadowing): 

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/60033184/73262423-1fd37980-41f4-11ea-842b-cf903d933ac3.png)

**Additional context**
I tried reinstalling all the modules.
I also tried to follow step by step tutorials from [this course](https://egghead.io/lessons/gatsby-set-up-yarn-workspaces-for-gatsby-theme-development). Two times.

**Comment by hasparus** [comment]
Hey @aditya-lw! Header has been removed in 0.3.

https://theme-ui.com/migrating/

![image](https://user-images.githubusercontent.com/15332326/73274054-37efcc80-41e5-11ea-95fa-c81ae622ccf4.png)

**Comment by lachlanjc** [comment]
Yep, this is intended behavior now. This issue can be closed.
