### ISSUE TITLE
Multiple Variants of Layout Components

### ISSUE THREAD

**Issue by moshemo** [system-ui/theme-ui#629]
As noted on the [Guide to using Layouts](https://theme-ui.com/guides/layouts/), it is possible to create variants for layout components.  

I am wondering, though, how to create multiple variants for a layout component (similar to how I can create [multiple variants for a button](https://theme-ui.com/guides/variants/)).  

For example, let's say that I have a site with three different variations of a `Header` component -- one for the main site, one for the shop section and a third for a backend section for logged in users.  I would like to use the same `Header` component, and just vary the style using a variant.  In this case, I could imagine three variants:

* Main
* Shop
* Admin

It would look something like this:

```
<Header variant="shop">HEADER CONTENT</Header>
```

Is that possible?  If so, how can I do it?

Thanks.

**Comment by CanRau** [comment]
Just written here in the comments but this should work
```js
const headerStyle = 'shop' // or 'main', or 'admin'
<Header sx={{ variant: theme => theme.styles[headerStyle] }}>Header Content</Header>
```
assuming you define the variations in `theme.styles`

By the way, that should work because of [theme-ui.com/sx-prop/#functional-values](https://theme-ui.com/sx-prop/#functional-values)
Haven't tried it with `variant` myself tho

**Comment by jxnblk** [comment]
As of v0.3, the Header component is deprecated, but you can use variants with any of the components, including the Box component

**Comment by a-y-u-s-h** [comment]
@jxnblk I'm new to Theme UI. This is what I have in my `theme.js` file:

```jsx
import { tailwind } from "@theme-ui/presets"

export default {
  ...tailwind,
  boxes: {
    container: {
      padding: "1rem",
      backgroundColor: "gold"
    }
  }
}

```

And this is my component:

```jsx
import React from "react"
import { Box } from "theme-ui"
const Home = () => {
  const [opacity, setOpacity] = React.useState(0)
  const color = `#404040${opacity}${opacity}`
  return (
    <>
      <Box sx={{ variant: "container" }}>
        <h1>Heading 1</h1>
        <p>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Repellat,
          doloremque, dolorum natus voluptas possimus veniam laudantium, ipsum
          rerum consequuntur officiis tenetur, molestias quidem ad? Similique,
          consectetur! Quasi omnis et nulla!
        </p>
        <button onClick={e => setOpacity(opacity + 1)}>Increment</button>
        <button onClick={e => setOpacity(opacity - 1)}>Decrement</button>
      </Box>
      <style jsx>{`
        p {
          background-color: ${color};
        }
      `}</style>
    </>
  )
}

export default Home

```

Output: 

![2020-09-25_09-43-35_screenshot](https://user-images.githubusercontent.com/19586719/94225832-acfdd800-ff13-11ea-863a-79d9ddeef6ef.png)

The variant is not applied. The docs don't tell me the variant group of `Box` component. I've tried out replacing the `boxes` key in theme with `grids` `layout` `cards`...no luck. Can you help me out? Thanks. [Here's what the docs say](https://theme-ui.com/components/variants): 

![2020-09-25_09-47-06_screenshot](https://user-images.githubusercontent.com/19586719/94226018-25649900-ff14-11ea-8345-83d96bd6f42d.png)

**Comment by a-y-u-s-h** [comment]
@jxnblk Nevermind, Got it. Have to make a layout variant in `theme` and access it with `layout.container` instead of just passing variant="container" to Box. Just read the [Guide for Layouts](https://theme-ui.com/guides/layouts).

**Comment by anmpog** [comment]
Seeing this thread and commenting that the documentation could do a good deal more to explain how to define and utilize variants for components like `Box` and `Flex`. These are key components and I have to say that IMO the documentation does not do a great job of explaining how you might set up some base variants to use with these components.

**Comment by lachlanjc** [comment]
> Seeing this thread and commenting that the documentation could do a good deal more to explain how to define and utilize variants for components like `Box` and `Flex`. These are key components and I have to say that IMO the documentation does not do a great job of explaining how you might set up some base variants to use with these components.

As the primary docs maintainer, I super agree! I would absolutely love contributions to make this clearer; it's certainly difficult to understand right now.
