### ISSUE TITLE
Theme Preset not loading all the styles:

### ISSUE THREAD

**Issue by jean182** [system-ui/theme-ui#631]
Hi I was wondering why all the theme presets I'm trying to load are not loading completely, the thing is that I'm trying to build a simple app using theme ui with the `deep`preset and it seems that not all colors are being loaded

**To Reproduce**
theme.js
```
import { deep } from '@theme-ui/presets'

export default {
  ...deep,
  styles: {
    ...deep.styles,
  },
}
```
Inject the theme provider in the root of the app.

```
import React from 'react';
import { ThemeProvider } from 'theme-ui'
import theme from './theme'
import AppRouter from './router/AppRouter';

function App() {
  return (
    <ThemeProvider theme={theme}>
      <AppRouter />
    </ThemeProvider>
  );
}

export default App;
```

Run the app shows me the correct backgroung but it seems that links don't style properly.

<img width="233" alt="Screen Shot 2020-01-29 at 22 07 53" src="https://user-images.githubusercontent.com/7577652/73419203-dfebbf80-42e3-11ea-97e7-a955ac8eed7d.png">

Body styles looks like this, I think it should have more style properties
<img width="308" alt="Screen Shot 2020-01-29 at 22 08 59" src="https://user-images.githubusercontent.com/7577652/73419258-0dd10400-42e4-11ea-8c3f-b94f9a1c2d0a.png">

**Expected behavior**
I expect the preset to behave like the theme-ui doc page:
<img width="1440" alt="Screen Shot 2020-01-29 at 22 11 23" src="https://user-images.githubusercontent.com/7577652/73419334-55f02680-42e4-11ea-8732-55dca16c1b56.png">

Currently repo is not on github but if you want me to upload it I will do it.

I'm using **react-create-app** not gatsby

Versions
`"theme-ui": "^0.3.1"`
`"@theme-ui/presets": "^0.3.0",`

Also using `@emotion/core` and `@emotion/styled` if that's relevant.

**Comment by CanRau** [comment]
I think, if I understand your explanation correctly, you're not yet using those colors. Theme UI won't apply all styles automatically, just body background and text color (as of v0.3.0).
Everything else has to be applied manually. Hope that helps already I'm in the need for sleep now.
If not please comment maybe with a repo if possible.

**Comment by jean182** [comment]
Thanks for the reply, I'll post the repo tonight, for example in the page stylesheets, I guess the body element should contain all the colors available in the palette of that theme? not just the body and text colors(check the image in the first comment). I mean I guess I should see the primary color being injected in the styles. I don't know if my config is missing anything but I basically copy paste the [docs](https://theme-ui.com/packages/presets) information

**Comment by CanRau** [comment]
Uh I see you mean the css custom properties should be at least defined 🤔 
yea my `body` looks like this
```css
body {
    --theme-ui-colors-primary: #fff;
    --theme-ui-colors-text: #fff;
    --theme-ui-colors-background: #000;
    --theme-ui-colors-secondary: #fff;
    --theme-ui-colors-accent: #fff;
    --theme-ui-colors-muted: hsla(0,0%,100%,0.75 ));
    color: #fff;
    background-color: #000;
}
```

**Comment by jean182** [comment]
Yes the css variables are not defined, and if you check this image
https://user-images.githubusercontent.com/7577652/73419258-0dd10400-42e4-11ea-8c3f-b94f9a1c2d0a.png
the background and text variables are different from your body. This is the repo branch where is reproducible https://github.com/jean182/poke-app/tree/theme-ui-test

**Comment by CanRau** [comment]
I see, yet as mentioned you're not using any colors so far.
Try changing the h1 to
```js
<h1 sx={{color: 'primary'}}>Theme UI sample</h1>
```
for me it's working properly. As I said only body background and color are set by default

**Comment by jean182** [comment]
Thanks, I did saw changes if I apply the `sx` prop and change the import to this `/** @jsx jsx */
import { jsx } from 'theme-ui'` but anyways I still do not have the css variables defined in the body? now it works but that primary color is just being applied to the html tag, I can't find the variable anywhere else in the styles. For example:

```jsx
<a href="/" sx={{color: 'primary'}}>Theme UI sample</a>
```

Translates to this:

```html
<a href="/" class="css-1no8im9-App">Theme UI sample</a>
```

And the styles for that `a` tag are these ones:
<img width="304" alt="Screen Shot 2020-01-31 at 09 02 01" src="https://user-images.githubusercontent.com/7577652/73549577-774a3300-4408-11ea-9229-03d9b88eddcd.png">

And if we take look at the body styles:
<img width="307" alt="Screen Shot 2020-01-31 at 09 02 17" src="https://user-images.githubusercontent.com/7577652/73549597-7fa26e00-4408-11ea-9042-1585fbe2067d.png">

They're not the same output as the ones you posted. 🤔

> Uh I see you mean the css custom properties should be at least defined 🤔
> yea my `body` looks like this
> 
> ```css
> body {
>     --theme-ui-colors-primary: #fff;
>     --theme-ui-colors-text: #fff;
>     --theme-ui-colors-background: #000;
>     --theme-ui-colors-secondary: #fff;
>     --theme-ui-colors-accent: #fff;
>     --theme-ui-colors-muted: hsla(0,0%,100%,0.75 ));
>     color: #fff;
>     background-color: #000;
> }
> ```

**Comment by jxnblk** [comment]
The custom properties are an implementation detail, which aren't provided when there are no color modes -- based on the example above, I don't see `theme.colors.modes` defined. Since this uses Emotion's theming context to provide the color values, the custom properties *shouldn't* be necessary -- not sure if that's the issue you're running into or not, but let me know if that doesn't make sense

**Comment by jean182** [comment]
Hmmm I think I understand, I believe we can close this, just wondering if I want to check all the design tokens for certain theme ui preset where I can find that for. To start using it with the sx prop?

**Comment by CanRau** [comment]
I usually "just" log the result of `useThemeUI` hook
```js
/** @jsx jsx */
import { jsx, useThemeUI } from 'theme-ui'

export default (props) => {
  const { theme } = useThemeUI()
  console.log(theme)
  return <h1>My website</h1>
}
```

**Comment by jean182** [comment]
Thanks for the help guys I appreciate it.
