### ISSUE TITLE
UI Library to Complement Theme-UI

### ISSUE THREAD

**Issue by moshemo** [system-ui/theme-ui#632]
Any recommendations for a good ui library that works well with theme-ui that provides components that are not included with theme-ui (such as modal popup windows, tabs, accordions, etc)?  In other words, a ui library that will provide the functionality needed while allowing theme-ui to take care of the styling?

**Comment by lachlanjc** [comment]
Afaik this doesn’t exist. I know Brent has used Reakit in places: https://reakit.io/

**Comment by jxnblk** [comment]
Part of the rationale of creating a theme specification was to enable component authors to create components like you describe, but as of today I do not think any exist

**Comment by moshemo** [comment]
I hear.

In the meantime, are there any recommendations of what to use until such a component library is built?  

For example, reakit or reach-ui (or something else)?

**Comment by jxnblk** [comment]
Reach UI is good, but Reakit is probably easier to use with a CSS-in-JS solution. There are also single-component packages like React Select, which could be used alongside Theme UI -- if you find anything that works really well, feel free to comment here or somewhere where it could potentially be added to a guide in the docs

**Comment by dowi** [comment]
Hi @moshemo , did you find a Modal component that works with Them-UI? Thanks!

**Comment by jxnblk** [comment]
Following up here, another *really* good library to look into for more complex UI components is [Adobe Spectrum](https://react-spectrum.adobe.com/react-aria/index.html)

**Comment by b-b0t** [comment]
@jxnblk what is the process for getting theme-ui working with spectrum? ie. using color modes from theme-ui but locale from spectrum.
