### ISSUE TITLE
TS Error: Property 'sx' does not exist on type 'HTMLAttributes' when using Preact

### ISSUE THREAD

**Issue by likidu** [system-ui/theme-ui#633]
**Describe the bug**
I am trying to use theme-ui with a Preact app with Typescript. When I am using the `sx` prop, there was Typescript error prompted in the editor.

**To Reproduce**

I am using VS Code with ESlint and Prettier extensions. A simple **button.tsx**:

```tsx
/** @jsx jsx*/
import { h } from "preact"
import { jsx } from "theme-ui"

type ButtonProps = {
  text: string
}

const Button: preact.FunctionalComponent<ButtonProps> = ({ text }) => (
  <div sx={{ m: 3 }}>
    <button type="button" tabIndex={0} >
      <p>{text}</p>
    </button>
  </div>
)

export default Button
```

The code can be compiled successfully with the right CSS applied to it. But it's with the VS Code, it shows the `sx` prop has error:

> Type '{ children: Element; sx: { m: number; }; }' is not assignable to type 'HTMLAttributes<HTMLDivElement>'.
> Property 'sx' does not exist on type 'HTMLAttributes<HTMLDivElement>'. .ts(2322)

And one more side effect here is I have set the pragma as `h` which is using the Preact. But to use `sx` from theme-ui, it requires to add `/** @jsx jsx */` at the beginning of the module which overlaps the Preact one. Then it also gives a warning:

> 'h' is defined but never used.eslint(@typescript-eslint/no-unused-vars)

**Expected behavior**
There should be none errors shown in the editor when using theme-ui with Preact in Typescript.

**Screenshots**
![image](https://user-images.githubusercontent.com/575981/73453222-800a1d00-43a6-11ea-9b31-b7bb0eb52dce.png)

**Additional context**
Npm package versions:
* `theme-ui`: 0.3.1
* `preact`: 10.0.0

**Comment by CanRau** [comment]
Not sure it already supports Preact 🤔 

> By default the Babel plugin will convert JSX into React.createElement, but libraries like Preact, MDX, Emotion, and Vuejs use custom create elements functions with JSX.

quote from [theme-ui.com/guides/jsx-pragma](https://theme-ui.com/guides/jsx-pragma)

**Comment by jxnblk** [comment]
Yes, this library is only intended for use with React and Preact may or may not work. You can use some of the underlying utilities that theme-ui is built with (like `@theme-ui/css`) if you want to use this outside of React

**Comment by hasparus** [comment]
@likidu You can alias `react` and `react-dom` to [`preact/compat` in your webpack config](https://preactjs.com/guide/v10/switching-to-preact/#setting-up-compat). Then, `React.createElement` that `jsx` function is using is actually `h` from Preact.

To let TypeScript know what `sx` prop is, you'd have to use [module augmentation](https://www.typescriptlang.org/docs/handbook/declaration-merging.html#module-augmentation). 
Take a look how _@types/theme-ui_ sets this up for React.
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/theme-ui/index.d.ts#L221-L231

I'd try declaration merging of `preact.PreactDOMAttributes`
https://github.com/preactjs/preact/blob/master/src/index.d.ts#L61-L66

something along these lines

```ts
/** @jsx jsx */
import { jsx, SxStyleProp } from 'theme-ui';

declare global {
  namespace preact {
    interface PreactDOMAttributes {
      sx: SxStyleProp
    }
  }
}
```

**Comment by lachlanjc** [comment]
@hasparus Can we close?
