### ISSUE TITLE
Custom Pragma Breaks Gesture-Based Animations in Chrome

### ISSUE THREAD

**Issue by medelman17** [system-ui/theme-ui#634]
**Describe the bug**
Importing theme-ui's `jsx` pragma causes gesture-based animations (e.g., sliders, etc) to no longer animate appropriately (or at all?) in Chrome; reverting to react's pragma (i.e., removing the custom jsx comment and importing react) resolves the issue without further intervention. This issue appears to be browser-specific--appears to work fine in Safari and Firefox. 🤷‍♂️  

I am using Chrome Version 79.0.3945.130 (Official Build) (64-bit) on macOS 10.15.3      

**To Reproduce**

1. Use Chrome
2. See this code [sandbox](https://codesandbox.io/s/tender-lewin-fbsok) or import/use the following component: 

```jsx
/** @jsx jsx */
import { jsx } from "theme-ui";
// import React from "react";
import { useSpring, animated } from "react-spring";
import { Heart } from "react-feather";
import { useGestureResponder } from "react-gesture-responder";

export function Slider({ children }) {
  const [{ x }, set] = useSpring(() => {
    return { x: 0 };
  });
  const { bind } = useGestureResponder({
    onStartShouldSet: () => true,
    onMove: state => {
      const [x] = state.delta;
      // We can see the event firing appropriately,
      // but nothing happens on the screen. If we remove
      // the custom pragma and do nothing else,
      // it works as expected.
      console.log(x);
      set({ x, immediate: true });
    },
    onRelease: state => {
      set({ x: 0, immediate: false });
    }
  });

  return (
    <div className="list-item">
      <div className="background">
        <Heart />
      </div>
      <animated.div
        {...bind}
        className="sliding-pane"
        style={{ transform: x.interpolate(x => `translateX(${x}px)`) }}
      >
        {children}
      </animated.div>
    </div>
  );
}

```

**Expected behavior**
Custom pragma should provide functionality at parity with react's pragma and/or more clearly document any limitations with respect to browser support.

**Comment by jxnblk** [comment]
The custom pragma *shouldn't* affect anything related to this. This codesandbox seems to be running really slowly in general on my computer, even without theme-ui's pragma -- have you noticed the issue in a non-codesandbox setup?

**Comment by medelman17** [comment]
Unfortunately, yes, I believe so... I was having the same problem yesterday in a Gatsby project. However, I didn't have a chance to confirm yet--going to take a look now and will update once I do.

**Comment by medelman17** [comment]
I'm, fairly certain I narrowed it down to a react-spring version difference--so weird though. Anyways, got it to work and sorry for wasting y'all's time. Closing this issue.
