### ISSUE TITLE
Dynamic Values and Variants

### ISSUE THREAD

**Issue by moshemo** [system-ui/theme-ui#638]
I have a variant that sets the width of an element.  I want the width value to be dynamic.  For example, it starts at 100%, but is set to 0 if someone clicks on a button.  

Here is a simplified version of the code as it currently stands:

```
// Variant:
const sidebar = {
  width: "100%",
}

// Component
<Sidebar open={isOpen} variant="sidebar">
 // Sidebar Content
</Sidebar>
<Button onClick={toggleOpen}>Toggle Sidebar</Button>
```

Is there a way for me to make the width value dynamic while still setting its value as a variant?  Can I do so inside the variant definition itself?

**Comment by CanRau** [comment]
How about 2 (or more) variants you swap on toggle?
As it's all JS almost everything should be possible yet I'd say the theme shouldn't really include business logic, I think it should be as static as possible and let others handle the logic.. 🤔

**Comment by jxnblk** [comment]
You can change the variant value as mentioned, but for dynamic behavior, you might want to consider using inline styles instead of CSS if possible
