### ISSUE TITLE
When using `useThemeUI`, the `theme` does not return default theme values

### ISSUE THREAD

**Issue by jordanoverbye** [system-ui/theme-ui#651]
I was speaking with @johno  about this as it's an issue with Blocks UI.

Lets say you have a super basic theme like this and you use that with `ThemeProvider`.

```js
const theme = {
  colors: {
    primary: 'red',
    secondary: 'blue',
  },
}

export const App = props => <ThemeProvider theme={theme}>{props.children}</Theme>
```

When you use the `useThemeUI` hook, it only returns the original theme. 

```js
export const ExampleComponent = props => {
  const { theme } = useThemeUI()
  // `theme` is the same object as above
}
```
This is kind of confusing, because it does not show the default values that get applied when using the `sx` prop like `spacing`, `fontSizes`, `fontWeights` etc.

## Expected behaviour:
The `theme` object returned from `useThemeUI` has all the default theme values merged.

**Comment by jxnblk** [comment]
This makes a ton of sense. I think only the `space` and `fontSizes` scales use default values and those are defined in `@theme-ui/css` if anyone wants to look into this -- potentially could be refactored to behave more like default values at the theme level

**Comment by hasparus** [comment]
Is this up for grabs? I just encountered this problem and it seems pretty straightforward so I'd rather contribute than workaround on my side.

**Comment by jxnblk** [comment]
@hasparus feel free to take a look into this -- if it ends up being a cross-package refactor, we'll probably want to make sure there we don't introduce any unintentional breaking changes FWIW
