### ISSUE TITLE
[gatsby-plugin] Transform `sx` prop without using JSX pragma

### ISSUE THREAD

**Issue by kripod** [system-ui/theme-ui#652]
**Is your feature request related to a problem? Please describe.**
The [`sx` prop](https://theme-ui.com/sx-prop) requires using a custom pragma like below:

```jsx
/** @jsx jsx */
import { jsx } from 'theme-ui'
```

**Describe the solution you'd like**
By using [https://babeljs.io/docs/en/babel-plugin-transform-react-jsx](babel-plugin-transform-react-jsx), the Theme UI's `jsx` function gets applied instead of `React.createElement`.

**Describe alternatives you've considered**
Suggest opting into using [https://babeljs.io/docs/en/babel-plugin-transform-react-jsx](babel-plugin-transform-react-jsx) in the docs.

**Comment by kripod** [comment]
Related: #227

**Comment by lachlanjc** [comment]
I’m cool with closing in favor of the Babel plugin idea, since that’s not framework-specific, which is tracked in #1234. @hasparus?

**Comment by lachlanjc** [comment]
Due to our new support for automatic runtimes, this is now supported! Docs here: https://github.com/system-ui/theme-ui/blob/master/packages/docs/src/pages/guides/jsx-pragma.mdx
