### ISSUE TITLE
[eslint-plugin] Warn about missing JSX pragma when using the `sx` prop

### ISSUE THREAD

**Issue by kripod** [system-ui/theme-ui#653]
**Is your feature request related to a problem? Please describe.**
When using the `sx` prop, the corresponding [JSX pragma](https://theme-ui.com/guides/jsx-pragma/) may be forgotten, resulting in missing styles.

**Describe the solution you'd like**
A separate ESLint plugin may detect the use of `sx` and warn about the missing lines below:

```jsx
/** @jsx jsx */

import { jsx } from 'theme-ui';
```

An auto-fix may also be provided.

**Comment by lachlanjc** [comment]
Personally I'd prefer to have the Babel plugin to make this a non-issue (#1234) & keep the current behavior than have an eslint plugin, but if you'd like to contribute this for folks who want it, go for it!

**Comment by hasparus** [comment]
> A separate ESLint plugin may detect the use of sx and warn about the missing lines below:

Components based on Box accept `sx` prop even without the pragma comment, and we can't forbid users to name their props `sx`. An ESLint plugin would need a list of "accepted components" or some TypeScript shenanigans to check if the `sx: ThemeUIStyleObject` is present in component props.

**Comment by lachlanjc** [comment]
Closing this since the new automatic runtime support handles it, which we’ll be documenting with #1335.
