### ISSUE TITLE
[Feature Request] Flex related style props on the Flex component

### ISSUE THREAD

**Issue by cour64** [system-ui/theme-ui#655]
Add Flex related styles props to the Flex component (similar to the Grid component) for a more terse syntax and better readability.

Props could include: 
| component prop | css prop | type |
|--|--|--|
| inline | display | bool |
| direction | flexDirection | string|
| wrap | flexWrap | string |
| justify | justifyContent | string |
| alignItems | alignItems | string |
| alignContent | alignContent | string |

Implementation is rather simple I'm guessing:
```javascript
const Flex = styled(Box)(props => ({
  display: props.inline ? 'inline-flex' : 'flex',
  flexWrap: props.wrap || 'nowrap',
  flexDirection: props.direction || 'row',
  justifyContent: props.justify || 'flex-start',
  alignItems: props.alignItems || 'stretch',
  alignContent: props.alignContent || 'stretch'
}))
```
Not sure if there is a specific reason that these style props aren't included? Anyway I could submit a PR if needed.

**Comment by jxnblk** [comment]
Thanks for the suggestion! This looks a lot like Reflexbox's original API, but generally speaking, I don't think it's a great idea to reinvent too many CSS property names via props. Everything listed above is already possible to achieve with the `sx` prop, which keeps a consistent API across all components and (IMO) reduces the overall API surface area

**Comment by cour64** [comment]
Yeah that's fully understandable. It's easy enough to create a thin wrapper over Flex that add's these props anyway. Thanks for the response and all the time and great work you've put into this library!
