### ISSUE TITLE
Responsive Values in theme get not applied

### ISSUE THREAD

**Issue by oschade** [system-ui/theme-ui#664]
**Describe the bug**
Responsive Values in theme get not applied

**To Reproduce**
1. Add this to your theme:

```
  sizes: {
    container: ['540px', '720px', '960px', '1140px'],
  },
```

2. Use Container Component of "theme-ui". The values of size.container will be all applied to the element, but not assigned to the any breakpoint.

**Comment by jxnblk** [comment]
Values in theme *scales* are not responsive. With the above, you can use e.g. `'container.0'` to use the first value. If you'd like to store partial styles in your theme and use responsive values, you can use [variants](https://theme-ui.com/guides/variants)

**Comment by oschade** [comment]
Thank you, this worked! But nevertheless an unexpected behaviour.
