### ISSUE TITLE
Support right-to-left directional styling

### ISSUE THREAD

**Issue by tesseralis** [system-ui/theme-ui#689]
**Is your feature request related to a problem? Please describe.**
In right-to-left (RTL) languages such as Arabic and Hebrew, the direction of the layout must be switched. Implementing this without a framework would lead to a lot of if-else statements and a lot of copied styles (for example, see the [reactjs.org Hebrew translation](https://github.com/reactjs/he.reactjs.org/pull/6/files).

**Describe the solution you'd like**
The ideal solution would be something akin to React Native Web's [I18nManager](https://necolas.github.io/react-native-web/docs/?path=/docs/apis-i18nmanager--layout-rtl). This feature allows users to define styles in a direction-agnostic manner, using `start` and `end` properties instead of `left` and `right`.

We would also need to provide a method for setting the direction, either using a `useDirection()` hook or determining the direction from the [current locale](https://github.com/system-ui/theme-ui/issues/688).

**Describe alternatives you've considered**
We may consider implementing these changes upstream in Emotion.

**Additional context**
Related: #688

**Comment by hasparus** [comment]
It's supported upstream by Emotion's CacheProvider and `stylis-rtl`.

https://github.com/emotion-js/emotion/issues/793#issuecomment-447994682

**Comment by lachlanjc** [comment]
Closing for now since you can use what @hasparus suggested or use custom themes such as https://github.com/system-ui/theme-ui/issues/688#issuecomment-739550249!
