### ISSUE TITLE
Add "Theme UI" Figma plugin to documentation

### ISSUE THREAD

**Issue by LekoArts** [system-ui/theme-ui#697]
I published https://github.com/LekoArts/figma-theme-ui and Jackson said that we should add that to the docs somewhere. Where could this go?

Preview of the plugin in Figma can be found here: https://www.figma.com/community/plugin/797015796747379907/Theme-UI

**Comment by jxnblk** [comment]
Love this plugin! And... that is a great question. 🤔 To start, it might make sense to have a page at `/packages/figma-plugin`, even if it's not technically a "package." Or, it could be at the top level as `/figma-plugin` -- Ideally I'd like plugins like this and things like a VS Code plugin (if that ever comes together) to be prominently featured in the getting started pages

If the README is published to npm (or maybe installed from GitHub), we should be able to import it as an MDX component for the docs page

**Comment by LekoArts** [comment]
> to be prominently featured in the getting started pages

That's awesome to hear! I have no strong opinion on where it should go, I'm happy with any solution.

> If the README is published to npm (or maybe installed from GitHub), we should be able to import it as an MDX component for the docs page

The package isn't published to npm so you'd need to source GitHub. I could update the README for that then as it currently isn't really describing the usage on Figma itself.

**Comment by lachlanjc** [comment]
Related: #751
