### ISSUE TITLE
Add support for pnp and yarn v2 (berry)

### ISSUE THREAD

**Issue by ghost** [system-ui/theme-ui#725]
**Is your feature request related to a problem? Please describe.**
Currently, theme-ui doesn't work with pnp/yarn berry because it doesn't list peer dependencies properly in multiple packages such as theme-provider and core. It also depends on emotion and mdx-js which have similar issues.

**Describe the solution you'd like**
Fix the peer dependencies by adding them to the suitable packages and ask dependencies to fix it as well.

**Describe alternatives you've considered**
[packageExtensions in .yamlrc.yml ](https://www.reddit.com/r/javascript/comments/f4r213/askjs_is_someone_using_yarn_v2_in_business/fht7emv/) but it gets out of hand and would be more helpful to just have the project fix it.

It would be good if someone can take it otherwise I will try to fix it and PR myself in a few days.

**Comment by sjmeverett** [comment]
I've created a new PR which attempts to fix this more correctly.

For extra info, the specific error message that is reported is:

`Module not found: @theme-ui/core tried to access react (a peer dependency) but it isn't provided by its ancestors; this makes the require call ambiguous and unsound.`

**Comment by lachlanjc** [comment]
Can we close this since #836 is merged @hasparus?
