### ISSUE TITLE
Add component type definitions to @types/theme-ui 

### ISSUE THREAD

**Issue by Muijf** [system-ui/theme-ui#728]
Type definitions for components are currently being installed under @types/theme-ui__components even though components get installed under @theme-ui/components.

**Comment by CanRau** [comment]
Are you facing issues with that? I thought that's expected naming convention as I have for example `@types/testing-library__dom` for `@testing-library/dom` and `@types/babel__core` for `@babel/core`

**Comment by Muijf** [comment]
Yup, it's not linking up for me. Deploying using Zeit NOW also gives the same error.

**Comment by mxstbr** [comment]
`@types/theme-ui__components` is just DefinitelyTyped's naming convention for scoped packages. There is nothing we can do to change that.
