### ISSUE TITLE
Default theme problems

### ISSUE THREAD

**Issue by AndrewPrifer** [system-ui/theme-ui#729]
I'm not sure all this qualify as bugs, however I was a little confused by the way the default theme is applied.

- It doesn't seem to be documented anywhere that a default theme is applied
- I couldn't find anywhere what the default theme is
- useThemeUI only returns my theme, not the default values that are merged in somewhere deeper
- Some choices seem a little baffling for a default theme, e.g. the purple background color set on the body

Personally I don't think theme-ui should apply a default theme at all, especially since applying a pre-made theme manually is as easy as importing a theme from @theme-ui/presets and merging it. I don't want to have to define things in my theme just to reset default values. Having to include CSS resets is bad enough already.

**Comment by jxnblk** [comment]
The colors are not part of a default theme, but rather built-in browser color keywords, see https://www.w3.org/TR/2018/REC-css-color-3-20180619/#css2-system

The only default values provided by Theme UI are `breakpoints`, `space`, and `fontSizes`

**Comment by AndrewPrifer** [comment]
@jxnblk I see now that when using ThemeProvider, `background-color: background` is set on the body element. Why is this necessary even if the color itself is a built-in browser keyword? This requires me to add

```js
  styles: {
    root: {
      bg: 'unset'
    }
  }
```

to my theme just to get rid of the purple background color, browser defined or not. Are there other instance where theme-ui sets browser builtin values? Maybe I'm missing a bigger picture here, is there a specific reason this is done?

**Comment by jxnblk** [comment]
You can set `useBodyStyles: false` to disable the default behavior, see https://theme-ui.com/theming#configuration-flags

**Comment by AndrewPrifer** [comment]
@jxnblk sorry for the nitpicking, at this point my specific issue is solved for now, however what if I do want to specify root styles? Using `useBodyStyles: false` would also disable root styles set in my theme, not just the default body styles like the above mentioned `background-color: background`. Then I would again have no option but to specifically reset the background color.

I guess what I'm getting at is, does setting these browser builtin values (or even `fontSizes` and the rest) have any justifiable purpose? I get that theme-ui is meant to be more opinionated than styled-system but setting certain styles by default that you specifically have to disable is a step too far in my opinion and just increases the learning curve and initial setup.

**Comment by jxnblk** [comment]
You'll generally want some styles applied to the `<body>` element in any application. Theme UI has a way to do that and also a way to disable that if you don't want that handled with the library. It sounds like the original issue is resolved, so closing this out

**Comment by AndrewPrifer** [comment]
Thanks for the help @jxnblk! Didn't mean to drag this out, I was just curious about the purpose of `background-color: background`. ;)

**Comment by knowler** [comment]
I had this same problem when I accidentally mis-typed the `theme.colors` property’s key as singular, `color`. I thought I’d leave this here in case anyone else makes the same mistake.
