### ISSUE TITLE
Responsive styles using objects

### ISSUE THREAD

**Issue by rafaelderolez** [system-ui/theme-ui#73]
Does theme-ui support responsive styles using objects, [as in styled-system](https://styled-system.com/responsive-styles/#using-objects)? Or are you moving away from this approach?

### Theme UI
```
<div
  css={css({
    width: [ '100%', '50%', '25%' ],
  })}
/>
```

### Styled System 
```
<div
  width={{ _: '100%', sm: '100%', md: '50%', lg: '25%' }}
/>
```

**Comment by jxnblk** [comment]
[Styled System CSS](https://styled-system.com/css/) does not support this because it'd be difficult/require more code to check whether a nested array was a nested style or meant to be a single property. E.g.
```
{
  ':hover': {
    color: 'primary',
  },
  width: {
    someBreakpoint: '100%',
    anotherBreakpoint: '50%',
  },
  '@media screen and (min-width: 64em)': {
    width: '25%'
  }
}
```

If you want to use objects, use the standard media query syntax

**Comment by rafaelderolez** [comment]
Got it, thanks!
