### ISSUE TITLE
Styleguide generator

### ISSUE THREAD

**Issue by flaviolivolsi** [system-ui/theme-ui#732]
It would be very useful to have a way to generate a styleguide based on Theme UI specification. As far as you know, is there anything that accomplishes that?

Feel free to close the issue if it doesn't belong here.

Thanks!

**Comment by flaviolivolsi** [comment]
I [found it](https://theme-ui.com/packages/style-guide/) :) closing the issue.

**Comment by LekoArts** [comment]
There’s also this:
https://github.com/LekoArts/gatsby-themes/blob/master/themes/gatsby-theme-styleguide/README.md
