### ISSUE TITLE
Gutenberg <style data-emotion="css"> created multiple times

### ISSUE THREAD

**Issue by quadlayers** [system-ui/theme-ui#734]
**Describe the bug**
Hello guys
We're trying to integrate with a Gutenberg blocks
Every time we change the value of the color in the theme, the style tag is recreated again and again

**To Reproduce**
1. Create Gutenberg block
2. Add sx property to div
3. Wrap block inside <div sc={}>
4. Change the value of the color

**Expected behavior**
We expect the same behavior of your theme, class doesn't change and <style data-emotion="css"> is not recreated on each change

**Video**
https://www.loom.com/share/b2b6870a12e643d6b584e6ba63712a54

**Code**
container.js
```
/** @jsx jsx */
import { jsx } from 'theme-ui'

export default props => (
  <div
    {...props}
    sx={{
      color: 'text',
    }}
  >
  {props.children}
  </div>
)
```
block-edit.js

 ```
<Fragment>
        <ThemeProvider theme={theme}>
          <Container className={'wp-wowmall-block ' + className}>
            <BlockEdit { ...props } />
          </Container>
        </ThemeProvider>
      </Fragment>
```

**Comment by quadlayers** [comment]
this is the entire block code
as you can see the theme is updated trough the withSelect function
thanks in advane

`/**
 * External dependencies
 */

import classnames from 'classnames';
import { ThemeProvider } from 'theme-ui';

/**
 * WordPress dependencies
 */

import { __ } from '@wordpress/i18n';
import { Component, Fragment } from '@wordpress/element';
import { InnerBlocks } from '@wordpress/block-editor';
import { compose } from '@wordpress/compose';
import { withSelect } from '@wordpress/data';

import Container from '../../theme/css/container';
import theme from '../../theme/theme';

class View extends Component {

  constructor(props) {
    super(...arguments);
  }

  render() {
    const {attributes} = this.props;
    
        const currentTheme = {
      ...theme,
      ...this.props.preferences
    }
    
    return [
      <Fragment key='view'>
        <ThemeProvider theme={currentTheme}>
          <Container className={'wp-test-block ' + this.props.className}>
            <div className='wrapper-inner'>
              <div className='wrapper-inner-blocks wp-block'>
                <InnerBlocks
                  templateLock={ attributes.templateLock }
                  renderAppender={ () => (
                        <InnerBlocks.ButtonBlockAppender />
                  ) }
                  />
              </div>
            </div>
          </Container>
        </ThemeProvider>
      </Fragment>
    ];
  }
}

export default compose( [
	withSelect( ( select ) => {
          const {
            getPreferences
          } = select('test-store');

          return {
            preferences: getPreferences(),
          };
	} ),
] )( View );`

**Comment by jxnblk** [comment]
I suspect this has more to do with how Emotion works than anything specific in this library -- I'm also not sure if there would be any significant performance issues with this happening. Are you seeing this in development or production?

**Comment by quadlayers** [comment]
hello @jxnblk 
thanks for your prompt response
correct im in development mode
i've compiled scripts in production mode and the issue has gone
do you have any idea why this happen in development mode?
kind regards

**Comment by jxnblk** [comment]
I suspect this is an optimization that Emotion does. Since it's an abstraction, I think you can ignore this unless it becomes noticeably "leaky"

**Comment by quadlayers** [comment]
Great! there is no difference in performance

Do you have an idea of how to access the whole CSS generated by Emotion? 

We need to convert this in a CSS file and save it to use in frontend

Thanks in advance, this project has saved us hours of development :)

**Comment by jxnblk** [comment]
Haven't tried doing that recently, but you can dig into Emotion's API. I'd start looking here: https://emotion.sh/docs/ssr -- also note that Emotion v11 is coming soon and I'd guess that some of the advanced API might change soon

**Comment by quadlayers** [comment]
great thanks @jxnblk 

keep up with this amazing library
