### ISSUE TITLE
Support variant props?

### ISSUE THREAD

**Issue by devdigital** [system-ui/theme-ui#735]
I have an issue where a Theme UI component is styled differently depending on the component props. I would like the user to be able to override the styling centrally via the theme object, but they don't have access to the props to make styling decisions.

For example, if there is a `Message` component that changes border color based on the `type` of the message (`error`, `info` etc):

```jsx
const Message = ({ message, type }) =>
  <Box 
    __css={{ 
      borderColor: type === 'error' ? '#f00' : '#ccc' 
    }}
    variant='message'
  >...</Box>
```

If the user specifies a variant border color, they lose the dynamic behaviour:

```javascript
message: {
   borderColor: '#ddd'
}
```

Would it be possible to pass props to variants to allow users to make theme decisions?

E.g:

```jsx
<Box 
    __css={{ 
      borderColor: type === 'error' ? '#f00' : '#ccc' 
    }}
    variant={['message', { type }]}
  />
```

and the theme:

```javascript
message: {
   borderColor: ({ type }) => type === 'error' ? '#f55d42' : '#ddd'
}
```

Alternatively, in the component:

```javascript
variant={{
   name: 'message',
   props: { type }
}}
```

**Comment by jxnblk** [comment]
The intent with the theme object is to be JSON serializable, and although you can use functional values in variants for access to the theme itself, we don't plan on handling props-based logic in the theme. Generally speaking, any props-based conditions should happen in the component, and you should be able to wrap the built-in components with custom components if you want to use custom props APIs.

With your example above, I'd imagine you can remap the `type` prop (which is also an HTML attribute, and might be overloaded) to the `variant` prop like so:

```jsx
const Message = ({ type, ...props }) =>
  <ThemeUIMessage {...props} variant={type} />
```

**Comment by devdigital** [comment]
Thanks, that was just a (bad) example. I suppose for simple cases this approach would work, but as the variants based on number of props increases, that could end up as a lot of variant combinations on the theme object. But thanks, I'll use the prop to name mapping approach for now.

**Comment by lachlanjc** [comment]
@hasparus Looks like we can close this
