### ISSUE TITLE
Nest scales and variants like styles in the theme object

### ISSUE THREAD

**Issue by bearror** [system-ui/theme-ui#736]
**Is your feature request related to a problem? Please describe.**
The [documentation](https://theme-ui.com/theme-spec#theme-scales) suggests that additional scales can be present in the `theme` object in addition to the various `variant` properties.
>A theme does not require that all these fields be present and can include additional values as needed.

With both kinds of user-created properties being in the object root, it is not obvious if, say, `pageTransitions` is a variant or a scale. To my understanding, an index type for the `Theme` would also have to be permissive enough for scales, variants, styles, and all of the configuration flags.

**Describe the solution you'd like**
With the `styles` property being already nested - and with `scales`, `variants`, and `styles` being the three primary kinds of data in the theme - _I propose that both `scales` and `variants` be nested as well._

```ts
const theme: Theme = {
  useCustomProperties,
  // Rest of the configuration flags
  scales: {
    breakpoints,
    // Rest of the scales
  },
  variants: {
    alerts,
    // Rest of the variants
  },
  styles: {
    a,
    // Rest of the styles
  }
}
```
I believe that introducing a clear structural separation between the various types would make future life easier.

**Describe alternatives you've considered**
In user-land, I'm currently explicitly defining all of the `VariantGroups`, such as `theme.alerts.*`.

```ts
export interface VariantGroup {
  [key: string]: SxStyleProp; // Potentially `SystemStyleObject` instead
}

interface VariantGroups {
  // Would like to use `[key: string]: VariantGroup;`
  alerts?: VariantGroup;
  badges?: VariantGroup;
  // Rest of Theme-UI & user-defined variants
}

// Resolve collisions with `Theme`, namely the `theme.buttons` scale
type Override<T, R> = Omit<T, keyof R> & R;
type ThemeWithVariantGroups = Override<Theme, VariantGroups>;
```

**Additional context**
This would be a breaking change, since accessing `theme.${variant}` and `theme.${scale}` would change to `theme.variant.${variant}` and `theme.scale.${scale}`.

**Comment by jxnblk** [comment]
Thanks for the suggestion. Since there are already a lot of theme objects in userland that use this flatter data structure, I don't think we would add additional nesting in the near future. With the conversion to TypeScript, I imagine this will be less of an issue in the future. If you want to nest your variants in an object named `variants` or similar, you can do that with the current implementation

**Comment by bearror** [comment]
Fair points. Constructing the theme from a custom structure works as well - and is more flexible, I suppose. For that to work well, it'd be helpful to have direct access to the types of the individual kinds of properties one might add to the theme.

As an example, my current user-land solution uses the above mentioned `VariantGroup` interface so that the various kinds of `variant`s can be defined in individual files without losing type information.
```ts
// theme/variants/buttons.ts
export const buttons: VariantGroup = {
  primary: {}
}
```

**Comment by jxnblk** [comment]
We're working on converting the code base to TS, which will include more interfaces in the next version
