### ISSUE TITLE
Are CSS template literal strings supported?

### ISSUE THREAD

**Issue by saikatdas0790** [system-ui/theme-ui#738]
**Is your feature request related to a problem? Please describe.**
I have a codebase that I'm currently migrating to theme-ui from Emotion due to the extra niceties that theme-ui provides. However, my current codebase uses the Emotion css template literal string syntax shown [here](https://emotion.sh/docs/introduction#react) and [here](https://emotion.sh/docs/css-prop#string-styles). I am really struggling to figure out if this can be made to work with theme-ui's styling systems (`sx` and `css` props)

**Describe the solution you'd like**
I can pass the template literal string of css styles to a prop or a utility function that an existing prop can consume

**Describe alternatives you've considered**
I've tried to use the css import from "theme-ui" without luck like this

```javascript
import { css } from "theme-ui";
```
and then in my code as in the emotion docs

**Additional context**
None

**Comment by jxnblk** [comment]
Currently only object syntax is supported in Theme UI due to the implementation. You can probably find something to convert CSS strings into objects, but note that the Theme UI `css` function **is not** the same as Emotion's `css` utility

**Comment by lachlanjc** [comment]
> You can probably find something to convert CSS strings into objects

https://github.com/jxnblk/css-to-object :)
