### ISSUE TITLE
Pass through of data- & aria- attributes

### ISSUE THREAD

**Issue by domtronn** [system-ui/theme-ui#739]
**Describe the bug**
When rendering components using Theme UIs `jsx` pragma, I don't see `data-` & `aria-` attributes appear in the DOM.

**To Reproduce**
```jsx
/** @jsx jsx */

export default () => (
  <div data-my-id="1234">
    Hello!
  </div>
)
```
**Expected behavior**
I would expect the above example to render the data attribute `data-my-id` in the resulting DOM. React has always supported `aria` & `data` attributes, as documented [here](https://reactjs.org/docs/dom-elements.html).

React 16 also now supports arbitrary pass through of attributes to the DOM as documented [here](https://reactjs.org/blog/2017/09/08/dom-attributes-in-react-16.html)

**Comment by jonavila** [comment]
@domtronn Seems to work fine here: https://codesandbox.io/s/heuristic-fermi-6d9xk

Can you reproduce in a Sandbox?

**Comment by domtronn** [comment]
Thanks for the quick response... I've done a little more investigation and seem to understand what's causing it.

It's since I'm adding the data attributes on component library components, but they won't attach them with explicitly spreading the props onto the child, i.e.

```jsx
/** @jsx jsx */
import { jsx } from "theme-ui";
import "./styles.css";

const Intro = () => (
  <div className="App">
    <h1>Hello CodeSandbox</h1>
    <h2>Start editing to see some magic happen!</h2>
  </div>
)

export default function App() {
  return (
    <Intro data-my-id='123232' />
  )
}
```

Closing as this isn't an issue with `theme-ui` but the component library I'm using 😄 apologies for the issue.
