### ISSUE TITLE
Update CI badge in README.md and website

### ISSUE THREAD

**Issue by jxnblk** [system-ui/theme-ui#753]
**Is your feature request related to a problem? Please describe.**

Currently, the README and site show a Circle CI badge, but we're now using GH actions.

**Describe the solution you'd like**

The badge should be updated

**Comment by hasparus** [comment]
hey I'm not sure if the badge is correct. I only see "pending".
The official one from GitHub ![](https://github.com/system-ui/theme-ui/workflows/CI/badge.svg) isn't flat, so it would probably require removing "flat." from the rest of them, but it displays a correct status :D
