### ISSUE TITLE
Low precision TypeScript error in SystemStyleObject

### ISSUE THREAD

**Issue by hasparus** [system-ui/theme-ui#764]
**Describe the bug**

The error for incorrect SystemStyleObject is wonky.
This will need some work on typings. Not sure how to fix it yet.

I'll work on it next weekend if nobody picks this up faster.

To be clear, I am not reporting that `size` is missing. This is an easy problem to fix.
My beef is with this error message, which deems entire object to be incorrect, while it's not.

**To Reproduce**
1. `size` property is not  is not supported (in typings)
2. We add `size`.
3. Entire object becomes burning red.

**Expected behavior**
Expected: The error is local to the `size` property.

**Screenshots**
![theme-ui](https://user-images.githubusercontent.com/15332326/76743148-7714b580-6772-11ea-8ed2-0c6b5e52c45d.gif)

**Notes**
`SystemStyleObject` name is inherited from `styled-system`. Should it be renamed to something more user-friendly before next release?

**Comment by jxnblk** [comment]
I don't know if I have any insight for the core issue here, but would it make sense to name the type `SxStyle`? If there are still any dependencies on the `styled-system` library, we should move away from that as well, since the library is not written in TypeScript

**Comment by hasparus** [comment]
I fixed the missing `size` thing in https://github.com/system-ui/theme-ui/pull/765.

**Comment by hasparus** [comment]
Thanks for the issue @hasparus.
I think @hasparus has already fixed this problem in #1002. You can read more about it in https://github.com/system-ui/theme-ui/pull/1002#discussion_r439948001.

Let's close.
