### ISSUE TITLE
Theme color for caretColor on input element not resolved properly

### ISSUE THREAD

**Issue by henrikland** [system-ui/theme-ui#775]
**Describe the bug**
Setting the `caretColor` prop on an input element to a color defined in `theme.colors` renders broken CSS.

**To Reproduce**
1. Define some color in your theme, for example `accent: "#FF0000"`.
2. Set the `caretColor` prop to `"accent"` on an input:
```<input sx={{ caretColor: "accent" }}>...</input>```
3. Rendered CSS will be `caret-color: accent`.

**Expected behavior**
Expected rendered CSS to be `caret-color: #FF0000`.

**Comment by jxnblk** [comment]
This property is not currently mapped to the `theme.colors` scale -- in the meantime, you can use [functional values](https://theme-ui.com/sx-prop#functional-values)

**Comment by lachlanjc** [comment]
https://github.com/system-ui/theme-ui/pull/780 will close this issue :)
