### ISSUE TITLE
Ways to inherit styles from root object to theme.styles

### ISSUE THREAD

**Issue by pmarsceill** [system-ui/theme-ui#776]
**Is your feature request related to a problem? Please describe.**
I have all of my default styling for things like `<a>` and `<code>` that I want consistently styled across my site. I define them in my `root` object. Unfortunately this gets ignored by content that gets styled by `theme.styles` and forces me to define the same styles twice... once in the `root` object and once in the actual theme.

**Describe the solution you'd like**
Some way to inherit these from `root` -> `theme` or vice versa.

**Describe alternatives you've considered**
Defining them twice, which isn't good.

**Comment by lachlanjc** [comment]
Since Theme UI discourages using child selectors, making this harder is partly purposeful I believe (might be wrong here).

In the meantime, if you’d like to not duplicate the code, you could also use a line of JS after creating your theme to push non-root styles into `theme.styles.root`.

**Comment by jxnblk** [comment]
If you're defining styles in `theme.styles`, you can use that as a *variant* for a wrapping component for non-MDX content, e.g. `<div sx={{ variant: 'theme.styles' }} />` -- would that work in your case?

**Comment by pmarsceill** [comment]
> If you're defining styles in `theme.styles`, you can use that as a *variant* for a wrapping component for non-MDX content, e.g. `<div sx={{ variant: 'theme.styles' }} />` -- would that work in your case?

I think so, let me give it a whirl.
