### ISSUE TITLE
Reduce bundle size?

### ISSUE THREAD

**Issue by dburles** [system-ui/theme-ui#783]
Since `0.3.0` there's been a [jump in the bundle size](https://bundlephobia.com/result?p=theme-ui@0.3.1). Note that a chunk of it can be ignored due to the addition of the `@emotion/core` dependency. I feel like the library at its core could be kept minimal and fundamentally about the theme and `sx` prop relationship. `@theme-ui/components` seems like an obvious one to keep stand-alone, however lately it seems it's now part of `theme-ui` which has definitely also added to the size of the bundle.

**Comment by jxnblk** [comment]
1. The `theme-ui` package is meant to be the "batteries-included" version
2. It *should* support tree-shaking -- i.e. if you're not using the components, they shouldn't be included in the final bundle (but knowing how tree-shaking works in practice YMMV)
3. The `@theme-ui/core` package can be used if you want the `sx` prop without components or MDX

**Comment by dburles** [comment]
> 3. The `@theme-ui/core` package can be used if you want the `sx` prop without components or MDX
I didn't know that you could use it that way, that would solve the concern with the bigger install size of the main package. Do you think it would be worth documenting? Perhaps it can just be added to the Packages section along with a note and link somewhere in Getting Started.

**Comment by jxnblk** [comment]
Yeah, this could definitely use better documentation -- I think starting with the packages README.md would be a good place

**Comment by dburles** [comment]
If we recommend this officially, do you see any potential issues down the line in then having to support users who have chosen to install this way?

**Comment by jxnblk** [comment]
I think any of the packages available will follow semver and should be safe to use their public APIs. The core package was split off based on dependencies, and I don't imagine there will be a ton of breaking changes there

**Comment by lachlanjc** [comment]
We have several ideas for reducing bundle size & active plans in this area, so I’m going to close this for now since we don’t have a specific objective in this issue
