### ISSUE TITLE
Nested ThemeProvider and color mode switching

### ISSUE THREAD

**Issue by ehowey** [system-ui/theme-ui#798]
**Describe the bug**
I believe this may be a known issue from the reading I have done on nested ThemeProviders. I just wanted to double check that this is not something I am doing wrong on my end.

I am trying to nest ThemeProviders in a Gatsby Theme. I am dynamically creating the theme specification JSON from SANITY.io, basically allowing users to configure and change colors in their site using the CMS. I can get this working for colors but not for switching color modes. I have tried putting the ThemeProvider in gatsby-browser/ssr, I have tried wrapping a page-template with the ThemeProvider, and I have tried shadowing the Layout component and nesting it inside of there. 

Is there a pattern or way to nest theme providers and have dark mode work or should I just stop trying to get this to work and move on?  It is already pretty cool to change colors via SANITY.io anyways.

**Expected behavior**
Color Mode switching works with nested ThemeProviders.

**Comment by jxnblk** [comment]
I might not understand the question fully, but color modes *only* work in the top-level `ThemeProvider`. If you have color modes defined there, the nested Theme Providers should pick up colors from the currently selected color mode. There isn't a built-in way to change color modes in the nested ThemeProviders independently.

You *might* be able to use the separate packages [`@theme-ui/color-modes`](https://github.com/system-ui/theme-ui/tree/master/packages/color-modes) and [`@theme-ui/core`](https://github.com/system-ui/theme-ui/tree/master/packages/core) to handle color modes in nested Theme Providers, but I haven't tried this out.

Let me know if that doesn't answer your question

**Comment by ehowey** [comment]
Yep - That is what I just wanted to confirm.  I was banging my head trying to get it working, and gave up for now. It is okay though, more technical users can just do the theme in JSON and dark mode will work.  I wanted to enable some ability to customize the theme via SANITY.io. Thanks Jackson!  Closing this issue.
