### ISSUE TITLE
Support all HTML elements including span

### ISSUE THREAD

**Issue by jeffscottward** [system-ui/theme-ui#799]
**Is your feature request related to a problem? Please describe.**
I discovered there is no `span` element available in the Styles object
See https://theme-ui.com/theme-spec#styles

**Describe the solution you'd like**
I should be able to semantically write my code yet retain extensibility of ThemeUI

**Describe alternatives you've considered**
None, it is absolutely crazy I can't use a `<Styled.span>` element of all things. 
It's the perfect thing to throw typographic variants into.

**Additional context**
Why are there so few things you can put in the `styles` object?

**Comment by jxnblk** [comment]
The `theme.styles` object is only intended for markdown content and markdown syntax does not include a `span` element. You can use `<span sx={styles} />` outside of MDX content if needed. Hope that makes sense!

Also note that the `span` element is for content without semantic meaning, from the spec:

> The span element doesn't mean anything on its own
