### ISSUE TITLE
Use default theme when ThemeProvider isn't included in the tree

### ISSUE THREAD

**Issue by mlynam** [system-ui/theme-ui#801]
**Describe the bug**
When using testing a component that uses `useThemeUI` the them object is initialized to null.

**To Reproduce**
1. Unit test a component that uses the `useThemeUI` hook.

**Expected behavior**
Without a ThemeProvider in the tree, the theme object returned from `useThemeUI` should return a default that includes expected properties so we don't need to use a ThemeProvider for every test.

**Comment by flo-sch** [comment]
Wouldn't that be anti-pattern with how theme-ui works?

Not sure which test runner you are using, but with jest, you can easily add a "wrapper" to provide a theme for your unit tests (ideally the same theme that you use in your app)

It is even illustrated the official documentation from testing-library (if that is the one you are using):
https://testing-library.com/docs/react-testing-library/setup

Most of the test runners and utilities out there allow for wrapping components ;)

**Comment by jxnblk** [comment]
I'm guessing this is related to the notion of a "default theme", which might be removed in v1: related #832

**Comment by lachlanjc** [comment]
I think the direction we’re moving in (as Brent mentioned) is away from having a default theme & this isn’t something we’re planning to support.

@hasparus close?

**Comment by mlynam** [comment]
Understood.
