### ISSUE TITLE
no body fonts changes

### ISSUE THREAD

**Issue by george-norris-salesforce** [system-ui/theme-ui#838]
```
fonts: {
    heading: '"Courier",
    body: '"Courier"
  },
```

Headers are `Courier`
Body is not`Courier`

**Comment by dburles** [comment]
You just need to add it to the root object in the theme https://theme-ui.com/theming#body-styles

**Comment by amcc** [comment]
This is from that page, linked in @dburles comment above:
```
styles: {
    root: {
      // uses the theme values provided
      fontFamily: "body",
      fontWeight: "body",
    },
  },
```

This got me too - perhaps explaining why some values automatically get added to the body and the why the fonts don't should be in the documentation, Including on the Gatsby site: https://www.gatsbyjs.org/docs/theme-ui/

Looking at the page on theming it seems that the base for theme-ui uses the above theme.styles.root to already set font-family and other styles, but not things like background colour. Out of the box this made me a quite confused!

**Comment by george-norris-salesforce** [comment]
Thanks!
