### ISSUE TITLE
Restrictive color type in Theme

### ISSUE THREAD

**Issue by robphoenix** [system-ui/theme-ui#849]
**Is your feature request related to a problem? Please describe.**

Currently the `color.primary` field in the `Theme` object expects only a string. I currently use a series of color scales inside my colors object so can access any one on a range as so `primary.n`, so get a warning when typing my theme object. This restriction is only on *text/background/primary/secondary/muted/accent*, so my other scales, warning/info etc., don't throw any warning.

**Describe the solution you'd like**
Would it be possible to also accept an array of strings?

**Describe alternatives you've considered**

I can add another object to the colors object, ie.

```
 {
  ...
  colors: {
    scales: {
      primary: [
        '#ff5722',
        ...
      ]
    }
  }
}
```

I prefer being able to reference `primary.5` than `scales.primary.5`. 

**Additional context**

![image](https://user-images.githubusercontent.com/9257284/79460570-eb9a7880-7fec-11ea-83ab-0c53adb4a52e.png)

I'm happy to open a PR for this. The code is here I believe - https://github.com/system-ui/theme-ui/blob/master/packages/css/src/types.ts#L491-L494

**Comment by dburles** [comment]
The intent behind these specially named colour keys is interoperability between themes, so they're intentionally restricted to single colours. (See https://theme-ui.com/theming#colors). Like you're doing I'd just use an alternate name, I think the scales object is fine if you wish to retain the `primary` name.

**Comment by robphoenix** [comment]
Ok, no worries, thanks @dburles 👍

**Comment by jxnblk** [comment]
FWIW, when the conversion to TypeScript is complete, you should be able to either opt-in to using a stricter, interoperable theme interface or create your own custom typings and interface for your theme shape
