### ISSUE TITLE
Add a palette key to the colors object types

### ISSUE THREAD

**Issue by robphoenix** [system-ui/theme-ui#852]
**Is your feature request related to a problem? Please describe.**
As described in this issue #849 I have a series of colour ranges in my theme. The `colors.primary` key is essentially reserved for theme interoperability, so a primary colour scale will have to be nested in the colors object. I've opted for `colors.palette`, and wondered if there was value in having a typed key for colour palettes in the same way there is for individual colours? 

I realise for most use cases it's easy enough to just have colour ranges in the top-level `colors` object, though I can think of situations where one may want to access a primary range, rather than specific colours, and be able to change that range based on a theme.

Say a button component:

```js
<Box
  as='button'
  sx={{
    color: 'palette.primary.4',
    ':hover': {
      'palette.primary.5'
    },
    ':active': {
      'palette.primary.6',
    }
  }
/>
```

**Describe the solution you'd like**

```typescript
/**
   * Define the colors that are available through this theme
   */
  colors?: ColorMode & {
    /**
     * Nested color modes can provide overrides when used in conjunction with
     * `Theme.initialColorModeName and `useColorMode()`
     */
    modes?: {
      [k: string]: ColorMode
    }

  /**
     * Nested color palettes can provide color scales
     */
    palette?: {
      [k: string]: ObjectOrArray<CSS.ColorProperty>
    }
  }
```

**Describe alternatives you've considered**
I can extend the Theme interface in my own code.

```typescript
import { Theme, ColorMode } from 'theme-ui'
import * as CSS from 'csstype'

interface MyTheme extends Theme {
  colors: ColorMode & {
    palette?: {
      [k: string]: CSS.ColorProperty[]
    }
  }
}
```

**Comment by TheFirstMe** [comment]
This could also benefit #819. Material UI uses this specification for their color palette's primary.

**Comment by jxnblk** [comment]
You should be able to create whatever theme interface you want with TypeScript. Since the current version of the library is written in JavaScript, some of the typings might not be accurate. `theme.colors.primary` isn't so much a "reserved" key as it is a convention for interoperability

**Comment by robphoenix** [comment]
Grand, thanks @jxnblk I figured as much.

> a convention for interoperability

I'll close this, but as an aside, are there discussions to introduce any other conventions?
