### ISSUE TITLE
Feature: Responsive styles whitelist mobile

### ISSUE THREAD

**Issue by lekterable** [system-ui/theme-ui#856]
**Is your feature request related to a problem? Please describe.**
I wish I could just whitelist mobile instead of blacklisting the rest of the devices while I use the responsive prop.

**Describe the solution you'd like**
If we would explicitly pass just one argument to the array of responsive styles it would mean that we want to apply this value only to the smallest breakpoint, eg:
we got 3 breakpoints [mobile, tablet, PC] and we want to display hamburger menu only for mobile, instead of doing 
```
display: ["block", "none", "none"]
```
we could do:
```
display: ["block"]
```
in the CSS media queries, the equivalent would be using:
```
@media only screen and (max-width: <mobile>)
```

Let me know what you think :)

**Comment by IAmNatch** [comment]
Breakpoints based on screen size are important to a lot of dev and design process across a lot of organizations. For example differentiating between 13" layouts and 27" layouts.

**Comment by lekterable** [comment]
Thanks for the comment @IAmNatch , but I don't think you understand what I'm proposing. I'm definitely not trying to get rid of "breakpoints based on screen size", my suggestion is to add an API which would let us apply styles specifically to the smallest breakpoint, not to the smallest and all of the above as it is currently.

**Comment by IAmNatch** [comment]
I see! It’s essentially reversing “min” to a “max” when generating the breakpoints. 

If you wanted this right away I’m sure you could fork theme-ui and change the single line of code that creates the query.

**Comment by lekterable** [comment]
@IAmNatch yes, that's exactly that! :) I'm not in a hurry tbh, just seemed like a cool feature especially that most of the theme-ui's API looks very opinionated. Thanks for the tip tho! ;)

**Comment by jxnblk** [comment]
Generally speaking the responsive array is meant to be "mobile first" (see https://styled-system.com/guides/array-props for some background). You might find the [`@theme-ui/match-media`](https://theme-ui.com/packages/match-media) package to be a better fit for conditionally showing and hiding elements based on viewport width. I'd be open for more hooks-based APIs to explore your use-case, but I don't think it would be a good idea to overload the responsive array values with `max-width` media queries

**Comment by lekterable** [comment]
@jxnblk totally understand, it just felt really handy for those situations where a css should be applied ONLY to mobile e.g. hamburger menu or a mobile-specific height which takes into account the google chrome's bottom tab + it was not a breaking change as this api was not used before. thanks for the reply :)

**Comment by lachlanjc** [comment]
Some way to do this would be super cool, but personally this solution strikes me as very confusing to debug/read & would definitely cause breaking changes that were hard to find. I’d love to make max-width media queries easier to use in Theme UI sometime though, as when making a totally different UI on mobile they are quite handy even if [mobile-first CSS](http://mrmrs.cc/writing/mobile-first-css/) is generally the best.

**Comment by lachlanjc** [comment]
Closing since we’re not planning to implement.
