### ISSUE TITLE
Global styles

### ISSUE THREAD

**Issue by nkrmr** [system-ui/theme-ui#857]
Hi, I would like to know if @emotion/core are now dependencies of theme-ui how I can use Global component to set global styles? 
Actually, in the doc, to make it work I have to load @emotion/core package.

**Comment by lachlanjc** [comment]
Yes, @emotion/core is a dependency. Here’s the docs on that: https://theme-ui.com/guides/global-styles

**Comment by nkrmr** [comment]
OK but in the doc's example I have to add @emotion/core package, while in the migrating doc they said : 

> @emotion/core and @mdx-js/react are now dependencies of theme-ui and should not be installed separately.

But I don't know how to use Global component directly from theme-ui, maybe it's not possible ?

**Comment by lachlanjc** [comment]
@emotion/core is installed by Theme UI, so you can go ahead & use it directly in your project without installing it yourself.

**Comment by nkrmr** [comment]
Ok it works thanks
