### ISSUE TITLE
Recipes uses variants for different components, couldn't locate

### ISSUE THREAD

**Issue by nachiket-p** [system-ui/theme-ui#864]
[Recipes ](https://theme-ui.com/recipes) section uses variants to implement layout / design. 
I tried to find the theme source for it, couldn't find anywhere in the repository.

Example: 
```
<footer
  sx={{
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    p: 2,
    variant: 'styles.footer', 
  }}>
```
where is the theme source for **styles.footer**?

**Comment by lachlanjc** [comment]
So as the [Variants docs](https://theme-ui.com/guides/variants/ ) describe, those are typically stored in the theme file (at `styles.footer`). I may be mistaken, but I don’t think it’s doing anything here—I believe that’s an example of how to use a variant if you want to have shared styles in your own project. I can’t locate anything relevant in the Docs site theme that it might be referencing.

**Comment by nachiket-p** [comment]
Understood. 
What I meant, the docs example page is using variant as mentioned above, but couldn't find the definition of it in the source code.

**Comment by jxnblk** [comment]
The theme for the docs site itself is here, if that's what you're looking for?? https://github.com/system-ui/theme-ui/blob/master/packages/docs/src/gatsby-plugin-theme-ui/index.js
