### ISSUE TITLE
warn "export 'ColorMode' was not found in 'theme-ui'

### ISSUE THREAD

**Issue by Defite** [system-ui/theme-ui#868]
**Describe the bug**
Just updated `theme-ui` to latest version - `0.3.1`, `"gatsby-theme-ui": "0.2.0",`. After the build I got in console: 
```
warn "export 'ColorMode' was not found in 'theme-ui'
```

**Additional context**

Got some strange styles in the browser right after upgrading.

<img width="265" alt="Снимок экрана 2020-04-25 в 18 59 56" src="https://user-images.githubusercontent.com/299118/80284405-fe1c5c80-8726-11ea-9762-1cbc09f41d50.png">

I don't use `colors` in my theme.js, it's important. It was never an issue.

**Comment by lachlanjc** [comment]
Hey! Highly recommend checking out the Migrating guide, here: https://theme-ui.com/migrating

`ColorMode` was deprecated, in short, among other changes. Try following each of the steps there & report back if something’s still wrong. Otherwise, I think this can be closed. 👍

**Comment by Defite** [comment]
I've already tried 'migration' steps, but still no luck :(

**Comment by lachlanjc** [comment]
@Defite Ok cool. So the ColorMode component is deprecated/no longer needed—did you remove it from your project? Can you post the code triggering this issue?

**Comment by Defite** [comment]
@lachlanjc I've never used ColorMode before :) https://github.com/Defite/gatsby-theme-defite/tree/theme-v2 here is my work in progress, and here is `theme.js`: https://github.com/Defite/gatsby-theme-defite/blob/theme-v2/gatsby-theme-defite/src/theme.js

**Comment by lachlanjc** [comment]
Honestly, never used Gatsby Themes before so a bit out of my depth here. Sorry.

**Comment by Defite** [comment]
How can I help you with that? Is my `theme.js` looks ok?

**Comment by LekoArts** [comment]
You'll also need to update the gatsby plugin to 0.3.0

**Comment by Defite** [comment]
> You'll also need to update the gatsby plugin to 0.3.0

and it is `gatsby-plugin-theme-ui`...

**Comment by Defite** [comment]
Installing `gatsby-plugin-theme-ui@0.3.0` resolves this issue, thank you, @LekoArts

**Comment by ansonlowzf** [comment]
> You'll also need to update the gatsby plugin to 0.3.0

LekoArts, Thank you for your solution. I think the gatsby-theme-blog packages also need to update the theme-ui to latest version
