### ISSUE TITLE
theme-ui compound ui.component syntax.

### ISSUE THREAD

**Issue by a7sc11u** [system-ui/theme-ui#871]
It's silly, but personally I just can't remember the jsx custom pragma syntax and also (to me) it feels a little bit unidiomatic. At least that's how the idea it came to me. Looking at framer-motion and react-spring, I thought I could borrow their compound component syntax and wrap theme-ui's jsx function into a similar component.

This is the proposed syntax.

```
import {ui} from '@theme-ui'

const component = () => (
  <ui.h1
    sx={{
      fontFamily: 'body',
      color: 'text',
      fontSize: 8,
    }}>
       Theme <ui.span sx={{ color: 'secondary' }}>UI</ui.span>
  </ui.h1>
);
```

Additional use cases
 
```
// html tags
<ui.button/>

// svg tags
<ui.svg/>

// react fragment
<ui.fragment/>
  
// as tag
<ui.tag as="button"/>

// custom components
ui.custom(CustomComponent)

// theme-ui provider
<ui.provider theme={...}/.>
```

I have a first draft on this fork. For now it's under a `markup` package, but could be core. Also it's not in typescript, but my typedjs-fu is a little bit basic. 
https://github.com/a7sc11u/theme-ui/tree/feature/ui/packages/markup

And an example
https://github.com/a7sc11u/theme-ui/blob/feature/ui/examples/markup-ui/src/App.js

I'm not sure if there's a runtime benefit but I imagine it won't hurt if not every single html tag goes through theme-ui's jsx and emotion. It's not much by itself but there can be other use-cases, that if implemented, combined, it might make more sense.

**Comment by jxnblk** [comment]
Thanks for the suggestion -- this seems like duplicate functionality to maybe the `Styled` API or the built-in components -- am I missing something here? Also note that JSX requires components be uppercase

**Comment by hasparus** [comment]
I'm usually rolling like this https://github.com/system-ui/theme-ui/issues/227#issuecomment-591659709 with babel plugin.

It's good to note that you don't need the pragma for any components derived from _@theme-ui/components_ **`Box`**, though the global typings of Emotion and theme-ui assume that you're using the pragma, so you'd need to patch package it for TypeScript to stop lying to you that `sx` works everywhere.

**Comment by lachlanjc** [comment]
I think between the aforementioned upcoming Babel plugin, the [Components](https://theme-ui.com/components), JSX pragma, & Styled, there isn’t room for this solution as well in our API. Personally I find it confusing as well.

@hasparus I’m cool to close
