### ISSUE TITLE
Question about styling html tags outside mdx

### ISSUE THREAD

**Issue by tbntdima** [system-ui/theme-ui#877]
Hi, in my project I faced a case where I needed to apply mdx styles to html tags outside the mdx.

Example:
`gatsby-plugin-theme.ui/index.js`

```js
export default {
  styles: {
    root: {
      fontFamily: "body",
      lineHeight: "body",
      fontWeight: "body",
      fontSize: 2,
    },
    h1: {
      mt: 0,
      mb: 3,
      color: "text",
      fontFamily: "heading",
      lineHeight: "heading",
      fontWeight: "heading",
      fontSize: 5,
    },
  },
}
```

So I wanted `h1` for example on my homepage to have these styles.
The only solution I came up with, is to put the same styles into root.

```js
export default {
  styles: {
    root: {
      fontFamily: "body",
      lineHeight: "body",
      fontWeight: "body",
      fontSize: 2,
      h1: {
        mt: 0,
        mb: 3,
        color: "text",
        fontFamily: "heading",
        lineHeight: "heading",
        fontWeight: "heading",
        fontSize: 5,
      },
    },
    h1: {
      mt: 0,
      mb: 3,
      color: "text",
      fontFamily: "heading",
      lineHeight: "heading",
      fontWeight: "heading",
      fontSize: 5,
    },
  },
}
```

And to reduce repetition:
```js
const primitiveStyles = {
  h1: {
    mt: 0,
    mb: 3,
    color: "text",
    fontFamily: "heading",
    lineHeight: "heading",
    fontWeight: "heading",
    fontSize: 5,
  },
}

export default {
  styles: {
    root: {
      fontFamily: "body",
      lineHeight: "body",
      fontWeight: "body",
      fontSize: 2,
      ...primitiveStyles
    },
    ...primitiveStyles
  },
}
```

This solution worked for me. But I'm still not sure if this is the most optimal solution, since I couldn't find anything in the documentation. Any feedback would be great. Maybe this question will also help someone else 🙂 

My other thought to solve this case was if I should use `theme-ui` components instead of regular tags 🤔

**Comment by arshad** [comment]
@tbntdima You can use the `Styled` h1 using:

```jsx
...
import { Styled } from 'theme-ui'

export default props => (
  <div>
    <Styled.h1>This is styled from theme.styles</Styled.h1>
    <h1>This is not</h1>
  </div>
)
```

Here's the documentation for `Styled` components: https://theme-ui.com/styled

**Comment by tbntdima** [comment]
@arshad, thanks for the answer, I see, adding `Styled` is the documented version 🤔 
To be honest, adding `Styled` to all tags looks kind of tiresome to me xD
Closing this issue.
