### ISSUE TITLE
Multiple files for themes

### ISSUE THREAD

**Issue by amcc** [system-ui/theme-ui#885]
This is more of a documentation suggestion (i've not tried to edit it directly as guidance may be needed)

Following this doc page I initially had trouble splitting my theme into multiple files
https://theme-ui.com/guides/merging-themes/

If I wanted a file for all my typographic stuff, one for all colors and modes, and perhaps one for all the styles I am faced with including nested objects, or even single whole objects. The guide has examples where the file itself imports a single simple object.

So if my colors file looked like this:
```javascript
export default {
  colors: {
    text: "#000",
    background: "#fff",
    primary: "#07c",
    modes: {
      dark: {
        text: "#fff",
        background: "#000",
        primary: "#0cf",
      },
    },
  },
}
```

to import it I would need to spread the imported object like this:
```js
import colors from "./colors"
export default {
  ...colors,
}
```

This might be something obvious to many people, but it wasn't to me at first. This method does suit the way that many people might organise their stylesheets, into areas of concern, rather than very simple small files.

If people think this is a useful edition into the docs I can fork and add something.

**Comment by jxnblk** [comment]
It involves the same syntax you'd need to split any JS object into multiple modules, but yeah, might not be obvious to some. I think adding a guide demonstrating this would be great if you want to take a stab at it!

**Comment by amcc** [comment]
I'll have a stab when i get a chance. I think this falls into the gap between experienced developers, who will certainly know this, and those much newer to coding (which Gatsby is often attracting for instance, using React and more advanced JavaScript for the first time). It seems the likely usecase for moving parts of a theme to separate files is more likely to involve nested objects, certainly for me anyway.

**Comment by cobraz** [comment]
I would say this duplicates #359. I am implementing one for a UI-kit, have a look at tabetalt/kit#24. This features using Typescript as well, but not extending a Theme UI theme.
