### ISSUE TITLE
useColorMode hook render component 2 times

### ISSUE THREAD

**Issue by bardak-dev** [system-ui/theme-ui#887]
**Describe the bug**
In case when client has MediaQuery=`dark` and component uses **useColorMode** this component will render 2 times.

**To Reproduce**
1. Go to https://codesandbox.io/s/black-smoke-o0tj9
2. Switch your client MediaQuery to `dark`
3. See render counter number

**Expected behavior**
Render only 1 time on component initialization.

**Screenshots**
![gif](https://user-images.githubusercontent.com/5928632/80890863-e285f880-8cc8-11ea-8ffa-ce78f85efef8.gif)

**Additional context**
The workaround for this is set initialColorModeName to `dark` (actually this can be done from localStorage) but another thing just came up from this is console.warn(_`The initialColorModeName value should be a unique name and cannot reference a key in theme.colors.modes.`_)

**Comment by jxnblk** [comment]
Since color mode is stored in `localStorage` or coming from the media query check, I don't think there's a way to avoid the second render on the client side, but let me know if I'm missing something obvious here

**Comment by lachlanjc** [comment]
I’m going to close this for now since we haven’t found a solution/fix, but feel free to comment/re-open if there’s a solution here!
