### ISSUE TITLE
background and backgroundImage not applied

### ISSUE THREAD

**Issue by arnaudjnn** [system-ui/theme-ui#888]
I can't use ` background` and `backgroundImage` properties inside sx or theme. CSS is not applied.

```
<div
   sx={{
      backgroundImage: 'https://example.jpg',
      backgroundRepeat: 'no-repeat no-repeat',
      backgroundSize: 'cover'
   }}
>
   ...
</div>
```

**Comment by yesnotnode** [comment]
Did you ever get this sorted? Been having issues myself

**Comment by hasparus** [comment]
Hey @yesnotnode, do you have any reproduction? Or code snippets?

Here's a CodeSandbox I just made: https://codesandbox.io/s/youthful-antonelli-g4ts9?file=/src/App.js

I've been puzzled for a few seconds myself, because I initially wrote 

```
 backgroundImage: 'https://example.jpg'
```

instead of

```
 backgroundImage: "url('https://example.jpg')"
```

but it definitely works if you wrap it in `url()`

**Comment by yesnotnode** [comment]
@hasparus I appreciate you getting back with me, I ended up figuring out that syntax shortly after I posted! Took me way too long to find my way to the right string but it definitely works just like you said!

**Comment by Psychobellic** [comment]
What about locally stored images? 

I can't sort this out either in /src/img/ as in /public

**Comment by yesnotnode** [comment]
Hey @Psychobellic I did this with local images.

`import src from "../images/****.jpg"`

and then in the sx prop...

`backgroundImage: "url(${src})"`

If you are running a query for a local image just store the path in a variable and you should be able to use the same syntax I used.

**Comment by chidera-ovuoba** [comment]
@yesnotnode 
still didn't work
