### ISSUE TITLE
Should Box define margin?

### ISSUE THREAD

**Issue by devdigital** [system-ui/theme-ui#889]
Hi, should the Box component define `margin: 0`, as it can affect its use in various contexts. For example, if you define a simple `Stack` component that adds a space between child components:

```jsx
const Stack = ({ children, space, ...props }) => (
  <Box
    {...props}
    __css={{
      ":only-child": {
        height: "100%"
      },
      "> *": {
        marginTop: space
      }
    }}
  >
    {children}
  </Box>
);
```

The following works as expected:

```jsx
<Stack space="5rem">
  <div sx={{ border: "1px solid #ccc" }}>Content</div>
  <div sx={{ border: "1px solid #ccc" }}>Content</div>
</Stack>
```

The following does not as the `Box` `margin: 0` overrides the `Stack` defined value:

```jsx
<Stack space="5rem">
  <Box sx={{ border: "1px solid #ccc" }}>Content</Box>
  <Box sx={{ border: "1px solid #ccc" }}>Content</Box>
</Stack>
```

**Comment by KimPaow** [comment]
Could I ask why this was closed? Fighting this problem now. @devdigital

**Comment by deckchairlabs** [comment]
@KimPaow  `__css` is an internal prop, and shouldn't be used. It's a bit confusing as the Box component exposes 3 different props for styling.

The `sx` prop should be used as the primary way of styling components.

**Comment by KimPaow** [comment]
Ah my bad, didn't notice that `__css` was used above. In my case I'm using the `sx` prop, but the margin 0 from box randomly decides to override it from time to time. Having the same problem with `<Text/>` component, where I'm setting a marginBottom in the variants in the theme file. But the style that gets prioritized is the one in the base Text component. This seems to work sometimes, and sometimes not.

I'm at a loss as to why this is happening.

**Comment by deckchairlabs** [comment]
When you inspect a child in browser devtools, is the child selector applying and being overridden?

**Comment by KimPaow** [comment]
@deckchairlabs Yes, I can see it being applied, but the Box padding is taking precedence. Right now I have one page where it is working as intended, and another where it does not. Any ideas what could be causing this? A workaround that might work in my case would be to use normal html tags instead of box for my section containers. 

Here's the code for my component. 
```export const Stack = ({ recursive, space, splitAfter, ...props }) => {
  const splitStyle = {};
  const recursiveStyle = {};

  if (splitAfter) {
    splitStyle[":only-child"] = { height: "100%" };
    splitStyle[`:nth-child(${splitAfter})`] = { marginBottom: "auto" };
  }

  if (recursive) {
    recursiveStyle["* + *"] = { marginTop: space };
  }

  if (!recursive) {
    recursiveStyle["> * + *"] = { marginTop: space };
  }

  return (
    <Flex
      sx={{
        flexDirection: "column",
        justifyContent: "flex-start",

        ...recursiveStyle,
        ...splitStyle,
      }}
      {...props}
    />
  );
};

Stack.defaultProps = {
  recursive: false,
  space: [3, 4, 5],
  splitAfter: undefined,
};```

**Comment by deckchairlabs** [comment]
Would you be able to create a codesandbox replicating the issue your seeing? My guess is there's something going on with selector specificity.

**Comment by deckchairlabs** [comment]
And just a quick thought, when you are using your `Stack` component are you defining an `sx` prop?

Example

```jsx
function App() {
  <Stack space={3} sx={{ padding: 2 }}>
    <Box>Child 1</Box>
    <Box>Child 2</Box>
  </Stack>
}
```

**Comment by simontaisne** [comment]
Same issue here! The following style is applied to the nested `Box`, overriding the `Stack` margin.

```css
box-sizing: border-box;
margin: 0;
min-width: 0;
```

**Comment by eddysims** [comment]
having this issue, is there a fix?

**Comment by atanasster** [comment]
@eddysims the fix would be a breaking change unfortunately. Can you overcome by specifying `sx ` prop with a margin on your `<Box>` component?

**Comment by lachlanjc** [comment]
Theme UI doesn't work super well with descendent selectors unfortunately. You could maybe try using React.Children/React.cloneElement?
