### ISSUE TITLE
Splitting out root ThemeProvider and nested ThemeProviders

### ISSUE THREAD

**Issue by jxnblk** [system-ui/theme-ui#89]
Currently the ThemeProvider component can be nested to create theming contexts inside of a parent theme. This allows components like the experimental [MDX Blocks](https://mdx-blocks.netlify.com/) to work and is a powerful feature that probably isn't leveraged much yet.

That said, there are a few issues with this in its current implementation:

- Color mode state is only kept at the root-level ThemeProvider
- ThemeProvider deeply merges theme objects, which can easily cause styling bugs and unreadable text when combined with things like syntax highlighting in `pre` tags
- The `gatsby-theme-ui` package is geared towards having one, single root theme
- The Chrome extension is also geared towards having a single root theme provider

This is a proposal to split the functionality of the ThemeProvider into two separate components.

1. The top-level, root ThemeProvider:
  - Handles the base theme object
  - Provides the styled MDX components in context
  - Includes hooks for stateful theme object changes which could be leveraged in the Chrome extension and other editing tools
  - Would not pick up outer context
  - Would warn when nested in another ThemeProvider
2. A nested context provider (name TBD):
  - Only includes a nested emotion context (no MDX)
  - Does not handle color modes
  - Can deep merge the base `theme` object (ignoring `theme.styles`)
  - Only shallow merges `theme.styles`

With the two separate components, an application tree could look something like the following:

```jsx
<ThemeProvider theme={theme}>
  <div>root-level context available</div>
  <NestedTheme theme={subTheme}>
    <div>nested context available</div>
  </NestedTheme>
</ThemeProvider>
```

**Comment by johno** [comment]
The one thing that might be worth considering is the additional cognitive overhead of an additional provider that's subtly different. I wonder if some of these issues could be avoided by only shallow merging? If a user wants something more custom they could pass a function and deep merge.

It seems the primary issues are:

- merging of `theme.styles` and the association MDX component context
- color modes

Perhaps we can detect if the nested provider doesn't contain a `theme.styles` we don't handle anything MDX/component factory related?

I'm sure I'm missing some nuance here, but these are my initial thoughts.

---

I'd also propose a name along the lines of `TokenProvider` maybe?

**Comment by jxnblk** [comment]
Those two are definitely part of the issue, but I also think the idea of having a single, canonical provider at the root is what I'm aiming for here – there's already a bit of logic to handle nesting, and I think the code could be simpler for what it's doing.

It would definitely add another component to the API, but I think the behavior and API of each component would be a lot easier to reason about, and the nested provider would be more of an advanced feature that most people wouldn't necessarily use

**Comment by jxnblk** [comment]
API-wise, it's still the same component, but I think the refactor in #106 mostly addresses this issue
