### ISSUE TITLE
Unreleased features are documented in live docs

### ISSUE THREAD

**Issue by yuriybelike** [system-ui/theme-ui#893]
**Describe the bug**
Some features are already documented in the live docs, but not present in the latest release.

**To Reproduce**
Opacities example:
1. Go to https://theme-ui.com/theme-spec#theme-scales
2. Realize that you can use "opacities" theme property
3. Use it in `sx` prop
4. See that it doesn't work
5. Realize that it is a feature added [2 days ago](https://github.com/system-ui/theme-ui/pull/866)

**Expected behavior**
Unreleased features aren't documented the same way as released ones (for example with a "Unreleased" badge, a version badge or the docs have a selector in order to choose a version a la https://angular.io/docs)

**Comment by jxnblk** [comment]
Thanks for pointing this out. Typically the packages are released as soon as they're merged, but with the current conversion to TypeScript, we're only doing canary releases at the moment. Hopefully a stable version will be released soon, and I don't think there's a need for additional badges in the docs

**Comment by lachlanjc** [comment]
Sounds like we should close?
