### ISSUE TITLE
<Grid> and SX do not support grid-template-rows and grid-row-gap

### ISSUE THREAD

**Issue by jeffscottward** [system-ui/theme-ui#903]
Also `grid-column-gap` in SX prop

**Comment by lachlanjc** [comment]
Hey! `gridColumnGap` & `gridRowGap` are already supported: https://github.com/system-ui/theme-ui/blob/master/packages/css/src/index.ts#L99

**Comment by jeffscottward** [comment]
Very weird, it was choking on that. Will try again this week.

**Comment by jeffscottward** [comment]
`gap` does work for `<Grid>` but can you specify each specifically though?

**Comment by lachlanjc** [comment]
Yup! `sx={{ gridColumnGap: 3, gridRowGap: 2 }}`

**Comment by lachlanjc** [comment]
I think we can close this?
