### ISSUE TITLE
(docs) Can't start gatsby dev server: The result of StaticQuery can't be fetched

### ISSUE THREAD

**Issue by hasparus** [system-ui/theme-ui#908]
**Describe the bug**
StaticQuery can't be fetched. Page is blank after closing error overlay.

**To Reproduce**
Run `yarn start`.

**Expected behavior**
Well, build works, deploy previews work. I'd expect it to work too.

**Screenshots**
![image](https://user-images.githubusercontent.com/15332326/81504011-4753db00-92e7-11ea-8773-bd43b7be9b73.png)

**Additional context**

Might(?) be connected to https://github.com/system-ui/theme-ui/pull/878?
No clue tbh. @laurieontech @jxnblk does it work for you? Is it a problem only on my machine?

**Comment by laurieontech** [comment]
Nope, not just you. I see it too. Let me take a look.

**Comment by beckzayi** [comment]
I had exactly the same issue as @hasparus .
To reproduce: (1) clone the whole project. (2) run `yarn` (3) run `yarn start docs.`

Building development bundle was successful, but error appeared when trying to open it on browser. Thanks. By the way, I'm new to theme-ui, which is a great project.

**Comment by dcastil** [comment]
Same issue here. 🙋

**Comment by jxnblk** [comment]
The docs *should* be working now (think there was a sharp-related dependency causing issues, which can be addressed later)
