### ISSUE TITLE
VS Code plugin

### ISSUE THREAD

**Issue by jxnblk** [system-ui/theme-ui#91]
Similar to the idea of a Chrome extension (#86), it would be nice to have a plugin for VS Code and/or other IDEs with graphical interfaces for editing things like colors and typography

**Comment by johnletey** [comment]
This sounds like a cool feature ... why don't use create a `vscode-theme-ui` repo under the `system-ui` org ... and I can start working on it!

**Comment by jxnblk** [comment]
I assume this package could live in this same monorepo. Is there a particular reason for another repo?

**Comment by johnletey** [comment]
oh yes ... it totally could!

> Is there a particular reason for another repo?

I was just thinking that it would be cleaner ... but keeping all the theme-ui stuff together is nice

BTW ... what do you think of the sidebar icon that I just designed for the extension? [Figma](https://www.figma.com/file/9Ux0d98R0ebRvqDHsQOlpA/vscode-theme-ui)

**Comment by jxnblk** [comment]
Closing this out since there hasn't been any traction on this -- might revisit this idea in the future
