### ISSUE TITLE
How to style Gatsby Link in MDX?

### ISSUE THREAD

**Issue by ansonlowzf** [system-ui/theme-ui#918]
Hi, theme-ui team

I'm using gatsby-starter-blog-theme.

I  style my MDX anchor tag as below:-

```js
// src/gatsby-plugin-theme-ui/styles
a: {
    color: `primary`,
    textDecoration: `none`,

    ":hover, :focus": {
      color: `orange`,
    },
  },
```

Every a tags in MDX are  styling probably

However, when I

```js
import { Link } from 'gatsby'
```
which also an anchor tag behind,

The style and class is not apply to this Link Component even they are in a MDX file

I try find answer in google, in GitHub, and theme-ui doc
and also try creating a GatsbyLink Component like so:-

```js
/**@jsx jsx */
import { jsx } from "theme-ui"
import { Link } from "gatsby"

const GatsbyLink = ({ props, children }) => {
  <Link
    {...props}
    sx={{
      color: `primary`,
      ":hover :focus": {
        color: `orange`,
      },
    }}
  >
    {children}
  </Link>
}

export default GatsbyLink

```

and import it to MDX and apply 

```js
<GatsbyLink to='/'>Home</GatsbyLink>
```

It's not working, 

May I know how to style third party router in theme-ui?

Hope to hear from you soon

**Comment by hasparus** [comment]
Hi! If you want `GatsbyLink` to be accessible in MDX without import (you just `import` your code there too), you're probably looking for `components` dict. You can shadow it in [_src/gatsby-plugin-theme-ui/components_](https://github.com/system-ui/theme-ui/blob/master/packages/gatsby-plugin-theme-ui/src/components.js).

I did this in one website.

```js
// src/gatsby-plugin-theme-ui/components.tsx
export default {
  a: (props: ComponentPropsWithoutRef<"a">) => {
    if (
      !props.href ||
      props.href.match(/^(https?|\/\/|#|mailto:|javascript:)/)
    ) {
      return <a sx={theme.styles.a} {...props} />;
    }
    const { href, ...rest } = props;
    return <Link sx={theme.styles.a} to={href} {...rest} />;
  }
};
```

For this particular usecase you can also find [gatsby-plugin-catch-links](https://www.gatsbyjs.org/packages/gatsby-plugin-catch-links/) interesting.

**Comment by hasparus** [comment]
> The style and class is not apply to this Link Component even they are in a MDX file

Quick explanation:

Theme UI doesn't cascade these styles on every anchor below MDX Provider.

Tags used in MDX are defined in the `components` object.
They are by default just styled with in `theme.styles`, but you can provide your own implementation (_src/gatsby-plugin-theme-ui/components_).

The magic needed for this to work on Theme UI side is in _@theme-ui/mdx_.

**Comment by ansonlowzf** [comment]
Thank you Hasparus for introducing **gatsby-plugin-catch-links**

Now, I just need to use Markdown link syntax, internal anchor tag is a gatsby link now.
