### ISSUE TITLE
Can I define a second breakpoints array?

### ISSUE THREAD

**Issue by kuworking** [system-ui/theme-ui#920]
I am designing a page that I would benefit having a different `brealpoints` array

Is this use case covered? Something like

```js
landing: {
    breakpoints: ['400px', '800px'],
    h1: {
      fontSize: [3,4,5],
    }
}
```

so that if I'm using `sx={{ variant: 'landing' }}` then I'll be using that specific array and not the base one?

**Comment by jxnblk** [comment]
You can use a nested ThemeProvider for things like this (i.e. contextually changing `theme.breakpoints`), see https://theme-ui.com/guides/nested-theme-providers

**Comment by kuworking** [comment]
thanks!
