### ISSUE TITLE
Targeting child components with sx

### ISSUE THREAD

**Issue by fredshevek** [system-ui/theme-ui#926]
Hi, is there a way to target child components with sx, like you do in @emotion/styled?

```jsx
import styled from '@emotion/styled'

const Child = styled.div`
  color: red;
`

const Parent = styled.div`
  ${Child} {
    color: green;
  }
`

render(
  <div>
    <Parent>
      <Child>Green because I am inside a Parent</Child>
    </Parent>
    <Child>Red because I am not inside a Parent</Child>
  </div>
)
```

So, I'm looking for an equivalent something like:

```jsx
<Parent sx={{ [Child]: {color: "green} }}>
  <Child>Green because I am inside a Parent</Child>
</Parent>
```
The use case is not obvious when you have one `<Child>` but kinda makes sense if you have many
 
Thanks

**Comment by hasparus** [comment]
Well, since `Child` is an function, we can't pass it as a key in an object literal.

Tagged template literals of the `styled` API are pretty powerful high level API.
Theme UI's `sx` is a bit simpler.

You can do
```jsx
<ul sx={{ li: { color: "green" } }}>
  <li>1</li>
  <li>1</li>
  <li>1</li>
  <li>1</li>
</li>
```

**Comment by hasparus** [comment]
Here's a quick CodeSandbox example.
https://codesandbox.io/s/mystifying-hodgkin-7mrov?file=/src/App.js

**Comment by fredshevek** [comment]
Thanks @hasparus

**Comment by hasparus** [comment]
Thanks for the issue @fredshevek.

It might be worth to mention it in the guides. You're not the only one asking about it.
https://theme-ui.com/guides

**Comment by masoud-naji** [comment]
Thanks 
I know it's an old issue but I was looking for it on Next-Js , it finally works like this.


 "> li:nth-child(2)": {
                border: "1px solid red",
         },

**Comment by AgustinSTC** [comment]
@masoud-naji you save my day, buddy. Thank so much.

Thanks to @hasparus and @fredshevek as well
