### ISSUE TITLE
How to use styles object for Heading when theming

### ISSUE THREAD

**Issue by iwatakeshi** [system-ui/theme-ui#929]
**Describe the bug**

Hi. I'm not sure if this is a bug or if it's the way it works, but I'm trying to define some basic heading styles in the theme's `styles` object and use them with `Heading`. However, it doesn't seem to work or it might be that I'm missing something.

To illustrate, I'm trying to define some headings like so:
```js
{
  text: {
    heading: { /* ... */ }
  },
  styles: {
    root: { /* ... */ } 
    h1: {
      variant: 'text.heading',
      // override the font-size
      fontSize: [7, 8]
    }
  // ...
 }
}
```

Then use the `Heading` component:

```jsx
<Heading as="h1">...</Heading>
```

**To Reproduce**

I've created a reproduce-able example that shows what I'm going after:

https://codesandbox.io/s/eager-haslett-4h0ct

**Expected behavior**

My goal was to define the headings and override the font-sizes for each heading. I expected the font-sizes to be reflected when using the `as` prop.

**Comment by jxnblk** [comment]
The documentation might be a little unclear, but the `Heading` component pulls its styles from `theme.text.heading` (see https://theme-ui.com/components/heading/) -- the `theme.styles.h1` is for MDX headings or the `Styled.h1` component -- hope that makes sense!

**Comment by iwatakeshi** [comment]
@jxnblk I had a hunch that that might be the case. I've got a workaround where I define the variants inline using `styled(Heading)` so it ends up looking like this:

```jsx
<Heading as="h1" variant="h1">...</Heading>
```

Thanks though!
