### ISSUE TITLE
Add example with Primer Components

### ISSUE THREAD

**Issue by jxnblk** [system-ui/theme-ui#94]

**Comment by okonet** [comment]
I could take this one since I’ve done this in design tokens repo

**Comment by jxnblk** [comment]
Just remembered that Primer Components is built with Styled Components, so an additional ThemeProvider would be required since the two libraries do not share the same React context. It's certainly doable, but less out-of-the-box that I was originally thinking

**Comment by jxnblk** [comment]
@okonet is this still something you're interested in? If not, I think we could probably close this issue out

**Comment by okonet** [comment]
I'm super busy with other stuff now so let's close for now.
