### ISSUE TITLE
Console warnings in latest gatsby version due to Styled component

### ISSUE THREAD

**Issue by ehowey** [system-ui/theme-ui#947]
**Describe the bug**
Since updating to the latest version of Gatsby I am seeing a bunch of console warnings that look like this:

```shell
warn ESLintError: 
/Users/erichowey/Coding/erichoweydev/src/components/work-card.js
  44:9  warning  Imported JSX component h4 must be in PascalCase or SCREAMING_SNAKE_CASE  react/jsx-pascal-case
  45:9  warning  Imported JSX component p must be in PascalCase or SCREAMING_SNAKE_CASE   react/jsx-pascal-case
  48:9  warning  Imported JSX component p must be in PascalCase or SCREAMING_SNAKE_CASE   react/jsx-pascal-case
```
Basically what is happening is that it doesn't like the `<Styled.p>` syntax and is complaining. Not a big deal - but maybe worrying for newer users of Theme-UI.  Not sure if this would be resolved here or on the Gatsby end so I will cross post it.

**Comment by jxnblk** [comment]
Thanks! Since nothing has changed in Theme UI's API and this sounds like a change in a lint rule, I think this would need to be addressed either in Gatsby or upstream

**Comment by ehowey** [comment]
That is what I figured - more of an annoyance than anything.  I will leave this open just in case anyone else comes across the issue.  Hopefully resolved on Gatsby's end of things.

**Comment by ehowey** [comment]
Closed by https://github.com/gatsbyjs/gatsby/pull/24560

**Comment by Kev-Y-Huang** [comment]
As of gatsby version 2.31.0, this error is back.
![image](https://user-images.githubusercontent.com/12895833/106411382-2c943a00-6413-11eb-80fa-09567f1402da.png)
