### ISSUE TITLE
top, bottom, left, right negative values

### ISSUE THREAD

**Issue by VinSpee** [system-ui/theme-ui#96]
Hi!

Maybe the `top`, `bottom`, `left`, and `right` properties should follow the same _negative value rules_ as margins?

Personally, I find myself often doing something like this:

```jsx
<Card>
  <Box
    css={{
      position: 'relative',
      top: `-${theme.sizes[1]}`,
    }}
  >
    <Avatar size="2" />
  </Box>
  <Content />
</Card>
```

Is this a common enough occurrence to warrant an API breaking change?

**Comment by jxnblk** [comment]
I don't think that'd be a breaking change, and I can't see anything wrong with this. The relevant code would be in [styled-system/css](https://github.com/styled-system/styled-system/tree/master/packages/css) for now though

**Comment by jxnblk** [comment]
This *should* work now, thanks to your PR, but feel free to reopen if you notice any issues
