### ISSUE TITLE
How to compile a library that uses theme-ui with typescript?

### ISSUE THREAD

**Issue by nkint** [system-ui/theme-ui#960]
Hi! This is my first issue here, and it's more a clarification advice then a feature request or a bug. Hope it's ok until the GitHub Discussions works (referring from [here](https://github.com/system-ui/theme-ui/issues/555)).

I'm using theme-ui and I'm super happy about it.

I'm writing a library with theme-ui and typescript from scratch using parcel bundler for the demo. When I'm using it inside an application bootstrapped with create-react-app I see the error: 
```
Module parse failed: Unexpected token (14:12)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| export var Loader = function (_a) {
>     return (<div sx={{
```

Briefly this is my folder structure:

Library:
```
src/index.tsx        <---- the file of my library
src-demo/index.html  <---- the index.html used by parcel
src-demo/index.tsx   <---- the index.tsx used by parcel
package.json
```

In here I have those scripts in the package.json:
```
    "scripts": {
		"clean": "rm -rf .parcel-cache dist build",
		"build-lib": "npm run clean && tsc",
		"start": "parcel src-demo/index.html",
```

and everything is working fine, I have `"react": "^16.13.1"`, `"theme-ui": "^0.3.1"`, `"parcel": "^2.0.0-alpha.3.2"`, `"typescript": "^3.9.2"`.

Now I want to use this library inside a different repository, inside an application done with create-react-app. To link the library without publish I'm using `yarn link`. But I see the error above. Note that I already installed theme-ui in the application and it's working fine.

I think I should do an additional build step with babel over the `tsc` compiled files, but I'm not an expert on those build step. I've tried to do some trials using `@emotion/babel-preset-css-prop` but nothing really works neither I understood exactly what I was doing, so maybe here someone can help me.

I think that because in the build output files from `tsc` there is no *jsx pragma* thing.

Thanks in advance and I hope everything is clear, maybe I will be happy to add some clarification on my question or a MWE.

**Comment by nkint** [comment]
After some trials with `babel` + `tsc` I used [microbundle](https://github.com/developit/microbundle).

I had to add the jsx pragma
```
/** @jsx jsx */
import { jsx } from 'theme-ui';
```
also in the file where I don't use `sx` props because otherwise in the bundle of that files I have a weird compiled `return react(` thing (that result in `"ReferenceError: react is not defined"` error at runtime).

Microbundle works pretty well without any `babelrc` o babel config.

Also, I think this is mandatory in tsconfig: `"jsx": "preserve",` (could be obvious but I wrote here for reference if anyone will read this issue).

Maybe a rollup custom config would be faster in watch mode, and this should be the other thing I will look at!

**Comment by tbrasington** [comment]
@nkint I am having a similar issue where there are no compile errors, everything gets pulled through but none of the sx props are parsed. Would it be possible to see your microbundle and tsconfig setup?

**Comment by nkint** [comment]
hei @tbrasington , sure.

here is my `package.json` with everything unnecessary removed (I hope):

```json
{
	"scripts": {
		"build-lib": "npm run clean && microbundle --no-compress && dts-bundle-generator ./src/index.ts -o ./build/index.d.ts",
	},
	"source": "src/index.ts",
	"main": "build/index.js",
	"types": "build/index.d.ts",
	"files": [
		"build/"
	],
	"devDependencies": {
		"dts-bundle-generator": "^3.2.0",
		"microbundle": "^0.12.0",
		"parcel": "^2.0.0-alpha.3.2",
		"typescript": "^3.9.2"
	},
	"browserslist": {
		"production": [
			">0.2%",
			"not dead",
			"not op_mini all"
		],
		"development": [
			"last 1 chrome version",
			"last 1 firefox version",
			"last 1 safari version"
		]
	},
	"targets": {
		"default": {}
	}
}
```

and the `tsconfig.json`:

```json
{
	"compilerOptions": {
		"strict": true,
		"baseUrl": ".",
		"rootDir": ".",
		"outDir": "build",
		"module": "esnext",
		"moduleResolution": "node",
		"target": "ES5",
		"sourceMap": true,
		"declaration": true,
		"declarationMap": true,
		"lib": ["esnext", "dom", "dom.iterable"],
		"resolveJsonModule": true,
		"skipLibCheck": true,
		"esModuleInterop": true,
		"experimentalDecorators": true,
		"allowSyntheticDefaultImports": true,
		"jsx": "preserve",
		"strictNullChecks": false,
		"downlevelIteration": true,
		"forceConsistentCasingInFileNames": true,
		"isolatedModules": false,
		"noUnusedLocals": false,
		"noImplicitReturns": true,
		"noImplicitThis": true,
		"noImplicitAny": true
	},
	"exclude": ["node_modules", "build"],
	"include": ["./src/**/*.ts", "./src/**/*.tsx"]
}
```

let me know if it helps

**Comment by tbrasington** [comment]
Thank you @nkint I have been pulling my hair out with this one.
