### ISSUE TITLE
Breakpoints for "@media print"

### ISSUE THREAD

**Issue by 0phoff** [system-ui/theme-ui#962]
**Is your feature request related to a problem? Please describe.**
Currently breakpoints only apply for "@media screen", which breaks my layouts when trying to generate a PDF with puppeteer.

**Describe the solution you'd like**
1. Option 1
One option would be to remove the "@media screen" from breakpoints, which would make it so that the breakpoints work for all media types (screen, print and speech).
I have no idea of the implications of this and whether or not this is actually a good idea.

2. Option 2
Another option would be to add an extra key to the theme (eg. `breakpointMedia`), that allows to choose for which mediatypes the breakpoints are used.

3. Option 3
Finally, you could also allow for complete "@media ..." rules in the breakpoint array and use those.
```js
breakpoints = ['40em', '56em', '64em']  // Current behavior: use as min-width

// New behavior: use these exact media queries
breakpoints = [
  '@media screen and (min-width: 800px)',
  '@media print and (max-width: 800px)',
  '@media (min-width: 1500px)'
]
```

**Describe alternatives you've considered**
Currently, you need to manually use media queries to "copy" the behavior for print media types, which is tedious in your theme object and infeasible inside of components.

**Comment by jxnblk** [comment]
This should only affect mobile-first, responsive array values. For print-specific styles, I recommend using standard CSS media query syntax where needed. If it's purely for a grid/layout system, you can wrap your own custom components to handle print styles the way you'd like to

**Comment by 0phoff** [comment]
Well my use case is a library, and thus I don't want to bother my users to set "print" specific styles and would like for everything to work at the correct size. I am generating my PDF at a viewport of 1920x1080px, but because the styles are defined mobile-first, that means that for "print", all sizes are set to the smallest, base size of the website.

For what it's worth, the [styled system specification](https://styled-system.com/theme-specification#media-queries) does seem to allow for a `mediaQueries` key.

---

Currently I found a work-around, which is to add a breakpoint of '0px'.  
This allows me to set a "default" state for styling the '@media print', which gets overwritten by the '0px' breakpoint for the smallest screens.

```js
{
  breakpoints: ['0px','800px', '1200px'],
  styles: {
    p: {
      fontSize: ['large', 'small', 'medium', 'large']
    }
  }
}
```

But all of this seems quite a hack around the fact that you start from a "mobile-first" approach (combined with the fact that your media queries only target screen), where I would like the desktop version to be the default for printing purposes.

---

At the end of the day, my library will be used to create presentations and users will usually not bother creating mobile-friendly versions so this becomes a non-issue, but I'll leave this here for people stumbling upon the same or similar problems.
