### ISSUE TITLE
Embed additional props for accessibility and others

### ISSUE THREAD

**Issue by Slooowpoke** [system-ui/theme-ui#966]
When using the <Embed> component, it would be nice to be able to pass down props onto the iframe. I couldn't find anything in the docs for it, but perhaps I've missed something?

Currently the <Embed> component wraps an iframe in the div and props like aria-label or title are attached to the parent div instead of the iframe. Perhaps having something like ```iframeProps: {}``` is too verbose and not in keeping with ThemeUI but I can't think of anything that would work better.

An alternative could be for me to create a custom component with the nessecary props and I'm happy to do it if that's the recommended guidelines.

**Additional context**
It's mostly for some accessibility reasons but I'm sure there are other cases where it would be helpful.

**Comment by lachlanjc** [comment]
To add clarity, I believe this issue is referring to the `Embed` component specifically

**Comment by lachlanjc** [comment]
Related: #706
