### ISSUE TITLE
[docs] possible missing information for it to work with gatsby

### ISSUE THREAD

**Issue by daydream05** [system-ui/theme-ui#98]
Hi Jackson! Awesome stuff as usual.

Just gave this a test run while making a gatsby theme.

I was following one of the examples on how to use it with gatsby. (not as a plugin)

And I got stuck with a dom attribute error saying `css` shouldn't be there. Turns out
you need to have [gatsby-plugin-emotion](https://www.gatsbyjs.org/packages/gatsby-plugin-emotion/?=emotion) installed as well

I guess just a heads up to anyone who might encounter the same issue.

**Comment by jxnblk** [comment]
Thanks! Yeah, that part’s definitely missing at the moment. We’re still working out how the custom JSX pragma should work, which should (hopefully) make the setup nicer – we should add a note about the emotion plugin for now though

**Comment by jxnblk** [comment]
With version `0.2.0` the custom pragma now uses the `sx` prop, which should work with or without the Emotion plugin. I've updated the docs to try to clarify using Emotion's `css` prop without Theme UI here: https://theme-ui.com/sx-prop/#without-using-the-custom-pragma
