### ISSUE TITLE
Update Next.js example with latest Emotion

### ISSUE THREAD

**Issue by joeyvanlierop** [system-ui/theme-ui#992]
**Describe the bug**
When reloading a page which is supposed to display the current color mode's background color, a brief blue background is visible. 

**To Reproduce**
1. Clone https://github.com/joeyvanlierop/theme-ui-flicker
2. Run `yarn install` and `yarn dev`
3. Open http://localhost:3000 in your browser and reload the page to view the flicker

**Expected behavior**
The background should not flicker blue when reloading the page. Instead it should immediately show the current color mode's background color.
To view the expected behavior, uncomment [this line](https://github.com/joeyvanlierop/theme-ui-flicker/blob/93e6914b0907892dd63b6bd807cde1a992535bbd/src/theme.js#L2) in `src/theme.js` and reload the page.

**Screenshots**
In the example repository I have set a transition for the background color to further demonstrate the inital blue background. It is less evident (but still visible) without the transition. To view the flicker without any transition, comment out [this line](https://github.com/joeyvanlierop/theme-ui-flicker/blob/93e6914b0907892dd63b6bd807cde1a992535bbd/src/theme.js#L18).

- Blue flicker on reload (Bug):
https://streamable.com/3y85jd

- No flicker on reload (Expected behavior):
https://streamable.com/gi0ck9

**Additional context**
The workaround that I am using by setting `initialColorModeName` to one of the color modes seems to be a very odd solution. There is a warning which outputs:

> The `initialColorModeName` value should be a unique name and cannot reference a key in `theme.colors.modes`.

[The docs](https://theme-ui.com/theming/#configuration-flags) state that `initialColorModeName` is used to define the key used for the top-level color palette, so I do not know why this fix works. Furthermore, if I change `initialColorModeName` to something other than `light` or `dark`, the flicker returns. I would appreciate any clarification on why this is happening. Thanks!

**Comment by lachlanjc** [comment]
This problem has been fixed, but leaving this issue open for updating our Next example with a `.babelrc` file: https://github.com/vercel/next.js/blob/canary/examples/with-emotion/.babelrc

**Comment by joeyvanlierop** [comment]
@lachlanjc That's great to hear! Would you mind referencing the commit or pull request where this was fixed?

**Comment by hasparus** [comment]
:rocket: Issue was released in [`v0.14.0-develop.0`](https://github.com/system-ui/theme-ui/releases/tag/v0.14.0-develop.0) :rocket:

**Comment by hasparus** [comment]
:rocket: Issue was released in [`v0.14.0`](https://github.com/system-ui/theme-ui/releases/tag/v0.14.0) :rocket:
