### ISSUE TITLE
How to use custom class from theme js file

### ISSUE THREAD

**Issue by bilalsha** [system-ui/theme-ui#994]
I am using `gatsby-plugin-theme-ui` in my static site. I added custom style class in `index.js` like this

    styles: {
    custom: {
      backgroundColor: "background",
      color: "text",
      fontFamily: "default",
      fontSize: 2,
      lineHeight: "text",
      padding: 0,
      overflowY: "auto",
    }}

In component, I import `styled` from `theme-ui` and trying to use it like this
```
<Styled.custom>
  <component/>
</Styled.cusotm>
```

But I am unable to use it.

**Comment by jxnblk** [comment]
You'll need to use the `sx` prop to apply styles, you might want to start here https://theme-ui.com/sx-prop/

**Comment by lachlanjc** [comment]
Hey @bilalsha! The Styled component can [only be used](https://theme-ui.com/styled#changing-the-html-element-or-component) with Theme UI’s predefined tags, not custom variants. You can use the sx prop as Brent mentioned, like `<div sx={{ variant: ‘styles.custom’ }}>` or with Theme UI’s components, like `<Box variant=“styles.custom”>`.

@hasparus We can close as a discussion 👍
