### ISSUE TITLE
Theme typescript defs

### ISSUE THREAD

**Issue by atanasster** [system-ui/theme-ui#995]
**Is your feature request related to a problem? Please describe.**
The `tbody` tag is not part of the Theme.styles definition

**Describe the solution you'd like**
Possibly add `tbody` (possibly also `thead`) tags to the typescript definitions: 
https://github.com/system-ui/theme-ui/blob/e22df3c442bc86634902baf21a5919f5a5090da8/packages/css/src/types.ts#L541

**Describe alternatives you've considered**
//@ts-ignore

If the suggestion is ok, I can also submit a PR

**Comment by hasparus** [comment]
The list of "autocompleted" keys are the same as keys of [`Styled`](https://github.com/system-ui/theme-ui/blob/e22df3c442bc86634902baf21a5919f5a5090da8/packages/mdx/src/index.js#L12)

However, there's an [index signature](https://github.com/system-ui/theme-ui/blob/e22df3c442bc86634902baf21a5919f5a5090da8/packages/css/src/types.ts#L570) in ThemeStyles, so it should be possible to use `tbody`, `thead` and even names of your HTML custom elements (like `funky-button`).

Do you get an error if you try to use `tbody` key?

**Comment by atanasster** [comment]
Thanks a lot for the answer
yes, i am getting ts errors on 0.3.1, however it seems there are some changes since then.
Any idea when an official release will be published?

**Comment by hasparus** [comment]
> I am getting ts errors on 0.3.1, however it seems there are some changes since then.

0.3.1 is typed in DefinitelyTyped. There are some small problems.

I'm using 0.4 alpha in my apps for quite a long time already. I recommend to give it a shot. There's only one runtime breaking change, and TypeScript should catch it.

BTW Out of curiosity: How are you using `theme.styles.tbody`?

> Any idea when an official release will be published?

From TypeScript perspective, I'll check if 0.4 can be used in TS codebase without `skipLibCheck` and if it's okay I think we're ready. I'm working on a PR with big changes to exported types (I'll send a PR this weekend I promise :P). I'm not sure if @jxnblk wants to wait for it.

**Comment by atanasster** [comment]
Thanks. I tried to update to the alphas, but had versioning problems that some of the packages were forcing a ‘highlight’ version of the css package. Resulting in an error of ‘ defaultBreakpoints Is not exported the @theme-ui/css’. I had upgraded all my theme-ui packages to alpha but using it within a gatsby setup - maybe gatsby was forcing the version, not sure.

I am styling my own react-table derived component and it does have a tbody part and that is where i am using the tbody style. Hope it makes sense or maybe there some alternative?

Thanks a lot for checking on a possible official release, much appreciated. Have a great weekend

**Comment by hasparus** [comment]
> I am styling my own react-table derived component and it does have a tbody part and that is where i am using the tbody style. Hope it makes sense or maybe there some alternative?

Okay, I think I get it.

> maybe there some alternative?

Well, you can cascade tbody styles from `styles.table`

```
{
  table: { '> tbody': { bg: 'blue' } }
}
``` 

or write the styles inline in your table component.

**Comment by atanasster** [comment]
I dont really want to write the styles inline for this particular case, but I am already using `//@ts-ignore`, so its ok.
Was just a suggestion to maybe add the field.

**Comment by hasparus** [comment]
> I'll check if 0.4 can be used in TS codebase without skipLibCheck

Okay, I think color-modes and mdx should at least have stub definitions before we publish 0.4.0.
As this wouldn't be alpha anymore, I expect as I user I would be reluctant to add `skipLibCheck: true` to my tsconfig.

```
export { useColorMode, InitializeColorMode } from '@theme-ui/color-modes';
export { Styled, components } from '@theme-ui/mdx';
```

There's also this error:
```
node_modules/@theme-ui/components/index.d.ts:4:53 - error TS7016: Could not find a declaration file for module 'styled-system'. '/home/hasparus/workspace/homepage/node_modules/styled-system/dist/index.js' implicitly has an 'any' type.
  Try `npm install @types/styled-system` if it exists or add a new declaration (.d.ts) file containing `declare module 'styled-system';`

4 import { SpaceProps, ColorProps, MarginProps } from 'styled-system'
```

**Comment by atanasster** [comment]
Thanks for letting us know. Do you think 0.4 is close?

**Comment by lachlanjc** [comment]
Closing since 0.4 is published
